### ISSUE TITLE
🐛 delta is using unstable library feature

### ISSUE THREAD

**Issue by WayneD** [dandavison/delta#1001]
Trying to build delta I get this:
```console
error[E0658]: use of unstable library feature 'array_methods'
  --> src/subcommands/diff.rs:27:30
   |
27 |         ["diff", "-u", "--"].as_slice()
   |                              ^^^^^^^^
   |
   = note: see issue #76118 <https://github.com/rust-lang/rust/issues/76118> for more information

error[E0658]: use of unstable library feature 'array_methods'
  --> src/subcommands/diff.rs:29:56
   |
29 |         ["git", "diff", "--no-index", "--color", "--"].as_slice()
   |                                                        ^^^^^^^^
   |
   = note: see issue #76118 <https://github.com/rust-lang/rust/issues/76118> for more information
```

I reworked diff.rs to avoid the issue, but due to rust complaining about the array sizes differing I just coded up some duplicate code in 2 alternate paths.  I'm sure someone more familiar with rust will have a better solution, so I'm not including mine here.

**Comment by dandavison** [comment]
Hi @WayneD, does updating your rust toolchain with `rustup update` make this go away?

**Comment by WayneD** [comment]
Indeed. I should have thought of that.  Rust 1.56.1 was too old, but 1.59.0 is fine.
