### ISSUE TITLE
🐛 Misplaced diff output

### ISSUE THREAD

**Issue by WayneD** [dandavison/delta#1002]
I had occasion to concatenate the `diff -u` output for several files into a single file and noticed that using delta to page the input stream misplaced a trailing chunk from one file into the start of the next file.  A simple example input that reproduces the issue:

```text
--- 1/x 2022-03-06 11:16:06.313403500 -0800
+++ 2/x 2022-03-06 11:18:14.083403500 -0800
@@ -1,5 +1,5 @@
 This
-is
+IS
 a
 few
-lines.
+LINES.
--- 1/y 2022-03-06 11:16:44.483403500 -0800
+++ 2/y 2022-03-06 11:16:55.213403500 -0800
@@ -1,4 +1,4 @@
 This
 is
-another
+ANOTHER
 test.
```
Running that text through delta on stdin displays the `-lines.` `+LINES.` chunk after the header for the "y" file.  If a "diff" line was prior to the "---" line in the input then delta would have flushed the dangling diff lines.

**Comment by dandavison** [comment]
Thanks @WayneD! Fix here if you'd like to check it: https://github.com/dandavison/delta/pull/1003

**Comment by WayneD** [comment]
Looks good!

**Comment by dandavison** [comment]
Thanks!
