### ISSUE TITLE
🚀 Support for anonymous named pipes as inputs

### ISSUE THREAD

**Issue by eve-cxrp** [dandavison/delta#1019]
Diff supports the following:

`diff <(cat file.txt | ag -i "foo-tool|STEP") <(cat ~/Downloads/file.txt | ag -i "foo-tool|STEP")`

Would be also nice to see this in delta 🙂.

**Comment by dandavison** [comment]
Hi @eve-cxrp, what's your delta version? This is fixed in the latest release; see https://github.com/dandavison/delta/pull/978 (I'm assuming that the error message you saw was something like

```
error: /dev/fd/11: unsupported file type
fatal: cannot hash /dev/fd/11
```
)

**Comment by eve-cxrp** [comment]
So the version I have seems to be:

```
❯ delta -help

    Delta version 2003.7.14
    delta implements the delta-debugging algorithm:
      http://www.st.cs.uni-sb.de/dd/
    Implemented by Daniel Wilkerson.
```

This is the error I see:

```
❯ delta <(echo "hi") <(echo "ho")
You must specify a test script.
```

Delta is also behaving strange for me. `--help` is not working but `-help` does. 

FYI: I'm on Apple M1.

**Comment by dandavison** [comment]
That's not delta, that's something else called "delta"! To install our delta it's `brew install git-delta`.

**Comment by eve-cxrp** [comment]
Oh, you are right. Thanks a lot. It works now 🙂
