### ISSUE TITLE
🚀  support difftastic

### ISSUE THREAD

**Issue by georgettica** [dandavison/delta#1026]
I would like the nice tool https://github.com/Wilfred/difftastic to have a way to be configured to be used here

it has filetype support for smart comparisons

**Comment by dandavison** [comment]
Hi @georgettica, I agree, I'd like that too. One way I can imagine this happening is

1. Someone designs a serialized format (presumably JSON) suitable for representing the token-level diff information that difftastic and delta display
2. Someone adds to difftastic the ability to output that format
3. Someone adds to delta the ability to consume that format

An alternative would be library-based integration, but neither project exists as a library yet.

cc @Wilfred

**Comment by boris-petrov** [comment]
This issue is a duplicate of #535. I also very much would like to use `difftastic` via `delta`! :)

**Comment by georgettica** [comment]
will close this as there is a duplication, if we have use for the separated card we can always reopen
