### ISSUE TITLE
🐛 Delta fails to print `⋮` character with less v590 on Windows

### ISSUE THREAD

**Issue by icy-comet** [dandavison/delta#1028]
I have `delta 0.12.1` and `less v590` installed on my system with Scoop.

However, if `less` is installed `delta` doesn't print `⋮` and instead prints `<U+22EE>`.
Some other character is failing as well as seen in the attached screenshot.

I can confirm that the issue gets resolved once `less` is uninstalled.

![image](https://user-images.githubusercontent.com/50461557/160805915-7640ff3b-ebde-4c28-9d95-8155d475f15a.png)

**Comment by jtroo** [comment]
Is this a bug with `delta` and not `less`? Does `less` Print `⋮` properly without using `delta`?

From my understanding, delta itself is not a pager and by default uses `less` as its pager. If `less` is not installed, it might use `bat` behind the scenes, not about that one.

https://github.com/dandavison/delta/blob/master/manual/src/how-delta-works.md

**Comment by icy-comet** [comment]
@jtroo yes, it does seem like a bug with `less`.

In the screenshot I attached previously, `delta` is using `bat` as its pager. And `bat` only produces wrong output if `less` is installed [since `bat` uses `less` for paging, if found]

This can be seen in this screenshot:
![2022_04_02_WindowsTerminal_7](https://user-images.githubusercontent.com/50461557/161375859-f263f165-88b9-497e-9d40-f0398170f86a.png)

Any workaround to avoid/fix this on Delta's side? 

And any idea where to report `less`' bugs? I have filed a bug report at gwsw/less#259 i.e. [here](https://github.com/gwsw/less/issues/259), but I am unsure if that's the right place for it.

**Comment by jtroo** [comment]
According to the [less website](http://greenwoodsoftware.com/less/), that's the correct place.

A workaround could be `--paging never`

```
        --paging <paging-mode>
            Whether to use a pager when displaying output. Options are: auto, always, and never. The default pager is
            `less`: this can be altered by setting the environment variables DELTA_PAGER, BAT_PAGER, or PAGER (and that
            is their order of priority) [default: auto]
```

Or in `.gitconfig`

```
[delta]
        paging = never
```

**Comment by icy-comet** [comment]
This clearly seems to be the issue on pager's side. I'm closing the issue.
