### ISSUE TITLE
list suggested terminal themes

### ISSUE THREAD

**Issue by stevemao** [dandavison/delta#103]
On my iterm dark theme and the blue colour is a bit hard to see. Would be great if you could recommend some colour theme.
<img width="404" alt="Screen Shot 2020-02-26 at 10 35 01 am" src="https://user-images.githubusercontent.com/6316590/75297379-d2ded380-5883-11ea-9aad-f5c9049e99fa.png">

**Comment by dandavison** [comment]
Agreed, thanks for reporting this. Delta doesn't (yet) have its own concept of colour theme for the structural elements surrounding the diff (it does allow syntax highlighting themes to be chosen which apply to the code in the diff itself). The blue you point out is hard-coded, so the simplest fix might be to introduce a command-line option allowing that colour to be specified.

(Ref #99 -- this issue and #99 are basically the same.)

**Comment by dandavison** [comment]
I'm working on a branch that will allow all colors to be specified as either RGB, or as an ANSI terminal code, using command line options.

By the way, that blue color is not specified as RGB by Delta: it's ANSI terminal color code 34 ("blue foreground"). I.e. the actual displayed colour is controlled by your terminal emulator, so there's a quick fix if it you're happy with altering that blue everywhere. In my terminal (iTerm2), I can change it like this:

![image](https://user-images.githubusercontent.com/52205/75356702-ec791e80-5875-11ea-8a9a-74f7d3625a56.png)

**Comment by dandavison** [comment]
I've merged a branch which allows all colors to be configured using command line options. The new options are described in the `--help` output:

```
--commit-color <commit_color>              Color for the commit section of git output. [default: yellow]
--commit-style <commit_style>                                                                   
    Formatting style for the commit section of git output. Options are: plain, box. [default: plain]

--file-color <file_color>                  Color for the file section of git output. [default: blue]
--file-style <file_style>
    Formatting style for the file section of git output. Options are: plain, box, underline. [default:
    underline]                                                                                  
--hunk-color <hunk_color>                  Color for the hunk-marker section of git output. [default: blue]
--hunk-style <hunk_style>
    Formatting style for the hunk-marker section of git output. Options are: plain, box. [default: box]
```

along with a section describing how to specify colors:

```
Colors
------

All delta color options work the same way. There are two ways to specify a color:

1. RGB hex code

   An example of passing an RGB hex code is:
   --file-color="#0e7c0e"

2. ANSI color name

   There are 8 ANSI color names:
   black, red, green, yellow, blue, magenta, cyan, white.

   In addition, all of them have a bright form:
   bright-black, bright-red, bright-green, bright-yellow, bright-blue, bright-magenta, bright-cyan, bright-white

   An example is:
   --file-color="green"

   Unlike RGB hex codes, ANSI color names are just names: you can choose the exact color that each
   name corresponds to in the settings of your terminal application (the application you use to run
   command line programs). This means that if you use ANSI color names, and you change the color
   theme used by your terminal, then delta's colors will respond automatically, without needing to
   change the delta command line.

   "purple" is accepted as a synonym for "magenta". Color names and codes are case-insensitive.
```

**Comment by keithrbennett** [comment]
I appreciate your adding the ability to override the dark blue, but given that it is unreadable, could you change the default color to a better one? As a first time user of this excellent utility, I was disappointed to see that I would have to invest additional time in compensating for the unusable default. I tried green and it works well.

**Comment by keithrbennett** [comment]
I noticed that the examples in the documentation show a bright yellow rather than the dark blue. Perhaps you could make that the default? It would also make the documentation and the off-the-shelf behavior consistent with each other.

**Comment by keithrbennett** [comment]
Also, it's probably worth mentioning in the readme that 1) the themes do not apply to the file headings (right?), which are in dark blue and the most in need of configurability, and 2) how to change the color of those file headings. I don't know if this is the correct way to do it, but I seem to have fixed it with the following in my .gitconfig:

```
	file-style = "green"
	file-decoration-style = "green ul"
	hunk-header-file-style = "green"
	hunk-header-line-number-style = "green"
	hunk-header-decoration-style = "green box"
```

...which I believe are all the settings that were dark blue.

**Comment by dandavison** [comment]
Hi @keithrbennett, delta is applying ANSI color code 34 ("blue") here. This is one of the 16 color codes that indexes into a palette provided by your terminal emulator. In other words, delta has no control over the actual visual appearance of that color. People adjust those colors via their terminal emulator configuration.


```bash
$ git diff --cached  | delta --no-gitconfig | cat -A
␊
␛[34mrenamed:·README.md·\u{27f6}···README.md.x␛[0m␊
```

**Comment by keithrbennett** [comment]
I understand that, but could an ANSI color that’s less prone to poor visibility and less likely to require extra setup (such as green or the yellow used in the docs) work better as the default instead?

I suspect some potential users will try out delta and give up before digging into how to modify their terminal or delta’s configuration. A more visible default color would reduce new‑user friction and make the behavior more consistent with the documentation.

If you decide this change makes sense, I’d be happy to open a PR if it would be helpful. I’m not a Rust developer and would be relying on AI plus visual inspection, but this kind of change seems low risk.
