### ISSUE TITLE
Add MacPorts to README if it becomes available there

### ISSUE THREAD

**Issue by FranklinYu** [dandavison/delta#104]
https://aur.archlinux.org/packages/git-delta/

I can help pushing MacPorts packages.

**Comment by dandavison** [comment]
Sure! Would you be able to propose the correct text for the README? Currently the relevant section reads

## Installation

Executables: [Linux](https://github.com/dandavison/delta/releases/download/0.0.16/delta-0.0.16-x86_64-unknown-linux-musl.tar.gz) | [MacOS](https://github.com/dandavison/delta/releases/download/0.0.16/delta-0.0.16-x86_64-apple-darwin.tar.gz) | [Windows](https://github.com/dandavison/delta/releases/download/0.0.15/delta-0.0.15-x86_64-pc-windows-msvc.zip) | [All](https://github.com/dandavison/delta/releases)

Homebrew:
```sh
brew install git-delta
```

FreeBSD pkg(8):
```sh
pkg install git-delta
```

**Comment by FranklinYu** [comment]
I frankly don’t have much idea how it looks best. If this project keep going, people would want it to be in different distributions. We already have Homebrew, FreeBSD and AUR (which might eventually go to main Arch Linux distribution), with MacPorts to come. I see that you are also providing `.deb` file, is it for Debian or Ubuntu?

If we make this package easier to consume, maybe it would reach popularity of `exa`.

Last, thanks for this nice project!

**Comment by dandavison** [comment]
Yes, I'm on board with making it available as conveniently as possible and making the README informative about that.

> mention package in AUR?

In the README, what should the text say for AUR? Should it give a `pacman` command, or should it just link to https://aur.archlinux.org/packages/git-delta/?

> with MacPorts to come (I created a request-to-package).

Great, thanks!

> I see that you are also providing .deb file, is it for Debian or Ubuntu?

To be honest I thought .deb worked on both Debian and Ubuntu.

**Comment by Kr1ss-XD** [comment]
Hi, AUR package maintainer here.
>In the README, what should the text say for AUR?

I'd suggest the following : 

---
Archlinux (AUR):
 - make sure `git` is installed
```sh
git clone https://aur.archlinux.org/git-delta.git
cd git-delta
makepkg -csi
```
---
_Thanks a lot !_

**Comment by dandavison** [comment]
Thanks, I've added those AUR instructions to the README. I'll leave this open to track the  MacPorts thread.

**Comment by FranklinYu** [comment]
> To be honest I thought .deb worked on both Debian and Ubuntu.

@dandavison Yes, as long as you don't fix version of your dependencies (some package in Ubuntu get some special patch so they add something to the version string).

**Comment by dandavison** [comment]
https://github.com/macports/macports-ports/pull/6963

**Comment by herbygillot** [comment]
Delta is now in MacPorts.  Install steps:

```
sudo port selfupdate
sudo port install git-delta
```

**Comment by dandavison** [comment]
Cool, thanks @herbygillot.
