### ISSUE TITLE
🐛 Change attributed to wrong file

### ISSUE THREAD

**Issue by abbeyj** [dandavison/delta#1042]
Given the following input to delta, delta will show the line "// Also to be removed" as being removed from two.txt when it is actually being removed from one.cpp.

```
$ delta --version
delta 0.12.1
$ cat diff_repro.patch
--- orig/one.cpp        2022-04-11 11:21:45.977732000 -0400
+++ ./one.cpp   2022-04-11 11:22:00.664111000 -0400
@@ -1,5 +1,3 @@
-// To be removed

 // To be kept

-// Also to be removed
--- orig/two.txt        2022-04-11 11:16:53.878365000 -0400
+++ ./two.txt   2022-04-11 11:16:46.737482000 -0400
@@ -1 +1 @@
-Something
+Something Else
$ cat diff_repro.patch | delta
```

![image](https://user-images.githubusercontent.com/99402/162779302-f3f82fcd-9532-4e39-96a1-21cdc8ed7c07.png)

Adding a blank line to the input before the `--- orig/two.txt` line is a workaround.

**Comment by dandavison** [comment]
Thank you very much @abbeyj. Sorry to be slow -- I was on holiday, and then a bit occupied by day job. This is clearly bad and we'll fix it!

**Comment by dandavison** [comment]
Actually, this one was already fixed in March by https://github.com/dandavison/delta/pull/1003 and has been released.
