### ISSUE TITLE
🚀 zdiff3 support?

### ISSUE THREAD

**Issue by skyfaller** [dandavison/delta#1048]
Hi folks, it's unclear to me whether delta supports zdiff3 conflict style: https://stackoverflow.com/q/27417656 Does it? If not, can it? Should it? 

zdiff3 only appears to work with Git 2.35 and above, so that might be a complication.

**Comment by dandavison** [comment]
Hi @skyfaller, I just tried very quickly and it looked superficially reasonable. Can you post some output of delta displaying a zdiff3 merge conflict and tell us what you think in terms of whether delta's doing it correctly?  You don't need to change anything in your delta config (as long as you have a reasonably recent delta version; merge conflict display was added last autumn).

> zdiff3 only appears to work with Git 2.35 and above, so that might be a complication.

I don't think this affects delta: git does the merge, and generates the merge diff using whatever the user has in `merge.conflictstyle`. If the user specifies zdiff3 and doesn't have an adequate git version then they'll get an error, but it's nothing to do with delta.

**Comment by aried3r** [comment]
I can't post a diff since it contains code from work, but switching to `zdiff3` for the `conflictstyle` does not seem to cause any obvious issues when using delta.

**Comment by dandavison** [comment]
Thanks @aried3r, I'll close this for now.
