### ISSUE TITLE
🚀 Use `bat`'s theme by default

### ISSUE THREAD

**Issue by MaxG87** [dandavison/delta#1051]
While struggling with setting up a theme from `bat` (#1050 ) I had the following idea.

If no colour scheme is configured, `delta` could use the one `bat` would use. In particular, if a user already configured `bat` to use a specific colour scheme, likely this one will be a good fit for `delta` too.

I think that would provide some convenience for users of `delta`.

**Comment by dandavison** [comment]
Hi @MaxG87, this is already the case in the sense that `delta` honors the `BAT_THEME` environment variable. (I don't think that I want delta to attempt to read a bat configuration file however.)

**Comment by dandavison** [comment]
```
        --syntax-theme <SYNTAX_THEME>
            The syntax-highlighting theme to use.

            Use --show-syntax-themes to demo available themes. Defaults to the value of the BAT_THEME environment variable, if that contains a valid theme name. --syntax-theme=none disables all syntax highlighting.
```
