### ISSUE TITLE
pager case sensitivity: add smart case support 🚀 

### ISSUE THREAD

**Issue by ilAYAli** [dandavison/delta#1079]
I find it very useful to have a pager with smart case support; searching for a text in lower case will also match the pattern in uppercase, and searching with a mixed case restricts the results to the specified case.
This is particularly useful when searching for text in e.g a commit that contains code with mixed case.

**Comment by bew** [comment]
delta is not a pager, delta uses the pager you tell it to use.
For example if your pager is `less` you can configure it with the env variable `$LESS` for example with `export LESS="-R --ignore-case --incsearch"` to get case insensitive search, incrementally. (not sure if less has smart case search yet)

**Comment by dandavison** [comment]
Thanks @bew. That's right: `less --help` / `man less` / online `less` documentation is the place to look for configuring delta's paging behavior. (This is the same as the [bat](https://github.com/sharkdp/bat/) application -- both `delta` and `bat` ultimately end up invoking `less`. So when you are interacting with `delta` or `bat` by sending mouse or keyboard events, it's actually the `less` application that's picking those up.)
