### ISSUE TITLE
🐛 Delta's output is not displaying correctly

### ISSUE THREAD

**Issue by Gers2017** [dandavison/delta#1080]
- [x] Please include the raw text output from git, so that we can reproduce the problem.
      (You can use `git --no-pager` to produce the raw text output.)
- [x] A screenshot of Delta's output is often helpful also.

### Raw text output from git
```bash
commit 934601ecc7163bc51b6270b14ba19456c6754a52
Author: Gers2017 <Gers2017@outlook.com>
Date:   Tue May 17 14:52:57 2022 -0600

    Update keymaps

diff --git a/lua/core/keymaps.lua b/lua/core/keymaps.lua
index 6b8d8e4..73cbc87 100644
--- a/lua/core/keymaps.lua
+++ b/lua/core/keymaps.lua
@@ -20,7 +20,8 @@ M.setup = function ()
   -- NvimTree
   map('n', '<C-b>', ':NvimTreeToggle<cr>')
   map('n', '<leader>nc', ':NvimTreeClose<cr>')
-  map('n', '<leader>ne', ':NvimTreeFocus<cr>')
+  map('n', '<leader>nf', ':NvimTreeFocus<cr>')
+  map('n', '<C-f>', ':NvimTreeFocus<cr>')
   
   -- Window navigation
   map('n', '<C-h>', '<C-w>h')
diff --git a/lua/plugins/init.lua b/lua/plugins/init.lua
index 6be5741..fb003f6 100644
--- a/lua/plugins/init.lua
+++ b/lua/plugins/init.lua
@@ -23,7 +23,9 @@ require('packer').startup(function()
   -- gitsigns
   use 'lewis6991/gitsigns.nvim'
   -- commentary
-  use 'tpope/vim-commentary'
+  -- gcc to commnent out a line (takes a count)
+  -- gc to comment out the target of a motion
+  use 'tpope/vim-commentary' -- gcc to comment out a line
   -- indent-blankline
   use 'lukas-reineke/indent-blankline.nvim'
   -- friendly snippets
```
### Screenshot of delta
![image](https://user-images.githubusercontent.com/49139988/168917023-336f6391-06b9-4faf-bea5-b8425f24cc7c.png)
![image](https://user-images.githubusercontent.com/49139988/168917450-4b74e56c-f4fa-47a7-9555-e1e1fc9013a5.png)

**Comment by dandavison** [comment]
Hi @Gers2017, delta sends its output to `less`, and problems like you are seeing are usually the result of a problem with `less`. Can you make sure you've got a recent version of `less` installed, and post the output of this shell script? https://raw.githubusercontent.com/dandavison/delta/master/etc/bin/diagnostics Are you using Windows? (It's common to have an old version of less installed on Windows; there are a few tickets like that that might be worth looking at.)

**Comment by Gers2017** [comment]
Hi @dandavison thanks for replying.

OS: `linux, arcolinux`
DE: `xfce4`
less: `less 590 (PCRE2 regular expressions)`

also here's output from the script you sent me

```bash
> delta --version
delta 0.13.0

> less --version | head -n1
less 590 (PCRE2 regular expressions)

> env | grep -iE '(less|pager|bat|delta)'
LESS=-R
PAGER=most

> printf '\e[34m\e[43mtext\e[m\n'
text

> printf '\e[38;5;19m\e[48;5;226mtext\e[m\n'
text

> printf '\e[38;2;0;0;255m\e[48;2;255;255;0mtext\e[m\n'
text

> printf '⋮│─'
⋮│─
> delta --no-gitconfig <(echo a) <(echo b) | cat -A
$
^[[34m/dev/fd/63 M-bM-^_M-6   /dev/fd/62^[[0m$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m$
$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m^[[34mM-bM-^TM-^P^[[0m$
^[[34m1^[[0m: ^[[34mM-bM-^TM-^B^[[0m$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m^[[34mM-bM-^TM-^X^[[0m$
^[[48;2;63;0;1ma^[[0m^[[48;2;63;0;1m^[[0K^[[0m$
^[[48;2;0;40;0;38;2;248;248;242mb^[[0m^[[48;2;0;40;0m^[[0K^[[0m$

> delta  --no-gitconfig <(echo a) <(echo b)
```
![image](https://user-images.githubusercontent.com/49139988/169373161-e2bea811-9a6f-41dd-9bee-4ef8355c4473.png)

I'm not sure if I should be using a beta version
![image](https://user-images.githubusercontent.com/49139988/169372711-952bb1da-2f62-4493-9409-faaba7e68fee.png)

**Comment by Gers2017** [comment]
```bash
#.gitconfig
[alias]
  # some aliases...
 
[core]
  pager = delta

[interactive]
  diffFilter = delta --color-only --features=interactive

[delta]
  features = decorations

[delta "interactive"]
  keep-plus-minus-markers = false

[delta "decorations"]
  commit-decoration-style = blue ol
  commit-style = raw
  file-style = omit
  hunk-header-decoration-style = blue box
  hunk-header-file-style = red
  hunk-header-line-number-style = "#067a00"
  hunk-header-style = file line-number syntax
```

**Comment by dandavison** [comment]
@Gers2017 @robtownsend1 problems like this are usually a problem with less (the pager that delta uses). I'm not at a computer now but if you disable the pager I suspect you'll see correct output. There are various ways to disable the pager, for example piping to `cat` (not bat! since that also uses a pager). See `--help` for other ways. If that's right, then the solution, of course, is to ensure you're using as adequate version of less and that it's being passed essential command line arguments (basically `-R`).

It's possible it's a problem with your terminal emulator, but more often it's less configuration/version/env vars.

**Comment by lyaaz** [comment]
same problem when set env `PAGER = most`, delta works normal after unset it.

**Comment by dandavison** [comment]
> same problem when set env `PAGER = most`

Yes, `most` isn't capable of working with delta (or bat I think). I believe it's unicode and/or 24-bit color handling isn't comprehensive enough.

**Comment by Gers2017** [comment]
@lyaaz is right, I had `PAGER = most` on my config
