### ISSUE TITLE
🚀  Changes at the module level in a Python file have unrelated/confusing "Headings"

### ISSUE THREAD

**Issue by taranlu-houzz** [dandavison/delta#1081]
I came across this while trying out `delta`. Technically, it is correct, since that is what the `git diff` is showing, but because `delta` makes the "Headings" stand-out more I was confused at first.

It seems like it could be helpful if chunks that are at the module level could have a special heading (e.g. something like `<MODULE>`). I do realize this is personal preference, but I think that it would make the Python diffs more user friendly.

```diff
diff --git a/----/cli.py b/----/cli.py
index 71a0c81..2399e96 100644
--- a/----/cli.py
+++ b/----/cli.py
@@ -22,7 +22,6 @@ from typing import Dict, Optional, List
 # ==Site-Packages==
 import rich_click
 import rich_click.typer as typer
-from rich.pretty import pretty_repr
 from PIL import Image
```

![Screen Shot 2022-05-18 at 02 07 00](https://user-images.githubusercontent.com/52425255/169117916-15ee8c76-7c21-48fa-99f3-6a9ae1e524d7.png)

**Comment by Kr1ss-XD** [comment]
Hi @taranlu-houzz !

If I'm getting you correctly, you can adjust this with a custom `.gitattributes` file, which contains : 

```gitattributes
*.py	text	diff=python
```

Here's what the output looks like : 

```diff
diff --git i/cli.py w/cli.py
index 71a0c81..2399e96 100644
--- a/cli.py
+++ b/cli.py
@@ -22,7 +22,6 @@
 # ==Site-Packages==
 import rich_click
 import rich_click.typer as typer
-from rich.pretty import pretty_repr
 from PIL import Image
 
```

Git attributes files can be repository-specific, global or system-wide, see the `gitattributes` [documentation](https://www.git-scm.com/docs/gitattributes) for the respective locations.

Also, here's a nice [article](https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more) about this topic, which might be interesting for you.

**Comment by taranlu-houzz** [comment]
@Kr1ss-XD Perfect, that is exactly what I needed! Great article too. Thank you for your help!
