### ISSUE TITLE
🐛 Delta stops working after updating bat color themes

### ISSUE THREAD

**Issue by armak** [dandavison/delta#1088]
I checked some new themes for `bat`, as [instructed in the documentation ](https://github.com/sharkdp/bat#adding-new-themes), after which delta stopped working with the following error:
```
$ git diff
[bat warning]: Unknown theme 'Monokai Extended', using default.
thread 'main' panicked at 'something is very wrong if the default theme is missing', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.21.0/src/assets.rs:205:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This error occurs for every theme, and when leaving the `syntax-theme` parameter empty. I could not find any way to resolve this. `bat` itself is unaffected and still works as normal, the error only comes up when invoking delta. I'm using Ubuntu 22.04 in WSL1.

**Comment by dandavison** [comment]
Hi @armak, please update to the latest delta and bat, and recreate the bat cache. (See #1075.)
