### ISSUE TITLE
Executing the `delta` command alone causes program to lock🐛 

### ISSUE THREAD

**Issue by daviclorisamazing** [dandavison/delta#1090]
Sometimes when people are new to a command, or make an error, they may execute `delta` without any arguments or options. For me, this causes the program to lock in a way that cannot be exited in an obvious manner. Neither ^D nor ^C worked for me in this situation. I had to resort to ^Z, then do a `ps` and manually `kill` the process.

`less` handles this situation gracefully and gives concise contextual help for n00bs. I would suggest its behavior as a point of reference for this situation. 

I'm on OS X 12.3.1 and using the default terminal program.

**Comment by dandavison** [comment]
Hi @daviclorisamazing, I agree, it's annoying and will be difficult for people who are at all new to command line usage. (I'd welcome a PR fixing this.)
