### ISSUE TITLE
❓  Missing themes when installed with homebrew

### ISSUE THREAD

**Issue by udl** [dandavison/delta#1092]
First and foremost thank you for the great tool! I've been using it to diff my git workspace for quite a while now and it's awesome.

I have installed the `git-delta` [homebrew tap](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/git-delta.rb) and also added https://github.com/dandavison/delta/blob/master/themes.gitconfig to my setup, which generally works fine. But for some time now, I'm seeing the following error when using a theme with `Github` or `Vibrant Sunburst`:
```
[bat warning]: Unknown theme 'Github', using default.
```
Other themes work fine. Do you have any idea where I need to install these missing themes?
Thank you!

**Comment by dandavison** [comment]
Hi @udl, I think that particular error is due to a typo; the github theme is spelled with a capital H in the middle: `GitHub`.

I don't think I'm familiar with Vibrant Sunburst though. @Kr1ss-XD @clnoll what is this mystery theme? :)

```
$  delta --list-syntax-themes
Light syntax themes:
    GitHub
    Monokai Extended Light
    OneHalfLight
    Solarized (light)
    gruvbox-light

Dark syntax themes:
    1337
    Coldark-Cold
    Coldark-Dark
    DarkNeon
    Dracula
    Monokai Extended
    Monokai Extended Bright
    Monokai Extended Origin
    Nord
    OneHalfDark
    Solarized (dark)
    Sublime Snazzy
    TwoDark
    Visual Studio Dark+
    ansi
    base16
    base16-256
    gruvbox-dark
    zenburn
```

**Comment by udl** [comment]
Oh yes, you're right! Sorry for the stupid mistake. It works just fine with the correct spelling.

**Comment by Amorymeltzer** [comment]
Vibrant Sunburst is still listed as a syntax-theme by tangara-chilensis and woolly-mammoth
