### ISSUE TITLE
🚀 Highlight lines without emph separately from lines with emph

### ISSUE THREAD

**Issue by tammersaleh** [dandavison/delta#1099]
LOVE delta!  Thank you!

I'd like to be able to highlight lines that do _not_ have emph in them differently from those that do, and I don't _think_ this is currently possible.

Use case:

Let's say I diff the following two files:

```
1 "Foobar"
2 Removed
```

```
1 Added
2 'Foobar'
```

I'd like to be able to show 

1. the `Removed` line as bright red
2. the `Added` line as bright green
3. the change of `"` to `'` as bright red/green
4. but the `Foobar` in that same line as normal color

**Comment by dandavison** [comment]
Hi @tammersaleh, how close is this to what you want?

```
delta --no-gitconfig \
      --minus-style='normal pink' --plus-style='normal palegreen' \
      --minus-emph-style='normal red' --plus-emph-style='normal green' \
      --minus-non-emph-style='normal normal' --plus-non-emph-style='normal normal' \
      a b
```

<img width="117" alt="image" src="https://user-images.githubusercontent.com/52205/173639195-92630a40-7f1f-4207-8d67-7e07019c7230.png">

**Comment by dandavison** [comment]
Friendly ping @tammersaleh -- does this give you what you need?

**Comment by tammersaleh** [comment]
thanks so much for responding and for the reminder.  I was seeing weird behavior where your command line produced the right results:

![eU0EiJSG](https://user-images.githubusercontent.com/2016/179035316-3effcaa8-bbbc-415d-9a00-1068a88c4c73.png)

...but `git` didn't:

![PKNX5tRa](https://user-images.githubusercontent.com/2016/179035478-7f56d328-56d4-457c-896e-987727b0ac25.png)

With your help above I figured out that I had a typo in my git config:

``` gitconfig
[delta "decorations"]
    ...
    minus-nonemph-style = ...
    plus-nonemph-style = ...
```

For anyone stumbling on this, those should be `minus-non-emph-style` (with the extra `-`, matching the command line flags).

If it's possible, it'd be great for Delta to notice unrecognized options under `[delta]` stanzas and error out.  But this was definitely PEBCAK.

**Comment by dandavison** [comment]
Great. Yes, maybe delta could have a `delta --doctor` command that outputs a bunch of diagnostics and does various checks?
