### ISSUE TITLE
crates.io support?

### ISSUE THREAD

**Issue by im-n1** [dandavison/delta#11]
I would be nice to be able to install via cargo

**Comment by dandavison** [comment]
Sure! Here it is: https://crates.io/crates/git-delta

**Comment by polyzen** [comment]
@dandavison, there hasn't been any updates to the crates.io listing.

**Comment by dandavison** [comment]
@polyzen thanks! Sorry about that, I've pushed v0.0.14 to crates.io and added a `release` Make target that, for now, just does `cargo publish`.
