### ISSUE TITLE
🐛 Unalignment due to timestamp in chameleon theme

### ISSUE THREAD

**Issue by tanishyadav** [dandavison/delta#1104]
The current `blame-format` for chameleon theme
```
blame-format = "{author:<18} ({commit:>7}) {timestamp:^12} "
```
causes unalignment in some cases.

![image](https://user-images.githubusercontent.com/68607350/173826597-6f0f8b0a-cd2c-474f-9373-e75cf516ff86.png)

This would perhaps be better
```
blame-format = "{author:<18} ({commit:>7}) {timestamp:^16} "
```

**Comment by dandavison** [comment]
Thanks @tanishyadav, I applied that change.
