### ISSUE TITLE
🐛 Using delta makes pretty format colours in git show ineffective

### ISSUE THREAD

**Issue by thatlittleboy** [dandavison/delta#1105]
# Description

1. When using `delta` as my `core.pager`, using `git show --pretty` with colour specifications doesn't work (the entire output is white). But using `less` or `--no-pager`, the colours show up as expected.

Is there some config I'm missing?

# Minimal reproducible example

### Setup
```shell
$ cd "$(mktemp -d)"
$ git init && git commit --allow-empty -m "initial"
```

### With delta
```shell
$ GIT_CONFIG=.git/config git config core.pager delta
$ GIT_CONFIG=.git/config git config -l --show-origin
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        core.precomposeunicode=true
file:.git/config        core.pager=delta

$ GIT_CONFIG=.git/config git show --pretty=tformat:"%Credred%Creset %Cgreengreen%Creset %C(Yellow)yellow%Creset %Cblueblue%Creset %C(magenta)magenta%Creset %C(cyan)cyan%Creset %C(white)white%Creset"
```
![image](https://user-images.githubusercontent.com/30731072/173873225-dd419136-9374-47e1-89f9-d7e488da7bab.png)

Output is all white.  
Using `--color=auto` or `--color=always` doesn't work as well.

Note that here I just set `core.pager` to delta with no additional settings. This same observation happens with the recommended basic setup for delta mentioned in the README. (see collapsed section)

<details>
  <summary>Fuller git config with delta</summary>

>   [core]
>       pager = delta
>   
>   [interactive]
>       diffFilter = delta --color-only --features=interactive
>   
>   [delta]
>       features = decorations
>   
>   [delta "interactive"]
>       keep-plus-minus-markers = false
>   
>   [delta "decorations"]
>       commit-decoration-style = blue ol
>       commit-style = raw
>       file-style = omit
>       hunk-header-decoration-style = blue box
>       hunk-header-file-style = red
>       hunk-header-line-number-style = "#067a00"
>       hunk-header-style = file line-number syntax

</details>

### Using no-pager
```shell
$ GIT_CONFIG=.git/config git --no-pager show --pretty=tformat:"%Credred%Creset %Cgreengreen%Creset %C(Yellow)yellow%Creset %Cblueblue%Creset %C(magenta)magenta%Creset %C(cyan)cyan%Creset %C(white)white%Creset"
```
![image](https://user-images.githubusercontent.com/30731072/173873451-9c5fb299-74b3-4573-a560-a5d4b37b593d.png)

### Meta

* delta 0.13.0
* Mac monterey 12.2
* zsh, kitty
* git version 2.36.1

**Comment by dandavison** [comment]
Thanks for this @thatlittleboy. I can see what's happening: we want the line to be handled by https://github.com/dandavison/delta/blob/e7dbdd48469699f6ce4054cf610e686563314efe/src/delta.rs#L174 but instead its getting handled by https://github.com/dandavison/delta/blob/e7dbdd48469699f6ce4054cf610e686563314efe/src/delta.rs#L170

The idea of the `git show` handler is that it allows us to do `git show $commit:/some/path.lang` and have it syntax-highlighted as `lang`. But unfortunately of course that means it is very promiscuous, if that's the word: it handles anything that "could be code".

So, next step here is someone comes up for a good resolution of this problem!

Incidentally, for any delta debuggers/developers, wrapping all the line handlers in `dbg!` as in https://github.com/dandavison/delta/commit/2e65853c368d697181b52321bf80d312cd2a8176 seems to be a decent way to diagnose problems like this:

<details>

```
src/delta(master અ ) git show --pretty=tformat:"%Credred%Creset %Cgreengreen%Creset %C(Yellow)yellow%Creset %Cblueblue%Creset %C(magenta)magenta%Creset %C(cyan)cyan%Creset %C(white)white%Creset"
[src/delta.rs:157] self.handle_commit_meta_header_line()? = false
[src/delta.rs:158] self.handle_diff_stat_line()? = false
[src/delta.rs:159] self.handle_diff_header_diff_line()? = false
[src/delta.rs:160] self.handle_diff_header_file_operation_line()? = false
[src/delta.rs:161] self.handle_diff_header_minus_line()? = false
[src/delta.rs:162] self.handle_diff_header_plus_line()? = false
[src/delta.rs:163] self.handle_hunk_header_line()? = false
[src/delta.rs:164] self.handle_diff_header_mode_line()? = false
[src/delta.rs:165] self.handle_diff_header_misc_line()? = false
[src/delta.rs:166] self.handle_submodule_log_line()? = false
[src/delta.rs:167] self.handle_submodule_short_line()? = false
[src/delta.rs:168] self.handle_merge_conflict_line()? = false
[src/delta.rs:169] self.handle_hunk_line()? = false
[src/delta.rs:170] self.handle_git_show_file_line()? = true
```
</details>

**Comment by dandavison** [comment]
Sorry, on re-reading that / thinking a bit more -- we actually already have the `git show` handler made much stricter by making it examine the calling parent process and only handle the line if it is indeed `git show`. But the problem here is that it was indeed `git show`, just not `git show $commit:./some/path`. It looks like the `git show` handler was not being strict enough with the result of parsing the command line. Fix here https://github.com/dandavison/delta/pull/1106

**Comment by thatlittleboy** [comment]
Thanks for the quick turnaround @dandavison , can't wait to give it a try. Appreciate it :)
