### ISSUE TITLE
🐛 Issue when using git am

### ISSUE THREAD

**Issue by ghost** [dandavison/delta#1109]
Running `git am -i PATCH` and pressing 'v' for 'view patch' results in

```
The main way to use delta is to configure it as the pager for git: see https://github.com/dandavison/delta#configuration. You can also use delta to diff two files: `delta file_A file_B`.
Commit Body is:
-------------------------------
```

with the suggested configuration.

**Comment by dandavison** [comment]
Thanks! #1547 is a dup of this one. Closing this in favor that seeing as it has a bit more dicussion.
