### ISSUE TITLE
Doesn't work with git version `2.37.0`

### ISSUE THREAD

**Issue by boris-petrov** [dandavison/delta#1114]
Using delta 0.13.0. I have this in my `.gitconfig` file:

```
[interactive]
	diffFilter = delta --color-only
```

Which worked great when using `git add -p`. Since version 2.37.0 of git, it blows up:

```
error: could not parse colored hunk header
```

And then some random stuff.

**Comment by OJFord** [comment]
Workaround:
```ini
[add.interactive]
    useBuiltin = false
```

(Credit to @malsyned in issue linked above)

**Comment by phil-blain** [comment]
I would say it is a Git regression, and should be reported to the Git mailing list: http://git-scm.com/community.

**Comment by phil-blain** [comment]
> I would say it is a Git regression, and should be reported to the Git mailing list: http://git-scm.com/community.

Reported here: https://lore.kernel.org/git/ecf6f5be-22ca-299f-a8f1-bda38e5ca246@gmail.com/T/#u

**Comment by boris-petrov** [comment]
Indeed it is! Thanks!

**Comment by WhyNotHugo** [comment]
Fixed for me too. Thanks for following up!
