### ISSUE TITLE
🚀 Configurable timestamp output format in git blame

### ISSUE THREAD

**Issue by mliszcz** [dandavison/delta#1157]
In git blame I noticed this:
![image](https://user-images.githubusercontent.com/6927259/184130106-14883b20-ec05-4ec3-ac65-060b4d35f85f.png)

It would be helpful to know e.g. which change was applied first but this can not be figured out from the humanized timestamp.
https://github.com/dandavison/delta/blob/738c5a141bf86d3e05aa348eb87df78c36a72337/src/handlers/blame.rs#L273

I changed it locally to: `blame.time.format("%H:%M %Y-%m-%d").to_string(),`.

Would it be possible to make this configurable? Perhaps a new option *--blame-**output**-timestamp-format* could be added. If present (and not empty) it would be used as a format string. If not, we will fall back to HumanTime formatting. What do you think?

I can work on a PR if this could be accepted.

**Comment by dandavison** [comment]
Hi @mliszcz, thanks! I agree with the feature proposal and I think that your proposed API is spot-on. Please do go ahead and make a PR if you have time, and let me know if anything's unclear about the development workflow.

**Comment by mliszcz** [comment]
Thanks. I've just opened a PR. Please review carefully because I'm doing rust for the first time! I guess the formatter job will most likely fail, I will run that tomorrow and eventually amend the commit.

**Comment by mliszcz** [comment]
Ready. @dandavison please have a look and trigger the pipeline when you find some time.
