### ISSUE TITLE
🚀 Allow `delta` to accept nonexistent files for diff mode

### ISSUE THREAD

**Issue by latipun7** [dandavison/delta#1162]
![image](https://user-images.githubusercontent.com/20012970/185063205-195a7056-e9db-4518-a9eb-7461746c0b14.png)

It would be cool to allow nonexistent files for delta in diff mode.
If the nonexistent file is the first argument of delta, then the diff is displayed as **"test1.ts added"**
If the nonexistent file is the second argument of delta, then the diff is displayed as **"test1.ts removed"**
or at least the option to enable this behavior.

Thank you. Delta is great tool 👍

**Comment by dandavison** [comment]
Hi @latipun7, can you give an example use case for this behavior? What would it allow you to do differently from what you can do today?

In general, the `delta file1 file2` behavior is intended to be similar to `diff`, and `diff` does not allow you to omit one of the files. Also, note that you can always use `/dev/null` as one of the files, to play the role of an empty file.

**Comment by latipun7** [comment]
Hi @dandavison , sorry for the use case.
Yeah, because I specify delta as [chezmoi's custom diff](https://www.chezmoi.io/user-guide/tools/diff/) so there's error printed when I bootstrap dotfiles when the initial files not found.
Here's the log from `chezmoi apply -v --debug` that stated that delta is error:
![image](https://user-images.githubusercontent.com/20012970/185258518-828ed6e5-f6fb-4633-8792-fb6963e9491a.png)

**Comment by dandavison** [comment]
I think it's pretty non-standard for a diff tool to accept a non-existent file as one of the positional arguments on the command line. In fact it's pretty non-standard for any command line tool to do that for file arguments, right?

Is it an option for you to write a shell wrapper script for delta that has the behavior you need?

**Comment by latipun7** [comment]
Hmm you might have a good point. I'll close this for now.
