### ISSUE TITLE
🚀 custom style of wrap symbols

### ISSUE THREAD

**Issue by timsu92** [dandavison/delta#1178]
I know I can customize the symbol itself by altering `wrap-left-symbol`, `wrap-right-prefix-symbol` and `wrap-right-symbol`. However, is there a way to change is color? The default color is dark blue which is hard to see in dark themes.
![image](https://user-images.githubusercontent.com/33785401/187665377-8223ffc0-f40e-44f6-ab06-e73a6dfa584d.png)

**Comment by dandavison** [comment]
Hi @timsu92, yes, it's `inline-hint-style`. Sorry, delta has a lot of options! There's a manual page for side-by-side -- do let me know if it's missing anything. https://dandavison.github.io/delta/side-by-side-view.html.

**Comment by timsu92** [comment]
Thanks a lot! I'm sorry that I didn't notice this option. A lot of options in delta is surely a nice feature!

**Comment by dandavison** [comment]
No problem!
