### ISSUE TITLE
Include new bat themes introduced in v0.13.0

### ISSUE THREAD

**Issue by stefanfrede** [dandavison/delta#118]
Hi!

bat introduced with [v0.13.0](https://github.com/sharkdp/bat/releases/tag/v0.13.0) new themes, in particular [Nord](https://www.nordtheme.com), which I'm using more or less everywhere.

It would be amazing if the new themes could be integrated into delta, because I use base16 at the moment which is a tat bit too dark and makes diffs hard to read.

Thanks.

**Comment by dandavison** [comment]
Hi @stefanfrede sorry for being so slow, I lost some notifications. Yes, absolutely, I've just added the new themes in master (not released yet).

Incidentally, delta reads bat's custom themes/syntax dir. So without having to compile delta or wait for a release, we can [add a new theme](https://github.com/sharkdp/bat#adding-new-themes) by copying the `foo.tmTheme` file to `~/.config/bat/themes/` and calling `bat cache --build`. So to add e.g. Nord, one can do 

```
cp /PATH/TO/bat/assets/themes/Nord-sublime/Nord.tmTheme ~/.config/bat/themes/
bat cache --build
```
