### ISSUE TITLE
🐛 Outdated download links in the markdown manual

### ISSUE THREAD

**Issue by ggrzybow** [dandavison/delta#1192]
The [Installation](https://github.com/dandavison/delta/blob/master/manual/src/installation.md) page of the manual has links to download delta 0.12.1, but the current version is 0.14.

The outdated links are those in the first body line, after "You can download an executable for your system".

Github [allows linking to the newest release](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases), but since the artifacts have versions in their names, I don't think it's possible to link to the latest binaries directly.

**Comment by dandavison** [comment]
Thanks for reporting that @ggrzybow. I've tightened up the shell script I use for making releases in 4e05ee5ef44361371bc7ef0882c52fabb62e68e7, but if I make the same mistake again maybe we should switch to the link to the newest release page.
