### ISSUE TITLE
Delta should be aware of diff.noprefix option (truncated filenames)

### ISSUE THREAD

**Issue by wookayin** [dandavison/delta#120]
The `diff.noprefix` option (e.g. `git config diff.noprefix true`) would strip away prefixes such as `a/` `b/`. When this option is enabled, the first two characters of filename would be stripped away even though they are a part of normal filenames.

Expected output: (without `diff.noprefix`)
```
package/filename.py
────────────────────────────────────────
...
```

Actual behavior:
```
ckage/filename.py
────────────────────────────────────────
...
```

Tested on 0.0.17.

Although we could configure so that this option is turned off when using delta as pager, delta should be aware of this option and strip prefixes only if the first two letters are git prefixes.

**Comment by dandavison** [comment]
Thanks @wookayin, I agree. Sorry for being slow, I missed the notification here. This sounds like it should be an easy change.

**Comment by dandavison** [comment]
That should be fixed in master. If a user has `git.noprefix = true`, and also has directories genuinely named "a" or "b", then there will still be incorrect stripping.

**Comment by wookayin** [comment]
Thanks! Yeah, I can imagine the corner case but should be fine for the most cases.
