### ISSUE TITLE
🐛 Cannot be installed with delta in Debian

### ISSUE THREAD

**Issue by baryluk** [dandavison/delta#1210]
```
user@debian:~$ sudo gdebi git-delta_0.14.0_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done
This package is uninstallable
Breaks existing package 'delta' that conflict: 'delta'. But the 'git-delta_0.14.0_amd64.deb' provides it via: 'delta'
```

This is because `git-delta` incorrectly sets "Provides: delta`

I use both delta (tigris tool for minimizing compiler and code bugs), and git-delta.

**Comment by dandavison** [comment]
Hi @baryluk, I'm sorry you're suffering from this clash and genuinely use both.

> This is because git-delta incorrectly sets "Provides: delta`

Hm, it is correct that it provides that executable isn't it? I mean, it would provide it were it allowed to be installed.

**Comment by dandavison** [comment]
Let's merge this with https://github.com/dandavison/delta/issues/26

**Comment by baryluk** [comment]
No, `Provides: delta` has nothing to do with how executable is named. Package can be named xyz, and have Provides foo.

`Provide: delta` means that program provides same functionality as real or virtual package named `delta` Which is not true here.

Debian Policy manual section 7 has more information about this https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides

Citation:

> A virtual package is one which appears in the Provides control field of another package.
...
...
> If there are both concrete and virtual packages of the same name, then the dependency may be satisfied (or the conflict caused) by either the concrete package with the name in question or any other concrete package which provides the virtual package with the name in question. This is so that, for example, supposing we have
>
>  ```
> Package: foo
> Depends: bar
> ```
> 
> and someone else releases an enhanced version of the bar package they can say:
> ```
> Package: bar-plus
> Provides: bar
> ```
>
> and the bar-plus package will now also satisfy the dependency for the foo package.



It is an error to put `Provides` in your package. Just remove `Provides: delta` and it will all be good and fully conformant to Debian policy.

**Comment by baryluk** [comment]
Please unmerge, as this is really rather different and easier to fix problem.

**Comment by baryluk** [comment]
I found where it is set, and I will send PR with the fix.

**Comment by baryluk** [comment]
I see the issue. You are building two packages. One with glibc one with musl, and try to set so they do not install at the same time.

I think this indeed might require `Provides`, but for this to work, it should also have `Replaces` and `Conflicts` set, as mentioned in section 7.6.1 and 7.6.2.

In that case renaming a package might be indeed required, or at least other name used that is unique.

**Comment by baryluk** [comment]
After reading manual, it looks that `Conflicts` as is already in the package is sufficient.

**Comment by dandavison** [comment]
Thanks for looking into this

**Comment by dandavison** [comment]
Thanks for looking into this @baryluk. I'm must admit that I just copied `etc/ci/before_deploy.sh` from another project (bat I think; when I started delta), and I had not given it much thought since.
