### ISSUE TITLE
🐛 Syntax highlighting doesn't work when the second file path includes a backslash on Windows

### ISSUE THREAD

**Issue by Mixaz017** [dandavison/delta#1220]
When passing a path containing backslashes `\` as the second argument (PLUS_FILE), the output have no syntax highlighting.
File contents:
![image](https://user-images.githubusercontent.com/31244102/197760024-50e5dc0f-8d1b-45d9-8f8b-1bd8aa6f2602.png)
Expected output (without backslashes):
![image](https://user-images.githubusercontent.com/31244102/197760366-3d26a1fb-3321-43dd-9180-6ca863ecd12d.png)
Actual output (with backslashes):
![image](https://user-images.githubusercontent.com/31244102/197760616-9db9e2a8-3ff5-453c-b7d3-2656fdf81205.png)
`git -v`: git version 2.38.1.windows.1 (problem still occurs with `--no-gitconfig`)
`delta -V`: delta 0.14.0
`less -V`: less 608 (Spencer V8 regular expressions)

It feels quite odd because this problem doesn't occur when the first file path (MINUS_FILE) contain backslashes, and delta is still reading file contents correctly.
A workaround is to replace backslashes with forward slashes, but it would be nice to be able to use backslashes since that is the "native" path on Windows, and PowerShell auto completion inserts backslashes so users have to manually fix the path.

**Comment by dandavison** [comment]
Thanks @Mixaz017, that certainly looks like a bug.

**Comment by Mixaz017** [comment]
Thank you @th1000s , I can confirm that the PR fixes the issue.

**Comment by Mixaz017** [comment]
The issue is gone in 0.15.0! Closing.
