### ISSUE TITLE
🐛 All themes look the same

### ISSUE THREAD

**Issue by esheehan-gsl** [dandavison/delta#1221]
When I run `delta --show-syntax-themes --dark`, all of the themes look the same.

![Screenshot of Dracula and Monokai Extended theme samples, both of which are just identical green and red](https://user-images.githubusercontent.com/85259329/198059493-cbb60b1e-ce40-4921-b024-ebf6b99308de.png)

- **Terminal**: Alacritty 0.10.1-rc1
- **Operating System**: Pop!_OS (Ubuntu) 22.04
- **Install method**: git-delta_0.14.0_amd64.deb

For reference, I have installed `bat` from the official Pop!_OS apt sources, and the themes all work there. I have also tested `delta` in GNOME Terminal 3.44.0 and the output is the same red and green that I get in Alacritty.

- [ ] Please include the raw text output from git, so that we can reproduce the problem.
      (You can use `git --no-pager` to produce the raw text output.)
- [x] A screenshot of Delta's output is often helpful also.

Thanks for filing a Delta bug report!

**Comment by magnus-ISU** [comment]
They clearly don't?

On the top, the green comment text is `#5862A2` and on the bottom `4E684E` for example.

**Comment by bizrad** [comment]
I'm seeing the same issue with delta 0.15.1, on current MacOs using iTerm2 and bat 0.23.0. Using the syntax theme in bat looks as expected, but I can't get delta to change themes using the what I've found in the documentation.
