### ISSUE TITLE
Negate --side-by-side flag (Question)

### ISSUE THREAD

**Issue by gennaro-tedesco** [dandavison/delta#1229]
In my `~/.gitconfig` I have set up `delta` to work `side-by-side`: whilst this serves most of the purposes, there are some situations where I would like to explicitly force instructions in order to display the diffs on top of each other. A typical example is when passing `delta` as a command to page diffs in scripts, or, in my specific use case, invoking it in certain neovim plugins or functions.

I have browsed the documentation but perhaps blindly missed how to negate the `--side-by-side`: I tried to pass `false/no` to it, but it generates exceptions as it clearly is not defined in such a way. Is it possible to do so or must one duplicate the general configurations necessarily (say by creating an alias with a different set of options)?

**Comment by dandavison** [comment]
Hi @gennaro-tedesco, can you take a look at the manual section and let me know if it answers your question and is clear, or if you can suggest improvements:

https://dandavison.github.io/delta/features-named-groups-of-settings.html

**Comment by gennaro-tedesco** [comment]
According to the documentation one can pass command line options on the fly with
```
export DELTA_FEATURES=+<feature>
```
and those will be momentarily added to the ones present in the config. However, by defaulting back to
```
export DELTA_FEATURES=+
```
one will default to the config itself, not to "zero features set": is my understanding correct?

Practically speaking, my configuration being:
```
...
[delta]
	features = side-by-side
	line-numbers = true
...
```
if I `export DELTA_FEATURES=+` and then `git diff` I _still_  see the side-to-side (which I wanted to remove in the first place).

**Comment by dandavison** [comment]
Oh sorry. Yes I think it is a bit awkward. If you only have one custom feature in your config then you could create one feature without `side-by-side` and one with, and select between them at command time using `DELTA_FEATURES`.

But it was suggested elsewhere that perhaps it would be helpful to have a `-` prefix syntax on the feature list meaning "remove these features but keep everything else". I haven't thought that through but superficially it sounds like it could be a good idea. If anyone wants to think it through and implement it if it makes sense then great!

**Comment by gennaro-tedesco** [comment]
Making two custom features seems to be the most practical approach, I will do so! Thank you for taking the time to answer!
