### ISSUE TITLE
🚀 Improve default colors for out-of-box usability on Mac

### ISSUE THREAD

**Issue by yang** [dandavison/delta#1235]
This is what I see when running git delta and dropping in the default configs in my gitconfig:

![image](https://user-images.githubusercontent.com/7129/201507726-f0ed1e74-9f7b-4a19-a418-5661b2269ae2.png)

```
[core]
  pager = delta

[init]
	defaultBranch = main

[interactive]
  diffFilter = delta --color-only

[delta]
  navigate = true    # use n and N to move between diff sections
  light = false      # set to true if you're in a terminal w/ a light background color (e.g. the default macOS terminal)

[merge]
  conflictstyle = diff3

[diff]
  colorMoved = default
```

Not sure if I'm missing something, new to this the tool so I haven't spent the time looking into its many knobs, but you can see that various colors are dark on dark, which is what most MacOS terminals ship with by default (including Terminal, iTerm2, Warp, etc.).

By the way, any quick hints for me while I'm here on how to make things readable?

**Comment by dandavison** [comment]
Hi @yang, I agree that the default colors are a bit hard to read against a dark terminal background. Do have a look at the custom themes that people have created: https://dandavison.github.io/delta/custom-themes.html. If you browse the PR list for the themes file you'll be able to see some screenshots: https://github.com/dandavison/delta/commits/master/themes.gitconfig

https://github.com/dandavison/delta/issues/481 is open for improving dark terminal defaults, so I'll close this one. (I use a light background and it's beautiful and very readable! )
