### ISSUE TITLE
🚀 Please consider another assets naming approach.

### ISSUE THREAD

**Issue by DarkPark** [dandavison/delta#1252]
At the momemnt your assets looks like this:
`https://github.com/dandavison/delta/releases/download/0.15.1/git-delta_0.15.1_amd64.deb`
Take a closer look - version `0.15.1` is used twice.
It's redundant and which is worst - prevent from use such links in automated scripts (for example in Ansible playbooks).
Github itself does everything to help with it. They provide helper link to always get the latest release:
`https://github.com/dandavison/delta/releases/latest/download/git-delta_0.15.1_amd64.deb`
but there is still `0.15.1` which is required to be changed manually in scripts after each release.
Is it really necessary to place this particular version in each asset file? When we inside one particular tag/release we understand that all assets connected with it and it's not necessary to repeat it again and again.

**Comment by dandavison** [comment]
Hi @DarkPark, this sounds reasonable. The reason I have not made changes like this is that I have absolutely no idea what the consequences would be. I would be happy to be educated in this area. Here is my extremely limited understanding:

1. I make "releases", which means that some executables are hosted by GitHub.
2. Some people, unknown to me, who work on packaging executables for inclusion in a variety of different package managers / distributions / operating systems, fetch these executables and do things with them.

Now, as far as I know, I have no way to enumerate the set of people that are depending on my executables, and I have no way to know what they do with them, and therefore no way to know what I would be breaking if I made a change to the URLs at which my executables are hosted, or if I were to change the contents.

**Comment by DarkPark** [comment]
@dandavison I understand.
But your current approach exclude any automation. You make hardly predictable versions. So there are nobody who relies on your assets names. They have to come to github and manually download a particular file. They probably even will not notice the change in naming )
But just to make sure you can produce releases in two naming conventions at the same time. With version and without.

**Comment by dandavison** [comment]
OK, yes we could do what you suggest.

I copied my CI/CD scripts from bat. And in general I look to ripgrep and bat when I'm in doubt about releasing Rust applications. They do the same thing that you're criticizing don't they?

https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb
https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb

**Comment by DarkPark** [comment]
These guys are next in my list ) At least `bat`, `zoxide` and `git-delta`.

**Comment by dandavison** [comment]
OK! I'll wait to see what the other maintainers say if you don't mind. I definitely agree that the `latest` link is more or less pointless if the file contains the version.

**Comment by jstelzer** [comment]
I just happened to stumble across this. First, love the tool. Bat is awesome.

That said, @DarkPark github has a perfectly usable api that supports what you're after right now. If you're already going down the ansible/automation path then use the GH api. Its way better than screen scraping and less brittle. For the latest release  of bat you're basically after something like the equivalent of:
```
 curl -s --request GET --url https://api.github.com/repos/sharkdp/bat/releases --header 'Accept: application/vnd.github+json' |jq '.[0].assets'| jq 'map(.browser_download_url)'

# Produces the below list of downloadable binaries for example
[
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_i686.deb",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-aarch64-unknown-linux-gnu.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-arm-unknown-linux-gnueabihf.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-arm-unknown-linux-musleabihf.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-pc-windows-msvc.zip",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-unknown-linux-gnu.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-unknown-linux-musl.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-apple-darwin.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-pc-windows-gnu.zip",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-pc-windows-msvc.zip",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-unknown-linux-musl.tar.gz",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_amd64.deb",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_arm64.deb",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_armhf.deb",
  "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_i686.deb"
  ```

**Comment by jstelzer** [comment]
because if you use the api, you can always get $latest vs a specific version.

**Comment by eggbean** [comment]
Yeah @DarkPark, just use the API. I have a load of github actions that update my git repository of tools which I symlink using GNU Stow.

```
          nameregex='^delta-\d[\d.]+?\d?-x86_64-unknown-linux-gnu\.tar\.gz$'
          wget -q "$(curl -s https://api.github.com/repos/dandavison/delta/releases/latest | jq -r '.assets[] | select(.name|test($name)).browser_download_url' --arg name "${nameregex}")"
          tar --wildcards --strip-components=1 -C bin/x86_64 -xvf delta-*-x86_64-unknown-linux-gnu.tar.gz delta-*-x86_64-unknown-linux-gnu/delta
          rm delta-*-x86_64-unknown-linux-gnu.tar.gz
```

**Comment by eggbean** [comment]
@DarkPark That's what I used and it's not that difficult.

https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28&tool=curl

**Comment by DarkPark** [comment]
@eggbean cool
only one question - why need to overcome something, to fight the system, to invent some good (or not so good) solutions, when you have an easy, correct, not a hack, official way of doing something?

**Comment by dandavison** [comment]
@eggbean the API frees you as a consumer of the package from dependency on the package author (me) -- it allows users like you and @eggbean to write consistent and uniform code, even when a package author like me has made a suboptimal decision, early on in the project, regarding my file names.
