### ISSUE TITLE
🚀 A CLI option to disable side-by-side mode

### ISSUE THREAD

**Issue by gotgenes** [dandavison/delta#1280]
I have `side-by-side` enabled in my `~/.git/config`, like so

```
[delta]
	side-by-side = true
```

I noticed there is a `--side-by-side` option that users can pass when invoking delta from the command line, but this option does not take a value; it works by presence/absence.

I'd like to sometimes override my config setting and disable side-by-side mode, but I do not see a command line option to do this. I was expecting something like `--disable-side-by-side` or `--no-side-by-side`, or some other "layout" option, but I didn't spot one in `delta --help`.

Am I missing the correct option to override and disable side-by-side mode from the CLI? If not, I'd appreciate considering adding such an option.

**Comment by dandavison** [comment]
Hi @gotgenes, thanks, this request makes sense. The things that's stopped me doing it is that it would bother me to have the special "disable" flag for side-by-side but not for all the other things that can be toggled. Instead, I suggest using the `DELTA_FEATURES` environment variable for this (this is what I do). I just added documentation of this technique to the side-by-side section of the manual: https://dandavison.github.io/delta/side-by-side-view.html

(but take a look at the "Features" section of the manual to understand the `+` syntax: https://dandavison.github.io/delta/features-named-groups-of-settings.html

**Comment by dandavison** [comment]
I believe the real solution here may be this open issue in the clap repo (the Rust CLI arg parsing library): https://github.com/clap-rs/clap/issues/815

**Comment by gotgenes** [comment]
@dandavison This was really helpful. I did not fully understand delta features before, and I was also unaware of the `DELTA_FEATURES` environment variable. This helps me. Thank you for your reply!

**Comment by gotgenes** [comment]
I just ran into this situation again today with [debugloop/telescope-undo.nvim](https://github.com/debugloop/telescope-undo.nvim), where I wanted to disable the side-by-side, which is still set to `true` in my Git config.

I discovered that

1. clap-rs/clap#815 is still open to this day, and
2. the Git config setting takes precedence over the `DELTA_FEATURES` environment variable.

My expected precedence for most CLI tools in terms of options, where a lower number means more overriding precedence, would be:

1. Values passed in as command-line options (`--side-by-side`)
2. Values of environment variables (`DELTA_FEATURES`)
3. Values from config files (`$XDG_CONFIG_HOME/git/config`)
4. Default values in the code of the program.

delta currently seems to have flipped the precedence of the environment variables and the config values, at the moment. Would you consider changing the order of precedence? I hope that part is under delta's control, not clap's.

**Comment by pablospe** [comment]
I ran into this while working on [diffnav](https://github.com/dlvhdr/diffnav), where we need to programmatically toggle side-by-side mode.

My config:
```ini
[delta]
    features = colibri
    side-by-side = true
```

`DELTA_FEATURES=+` (as mentioned in the [docs](https://dandavison.github.io/delta/side-by-side-view.html)) didn't work for me — it only controls named features, not the `side-by-side = true` setting in `[delta]`.

**Workaround**: git config uses last-value-wins, so you can create a file that includes your original config and overrides `side-by-side`:

```ini
[include]
    path = ~/.gitconfig
[delta]
    side-by-side = false
```

Then use `delta --config /path/to/override.gitconfig`. The `side-by-side = false` at the end overrides the `true` from the included config, while preserving all themes and features.

**Comment by dandavison** [comment]
Hi @pablospe. Using `DELTA_FEATURES=+` to toggle side-by-side does work, but you must not include `side-by-side` in your `.gitconfig` on disk.

Personally, I use the technique described here: https://dandavison.github.io/delta/tips-and-tricks/toggling-delta-features.html But I think it might make sense for someone to move that functionality into delta (`eval "$(delta <CLI_TBD_HERE>)"` ?) rather than using some random Python script...

**Comment by pablospe** [comment]
> Hi [@pablospe](https://github.com/pablospe). Using `DELTA_FEATURES=+` to toggle side-by-side does work, but you must not include `side-by-side` in your `.gitconfig` on disk.

Thanks! I am using it inside another project, [diffnav](https://github.com/dlvhdr/diffnav) and it doesn't work, I will investigate why.


> The things that's stopped me doing it is that it would bother me to have the special "disable" flag for side-by-side but not for all the other things that can be toggled

The `eval $(delta ...)` doesn't help in my case, if I understood correctly. Based on this comment, would you accept a PR adding all the `--no-*` flags? Here the PR: https://github.com/dandavison/delta/pull/2095
:)
