### ISSUE TITLE
🚀 Improve ripgrep with delta output layout

### ISSUE THREAD

**Issue by XhstormR** [dandavison/delta#1289]
Hi, I'm currently using delta with ripgrep, here is my delta config：
```
[delta]
    navigate = true
    line-numbers = true
    diff-so-fancy = true
    syntax-theme = Dracula
    plus-style = syntax bold auto
    minus-style = syntax bold auto
    grep-match-line-style = syntax bold auto
    grep-context-line-style = syntax bold auto
```

It can display syntax highlighting normally, but when used with ripgrep, no layout is applied, causing the code and path to be displayed in one line, and the display width is too large Big. 

The file path shows multiple lines, which is too redundant, we should apply layout to the ripgrep output as well.

Example:
`rg 'LexiconGroup' --json | delta` ：
![image](https://user-images.githubusercontent.com/10527522/213975184-21bc2b19-1718-4f53-9f82-184b013110f9.png)

`rg 'LexiconGroup'` ：
![image](https://user-images.githubusercontent.com/10527522/213975232-db2aa9a7-d344-483a-a6f7-ed5220a8f505.png)

**Comment by shurane** [comment]
@XhstormR  were you able to figure this out? I'm having similar issues when running `ripgrep --json` with delta.

**Comment by XhstormR** [comment]
@shurane no, currently i have to use rg only for better view

**Comment by dandavison** [comment]
I can't think of a blocker preventing someone adding an option to format delta's grep output as ripgrep does. Note that ripgrep only does that when output is going to screen (i.e. for a human to read/click on); when it's redirected to another process, ripgrep produces the output format with the filename on every line.

**Comment by dandavison** [comment]
And I think I'd like it also -- having more screen space to display the code.

**Comment by dandavison** [comment]
WIP branch that is close to implementing this: https://github.com/dandavison/delta/pull/1410

**Comment by dandavison** [comment]
If you get a chance to try the latest release I'd appreciate knowing whether it's doing what you want and whether you have ideas for improvements.

**Comment by XhstormR** [comment]
> If you get a chance to try the latest release I'd appreciate knowing whether it's doing what you want and whether you have ideas for improvements.


Thanks for the update, I have downloaded the latest version to use with ripgrep, but i found that the syntax highlighting is missing compared to the previous version.

`rg 'LexiconGroup' --json | delta`:
<img width="707" alt="image" src="https://github.com/dandavison/delta/assets/10527522/e3e2cf85-4c3b-4460-962b-2ab5174ef1b0">

**Comment by dandavison** [comment]
Thanks for testing! Hm, that must be something at your end. Can you try

```
rg --json LexiconGroup | delta --no-gitconfig
```

Does `git show | delta` have syntax highlighting for you?

**Comment by eugenesvk** [comment]
Just checked this, seems to be working fine, syntax highlighting is preserved in delta 0.16.5 at least with my config, thank you for adding this!

**Comment by XhstormR** [comment]
After adding `--no-gitconfig`, it now works. 

Yes, Command `git show | delta`' syntax highlighting just works fine.

This is my delta config:
```
[delta]
    navigate = true
    line-numbers = true
    diff-so-fancy = true
    syntax-theme = Dracula
    plus-style = syntax bold auto
    minus-style = syntax bold auto
```

**Comment by XhstormR** [comment]
It seems to conflict with `diff-so-fancy=true` flag.

**Comment by dandavison** [comment]
Yes, diff-so-fancy means "Emulate diff-so-fancy as closely as you can (and accordingly don't do any syntax highlighting)".

Thanks everyone! Don't hesitate to let me know if you come across any problems with the grep features.

**Comment by shurane** [comment]
Works for me too! Thanks @dandavison.

![image](https://github.com/dandavison/delta/assets/541433/0f70439b-f1d8-402a-8267-1f92cb999fba)

I was looking at how to implement this a few months ago. Thought it would be a simple change, but your PR looks more elegant than the hacky approach I was thinking of.
