### ISSUE TITLE
🚀  Can you support a case insensitive and ignore whitespace

### ISSUE THREAD

**Issue by bozlo** [dandavison/delta#1290]
Hi, I love this tool.
Can you support a case insensitive diff and ignore whitespace diff as well?

**Comment by dandavison** [comment]
Hi @bozlo, delta is just a visualizer for diffs -- it doesn't compute diffs itself. So I think the answer is "yes" -- if you create a case-insensitive diff, or a whitespace-ignored diff, and pass it to delta, it should render it nicely. If it doesn't then that's probably a bug. Do you have an example?

**Comment by bozlo** [comment]
Thanks, @dandavison , How would you like to setup git config for case-insensitive diff?

**Comment by bozlo** [comment]
I found a way to do this.
```
git config --global difftool.idiff.cmd 'diff -u --unified=3 --ignore-case -w $LOCAL $REMOTE | delta'
git config --global difftool.prompt 0
git config --global alias.idiff 'difftool --tool idiff'
```
