### ISSUE TITLE
🚀 Don't show line number for signature, it is confusing

### ISSUE THREAD

**Issue by Rizhiy** [dandavison/delta#1306]
Currently, the first number of diff is shown next to block start, this is confusing since it looks like a line number, which it is not, e.g.:
![image](https://user-images.githubusercontent.com/5617397/219979049-b5267ddc-88c3-4223-aeb8-c1b786a1671d.png)

116 Is the number at which the shown code starts, but the way it is currently formatted makes it look like it is the number where the block starts (`def round_dt(`), which is not the case.

Need to either change the output such that it is not confusing, or just hide it completely, especially if line numbers are enabled.

**Comment by dandavison** [comment]
Hi @Rizhiy, this is controlled by `--hunk-header-style` -- see `-delta --help`. E.g. you can use

```
--hunk-header-style syntax
```

to disable line numbers.

**Comment by gtirloni** [comment]
This removes the number but still indents the code. It's no big deal but made me think the YAML file it was showing had the wrong indent.
