### ISSUE TITLE
🚀 Make help terminal-width-sensitive

### ISSUE THREAD

**Issue by FGasper** [dandavison/delta#1316]
I generally use 80-column terminal windows, and the help text currently looks thus:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/844867/221735007-cca8e922-bf73-425f-b321-c56bc4f2bb8b.png">

It would be awesome if the help text deduced my terminal width automatically and line-wrapped text accordingly.

**Comment by dandavison** [comment]
It looks like the CLI library that delta uses (`clap`) has a `wrap_help` feature: https://github.com/search?q=repo%3Aclap-rs%2Fclap%20wrap_help&type=code Perhaps this will require finishing off this PR: https://github.com/dandavison/delta/pull/1253
