### ISSUE TITLE
🚀 Toggle side-by-side mode with a key

### ISSUE THREAD

**Issue by joshtriplett** [dandavison/delta#1330]
I'd love to toggle between normal-diff and side-by-side mode using a key. Sometimes, when browsing a diff, some sections make more sense side-by-side, while other sections may make more sense as a traditional unidiff. For that matter, toggling to traditional unidiff helps with copy-and-paste.

Thank you for delta; I'm really enjoying it!

**Comment by joshtriplett** [comment]
One possible approach for this: keybindings to toggle between delta "features", together with logic in delta to ensure it keeps displaying the same location after changing features.

**Comment by dandavison** [comment]
Hi @joshtriplett, with delta, and its standard pager less, you have to quit and re-invoke the delta process with the new options. Keypresses are received by the pager application and, currently, the only pager I'm aware of that works well with delta is less (and indeed some delta features like navigation are implemented in a way that only works with less or something recreating its interface very closely). Having the ability to attach arbitrary behavior to keypresses feels more like the domain of the git "TUIs" and there are some of those that can be used with delta, so it may be worth looking that them, e.g. https://github.com/jesseduffield/lazygit and https://github.com/extrawurst/gitui (not sure the latter can use delta yet). That said, I think less is due for some competition! I know there are some new pager projects, and I'd be interested to hear if anything clever can be done with them.

But at the end of the day, delta itself is a program that reads in stdin, writes to stdout, and exits. Like cat and grep, as opposed to a persistent interactive TUI.

**Comment by joshtriplett** [comment]
@dandavison Fair enough; thank you.
