### ISSUE TITLE
How to configure context lines or full-file diff?

### ISSUE THREAD

**Issue by jantari** [dandavison/delta#1346]
This feature probably exists already but I searched `--help`, the website and past issues and just couldn't find it.

In addition to integrating it with git I also like to use delta for diffing two files as well with `delta file1 file2`.

When using it like this, how can I configure it to not only show chunks of changes / diffs but output the entire file(s)? Alternatively, a configurable amount of context-lines would work too as I could just set it to 99999999 or something.

Usecase: For example I may be diffing version 1 vs version 2 of an OpenAPI spec file and seeing chunks like this:

```
─────┐
101: │
─────┘
│ 101│        "msi",                                                      │ 101│        "msi",
│ 102│        "appx",                                                     │ 102│        "appx",
│ 103│        "exe",                                                      │ 103│        "exe",
│    │                                                                    │ 104│        "zip",
│ 104│        "inno",                                                     │ 105│        "inno",
│ 105│        "nullsoft",                                                 │ 106│        "nullsoft",
│ 106│        "wix",                                                      │ 107│        "wix",
```

in the side-by-side diff just doesn't tell me anything - it looks like an additional value was added to an enum in the version on the right, but I have no clue where or which enum.

**Comment by dandavison** [comment]
Hi @jantari, to have the full range of diff options do

```
git diff -U9999999 /tmp/a /tmp/b | delta
```

`delta file_a file_b` is just a shortcut for that that doesn't let you pass options.

**Comment by jantari** [comment]
Thank you, I knew I was missing something and in this case I didn't know I could even use `git diff` on files that aren't in git

**Comment by dandavison** [comment]
> I didn't know I could even use `git diff` on files that aren't in git

Yup, I don't think I knew that either before implementing this. Useful though!
