### ISSUE TITLE
Add option to not show hunk headers

### ISSUE THREAD

**Issue by Yantrio** [dandavison/delta#138]
I think it would be a good idea to be able to disable the hunk highlighting in certain cases.
In javascript for example, some code is outside of the hunk that's highlighted, and this can get a bit confusing.

For example with the following code
```js
function test() {
    console.log("go go go");
}


test();
console.log("this isn't in the hunk!")
```

when adding the last line, the git diff detects the hunk for `function test()` and this can be a bit misleading as all changes are outside of hunks.

git diff result:
![ss](https://user-images.githubusercontent.com/237469/80466428-7441de80-8934-11ea-8cbc-52b984ed659f.png)

I think it would be best if i could disable hunks for a specific language (in this case anything that can have code outside of a hunk.

**Comment by dandavison** [comment]
Hi @Yantrio, thanks for opening an issue. So, to be clear, is your suggestion to offer an option which tells delta to hide the hunk header entirely?

The git documentation of the hunk header is here: https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header Note that in git/unified diff terminology a "hunk" is a region of nearby changes: it doesn't correspond to a syntactic element of the language. And the "hunk header" is a line that git pulls out in an attempt to identify the syntactic element within which the hunk falls. I agree with you that it's quite common for the header to fail to identify an appropriate syntactic element (and in your case there is none; it's like the header should say `<Top Level>` or something), but that is of course an issue with git, not delta. As the git docs say, it is possible to play around with the regular expression determining how that header is identified and formatted.

For your example, the raw output coming from git is this. The hunk header is on line 5. You can use delta's `--hunk-style` option to change the way that hunk header is displayed, but delta does not currently have an option to get rid of it entirely. Seeing as git's hunk header is a bit sketchy, I think I agree with you that an option not to display it is reasonable.

```
$ git --no-pager diff
diff --git a/z.js b/z.js
index 6b2a50f..cf70fdb 100644
--- a/z.js
+++ b/z.js
@@ -4,4 +4,4 @@ function test() {
 
 
 test();
-
+console.log("this isn't in the hunk!")
```

**Comment by dandavison** [comment]
Hi @Yantrio, sorry I forgot about this issue, but this is available in delta now: `--hunk-header-style omit` or in gitconfig

```gitconfig
[delta]
    hunk-header-style = omit
```

By the way, in #228 there's some discussion about git's hunk headers / `xfuncname` feature. I'm intending to look into it more with the aim of seeing if delta docs can e.g. point users towards a better collection of default xfuncnames than git's defaults, or otherwise improve the xfuncname experience.
