### ISSUE TITLE
🐛 Very low contrast with --light

### ISSUE THREAD

**Issue by WhyNotHugo** [dandavison/delta#1403]
Days are getting too sunny which has led me to configure a daytime light theme on my terminal so I can see something through all that reflection/glare.

I tried all the light themes that my terminal ships, but `delta` has very low contrast with all of them.

## Issue

When running `git --no-pager show | delta --light`, a lot of text has very low contrast, pretty much regardless of the specific theme in use.

There's a few issues:

- Using "light yellow" for text on a light theme (e.g.: the author and date) is kind of like using "dark grey" on a dark theme.
- The orange on the commit message is rather low contrast in all of them (not unreadable, but also not easy to read).
- Using light red with white text to highlight deleted lines is unreadable in almost all themes.

## Screenshots

I generated these with:

```sh
for THEME in $(cat ~/candidate-themes ); do export THEME; echo $THEME; foot --config /usr/share/foot/themes/$THEME --font="monospace:size=10" -H bash -c "echo $THEME; git --no-pager show | delta --light" ; done
```

Where `~/candidate-themes` has all the light themes that ship with [`foot`](https://codeberg.org/dnkl/foot):

```
gruvbox-light
material-amber
modus-operandi
paper-color-light
selenized-light
selenized-white
solarized-light
tempus-dawn
tempus-day
tempus-fugit
tempus-past
tempus-totus
tokyonight-day
```

![image](https://user-images.githubusercontent.com/730811/234265280-eb2e195c-2423-4ad2-9f50-39f6b974e4dc.png)

![image](https://user-images.githubusercontent.com/730811/234265295-4ff3b264-6151-473b-8386-659e5c7b87d8.png)

![image](https://user-images.githubusercontent.com/730811/234265313-9d0c0e2c-43d3-4c6e-a5ac-b45d1cbee5a4.png)

![image](https://user-images.githubusercontent.com/730811/234265340-275bc2ee-d6e5-4a13-b5af-0ed8cbac7d24.png)

![image](https://user-images.githubusercontent.com/730811/234265354-7ad108aa-5f31-4b9e-bea3-8e022b57a7fe.png)

![image](https://user-images.githubusercontent.com/730811/234265375-a417323c-9479-4224-8536-f6f44060217b.png)

![image](https://user-images.githubusercontent.com/730811/234265392-63d2f42c-6f67-4f2e-ba4a-e34f48ba95de.png)

![image](https://user-images.githubusercontent.com/730811/234265424-de185470-e451-4a1c-a039-454a77a56a67.png)

![image](https://user-images.githubusercontent.com/730811/234265451-7800f45e-ae22-49b2-a883-f1c27da3bad5.png)

![image](https://user-images.githubusercontent.com/730811/234265476-221271f7-ef42-4280-a891-97d368060ed2.png)

![image](https://user-images.githubusercontent.com/730811/234265499-a909d223-b490-4f71-ac15-e8acb4f6ecd9.png)

![image](https://user-images.githubusercontent.com/730811/234265506-f96789b5-da56-48b2-bb19-fcfcfd2a6caf.png)

![image](https://user-images.githubusercontent.com/730811/234265527-3f22c0af-acd6-46b3-bed5-ec64634c3618.png)

**Comment by WhyNotHugo** [comment]
Nice! That all has perfect contrast and is super easy to read!

I'm trying to avoid adding any light-theme-specific overrides into my git-config because I only use light theme when there's a lot of light around (e.g.: past sundown or when it's dark I prefer a dark theme; otherwise it's too much light directly into my eyes in a dark environment).

Do you think it's reasonable to include these tweaks automatically when `light = true`?

**Comment by dandavison** [comment]
> Do you think it's reasonable to include these tweaks automatically when light = true?

So Delta's answer to "how do I enable certain other things conditional on on setting" is what it calls "[features](https://dandavison.github.io/delta/features-named-groups-of-settings.html)". The idea is you would do something like

```gitconfig
[delta "my-light-theme-settings"]
    light = true
    commit-decoration-style = blue ol
    commit-style = raw
    file-style = omit blue
    hunk-header-decoration-style = blue box
    hunk-header-file-style = red
    hunk-header-line-number-style = "#067a00"
    hunk-header-style = file line-number syntax
```

and then enable them en bloc with e.g.

```
export DELTA_FEATURES=+my-light-theme-settings
```

As for the ideal approach, I feel like I haven't fully thought it through. In addition to delta settings, there are terminal emulator settings one may want to change in conjunction with this. There are some threads in delta issues where I and others have messed around with scripts and hacks to change everything in lock-step.

**Comment by WhyNotHugo** [comment]
Even with the above example, I'm getting a lot of "white on white" text.

**Comment by dandavison** [comment]
Can you paste a screenshot of `delta --show-config`?

Mine looks like

<img width="756" alt="image" src="https://github.com/dandavison/delta/assets/52205/de79266d-65e5-4ee4-a97e-05b8ca8d0f7a">

**Comment by WhyNotHugo** [comment]
`delta --show-config`, dark mode:

![image](https://github.com/dandavison/delta/assets/730811/95e0218b-9cd6-4231-ac65-2f4e36248c77)

`delta --show-config`, light mode:

![image](https://github.com/dandavison/delta/assets/730811/9baf2f20-ef89-497b-a4c2-6026d18ab880)

`git-log`, dark mode:

![image](https://github.com/dandavison/delta/assets/730811/7dc8db57-a5dc-479e-a2c8-a5e542209442)

`git-log`, light mode:

![image](https://github.com/dandavison/delta/assets/730811/a901b40c-eb85-48c4-a232-c5e971fab82f)

As you can see, `--show-config` doesn't render anything white-on-white, but `git log` does.
