### ISSUE TITLE
Unable to use Solarized (dark) theme

### ISSUE THREAD

**Issue by arlopurcell** [dandavison/delta#142]
Set up my git config as described in the README:
`
[core]
    pager = delta --dark --plus-color="#012800" --minus-color="#340001" --theme="Solarized (dark)"
`
but using "Solarized (dark)" theme

Then when running `git diff`, i get this error:
`delta --dark --plus-color=#012800 --minus-color=#340001 --theme=Solarized (dark): 1: delta --dark --plus-color=#012800 --minus-color=#340001 --theme=Solarized (dark): Syntax error: "(" unexpected`

Perhaps renaming the theme to something like "Solarized Dark" would fix the issue?

**Comment by dandavison** [comment]
Hi @arlopurcell, thanks for the report and sorry about this! Can you try with single quotes:

```
--theme='Solarized (dark)'
```

However, leave your color hex codes with double quotes...

I've added a note to the README, but it's a bit weird that I'm saying that color hex codes need to be in double quotes yet theme names need single quotes if they contain spaces. I'll look into whether I'm doing something wrong.

**Comment by arlopurcell** [comment]
that fixes it! thanks for your help!

**Comment by dandavison** [comment]
OK cool, no problem!

(The theme names come from Sublime syntax definition repositories, and I want Delta to behave the same as [bat](https://github.com/sharkdp/bat/), so I think I want to leave the theme names as they come).

**Comment by WChrisGraham** [comment]
Just a note that I don't see a mention of how to quote theme names in the the readme or in a recent PR.
(If I thought you'd want me messing with your dox for something that simple I'd add it.)

Nice tool!

(for the record, I'm finding any spaces need to be quoted, at least in gitconfig)

**Comment by dandavison** [comment]
Thanks @WChrisGraham! I'd forgotten to push that. There now. Hopefully it's true on Windows.

![image](https://user-images.githubusercontent.com/52205/80548480-0673d200-8989-11ea-92ff-b93113b47ce1.png)
