### ISSUE TITLE
🐛 Flickering when using ov as a pager and hyperlinks=true

### ISSUE THREAD

**Issue by orf** [dandavison/delta#1423]
I'm using [ov](https://github.com/noborus/ov) as my pager, configured via the `PAGER` env var.

After configuring this and running `git log` on homebrew, `ov` begins to flicker (see the video). When I run `git -c core.pager=ov log ...` the flickering does not occur, which implies it's an issue with delta rather than ov.

Running `git -c delta.hyperlinks=false log ...` makes the flickering stop.

I'm usng MacOS 13.3, `delta 0.15.1` (via homebrew), fish and iterm2.

https://github.com/dandavison/delta/assets/1027207/ef8b8e9a-f56e-470f-88c2-db558dbfeb87

**Comment by dandavison** [comment]
Hi @orf, that's an interesting finding -- have you reported it to the ov author? It sounds like you must have found something not quite right in ov. I suspect there's not a delta bug here -- I believe delta's hyperlinks are correctly constructed ( they work in terminal emulators) and delta is just writing to the pager process's stdin. Can you reproduce it by passing non-delta content containing hyperlinks to ov?

**Comment by orf** [comment]
I haven’t - I opened this here before I found that the hyperlinks configuration option causes this.

I will open an issue on ov and see what they say. Thanks!

**Comment by dandavison** [comment]
I can reproduce it with

```
while true; do ls --hyperlink=always; done | ov
```

```
$ ls --version
ls (GNU coreutils) 9.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
```
