### ISSUE TITLE
0.16.5 build failure on NetBSD🐛 

### ISSUE THREAD

**Issue by 0323pin** [dandavison/delta#1431]
Hi,

Trying to update our package to the latest release and getting a build failure.
This is because we have moved to `libgit2-1.6.x`.
Would it be possible to update the `git2` and `libgit2-sys` crates required by `delta`, so that we can update our package?

Thanks!

**Comment by dandavison** [comment]
Hi @0323pin, I've updated those packages in master 1c37bfa85bc192409e9855c3bf4813db74e2be7b since the 0.16.5 release. Is that any use to you or do you need a delta release?

**Comment by 0323pin** [comment]
@dandavison thanks!

> do you need a delta release?

Nah, it's fine. I can either pull from that commit or apply a local patch to the release. I'll fix it when I have some free time.

**Comment by 0323pin** [comment]
@dandavison fixed, https://mail-index.netbsd.org/pkgsrc-changes/2023/06/04/msg276137.html
