### ISSUE TITLE
🚀Support --color-moved-ws

### ISSUE THREAD

**Issue by andrey-bolduzev** [dandavison/delta#144]
I'm personally interested in [`--color-moved-ws=allow-indentation-change`](https://git-scm.com/docs/diff-options/2.19.0#Documentation/diff-options.txt-allow-indentation-change) which in combination with `--colorMoved=dimmed_zebra` (or similar) is a great way of enabling pure indentation changes to not be marked as 20 lines removed and 20 lines added.

**Comment by dandavison** [comment]
Thanks for the proposal @andrey-bolduzev! Linking #72 but I know that you've seen that one already :)

**Comment by andrey-bolduzev** [comment]
> Thanks for the proposal @andrey-bolduzev! Linking #72 but I know that you've seen that one already :)

Thank you! Yes, I had that feature proposal in mind but I figured I would log another one since `--color-moved-ws` is somewhat different.

**Comment by dandavison** [comment]
Just to be totally explicit, this feature request only becomes relevant if #72 is implemented, right? (I'm trying to plan work on existing issues).

**Comment by andrey-bolduzev** [comment]
> Just to be totally explicit, this feature request only becomes relevant if #72 is implemented, right? (I'm trying to plan work on existing issues).

I think you're correct. I just played with it, and `--color-moved-ws` seems to have no visible effect without `--color-moved` also set. Thank you.

**Comment by dandavison** [comment]
Hi @andrey-bolduzev, this is fixed in master and will be released soon. Detailed notes here: https://github.com/dandavison/delta/issues/72#issuecomment-667558468. (If it's easy for you to build Delta on master and check it's working for you, that's always very helpful.)
