### ISSUE TITLE
🐛 rg --json input: a highlighted match after a tab is in the wrong position

### ISSUE THREAD

**Issue by th1000s** [dandavison/delta#1441]
`echo -e "\t_abcABC987" >| foo; rg --json ABC98 foo | delta` using the current master:

![image](https://github.com/dandavison/delta/assets/78380144/0d1e714d-dfd3-4fc3-9c37-199ca0690418)

It seems the submatches from the json need to take the tabwidth into account.

**Comment by charego** [comment]
@dandavison @th1000s I believe this issue can be closed (fixed by https://github.com/dandavison/delta/pull/1507).

**Comment by dandavison** [comment]
Yes, that's correct, thanks!

<img width="614" alt="image" src="https://github.com/dandavison/delta/assets/52205/bfde74ae-4995-4228-a811-326f0ee97fd9">
