### ISSUE TITLE
🚀 Add option to show complete file, even if there are no differences

### ISSUE THREAD

**Issue by zergar** [dandavison/delta#1455]
Hei,

I need to show to someone less familiar with code that there are (almost) no differences between two files. In this case, right now delta will return without any output or print only only the very few changed lines. For my use case though it would be much more convincing, if I could show the complete files even if there are no or only one or two differences.

I've looked around a fair bit, and haven't found any option that would increase the amount of lines shown before or after a difference, or would force delta to always print the whole file. Am I missing something, or is this something that could be implemented?

**Comment by dandavison** [comment]
Hi @zergar, as long as there is some difference between the files, then you can use the `-U` option of `diff` (and git diff). For example

```
diff -u -U 999999 src/main.rs src/main.cp.with.change.rs | delta --side-by-side
```
