### ISSUE TITLE
🚀 replace /Users/username/path with ~/path

### ISSUE THREAD

**Issue by eugenesvk** [dandavison/delta#1476]
Would be nice to be able to shorten paths a bit by using a `~` prefix

**Comment by th1000s** [comment]
Do you mean in the `git diff` output? If so, wouldn't that imply a `.git` folder directly in root? Still, you could set the pager to first pipe the input through `sed` to replace one home path with `~`:

```sh
pager = sh -c "'sed s,/Users/name/,~/, | delta'"
```

**Comment by dandavison** [comment]
Delta actually has this functionality built in, so you can use

```gitconfig
[delta]
    file-transformation = "s,/Users/username/,~,"
````

However, I do have the same question as @th1000s: can you give an example command that is producing file paths like `/Users/username/path`?

**Comment by eugenesvk** [comment]
I meant direct diff with delta `delta '~/Dev/1/file—2.txt' '~/Dev/1/file—1.txt'`

Sorry for having missed the transform config (the irony is I use every single one of the other `file-` configs)

**Comment by dandavison** [comment]
OK I see, thanks -- no problem!
