### ISSUE TITLE
Delta appending ^[[OK at the end of each modified line ( color related i think )

### ISSUE THREAD

**Issue by ippsav** [dandavison/delta#1490]
![20230727_09h31m05s_grim](https://github.com/dandavison/delta/assets/69125922/84d3029d-49aa-4a79-a340-56a6050a919c)

Delta version: `delta 0.16.5`

**Comment by dandavison** [comment]
Hi @ippsav, this is likely to be a problem with your environment (terminal emulator) since it hasn't been reported by other users.

- Which terminal emulator are you using?
- Are you using tmux or screen?
- What OS are you using?

Please try a different terminal emulator and see if you see the same problem.

**Comment by ippsav** [comment]
Terminal: alacritty
Session manager: tmux
OS: Arch linux

**Comment by sophiabrandt** [comment]
I'm encountering the same issue when I use the fish shell.

It seems to make no difference if I use tmux or not.

Emulator: kitty
OS: macOs M1

It works when I use zsh with iterm2.
It also works with zsh and kitty.

I've been searching through the fish shell github, but haven't found an obvious solution.

Are you using fish shell as well @ippsav ?

**Comment by dandavison** [comment]
Hi @sophiabrandt, @ippsav. Hm, you probably already know this but for the record that code is ANSI CSI code "Erase in Line" (https://en.wikipedia.org/wiki/ANSI_escape_code). Delta uses it to cause the background colour to extend to the right-hand edge of the terminal window.

FWIW I can't reproduce it with fish 3.6.1, Alacritty, MacOS M2, with or without tmux.

**Comment by ippsav** [comment]
No i am using zsh

**Comment by sophiabrandt** [comment]
@dandavison in any case, many thanks for your work on delta. ❤️

**Comment by michenriksen** [comment]
@ippsav @sophiabrandt do you use [`most`](https://www.jedsoft.org/most/) or maybe some other fancy pager? (`echo $PAGER`)

I saw the same strange rendering problem, and I finally narrowed it down to `export PAGER='most'` in my `.zshrc` file.

I fixed it by configuring delta to use less in my `.gitconfig`:

```gitconfig
[delta]
  pager = less
```

@dandavison I found this in the [README for bat](https://github.com/sharkdp/bat#using-a-different-pager):

> _Note: If PAGER is more or most, bat will silently use less instead to ensure support for colors._

Maybe it would make sense for delta to do the same?

**Comment by sophiabrandt** [comment]
@michenriksen yes! That's it! Thank you. Never would have thought of the pager... 😅

**Comment by ippsav** [comment]
@michenriksen Worked for me as well thanks man !

**Comment by dandavison** [comment]
Excellent, thanks @michenriksen! Yeah I'm not quite sure where to slot in this advice; I don't think the README instructions should recommend
```
[delta]
    pager = less
```
Since IIRC that overrides less config the user might have e.g. in the `LESS` env var.

I think that the best solution for this is @clnoll's `delta --doctor` command: https://github.com/dandavison/delta/pull/1193. That will alert the user if they are not using `less`.

**Comment by michenriksen** [comment]
@dandavison yeah, adding `pager = less` in the README instructions would probably not be the best, that's why I wondered if it makes sense for delta to do [what bat does](https://github.com/sharkdp/bat#using-a-different-pager):

> _Note: If PAGER is more or most, bat will silently use less instead to ensure support for colors._

**Comment by dandavison** [comment]
@michenriksen Right, thanks I think that's a great idea. Researching briefly, it looks like if we change the entry for the bat crate in Cargo.toml to

```toml
bat = { version = "0.23.0", default-features = false, features = ["minimal-application", "paging", "regex-onig"] }
```

Then the `bat` function [`get_pager_executable`](https://docs.rs/bat/0.23.0/bat/config/fn.get_pager_executable.html) is available to us. I wonder if we can modify the delta code that invokes the pager to inherit the logic you suggest from bat, without copying more code from bat.

Backstory: when I first wrote delta, bat didn't exist as a library, and I copied/vendored some bat code dealing with invoking the pager (delta also uses bat's awesome collection of syntax highlighting assets of course). Subsequently, bat became available as a library, and as they make things available in the library, delta is trying to use them from the library. Delta's copied/vendored bat code is in `src/utils/bat/`.

If anyone would like to make the change I'm suggesting here that would be fantastic.

**Comment by dandavison** [comment]
[Closed since this issue is solved, but very happy for discussion to continue.]

**Comment by ippsav** [comment]
@dandavison that sounds like something nice to try to do, i ll give it a try !

**Comment by dandavison** [comment]
@ippsav excellent, thanks!

**Comment by ippsav** [comment]
@dandavison  I ve been reading the code trying to get the hang of it, i ll be making a pr soon i ll keep you updated it seems to be solved !

**Comment by ippsav** [comment]
@dandavison ready for review keep me updated !

**Comment by michenriksen** [comment]
Nice one, @ippsav! 👏

**Comment by ippsav** [comment]
@michenriksen thanks man
