### ISSUE TITLE
Add vim's torte color scheme➕

### ISSUE THREAD

**Issue by mrzv** [dandavison/delta#151]
There is a wonderful dark color scheme in Vim, called `torte`. I'd love to see it in delta.

**Comment by dandavison** [comment]
Hi @mrzv sorry for being slow to respond here. Is it available in `.tmTheme` format? Delta ships with the same themes as [bat](https://github.com/sharkdp/bat/#adding-new-themes), and if you add custom themes using [bat's custom themes](https://github.com/sharkdp/bat/#adding-new-themes) mechanisms, they are automatically available in delta also. So for this to happen we need torte in `.tmTheme` format, in which case you could either add it as a custom theme for yourself or (better) open a PR against bat adding it as one of the themes that bat ships with.

https://github.com/dandavison/delta#supported-languages-and-themes

**Comment by dandavison** [comment]
@mrzv I'm going to close this for now until we find a port of `torte` to `.tmTheme` format.
