### ISSUE TITLE
🐛 AUR package failing

### ISSUE THREAD

**Issue by Zeioth** [dandavison/delta#1510]
AUR package failing to compile due to "use of unestable feature is_terminal".

![screenshot_2023-08-16_01-56-24_301354839](https://github.com/dandavison/delta/assets/3357792/8e0d3874-ef26-4388-a921-0d5f74098233)

**Comment by nickelc** [comment]
The `IsTerminal` trait was stabilized with Rust 1.70 (2023-06-01).
If you update your rust compiler (`rustup update stable`) then it should work.

**Comment by Zeioth** [comment]
@nickelc Now I get a test failing and I can't still install, but what you said fixed that specific error thank you.
![screenshot_2023-08-17_05-56-51_226485255](https://github.com/dandavison/delta/assets/3357792/e07e65fb-34b0-4ce1-9555-931c7a597faa)

**Comment by Zeioth** [comment]
installed correctly with:

`paru -S git-delta` again. Closing issue.
