### ISSUE TITLE
🐛 Vue SFC syntax highlighting does not work, differs from `bat` output

### ISSUE THREAD

**Issue by pm0u** [dandavison/delta#1546]
When diffing Vue SFC files, delta does not properly syntax highlight - even when the diff is a syntax complete file.

```
diff --git ***/***/test.vue
index e69de29bb..ef35203ac 100644
--- a/***/***/test.vue
+++ b/***/***/test.vue
@@ -0,0 +1,15 @@
+<template>
+  <div class="className" />
+</template>
+
+<script setup>
+import fs from 'node:fs'
+
+fs.readFile()
+</script>
+
+<style>
+.css {
+  background: transparent;
+}
+</style>
```
- [ ] A screenshot of Delta's output is often helpful also.

<img width="957" alt="image" src="https://github.com/dandavison/delta/assets/410558/c286981c-793a-48e7-b1f3-c9bf64d2f4da">

bat for the same file
<img width="958" alt="image" src="https://github.com/dandavison/delta/assets/410558/0e62ebeb-efc1-4cae-9e74-740a5e3a52c1">

**Comment by pm0u** [comment]
Edit: take it back, it appears to syntax highlight correctly outside of the diff contents (that's probably my bad) however CSS does not seem to highlight correctly.

<img width="956" alt="image" src="https://github.com/dandavison/delta/assets/410558/c3338c80-3955-45a1-94e9-1647e0f3a9da">

**Comment by pm0u** [comment]
Closing - this was because in my delta config I had overrode the foreground colors for `plus`/`plus-emph` - this needed to be `syntax` - woo!

Great tool!

**Comment by pm0u** [comment]
Reopening as I am in fact having some issues still with Vue SFC - both in JS and CSS.. will update as I can.

**Comment by pm0u** [comment]
Ok I believe I've isolated this, and I think I have seen similar issues - 

If the diff does not include the `<script>` tag then the JS is not correctly highlighted.

Working (contents from blank file)

<img width="958" alt="image" src="https://github.com/dandavison/delta/assets/410558/54305df3-346e-4673-a91b-f46cba74f4f7">

```vue
@@ -0,0 +1,15 @@
+<template>
+  <div class="className" />
+</template>
+
+<script setup>
+import fs from 'node:fs'
+
+fs.readFile()
+</script>
+
+<style>
+.css {
+  background: transparent;
+}
+</style>
```

Not working - added a console.log() far away from the script tag opening

<img width="955" alt="image" src="https://github.com/dandavison/delta/assets/410558/85a38452-237c-4e0a-92c5-87484b3a3722">

```
@@ -15,6 +15,8 @@ console.log('')
 console.log('')
 console.log('')
 console.log('')
+console.log('')
+
 console.log('')
 </script>
 ```
 
 Full file in bat: 
<img width="959" alt="image" src="https://github.com/dandavison/delta/assets/410558/72e4b11a-cf02-40af-9c39-40488c0d508c">

**Comment by pm0u** [comment]
related: https://github.com/dandavison/delta/issues/162

Unsure if a similar workaround is available for Vue SFC

**Comment by pm0u** [comment]
I do not believe a similar fix would work, as the issue is that the opening and closing tags are needed to understand what part of the file we are in (I think).

Curiously when I force bat to only output lines that exclude the opening it still works - but perhaps it still parses the full file to infer syntax.

<img width="957" alt="image" src="https://github.com/dandavison/delta/assets/410558/290493ff-1589-48ea-aee0-1ec571f085cd">

<img width="956" alt="image" src="https://github.com/dandavison/delta/assets/410558/69b6d1d0-1418-43e6-8719-2e1f2e5c39f7">

**Comment by pm0u** [comment]
If I set the context to something huge like 200 then it highlights correctly as it manages to include the opening tag for script, style, etc. However this makes the diffs not very useful. It would be nice to have something like what bat must be doing where it parses the whole file and then displays the small section of it, although I realize this is relying on diff output

**Comment by dandavison** [comment]
Hi @pm0u, I think this is a dup of https://github.com/dandavison/delta/issues/117, right?

There is an easy-sounding fix that a couple of people have suggested and which someone should implement: add a `-U` option to delta, so that large context can be passed in, the syntax highlighting will probably be correct, and then delta can narrow the context down.

**Comment by pm0u** [comment]
I think that would do it, yes. Although providing an arbitrary number could be challenging (or I would likely just pass a giant number like 99999) since the boundaries of different parts of the file would be hard to predict. In this case, something like a full file option could be more succint but either would work.

**Comment by dandavison** [comment]
> something like a full file option could be more succint 

Right, but, this is out of delta's control. It is git that is generating the diff, and so it is git that controls how much context is supplied to delta. AFAIK git just offers

```
       -U<n>, --unified=<n>
           Generate diffs with <n> lines of context instead of the usual three. Implies --patch.
```

so yes, passing a "large" integer is how we'd use it.

**Comment by pm0u** [comment]
Ah gotcha, it wasn't clear to me who was interpreting the flag in question. So then I assume the `-U` for delta then limits back down the context? I have confirmed in the past that a huge context (or one that spans the whole file) fixes the issue for me - but also made the diff quite useless as I'm sure you've found. The addition of a context for delta would fix this for me

**Comment by d9k** [comment]
@dandavison, getting an error!

> git diff -U999999 50e765ebbc | delta -- -U10

```bash
> git diff -U99999 | delta -U10
error: unexpected argument '-U' found
  tip: to pass '-U' as a value, use '-- -U'
Usage: delta [OPTIONS] [MINUS_FILE] [PLUS_FILE]
For more information, try '--help'.

> delta --version
delta 0.18.2
```

And these `delta` calls doesn't affect number of context lines in the output, still seeing the whole file:

```
git diff -U999999 50e765ebbc | delta -- -U10
git diff -U999999 50e765ebbc | delta --diff-args=-U10
```

**Comment by d9k** [comment]
@dandavison ,

> add a `-U` option to delta, so that large context can be passed in, the syntax highlighting will probably be correct, and then delta can narrow the context down.

Seems `-U` option was not implemented yet...
Highly needed! Without it Delta is unusable for Vue projects.
