### ISSUE TITLE
🚀Allow configuration of underline width

### ISSUE THREAD

**Issue by evanrelf** [dandavison/delta#155]
I appreciate being able to customize the width of diff background color with the `--width` option, but it would be great if I could do the same with the width of the underlined headings. Shrinking the terminal after `delta` has run causes the underlines to wrap.

I imagine this would be implemented in one of two ways:

1. Make underlining respect the width specified with `--width`
2. Add another option to configure underline width independent of diff background color width

**Comment by dandavison** [comment]
Hi @evanrelf, thanks for this!

I think delta may have been doing something naive. In #136 it was pointed out to me that there is an ANSI escape sequence that causes colors to extend to the right edge of a terminal emulator; currently delta right-pads with space characters.

> I appreciate being able to customize the width of diff background color with the --width option...Shrinking the terminal after delta has run causes the underlines to wrap

I'm thinking that I may have been forcing you into an unnecessarily awkward workflow. I'm going to investigate switching over to use the ANSI sequence, and hopefully entirely eliminating the right-padding-with-spaces thing. That does mean that delta will no longer be able to set an intermediate width: the background colors will either extend to the full terminal width, or to the end of the text on that line (what delta currently calls `--width variable`). However, in the former case it will resize automatically with the terminal. And I'm not sure anyone really wants intermediate widths given that?

How does this sound to you? That would leave us with what you have actually opened this issue requesting, and I agree -- we need that too!

**Comment by evanrelf** [comment]
Hi @dandavison! 🙂

I personally don't care about setting an intermediate width, I just wanted to avoid wrapping when the window is resized. It sounds like switching to use the ANSI escape sequence for background color would be an improvement in that regard.

I don't understand how that relates to underlining though? Are you able to switch from printing underscores to using an ANSI escape code to format text with underlining?

**Comment by dandavison** [comment]
No you're right, it doesn't really relate. I mentioned it because I inferred from your comment that you were being forced to set an intermediate width in order to be able to subsequently reduce the width of the terminal window -- is that right? I'm hoping using the ANSI code will result in slightly more convenience for people with a workflow like yours (as well as just being what people will expect).

**Comment by evanrelf** [comment]
> I inferred from your comment that you were being forced to set an intermediate width in order to be able to subsequently reduce the width of the terminal window -- is that right?

Yes that's right. I was setting `--width=80` so that if I initially had my terminal window maximized, I could shrink my terminal window somewhat and avoid wrapping.

The problem is that underlines _always_ span the available width, because they ignore the value of `--width` and behave like it's set to `flexible`.

You can reproduce this by running `delta` with `--width=80` (or some other number that's less than the width of your terminal); you will see the background color stop at the maximum width you specified, but the underlines under file names span the width of the terminal. When you shrink the width of your terminal, the underlines will wrap.

I'm suggesting you make it so that underlines respect the `--width` option, or you add another option to control their width separately.

**Comment by dandavison** [comment]
> The problem is that underlines always span the available width

Yes, sorry, I'm not being clear. I do understand that :) And definitely plan to fix it.

**Comment by dandavison** [comment]
Hi @evanrelf, this is fixed in `master`: the decorations now respect `--width`.

**Comment by evanrelf** [comment]
Thanks, @dandavison! Can't wait to try it out.
