### ISSUE TITLE
🐛 Online user manual website not working

### ISSUE THREAD

**Issue by jamadagni** [dandavison/delta#1567]
As of 2023-Nov-20, https://dandavison.github.io/delta/ is not working. I am getting:

404
There isn't a GitHub Pages site here.

Please look into this. I am new to and would like to use Delta, but would like to see the documentation before doing so.

**Comment by inahga** [comment]
@jamadagni FWIW you can still read the documentation here https://github.com/dandavison/delta/tree/main/manual/src, until the site is fixed.

**Comment by Adnn** [comment]
This has the sad effect that the very first link in the readme (install it) is down.

**Comment by dandavison** [comment]
Sorry for that! Fixed now. (It was a casualty of me renaming the `master` branch to `main`).

**Comment by jamadagni** [comment]
Thank you! It's fixed now.
