### ISSUE TITLE
🐛 `--color-only` doesn't produce any colour

### ISSUE THREAD

**Issue by HaleTom** [dandavison/delta#1571]
Command:

    /bin/diff HOME.vimrc-2020-08-11 vimrc-committed | delta --color-only --config /dev/null

Output:

![image](https://github.com/dandavison/delta/assets/13854417/9f469484-0e85-46f7-8ae6-e1601ddb2e23)

I want to use delta as a `git` `--diff-filter`, or just to colour diffs produced by standard `diff`.  How do I do that?

**Comment by dandavison** [comment]
Hi @HaleTom, `diff` without arguments does not produce unified diff output, so pass the `-u` flag when piping diff output into delta. delta parses unified diff and git diff output. To use it with git, see https://github.com/dandavison/delta#get-started.

**Comment by HaleTom** [comment]
Thanks @dandavison for explaining!
