### ISSUE TITLE
🐛 Homebrew cannot install from HEAD

### ISSUE THREAD

**Issue by edosrecki** [dandavison/delta#1592]
Creating this issue for tracking purposes. 

Homebrew formula specifies `master` branch as HEAD branch. Instead it should be `main`. I created a PR in homebrew-core repository:

https://github.com/Homebrew/homebrew-core/pull/158544

**Comment by dandavison** [comment]
Nice, thanks! Responded in the PR.

**Comment by edosrecki** [comment]
Merged in homebrew-core. Closing.
