### ISSUE TITLE
🐛 Problem with base16 theme from bat v0.15

### ISSUE THREAD

**Issue by acidghost** [dandavison/delta#161]
I upgraded to the latest version of `bat` and tried to add a custom theme (which is then also used by `delta`). Unfortunately when I list the themes I get the following result:

![window_2020-04-29-18-38-48-crop-0](https://user-images.githubusercontent.com/1787979/80622932-ca547600-8a49-11ea-9cab-81b38b8af39d.png)

`base16` is the [following](https://github.com/sharkdp/bat/blob/v0.15.0/assets/themes/base16.tmTheme), `my-base16` is a minor modification of that (just a color change) and `old-base16` is the same theme but from a [previous version](https://github.com/sharkdp/bat/blob/v0.13.0/assets/themes/base16.tmTheme).

As you can see from the picture, the old version of the theme works without any problem.

Let me know if I can help any further.

**Comment by acidghost** [comment]
Also, if I run `bat cache --clean` and restore the cache to the initial state the default `base16` theme works fine.

**Comment by mk12** [comment]
This is fixed in [bat v0.15.1](https://github.com/sharkdp/bat/releases/tag/v0.15.1).

**Comment by acidghost** [comment]
Indeed, looks like it's fixed, closing.

Thanks for your fix on `bat`!
