### ISSUE TITLE
🐛 PHP syntax highlighting not working properly

### ISSUE THREAD

**Issue by gpressutto5** [dandavison/delta#162]
The syntax highlighting for PHP only works when there's an opening tag `<?php` in the hunk.

![image](https://user-images.githubusercontent.com/12385501/80622680-85b3e500-8a1f-11ea-8231-8fa92af1ae72.png)

```php
<?php

namespace App\Models;

use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialTrait;
use Illuminate\Database\Eloquent\Builder;
```

```php
public function restaurants(): BelongsToMany
{
     // Adding a comment
     return $this->belongsToMany(Restaurant::class);
}
```

**Comment by dandavison** [comment]
Hi @gpressutto5, thanks for the report! Delta uses the same language syntax definitions as [bat](https://github.com/sharkdp/bat/), and bat gets them from upstream repositories (sublime syntax definitions).

I think I'm seeing the behavior you're describing in bat as well as delta, do you agree? If so then this is neither a Delta bug nor a Bat bug.

But beyond that, I'm not entirely sure what's going on. I see sublime syntax definitions have a header key called `[first_line_match](https://www.sublimetext.com/docs/3/syntax.html)`  and that is used in the [PHP syntax file](https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/PHP/PHP.sublime-syntax#13) used by bat.

But doesn't it seem like that should be irrelevant if the file has the `.php` extension?

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/80629623-1dfe9980-8a21-11ea-9897-674b65db399f.png" alt="image" /></td></tr></table>


 - https://github.com/sharkdp/bat/tree/master/assets/syntaxes
- https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/PHP/PHP.sublime-syntax#13 
- https://www.sublimetext.com/docs/3/syntax.html

**Comment by gpressutto5** [comment]
@dandavison It makes sense when highlighting an entire file because the code is only interpreted as PHP after the `<?php` opening tag, otherwise it's only plain text. But it doesn't make sense when highlighting only parts of the file because after that tag everything is PHP, so it is best to assume there is an opening tag even if you can't see it in the current hunk.
The code highlighting works currently will rarely work for PHP the way it is currently.

**Comment by dasl-** [comment]
I am also seeing this bug. 

I believe this is related to the fact that sublime syntax's [support for embedding languages](https://www.sublimetext.com/docs/3/syntax.html#include-syntax):
>Sublime Syntax files support the notion of one syntax definition embedding another. For example, HTML can contain embedded JavaScript. Here's an example of a basic syntax defintion for HTML that does so: 

The sublime syntax file appears to assume we start in `html` scope until it sees a php opening tag: https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/PHP/PHP.sublime-syntax#L18

A php file often contains html that embeds php. Example: https://gist.github.com/dasl-/72242668bf2dde3634802d49a23ef7b6

Other times, a php file may contain pure php and no html, as in the example posted here. I am not sure what the best fix for this would be... it seems like a tricky thing to solve.

Perhaps we could assume that php files do not contain any html and just highlight them as php?

**Comment by dasl-** [comment]
As a workaround for this issue, you can: 
1. install [bat](https://github.com/sharkdp/bat), 
1. Place [this file](https://gist.github.com/dasl-/9ea0d83cd478f36f6c7deaa737480492) at `~/.config/bat/syntaxes/PHP.sublime-syntax`
1. `bat cache --build`

This will make delta assume that any file with a `.php` extension starts in the PHP scope, rather than HTML scope.

credit to @mjec for this fix

**Comment by dasl-** [comment]
Another improvement: the default `Monokai Extended` theme doesn't do the greatest job of coloring PHP code.

Instead, you can use a custom monokai theme  to get better coloring.

Before ("Monokai Extended"):
![monokai extended](https://user-images.githubusercontent.com/1332576/81459345-71818d80-916d-11ea-824b-15c5638ca87e.png)

After ("Monokai (SL)"):
![monokai (SL)](https://user-images.githubusercontent.com/1332576/81459355-7cd4b900-916d-11ea-80d2-42bb39d7003b.png)

Instructions for how to upgrade your monokai:
1. install [bat](https://github.com/sharkdp/bat)
2. Place [this file](https://gist.github.com/dasl-/255b183383bd412356d347c61d77181d) at `~/.config/bat/themes/Monokai (SL).tmTheme`
3. `bat cache --build`

**Comment by goodevilgenius** [comment]
I've also seen this issue, even though `bat` does proper syntax highlighting.

In this example, I've modified two `php` files: one is pure PHP, and one is mixed PHP and HTML.

![image](https://user-images.githubusercontent.com/254662/88075297-340e8880-cb3e-11ea-9e8d-376dea2643b3.png)

Now, if I use bat to simply print those two files, I get this:

![image](https://user-images.githubusercontent.com/254662/88075372-543e4780-cb3e-11ea-8b7c-7d59bc12898f.png)

![image](https://user-images.githubusercontent.com/254662/88075432-66b88100-cb3e-11ea-8f68-6e13ebacc76f.png)

In `bat`, you can see that the PHP sections are appropriately highlighted. However, in `delta`, the HTML sections are highlighted as HTML, but the PHP sections are unhighlighted.

**Comment by gpressutto5** [comment]
@goodevilgenius That's because in the first example you have the short open tag `<=`.
In the second example, when you're using bat you're highlighting the entire file, so it can see the open tag `<?php` in the start of the file.
I couldn't test the workaround yet, but I will later.

**Comment by goodevilgenius** [comment]
@gpressutto5 Good observation. I hadn't actually noticed that the code within the `<?=` was properly highlighted in the mixed file. I had just noticed that the pure PHP file wasn't highlighted at all.

That's a good catch. That would also explain why `bat` worked just fine, since it had the entire file, rather than just the diff, to work with.

**Comment by dandavison** [comment]
Somewhat related: https://github.com/dandavison/delta/issues/117

**Comment by pprkut** [comment]
@dandavison Would there be a way to enable the workaround purely in delta, without having to install bat?

**Comment by dandavison** [comment]
You don't need bat at run-time for this. But currently using `bat cache --build` is the only way to build custom versions of the static syntax-highlighting assets that Delta and Bat use. If that code is available in the bat crate then someone could add the asset-building functionality to delta.

**Comment by dandavison** [comment]
Closing as a bug in upstream sublime syntax support (does anyone know if situation has improved since this discussion?). See also https://github.com/dandavison/delta/issues/117

**Comment by iandunn** [comment]
> does anyone know if situation has improved since this discussion?

I'm still seeing the issue with Delta `0.18.2`.

The [workaround](https://github.com/dandavison/delta/issues/162#issuecomment-625952288) from @dasl- is still working with the latest `git-delta` and `bat` packages from homebrew. Thanks!

**Comment by jthemenace** [comment]
98%+ of our code is PHP.  Really want to take advantage of delta.  Running on debian Trixie using package for delta 0.18.2-4+b1 and bat 0.25.0-2+b2.  When I try to use the dasl- workaround in this thread, it gives me the error below.  No idea how to get around that issue.  We have a standard on running on the debian packages of the version of Debian we are on.

[bat error]: /home/user/.config/bat/syntaxes/PHP.sublime-syntax: Invalid YAML file syntax: String("push"): duplicated key in mapping at byte 425 line 25 column 3
