### ISSUE TITLE
🚀 New binary release please!

### ISSUE THREAD

**Issue by SPiCaRiA** [dandavison/delta#1654]
Hi, thank you for making this great piece :)

I noticed that the latest release is v0.16.5 (~9 months ago), which lacks a lot of game changing features such as `omit-code-fragment`. I'm sure a new binary release would be very helpful for those who don't want to install Rust toolchains. Plus I believe that I'm not the only one that builds delta from source but still wants to put it under package manager!

Thanks!

**Comment by dandavison** [comment]
Will do! It's been on my mind also. I think I've now merged everything that makes sense to release.

**Comment by dandavison** [comment]
https://github.com/dandavison/delta/releases/tag/0.17.0
