### ISSUE TITLE
🐛 .gitconfig entry breaks with space in theme name

### ISSUE THREAD

**Issue by mnemnion** [dandavison/delta#166]
```sh
delta -- version
delta 0.1.1
```

Following the instructions on the site for customizing, I put this into my `.gitconfig`:

```config
[core]
  pager = delta --dark --plus-color="#012800" --minus-color="#340001" --theme="Monokai Extended"
[interactive]
  diffFilter = delta --color-only
```

I get the following output:

```sh
➜ git diff
error: Found argument 'Extended' which wasn't expected, or isn't valid in this context

USAGE:
    delta --dark --minus-color <minus_color> --plus-color <plus_color> --theme <theme>

For more information try --help
```

`bat --list-themes` lists Monokai Extended, and I've confirmed that this string works correctly in bat's config:

```
--theme="Monokai Extended"
```

and that `delta` works correctly on themes without spaces in the name.

**Comment by 0xC0FFEE** [comment]
Hi @mnemnion,

using single quotes in `.gitconfig` works for me. For example:

```
[core]
  pager = delta --dark --plus-color="#012800" --minus-color="#340001" --theme='Monokai Extended'
```

Where did you get the instructions for the usage? FWICT the usage of single quotes is documented in the `README` already?

**Comment by dandavison** [comment]
Yes sorry about that @mnemnion! The README has incorrect instructions for a few hours the other day. As @0xC0FFEE says, the current instructions are accurate: https://github.com/dandavison/delta#configure-git-to-use-delta

**Comment by mnemnion** [comment]
Ok, that works. 

It's strange that double quotes work for the colors but not for the theme, and that they're fine for theme specification in the bat config but not here. 

But you don't control the format of a `.gitconfig` and hey, this works, so: thank you!
