### ISSUE TITLE
🚀 [Docs] Show the default config values

### ISSUE THREAD

**Issue by izelnakri** [dandavison/delta#1669]
Hi there, first of all thanks for this awesome package. Documentation is also well thought after, sectioned and easy to read. 

However I had a major problem in terms of DX: I'm not sure what is the default configuration(~/.config/delta/config.yml) delta uses.

Each config key is well described but I don't know what value is the default **without** checking each one out manually: I would like to have this default config object values shown in the documentation so I can save significant time learning this tool and ease my own configuration(if I need to configure certain thing). 

Without this declaration, delta results in too much time for setting it up for the first time and eventually, making sure whether an old config is not out-of-date with the current existing default configuration.

Also I tried to see if someone else created a similar issue, and couldn't find the specific issue there were many results. Would appreciate if we can have this on: https://dandavison.github.io/delta/configuration.html

Thanks again for all the good work!

**Comment by plgruener** [comment]
All default values are already documented in `delta --help`

**Comment by 0xDones** [comment]
That would be good indeed. I just opened an issue with an suggestion that could help us on this matter. 

#1849

**Comment by dandavison** [comment]
Does `delta --show-config` help?

<img width="751" alt="image" src="https://github.com/user-attachments/assets/23b42954-6bee-45ac-8d78-631c728b33f6">

**Comment by dandavison** [comment]
To see defaults without the influence of gitconfig or env vars, maybe this:

```
env -i /path/to/delta --no-gitconfig --show-config
```

> Would appreciate if we can have this on: https://dandavison.github.io/delta/configuration.html

The defaults are also listed in `delta --help`, which is updated here on each release https://dandavison.github.io/delta/full---help-output.html

I'm going to close this as that seems like plenty of avenues, but feel free to keep discussing.
