### ISSUE TITLE
Not working in Ubuntu 22.04 as intended🐛 

### ISSUE THREAD

**Issue by anoopd** [dandavison/delta#1675]
I was trying to install Delta in ubuntu 22.04  , but the result was not expected 

Os: Ubuntu AMD_64
bat : bat 0.24.0
delta : delta 0.17.0

What have i done wrong ? 

![Screenshot from 2024-04-20 12-39-10](https://github.com/dandavison/delta/assets/925418/a1c5a9bc-0c45-4eef-8b61-e70ffb0e278d)

**Comment by sskras** [comment]
Your screen shows that your tool compares `README.md` to nothing.
What command line do you run to get that?

**Comment by dandavison** [comment]
Closing, let us know if you're still having problems @anoopd
