### ISSUE TITLE
🚀 Add option to adjust/remove background color of lines with emphasized sections

### ISSUE THREAD

**Issue by Amorymeltzer** [dandavison/delta#169]
Apologies if this is doable and I'm just being thick, but it would be great to be able to have differential treatment of the background for added/removed lines and for lines with emphasis in them.  In particular, I'd love to be able to remove (or set to the terminal background) via something like `--background-emph-color` so that the emphasized areas stand out even more, and the full-line highlighting is just for non-emphasized added/removed lines.

**Comment by dandavison** [comment]
Hi @Amorymeltzer, thanks for this! I'm working on making colors much more configurable, including the ability to set foreground colors, bold/underline etc, and diff-so-fancy emulation.

Can I just check:, if you are familiar with diff-highlight/diff-so-fancy, is what you're requesting here basically to provide equivalent functionality as is provided by the `oldNormal`, `oldHighlight`, `newNormal`, `newHighlight` variables that can be used in `.gitconfig` with the `diff-highlight` script that ships with git (which is also used by diff-so-fancy)?

**Comment by Amorymeltzer** [comment]
Basically, yeah!  The `emph` stuff in delta is neat, some more configurability would be quite welcome.  For another, very different concept, [icdiff](https://github.com/jeffkaufman/icdiff) does something similar in terms of output.

**Comment by dandavison** [comment]
@Amorymeltzer I've done a major overhaul which is in `master` now. I'm going to do a write-up of the changes shortly.

**Comment by dandavison** [comment]
Hi @Amorymeltzer, full write up of all the new color/style options is in #205. 

Your specific feature request here _should_ be possible now with e.g.

```
delta --minus-non-emph-style 'syntax'
      --zero-style 'dim syntax'
      --plus-non-emph-style 'syntax'
```

However, I need to do a little bit more investigation here. It looks like `--minus-non-emph-style 'syntax'` isn't being honored:

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/83214336-5aadd580-a132-11ea-83e1-59dba3cf2132.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
>  It looks like `--minus-non-emph-style 'syntax'` isn't being honored

Ah, right, that's as it should be -- by default delta doesn't syntax highlight minus lines. (If you did want syntax-highlighting in the minus lines, then adding `--minus-style 'syntax auto' --minus-non-emph-style 'syntax'` would do it.)

**Comment by Amorymeltzer** [comment]
Awesome, thanks.  Will monitor #205 but looks grand from what I can tell!
