### ISSUE TITLE
🚀 Tweak --list-themes output

### ISSUE THREAD

**Issue by lydell** [dandavison/delta#170]
Hi! Thanks for this tool, I love it.

When I ran `delta --list-themes` for the first time I was pleasantly surprised – I expected a list of theme names to be printed, but you also get an example of each theme. Very helpful!

When scrolling somewhere in the middle, though, it’s hard to know which theme is which:

```
     println!("The square of {:.2} is {:.2}.", num, result);
 // Output the cube of a number.
 fn print_cube(num: f64) {
     let result = f64::powf(num, 3.0);
     println!("The cube of {:.2} is {:.2}.", num, result);
 }

Theme: TwoDark


example.rs
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
 // Output the square of a number.
 fn print_square(num: f64) {
     let result = f64::powf(num, 2.0);
     println!("The square of {:.2} is {:.2}.", num, result);
 // Output the cube of a number.
 fn print_cube(num: f64) {
     let result = f64::powf(num, 3.0);
     println!("The cube of {:.2} is {:.2}.", num, result);
 }

Theme: ansi-dark


example.rs
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
 // Output the square of a number.
 fn print_square(num: f64) {
     let result = f64::powf(num, 2.0);
     println!("The square of {:.2} is {:.2}.", num, result);
 // Output the cube of a number.
 fn print_cube(num: f64) {
     let result = f64::powf(num, 3.0);
     println!("The cube of {:.2} is {:.2}.", num, result);
 }

Theme: ansi-light


example.rs
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
 // Output the square of a number.
 fn print_square(num: f64) {
     let result = f64::powf(num, 2.0);
     println!("The square of {:.2} is {:.2}.", num, result);
```

In the above example, it looks like we first see a bit of “TwoDark”, then “ansi-dark”, then “ansi-light” and a little bit of yet another theme. But that’s not the case! I’m off-by-one! We’re actually seeing a little bit of some theme, then “TwoDark”, then “ansi-dark” and finally a bit of “ansi-light”.

I think the confusion comes from the long `────────` lines combined with `Theme: name` being positioned closer to the previous theme than the theme it belongs to, almost like an image caption.

Ideas:

- At least put `Theme: name` closer to the theme it belongs to than other themes.
- Show `name` instead of `example.rs`?
- Put the theme after the example (as an “image caption”) like my brain interprets the current design?

Btw, is there a theme with 0 green and red in it? I get confused sometimes about what is inserted/deleted and what is just syntax highlighted.

**Comment by dandavison** [comment]
Hi @lydell, thank you for opening this! I absolutely agree -- it was a mess, and just hadn't been revisited. I've pushed a clean-up to master. How's this?

<table><tr><td><img width=400px src="https://user-images.githubusercontent.com/52205/80850197-b8f5a000-8be8-11ea-8c9e-29c5b213c4b7.png" alt="image" /></td></tr></table>


<table><tr><td><img width=400px src="https://user-images.githubusercontent.com/52205/80850237-e04c6d00-8be8-11ea-9027-0d2ea62f15c2.png" alt="image" /></td></tr></table>

> Btw, is there a theme with 0 green and red in it? I get confused sometimes about what is inserted/deleted and what is just syntax highlighted.

One thought is that if you use the `base16` theme, then you can set your terminal emulator's red and green (bold and normal variants) to non-red-non-green colors. The themes are all the ones that [bat](https://github.com/sharkdp/bat/) offers, which are sublime syntax themes as supported by the [syntect](https://github.com/trishume/syntect/) rust library.

Incidentally, slightly random feature, but did you notice that you can pass your own input on stdin to the `--list-themes` demo?

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/80850601-c90e7f00-8bea-11ea-9d37-1f19f8c1da6f.png" alt="image" /></td></tr></table>

**Comment by lydell** [comment]
That looks great! :+1:

I would never have thought of passing stdin to `--list-themes`! Great feature, though.

I’ll keep playing around with colors and see what I end up with.

Thanks!
