### ISSUE TITLE
🐛 Weird/unexpected output on VS Code with 0.17.0

### ISSUE THREAD

**Issue by kfkonrad** [dandavison/delta#1735]
When running delta version 0.17.0 on a terminal in VS Code I get the following ouput:

```sh
bash-5.2$ delta
^[]11;rgb:1818/1818/1818^[\The main way to use delta is to configure it as the pager for git: see https://github.com/dandavison/delta#get-started. You can also use delta to diff two files: `delta file_A file_B`.
^[]11;rgb:1818/1818/1818^[\^[[?1;2cbash-5.2$ 11;rgb:1818/1818/18181;2c
```

Running delta in another terminal emulator such as iTerm or Terminal on my Mac yields the desired output. Due to this buggy ouput delta 0.17.0 is unusable on VS Code right now, at least on my machine.

I also did a `cargo build --release` to verify that the bug is still in the code base on main as of commit id f5b3717. The bug also comes up using zsh and fish as the shell btw

The bug does not occur with 0.16.5 so my quickfix for the meantime is to just use this older version.

**Comment by kfkonrad** [comment]
I can confirm using the `--dark` or `--light` flag or respective config also prevents the weird output
I'm on the latest VS Code version: 1.90.2
delta isn't slow, not that I could tell anyway.

**Comment by bash** [comment]
Unfortunately I can't reproduce this on my own mac or @janhohenheim's mac with VSCode 1.90.2 and delta 0.17.0.

Follow-up questions:
* Are you using a multiplexer (tmux, screen, zellij)? 
* Do you have any interesting settings set for the integrated terminal (Settings starting with `terminal.integrated`)?
* What are your delta settings?

I came up with a list of things that you could try to help figure out why this happens if you're up for it 😃 

* Does the issue persist with the updated version of terminal-colorsaurus (That's the library that does the color detection)? #1699
* What's the output of the following command (basically what happens when delta tries to detect the terminal's theme): 
  ```bash
  printf '\e]10;?\e\\' && printf '\e]11;?\e\\' && printf '\e[c' && cat -v
  #      ^^^^^^^^^^^^^           ^^^^^^^^^^^^^            ^^^^
  #   ask for the fg color   ask for the bg color    ask for some basic info
  ```
* What happens when you run the [`theme`](https://github.com/bash/terminal-colorsaurus/blob/main/examples/theme.rs) example from `terminal-colorsaurus` (only if you're comfortable running code from outside this repo).

**Comment by janhohenheim** [comment]
Note that we are both running Intel macs. I don't expect this to make a difference, but I've seen very weird issues come from different architectures in the past.

**Comment by kfkonrad** [comment]
I can't replicate the bug anymore. I don't know what changed about my system because I don't recall running updates in the last two days. I'm sorry if that means I/we pinpoint the error further if/when it reappears elsewhere.

Here's the answers to your questions in case that's still relevant:

I don't use a multiplexer and my delta config is as follows:

```
[delta]
    navigate = true    # use n and N to move between diff sections
    hunk-header-decoration-style = yellow box
    hyperlinks = true
    hyperlinks-file-link-format = "vscode://file/{path}:{line}"

    # delta detects terminal colors automatically; set one of these to disable auto-detection
    # dark = true
    # light = true
```

I'm not sure which parts of my VS Code settings are relevant so here's everything starting with `terminal.integrated`:

```
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.experimentalImageSupport": true,
    "terminal.integrated.tabs.enabled": true,
    "terminal.integrated.sendKeybindingsToShell": true,
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "terminal.integrated.scrollback": 1000000,
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "terminal.integrated.shellIntegration.decorationsEnabled": "never",
    "terminal.integrated.shellIntegration.enabled": false,
    "terminal.integrated.gpuAcceleration": "on"
```

-------

I tried compiling the version on your branch @bash and it worked fine (just like 0.16.5 and 0.17.0 do now).

The output of your printf-Snippet is `^[]10;rgb:cccc/cccc/cccc^[\^[]11;rgb:1818/1818/1818^[\^[[?1;2c`.

I also ran your example program and its output is `dark, fg: 82, bg: 8`

**Comment by bash** [comment]
@kfkonrad Thank you so much for working through my pinpoint steps 💛 
I'll try to apply your settings, maybe I'll find a way to reproduce it on my machine.

> I can't replicate the bug anymore. [..] I'm sorry if that means I/we pinpoint the error further if/when it reappears elsewhere.

No worries :) Let me know if the issue reappears.
