### ISSUE TITLE
🐛  strange hunk header for changes in generated code

### ISSUE THREAD

**Issue by fuzetsu** [dandavison/delta#1747]
![image](https://github.com/dandavison/delta/assets/848652/e6914eef-e25c-499e-94ce-06bb5fea8deb)

The `${r4}}`

Can be reproduced by running `git show d4a0b83c09cbd4cf9cc5e99754b77511253b252b`  on [this repo](https://github.com/fuzetsu/reddit-comments-on-youtube/commit/d4a0b83c09cbd4cf9cc5e99754b77511253b252b).

**Comment by th1000s** [comment]
That is what `git` thinks is the containing function (guessed from line 323) and uses it as a diff header (so does GitHub in the linked commit), the logic is maybe a bit simple and ignore the backticks and only looks at indentation. Then `delta` uses that, you can run `git show | less` to view the pure `git` output

**Comment by fuzetsu** [comment]
Oh interesting, didn't notice it was like that in the git diff as well! Make sense, thanks for the explanation 😄
