### ISSUE TITLE
🐛 Incorrectly highlighting removed characters

### ISSUE THREAD

**Issue by boris-petrov** [dandavison/delta#175]
`a.txt`:
```java
private final Foo foo = com.company.a.b.c.d.Company.getFoo();
```

`b.txt`:
```java
private final Foo foo = Company.getFoo();
```

```sh
diff -u a.txt b.txt | delta
```

Not sure how to give you "raw" output but if you try it out you'll see that the removed `com.company.a.b.c.d.` part of the first file is not highlighted. Interestingly enough, if you remove `a.b.c.d.`, then it works fine.

**Comment by dandavison** [comment]
Hi @boris-petrov, thanks for the issues you've opened! (Sorry for the slow reply, I have limited time this week but they are very useful to have.)

So this one, I think, is similar to #140 . We can achieve the expected highlighting by tweaking `--max-line-distance`. Basically, I agree with you, another iteration is needed on the details of this feature. There are a few considerations -- please see #140 for full discussion of the current state.

```
$ diff -u a b | delta --max-line-distance=0.6
```
<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/81227250-1ce9e100-8fba-11ea-9a03-e3ee1ff8949e.png" alt="image" /></td></tr></table>

**Comment by boris-petrov** [comment]
@dandavison - thank you for the support! No worries, you answer when you have the time! I'll close this issue as a duplicate then. Thanks again.
