### ISSUE TITLE
🐛 Incorrect highlighting

### ISSUE THREAD

**Issue by boris-petrov** [dandavison/delta#176]
`a.txt`:
```javascript
/call\(\)/.test(error.toString())
```

`b.txt`:
```javascript
/(foobar|call\(\))/.test(error.toString())
```

```sh
diff -u a.txt b.txt | delta
```

Check out the result. `call` is highlighted as both added and removed. One of the parentheses is marked as added which is also strange.

**Comment by dandavison** [comment]
Thanks @boris-petrov! I think this is fixed now:

**Previous version (0.1.1)**
<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86546118-17007580-bf01-11ea-8a19-7c3c0f322cce.png" alt="image" /></td></tr></table>

**Current version (0.2.0)**
<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86546112-1071fe00-bf01-11ea-8ca1-887f2176488d.png" alt="image" /></td></tr></table>

> One of the parentheses is marked as added which is also strange.

Isn't this correct? There is an added paren!

**Comment by boris-petrov** [comment]
@dandavison - great, thanks for the amazing support! You're right, the paren should be there. :) Thank you!
