### ISSUE TITLE
🚀 Add the ability to export saves as .sav files on iOS

### ISSUE THREAD

**Issue by binaryminutia0l** [dandavison/delta#1763]
Hi there.

Thanks for an awesome app :)

On iOS you can export save states as `.svs` files, through the app's GUI:

1. Long press game
2. View Save States
3. Long press on save state
4. Export
5. Save the `.sav` file

Could you add the ability to export a game's saves as an `.sav` file? Which is a more widely used file format for game saves.

How I'm doing this at the moment:

1. Enable syncing through DropBox (this lets you see the synced files, Google Drive does not)
2. Find the files in the "Delta Emulator" directory named in the format `GameSave-{HASH}`
3. Copy this and add `.sav` as an extension
4. Import into a different emulator (e.g. I'm using [mGBA](https://mgba.io) on macOS) running the game

Fortunately I'm currently only using 6 games in Delta, so I just had to try 6 `GameSave-{HASH}` files to find the right one. Ideally you'd be able to export from the app's GUI, so you would know which game it is for. But also so you didn't necessarily have to use DropBox.

Thanks :)

**Comment by bash** [comment]
Hi 👋🏼 

This is the repository for `delta`—a pager for git. \
I think you meant to report this issue to Delta—the game emulator :)
