### ISSUE TITLE
--commit-style box and/or --file-style box causes write_boxed_with_line to panic

### ISSUE THREAD

**Issue by nkouevda** [dandavison/delta#18]
With a narrow terminal (<= 48 chars), `--commit-style box` results in:

    > git show
    thread 'main' panicked at 'attempt to subtract with overflow', src/draw.rs:39:35
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Because `line_width <= box_width`, so `line_width - box_width - 1` would be negative.

Or a more practical scenario: even with a reasonably wide terminal, very long filenames cause the same issue under `--file-style box`.

**Comment by dandavison** [comment]
Thanks @nkouevda! These should be fixed in v0.0.13
