### ISSUE TITLE
🐛 `git blame -C` loses syntax highlighting

### ISSUE THREAD

**Issue by rmacklin** [dandavison/delta#1803]
The [`-C` flag](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt--Cltnumgt) for `git blame` is useful for tracking blame beyond code that was moved from one file to another. Unfortunately, it seems to cause delta to lose its syntax highlighting - the blame still has grouped background highlights in different shades of gray, but the code itself isn't highlighted. Here is an asciinema recording demonstrating the issue by running `git blame src/handlers/blame.rs` and `git blame -C src/handlers/blame.rs` in a clone of this repository (at commit a01141b72001f4c630d77cf5274267d7638851e4):

[![asciicast](https://asciinema.org/a/IYaYidJbWmM7wwXDGrtX6jRmo.svg)](https://asciinema.org/a/IYaYidJbWmM7wwXDGrtX6jRmo)

**Comment by rmacklin** [comment]
Possibly related:
- https://github.com/dandavison/delta/issues/1278

**Comment by rmacklin** [comment]
Hmm, okay this just got even weirder. If I run `git blame -C -w src/handlers/blame.rs` it works with syntax highlighting. But...swapping the order of those flags to `git blame -w -C src/handlers/blame.rs` has no syntax highlighting. Perhaps the issue only occurs if `-C` is the last flag...? 🤔

**Comment by th1000s** [comment]
Nice find! The blame output does not mention the file type, so delta uses the `git blame` command line to find it. It seems `-C` is not handled correctly in all cases, see [`guess_git_blame_filename_extension(..)` in src/utils/process.rs:117](https://github.com/dandavison/delta/blob/0.17.0/src/utils/process.rs#L117).
