### ISSUE TITLE
🐛 Running `delta --version` invokes the pager

### ISSUE THREAD

**Issue by abbeyj** [dandavison/delta#1818]
In previous versions, running `delta --version` would output the version number directly to stdout:

```
$ ./delta-0.17.0-x86_64-unknown-linux-musl/delta --version
delta 0.17.0
$ 
```

In delta v0.18.0, this invokes the pager and pipes the output through that.  The pager will then most likely quit immediately (because there is less than a page full of text to display).  However this can still be noticeable, depending on the settings of your pager.  For instance, with the environment variable `LESS=-c`, `less` will repaint the entire screen, even if there is only a single line of output.   It ends up looking like this:

```
$ LESS=-c ./delta-0.18.0-x86_64-unknown-linux-musl/delta --version
delta 0.18.0
~
~
~
~
~
~
~
$ 
```

I would expect that a request like `--version` would not invoke the pager and would not fill the screen with tildes.

**Comment by dandavison** [comment]
Thanks @abbeyj, I can repro that.

**Comment by n8henrie** [comment]
Depending on the environment this also breaks the ability to output the version at all:

Old behavior:

```
$ delta --version
delta 0.17.0
$ env -i $(type -p delta) --version
delta 0.17.0
```

New behavior:

```console
$ delta --version
delta 0.18.0
$ env -i $(type -p delta) --version
WARNING: terminal is not fully functional
Press RETURN to continue
```

Leading to downstream issues:
- https://github.com/eth-p/bat-extras/issues/126
- https://github.com/NixOS/nixpkgs/issues/336312

**Comment by dandavison** [comment]
Thanks @abbeyj @n8henrie, I've made a patch release 0.18.1 to fix this: https://github.com/dandavison/delta/releases
