### ISSUE TITLE
🐛 Changes in files with non-Latin names incorrectly imply these files being renamed

### ISSUE THREAD

**Issue by koterpillar** [dandavison/delta#1821]
When the name of a changed file contains non-Latin characters, `delta` shows it as renamed instead of just the contents being changed.

To reproduce:

```
$ git init
$ echo one > привет.txt; echo three > hello.txt
$ git add .
$ echo two > привет.txt; echo four > hello.txt
$ git diff
```

Delta output:

<img width="923" alt="image" src="https://github.com/user-attachments/assets/e11ebc9a-b032-4192-a846-d28a40a666ac">

Note the headers for the two files:

```
...
hello.txt
...
a/\320\277\321\200\320\270\320\262\320\265\321\202.txt ⟶   b/\320\277\321\200\320\270\320\262\320\265\321\202.txt
...
```

Raw `git diff` output:

```
$ git --no-pager diff
diff --git a/hello.txt b/hello.txt
index 2bdf67a..8510665 100644
--- a/hello.txt
+++ b/hello.txt
@@ -1 +1 @@
-three
+four
diff --git "a/\320\277\321\200\320\270\320\262\320\265\321\202.txt" "b/\320\277\321\200\320\270\320\262\320\265\321\202.txt"
index 5626abf..f719efd 100644
--- "a/\320\277\321\200\320\270\320\262\320\265\321\202.txt"
+++ "b/\320\277\321\200\320\270\320\262\320\265\321\202.txt"
@@ -1 +1 @@
-one
+two
```

**Comment by th1000s** [comment]
Thanks, should be fixed now.

You can also set  `git config [--global] core.quotepath false` so git (and delta) prints the filenames as-is (assuming the terminal supports Unicode/UTF-8, but most do).
