### ISSUE TITLE
Last line missing from output when last line of input lacks terminating newline character 🐛

### ISSUE THREAD

**Issue by brettp** [dandavison/delta#183]
Here is the raw diff:
```
diff --git a/app_name/apps/mod/__init__.py b/app_name/apps/mod/__init__.py
index c565656cb..0ab636b68 100644
--- a/app_name/apps/mod/__init__.py
+++ b/app_name/apps/mod/__init__.py
@@ -1,4 +1,4 @@
 from __future__ import unicode_literals

 default_app_config = 'mod.apps.ModApp'
-__mod_version__ = '3.3.0'
+__mod_version__ = '3.4.0'
```

The `4` is not shown as replacing the `3` in the version number:

<img width="350" alt="Screen Shot 2020-05-07 at 4 51 15 PM" src="https://user-images.githubusercontent.com/43375/81343437-fe9be800-9082-11ea-86a4-ed2778f9772f.png">

**Comment by dandavison** [comment]
Hi @brettp, thanks for reporting an issue! Can I check whether I am reproducing this correctly:

```
delta(master) cat > tests/examples/183.diff 
diff --git a/app_name/apps/mod/__init__.py b/app_name/apps/mod/__init__.py
index c565656cb..0ab636b68 100644
--- a/app_name/apps/mod/__init__.py
+++ b/app_name/apps/mod/__init__.py
@@ -1,4 +1,4 @@
 from __future__ import unicode_literals

 default_app_config = 'mod.apps.ModApp'
-__mod_version__ = '3.3.0'
+__mod_version__ = '3.4.0'
delta(master) md5sum tests/examples/183.diff
6716fc4cc58bbb07e151a40f92125605  tests/examples/183.diff
delta(master) /usr/local/bin/delta --version
delta 0.1.1
delta(master) /usr/local/bin/delta < tests/examples/183.diff 

app_name/apps/mod/__init__.py
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
 from __future__ import unicode_literals                                                                                                                                                                        
                                                                                                                                                                                                               
 default_app_config = 'mod.apps.ModApp'                                                                                                                                                                         
 __mod_version__ = '3.3.0'                                                                                                                                                                                      
 __mod_version__ = '3.4.0'                                                                                                                                                                                      
delta(master) env | grep DELTA
```

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/81344524-e4fba000-9084-11ea-9ad4-7f873ba4b3ef.png" alt="image" /></td></tr></table>

**Comment by brettp** [comment]
Thanks for the quick reply. It looks like the problem is if there's no newline at the end of the output. Here are the exact files I used and their output.
[delta-183-newline.patch.gz](https://github.com/dandavison/delta/files/4600464/delta-183-newline.patch.gz)
[delta-183.patch.gz](https://github.com/dandavison/delta/files/4600465/delta-183.patch.gz)
<img width="654" alt="Screen Shot 2020-05-08 at 12 55 43 PM" src="https://user-images.githubusercontent.com/43375/81429571-fc419880-912b-11ea-87a1-e582b5b09803.png">

**Comment by dandavison** [comment]
Hm, interesting, I can't reproduce this. Can you post the output of piping the output of delta into `cat -A` (or `bat -A`)?

```
delta < delta-183.patch | cat -A
```

That should tell us for sure whether delta is outputting that last line or not. It's just possible that your shell/terminal emulator combination is somehow managing not to display it, although if that were true you'd think that your `cat` output might exhibit the problem and it did not.

I've tried on MacOS only. iTerm2 and Terminal.app, with zsh 5.8, and bash 3.2 and 5.0. What OS, terminal emulator and shell are you using?

![image](https://user-images.githubusercontent.com/52205/84773140-fc924680-afa9-11ea-8b68-2604059ece4f.png)

**Comment by brettp** [comment]
Hi @dandavison - Sorry, I missed the notification for this, but it seems to work fine now.

I'm not sure what was updated (or how helpful this late info is), but I am currently on MacOS using iTerm2 v3.3.12 with bash 5.0.18.
