### ISSUE TITLE
🐛within-line insertion/deletion detection is not working in all cases that work with diff-highlight

### ISSUE THREAD

**Issue by dasl-** [dandavison/delta#184]
Applying [this diff](https://gist.github.com/dasl-/b78f823d62a6b27721dd1dbf3a9c4323) to your project, here is the result from delta:

![delta](https://user-images.githubusercontent.com/1332576/81441085-218bd200-913f-11ea-9a78-c47da5c0e591.png)

And here is the result from diff-highlight:
![diff-highlight](https://user-images.githubusercontent.com/1332576/81441116-2d779400-913f-11ea-8b12-cd13a5386b40.png)

So diff-highlight is doing a better job of detecting the within-line deletion.

**Comment by dandavison** [comment]
Hi @dasl-, thanks for the issue! There are two threads to this:

1. By default, delta looks for within-line edits at the level of "words", not character-by-character. In other words, its default behavior is analogous to `git diff --word-diff`, whereas what you were expecting is analogous to `git diff --word-diff --word-diff-regex=.`.

    Internally, delta has a regular expression that it uses to tokenize a line. What I'm planning to do is expose that regular expression as a command line option, so that you will get your expected result with `delta --word-diff-regex=.` (I haven't fixed the name of the option yet, but that's a possibility.)

2. If you adjust `--max-line-distance`, delta will currently show you a word diff for your example. See #140. E.g. with `--max-line-distance=0.5`  we get

    <table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/81566864-7874ef80-9369-11ea-9fe6-c4b05d233966.png" alt="image" /></td></tr></table>

**Comment by dasl-** [comment]
Thanks @dandavison , looking forward to `word-diff-regex` feature :)

**Comment by dandavison** [comment]
Hi @dasl-, in the master branch (unreleased) delta now has a `--word-diff-regex` option. Also in master, you can use ~/.gitconfig to configure delta. So if you do `delta --word-diff-regex=.` or

```
[delta]
    word-diff-regex = "."
```

 then you'll get

<table><tr><td><img width=200px src="https://user-images.githubusercontent.com/52205/84453429-c2314e00-ac25-11ea-9a22-987257dc634b.png" alt="image" /></td></tr></table>
