### ISSUE TITLE
🐛 404 https://dandavison.github.io/delta/tips-and-tricks/hyperlinks.html

### ISSUE THREAD

**Issue by kaovilai** [dandavison/delta#1848]
- [ ] Please include the raw text output from git, so that we can reproduce the problem.
      (You can use `git --no-pager` to produce the raw text output.)
- [ ] A screenshot of Delta's output is often helpful also.

Thanks for filing a Delta bug report!

**Comment by dandavison** [comment]
Can you explain a bit more?

This link works: https://dandavison.github.io/delta/hyperlinks.html

**Comment by kaovilai** [comment]
```sh
❯ curl -s https://dandavison.github.io/hyperlinks.html | grep 404
      <h1>404</h1>
```

that's the extent of the issue. I don't recall how I ended up there but I got there by clicking something somewhere.

**Comment by kaovilai** [comment]
> See [hyperlinks](https://dandavison.github.io/delta/tips-and-tricks/hyperlinks.html).

I guess here's one.

**Comment by dandavison** [comment]
Thanks, fixed!
