### ISSUE TITLE
🚀 create delta's own config file

### ISSUE THREAD

**Issue by 0xDones** [dandavison/delta#1849]
### Description

I don't plan to use delta with git, I use it pretty much to compare files manually. It would be good to configure delta by using a separate config file from `~/.gitconfig`, for example a yaml or toml file on the `~/.config/` dir. Also adding every option with the recommended setting on the documentation would be appreciated.

**Comment by dandavison** [comment]
Hi @0xDones let me push back a little here -- what exactly is the disadvantage of using `~/.gitconfig`? If you don't use git, that seems to make it even less liable to cause problems!

**Comment by dandavison** [comment]
I think if you take a look at the comments and code here you'll quickly see why this is not appealing and I would say not likely to happen: https://github.com/dandavison/delta/blob/main/src/options/get.rs

For example, we support this concept: https://dandavison.github.io/delta/features-named-groups-of-settings.html

I can report that, empirically, implementing the option reading/aggregating/interpreting/reconciling was actually one of the most arduous parts of delta's implementation :( The decision was taken early in the project to piggy-back on git config, and I think it would take an extremely strong reason to introduce a parallel config file; I honestly don't see it happening. So I'm going to close this on that basis but please feel free to continue discussing.

**Comment by 0xDones** [comment]
@dandavison thanks for giving me the context. I wonder if the gitconfig having no standard format made it more difficult to implement, and in this case I would say that this is one disadvantage when compared to other formats like YAML or TOML that are easy to read and parse. But giving all the context, I'm not seeing a substancial benefit since everything is already implemented. Cheers 😅
