### ISSUE TITLE
🐛 Graphical paging issues unless piped to `less`

### ISSUE THREAD

**Issue by Iron-E** [dandavison/delta#186]
# Description

It appears that `delta`'s paging implementation has some graphical issues. When there is preexisting text (or even just a large diff), not all of the diff will show, and scrolling up causes previous input from the terminal to be shown (and sometimes the diff will loop and repeat itself).

## Expected Behavior

`delta`'s paging behavior will work regardless of previous input, and will show the complete contents of a diff without `less`.

# Steps to Reproduce

1. Use `cat` or `bat` to add some text to the console (what that text is, is not important— just that there is _something_ there).
    * `cat /dev/urandom` works, for example. But any text will do.
2. Take some diff, using `git diff | delta` _or_ `git diff` using the instructions in the [README](./README.md).

<details><summary>raw diff (renders poorly on GitHub)</summary>
diff --git a/README.md b/README.md
index a7251d0..92cfb5e 100644
--- a/README.md
+++ b/README.md
@@ -83,11 +83,11 @@ function! s:FooMode()
 endfunction
 ```
 
-After defining said function, you can create a mapping to enter the mode. Be sure to use `<expr>`. Example:
+After defining said function, you can create a mapping to enter the mode. Example:
 
 ```viml
 command! FooModeEnter call libmodal#Enter('FOO', funcref('s:FooMode'))
-nnoremap <expr> <leader>n FooModeEnter
+nnoremap <leader>n :FooModeEnter
 ```
 
 - Note the `funcref()` call. __It must be there__ or else `libmodal#Enter` won't execute properly.
diff --git a/autoload/libmodal.vim b/autoload/libmodal.vim
index 9b63188..a5b1aeb 100644
--- a/autoload/libmodal.vim
+++ b/autoload/libmodal.vim
@@ -90,18 +90,17 @@ function! s:Get(comboDict, comboString) abort
 
 	" Make sure the dicitonary has a key for that value.
 	if has_key(a:comboDict, l:comboChar)
-		let l:valType = type(a:comboDict[l:comboChar])
+		let l:val = a:comboDict[l:comboChar]
+		let l:valType = type(l:val)
 
 		if l:valType == v:t_dict
-			if has_key(a:comboDict, s:EX_KEY)
-				return a:comboDict
+			if has_key(l:val, s:EX_KEY) && len(a:comboString) <= 1
+				return l:val
 			else
-				return s:Get(
-				\	a:comboDict[l:comboChar], a:comboString[1:]
-				\)
+				return s:Get(l:val, a:comboString[1:])
 			endif
 		elseif l:valType == v:t_string && len(a:comboString) <= 1
-			return a:comboDict[l:comboChar]
+			return l:val
 		endif
 	" The user input has run out, but there is more in the dictionary.
 	elseif a:comboString == ''
diff --git a/doc/libmodal.txt b/doc/libmodal.txt
index 29bc787..dd45e9f 100644
--- a/doc/libmodal.txt
+++ b/doc/libmodal.txt
@@ -117,11 +117,11 @@ To define a new mode, you must first create a |user-function| to pass into
 <
 
 After defining said |user-function|, you can create a |mapping| to enter the
-mode. Be sure to use |map-<expr>|. Example:
+mode.
 
 >
 	command! FooModeEnter call libmodal#Enter('FOO', funcref('s:FooMode'))
-	nnoremap <expr> <leader>n FooModeEnter
+	nnoremap <leader>n :FooModeEnter
 <
 
 - NOTE: the |funcref()| call must be there or else |libmodal#Enter| won't
</details>

3. Scroll up and notice that all the text from step one is still visible. 
    * Additionally, scroll down and notice that not all of the diff is viewable (it stops prematurely).
4. Use `git diff | delta | less` and attempt to reproduce step 3's behavior. None of the text from step 1 will be visible, and all of the diff will be visible.

**Comment by dandavison** [comment]
Hi @Iron-E, thanks for this. Could you look at the [Mouse scrolling](https://github.com/dandavison/delta#mouse-scrolling) section of the README, which links to https://github.com/dandavison/delta/issues/58 and https://github.com/sharkdp/bat#using-a-different-pager and report on whether those solutions fix your problem?

Delta does its paging using code from bat: Both delta and bat spawn a child `less` process, send their output to the stdin of `less`, and let `less` do the paging for them. There are however some environment variables which they set, which can cause differences between their behavior and the behavior of a `less` process invoked directly by your shell. The problems you see should be present if you send the diff to `bat` instead of `delta`. But I believe they should be fixed by the advice linked above.

It's worth running something like this to double-check your values of all the relevant environment variables:

```
env | grep -iE '(less|bat|pager)'
```

**Comment by Iron-E** [comment]
> Delta does its paging using code from bat…

That's interesting. Bat works when its paging is activated, and it also works with `git show` but it isn't as feature complete with `git` as `delta` (as it mentioned in their README). I wonder what the difference could be?

___

> `env | grep -iE '(less|bat|pager)'`

Here's what I get:

```log
LESSHISTFILE=-
PAGER=less
LESS=-R
```

___

> Could you look at the Mouse scrolling section of the README, which links to #58 and https://github.com/sharkdp/bat#using-a-different-pager and report on whether those solutions fix your problem?

After reading this, here's what I can interpret:

My `PAGER` env variable is `less`, and `less` uses the env variable `LESS` uses to apply `-R`.

I saw from the `bat` README that:

> If you want to enable mouse-wheel scrolling on older versions of less, you can pass just -R (as in the example above, this will disable the quit-if-one-screen feature). For less 530 or newer, it should work out of the box.

The version of `less` is 551 from June 2019, so it _should_ be compatable with this feature.

Just for the sake of trying everything, I specified `BAT_PAGER` to `less -R`. That didn't seem change anything though.

**Comment by dandavison** [comment]
> Just for the sake of trying everything, I specified BAT_PAGER to less -R.

Sorry, just to double-check, did you `export` that shell variable?

```
export BAT_PAGER='less -R'
```

I did think that should fix it. Of course you can also do `cat diff | BAT_PAGER='less -R' delta`.

**Comment by Iron-E** [comment]
> > Just for the sake of trying everything, I specified BAT_PAGER to less -R.
> 
> Sorry, just to double-check, did you `export` that shell variable?
> 
> ```
> export BAT_PAGER='less -R'
> ```

Yeah, I ran `export`— just to be sure I pasted it as it is here and it looks like I mistyped something. 

I am curious why `bat` worked without it, but `delta` required the specification. Probably isn't horribly important since its working now, but it is an oddity nonetheless.

**Comment by dandavison** [comment]
Excellent! I'm thinking it's because of this: https://github.com/dandavison/delta/pull/181. I merged that yesterday, so it's in master, but not in a released version of delta yet.
