### ISSUE TITLE
🐛 Some codes has no background colors

### ISSUE THREAD

**Issue by adoyle-h** [dandavison/delta#1860]
![2024-09-15_04 54 36@2x](https://github.com/user-attachments/assets/ea0ff843-53aa-4ffc-be33-d2ec6decda4a)

The `minus-style` and `plus-style` not work for these codes. And I not found other style options for these in `delta --help`.

## Reproduction

gitconfig:

```gitconfig
[delta]
    navigate = true
    side-by-side = true
    tabs = 2
```

```sh
git clone https://github.com/dandavison/delta.git
cd delta
git show a66ac8e182df5f2862c2385ce35264082d9c10f8
```

## Environments

MacOS 14.6.1
delta 0.18.0
iTerm2 3.5.4beta2

**Comment by dandavison** [comment]
Hi @adoyle-h, you have git's color-moved feature enabled, and that's what you're seeing. This is working as intended -- when delta encounters a color-moved block it just displays git's colors and doesn't apply its own colors. It might be possible to improve delta in this regard, but it's not a bug.
