### ISSUE TITLE
🚀 improve default colour theme use of dark blue and dark red

### ISSUE THREAD

**Issue by daniejstriata** [dandavison/delta#1874]
Can you please reconsider the blue used when color is enabled, hitting this scenario:
![image](https://github.com/user-attachments/assets/ac53db4d-ef5d-44ef-a5e9-f25674196606)
I've got eyes that is not able to read that blue. I'm sure I'm not alone, if the default could be slightly tuned I won't need to modify delta configs on all my hosts. I'm happy with the default, it is just that blue is too dark.

**Comment by dandavison** [comment]
Hi @daniejstriata I sympathise with this. I'd welcome someone proposing improvements to default colors for dark backgrounds.

This probably isn't what you want to hear but delta is very easy on the eyes using a white or light terminal background. With dark backgrounds, it is considerably harder to find background colors (i.e. for removed and and added material) that contrast both with the main terminal background color, and with all foreground colors that delta uses (syntax highlighting and decorations).

I have to admit that personally I stopped using dark terminal backgrounds several years ago: they seem to me to cause the screen to pick up too much reflection from ambient light, and are challenging for delta as described above. Therefore I have not done well at improving delta's dark-mode defaults, and I have always felt bad about it.
