### ISSUE TITLE
🐛 rg --json syntax highlighting around comments incorrect for Python

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#1876]
If we take this Rust code:

`z.rs`
```rs
// this is a comment
let x = "this is code";
```

and this Python code:

`z.py`
```python
# this is a comment
x = "this is code"
```

Then delta's `rg --json` handling correctly highlights the Rust:
<img width="448" alt="image" src="https://github.com/user-attachments/assets/febf0ba3-d844-429a-a23e-bec620f01070">

But is incorrect for Python: the syntax highlighting state incorrectly remains in comment mode on the second line:
<img width="445" alt="image" src="https://github.com/user-attachments/assets/088cab30-de3b-4a7a-ac43-ae13d089c7e4">

 
I'm not sure if this is a bug in syntect or delta. I notice that in `grep.rs` our line of code does _not_ have a terminal `\n`; adding this (with `push('\n')` in `ripgrep_json.rs`) fixes the issue superficially, but if the user has requested multiple context lines then it introduces undesired extra blank lines.

**Comment by louis-hsu** [comment]
#1668 describes the same issue.
Shell script with '#' as comment indicator has the same symptom .

**Comment by dandavison** [comment]
Oops, sorry I missed that one @louis-hsu. I'll close this as a dup. I'd definitely like to fix this but haven't found time to look into it yet. I don't know why the languages are differing in this way in the ripgrep highlighting when they are not in the main highlighting.

Closing as dup of https://github.com/dandavison/delta/issues/1668

**Comment by dandavison** [comment]
Fixed by @th1000s in https://github.com/dandavison/delta/pull/2057
