### ISSUE TITLE
🚀 Remove `file-style = omit` from configuration example in the manual

### ISSUE THREAD

**Issue by Janno** [dandavison/delta#1878]
I have been using delta happily for a long time but I only noticed just now that the configuration example in the manual suppresses renamed files from being shown at all in the output of `git log -u` or `git show`: https://github.com/dandavison/delta/blob/5b042fc3eaae1f580dd6441e031e89d6a8d1f6a0/manual/src/configuration.md?plain=1#L25  Not showing renamed files can lead to really, really confusing outcomes. I bet I am not the only one who just copies whatever default configuration example they can find without giving it much thought. And the configuration actually worked almost perfectly. (Until I led my coworker astray by telling him I hadn't changed file X in my commits based on the output of  `git log -u` which did indeed not show the change in which I renamed X to Y..)

I am not sure if `file-style = omit` is included for a particular purpose (maybe because `delta` developers prefer this setting?) but I would definitely recommend removing it to avoid confusion.

**Comment by dandavison** [comment]
Oops, thanks @Janno! That really should just be the same example as is suggested in the README. I had completely forgotten that people would encounter that and it would look like recommended config. Fixed in https://github.com/dandavison/delta/pull/1879
