### ISSUE TITLE
🐛 There is already a project calle "Delta" and it is rather well-known: https://github.com/dsw/delta

### ISSUE THREAD

**Issue by dsw** [dandavison/delta#1895]
The LLVM introduction by Latner refers to the "standard delta debugging tool", so it is rather well-known: https://aosabook.org/en/v1/llvm.html 'unlike the standard "delta" command line tool.'

**Comment by dsw** [comment]
My delta is over 18 years old.  It was released as open source because
Microsoft Research asked personally for me to do that.  Again, it is a
standard tool mentioned in the LLVM documentation.  You are the one who
created the namespace collision, not me.

**Comment by dandavison** [comment]
I'm sorry, I didn't realize that you were the author of the pre-existing delta, I thought it was just someone complaining about name clashes! (which has happened previously)

> You are the one who created the namespace collision, not me.

Yes, I 100% acknowledge the truth of this. The thing is, I'm not convinced that anyone should be avoiding "namespace" collisions. I suspect that you would agree that the "namespace" we're talking about here is extremely poorly defined. Where would I go to check for collisions? How do I know what package managers are in use in all the countries around the world, and what set of names are currently considered taken? No-one would ever be able to put pen to paper if that was a requirement for starting a project. Honestly, at the end of the day, my view is that the idea that someone, at the outset of an open source project, should try to choose a name that has not been used in previous decades is antiquated, and parochial.

**Comment by dsw** [comment]
Mozilla changed the name of "Firebird" to "Firefox" just because
another open source project was already called "Firebird".

https://support.mozilla.org/en-US/questions/1136208#answer-909999

http://www-archive.mozilla.org/projects/firefox/firefox-name-faq.html

It was Phoenix from 0.1 to 0.5 however Phoenix bios already had Phoenix name.

It was Firebird for 0.6, 0.6.1, 0.7, 0.7.1 (for Mac) however the open
source Firebird sql had Firebird name first.

Firefox started at version 0.8 and continues to be the name since.

Yes people there were Releases in the couple years before Firefox 1.0
in Nov 2004 as Firefox did not start then as some sources may claim.
