### ISSUE TITLE
🚀 expose {host} in hyperlinks

### ISSUE THREAD

**Issue by roylez** [dandavison/delta#1899]
I use Kitty terminal and occasionally take advantage of its open hyperlink feature to edit files over ssh. 

For any file, kitty creates a link like `file://{host}{path}`, and clicking the link opens my editor regardless of if the file is over ssh or not. Also this is defined by RFC 8089.

At this moment, delta creates links like `file://{path}`, and this makes kitty unable to open the correct file to edit over ssh.

**Comment by dandavison** [comment]
Hi @roylez, just to check I understand, is the following all correct?

1. As a workaround, you could use `hyperlinks-file-link-format`

2. But you'd have to ensure that your delta config sets the correct hostname on each machine

3. You feel that delta should by default obtain the hostname and inject it into its default file URLs

**Comment by dandavison** [comment]
What does `or {url}` in the issue title refer to?

**Comment by dandavison** [comment]
OK, thanks, what about the 3 points above?

**Comment by dandavison** [comment]
Would you like to try out this branch? https://github.com/dandavison/delta/pull/1901

That does not make it default yet, but it should allow `{host}` to be used. It uses a function from the ripgrep library, so cross-platform behavior should be similar to ripgrep.

**Comment by roylez** [comment]
About point 3 I agree it does not need to be in the default url. The branch builds and works well for me.
