### ISSUE TITLE
🐛 Memory allocation error on Windows

### ISSUE THREAD

**Issue by ofek** [dandavison/delta#1906]
Delta: 0.18.2
Windows: 11

The [recommended solution](https://github.com/dandavison/delta/issues/1712#issuecomment-2120118270) in the other issues does not work because building triggers the same behavior. Can nothing be done to fix this permanently on Delta's side?

![image](https://github.com/user-attachments/assets/868e6ed4-5bd9-4ed5-996b-fc5d772d510b)

**Comment by ofek** [comment]
My apologies, indeed upgrading bat resolved the issue. Thank you!

**Comment by dandavison** [comment]
No problem! We should maybe have a "troubleshooting" section in the manual with if-this-then-maybe-that recipes. But I'm inclined to think the best solution is for someone to continue the `delta doctor` work started in https://github.com/dandavison/delta/pull/1193
