### ISSUE TITLE
🚀 Allow multiple hyperlinks per line

### ISSUE THREAD

**Issue by Gorfeywog** [dandavison/delta#1907]
I have hyperlinks set up to make commit hashes link to corresponding pages on gitlab; for the most part it works great, but if there are multiple things resembling commit hashes on a line it seems to only make the last one a link. There are a few scenarios in which this behavior is inconvenient for me:

1. I'm using git range-diff, which displays multiple commit hashes per line, all of which I'd like to become links.
2. I'm using git log with a --pretty format that puts the commit hash and the commit title on the same line, and a commit title mentions another commit's hash (say, "revert commit xyz").
3. I'm using git log with a --pretty format that puts the commit hash and the commit title on the same line, and a commit title mentions something that _isn't_ a commit hash, but the parser thinks is one, like an 8 digit number. (The link to a nonexistent commit would be fine, except that it blocks creation of a useful link.)

Links would be more useful for me if in all of these scenarios it turned both into links (or even 3/4/5/etc. links on one line, if multiple of those things happened together, I suppose).

**Comment by th1000s** [comment]
Good idea. Also, can you think of any downsides when not linking numbers as commit hashes?

**Comment by Gorfeywog** [comment]
To the best of my knowledge there's no reason a repository couldn't have a commit hash that just happens to start with an 8 digit number, although it should be extremely rare (assuming a-z0-9 all equally likely, that's something like (10/36)⁸≈0.003% of commits)

**Comment by th1000s** [comment]
Should work now. And git hashes are just hexadecimal, so (10/16)⁸ i.e. 2.3% of commits. But is is enabled now, it could become a config var later on if needed.

**Comment by yeldiRium** [comment]
Sorry to necro this thread.
@Gorfeywog you mention that you use delta with `git range-diff`. How did you configure that? I can't seem to find the right git configuration for delta to work.
