### ISSUE TITLE
🐛 `delta rg` pager is not exiting on `q`

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#1919]
To repro, in the delta git repo, issue
```
LESS= ./target/release/delta rg match
```

Since there are multiple pages of matches, this will result in paging via `less`.  I expect `q` to exit the pager and give a shell prompt.

What I find instead is that `q` exits the pager, but does not give a shell prompt.

When I first issue the search command and the pager is active, the process tree looks like
```
delta(main) pstree 71721
-+= 71721 dan ./target/release/delta rg match
 |--- 71737 dan less -FR
 \--- 71749 dan rg --json match
```

After entering `q`, the pager content disappears and I'm left with a blank screen, which is not offering a shell prompt. The process tree looks like

```
delta(main) pstree 71721
-+= 71721 dan ./target/release/delta rg match
 |--- 71737 dan <defunct>
 \--- 71749 dan rg --json match
```

**Comment by th1000s** [comment]
Ah, not `wait()`-in on the subcommand on `EPIPE` had its advantages until clippy came along. Now fixed by `take()`-ing and thus closing stdout.

Simple one line fix, feel free to merge if that fixes it for you as well.

**Comment by th1000s** [comment]
Looking at the output handling, there is another (much more unlikely) issue: stderr of a subcommand is never read and just buffered by the OS's pipe until the command finishes. The entire construct hangs if too much stderr output is produced (and, it is lost entirely on `EPIPE`).

This should be resolved by also reading from stderr, either in a thread, by going full async, or copy-pasting the rustc internal `read2()` function which probably ends up doing `select()` (or something more modern) on stdout and stderr.

**Comment by dandavison** [comment]
> Simple one line fix, feel free to merge if that fixes it for you as well.

Perfect, that certainly fixes it for me. (Merged)
