### ISSUE TITLE
Include comparison with git/contrib/diff-highlight

### ISSUE THREAD

**Issue by waldyrious** [dandavison/delta#192]
The [comparison table in the README](https://github.com/dandavison/delta/blob/master/README.md#features) is great (I wish more projects did that!), but it looks like the [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight) script that is included in the git project is missing from it. It would be great if it were included as well.

**Comment by waldyrious** [comment]
Here are some screenshots that show some differences:

`git`:
<img width="325" alt="diff" src="https://user-images.githubusercontent.com/478237/82128838-1deaf180-97b6-11ea-8b1a-18feb90e297c.png">

`diff-highlight`
<img width="325" alt="diff-highlight" src="https://user-images.githubusercontent.com/478237/82128837-1cb9c480-97b6-11ea-8874-17e999a97c77.png">

`delta`:
<img width="325" alt="diff-delta" src="https://user-images.githubusercontent.com/478237/82128835-1c212e00-97b6-11ea-8274-4f786c09a7a1.png">

**Comment by dandavison** [comment]
Thanks again, that definitely makes sense. I wasn't aware of `diff-highlight` when I made that README content. Is it right to say that `diff-so-fancy` is built on top of `diff-highlight`?

https://github.com/so-fancy/diff-so-fancy/blob/master/lib/DiffHighlight.pm
https://github.com/git/git/blob/master/contrib/diff-highlight/DiffHighlight.pm

**Comment by waldyrious** [comment]
I wasn't aware of that! It makes sense — those files are identical [for the most part](https://www.diffchecker.com/IgSDzQs8). I'd say diff-highlight should be mentioned in the title of diff-so-fancy column, just to help people who may not be aware of the close relationship between the two :)
