### ISSUE TITLE
🚀 Flag to suppress the non-zero exit code 

### ISSUE THREAD

**Issue by SigmaSquadron** [dandavison/delta#1921]
Hi! I'm using `delta` as a diff viewer for Jujutsu, and `jj` warns the user if the diff program exits in a non-zero exit code. Would it be acceptable to add a flag to suppress the exit code when there is a diff?

**Comment by th1000s** [comment]
What command do you or `jj` call, and what input does it get? Diffs usually return a non-zero exit code, maybe adding `|| true` to it can help?

**Comment by SigmaSquadron** [comment]
`jj` calls it with something along the lines of `delta <flags> <dir1> <dir2>` There must be some weird shell escaping, quoting or word splitting (or lack thereof) going on, because `|| true` is parsed as a directory name:
```console
$ jj diff
delta> error: unexpected argument '||' found
delta>
delta> Usage: delta [OPTIONS] [MINUS_FILE] [PLUS_FILE]
```

Here's the `jj` log when delta is called normally: 
```console
$ jj diff --debug
INFO run_command:cmd_diff: jj_cli::merge_tools::external: Invoking the external diff generator: cmd="/nix/store/jaiid8gc746wsmf48pgaxc0x0j2xy8l5-delta-0.18.2/bin/delta" "--color-only" "--diff-so-fancy" "--navigate" "--side-by-side" "--line-numbers" "/tmp/jj-diff-4GBaTW/left" "/tmp/jj-diff-4GBaTW/right"
INFO run_command:cmd_diff: jj_cli::merge_tools::external: The external diff generator exited: cmd="/nix/store/jaiid8gc746wsmf48pgaxc0x0j2xy8l5-delta-0.18.2/bin/delta" "--color-only" "--diff-so-fancy" "--navigate" "--side-by-side" "--line-numbers" "/tmp/jj-diff-4GBaTW/left" "/tmp/jj-diff-4GBaTW/right" exit_status=ExitStatus(unix_wait_status(256))
Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)
```

**Comment by th1000s** [comment]
I see, `jj` doesn't do simple shell invocation, you would have to write you own wrapper, like `delta "$@"; true` in e.g. `delta_jj.sh`

Also,  the [comment here](https://github.com/martinvonz/jj/blob/v0.24.0/cli/src/merge_tools/external.rs#L386) in `merge_tools/external.rs` and the debug output somewhat disagree:

```
    // Non-zero exit code isn't an error. For example, the traditional diff command
    // will exit with 1 if inputs are different.
```

And `delta` _specifically_ does 0 / 1 / 2 for same / different / actually-an-error.

Is is only in the debug output, or does this bubble up to the shell?

**Comment by SigmaSquadron** [comment]
The `Warning: Tool exited with exit status: 1 (run with --debug to see the exact invocation)` message does appear without `--debug`. Could be that this is a configuration issue with `jj` somehow.

**Comment by th1000s** [comment]
Okay, in this case the `jj` diff handling is still incomplete, as the comment there suggests. This warning should only be printed on >= 2 exit status. Plain `git diff --no-index` or even `diff -u` have the same exit status as `delta`. Please file an issue there :)

**Comment by tschundler** [comment]
`jj` has a config to ignore certain error codes on call to diff visualizer:

```
[ui]
diff-formatter = "delta"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
```

(for anyone else landing here)
