### ISSUE TITLE
possible to use with git commit -v?

### ISSUE THREAD

**Issue by zachvalenta** [dandavison/delta#194]
Is it possible to configure delta to be used when committing with the `-v` (verbose) flag? I already use for delta for `git diff` but the other primary time I'm looking at diffs is when I commit and it'd be great to use delta then as well.

**Comment by dandavison** [comment]
Hi @zachvalenta, thanks for this. I'm not familiar with `commit -v`. Could you give an example of the exact command line invocation that you have in mind, and what you would want to happen?

I tried this out myself but I found that `git commit -v` displays the diff in an editor (depending on the git config `core.editor` setting, and perhaps also env vars such as `EDITOR`, `ALTERNATE_EDITOR`, `GIT_SEQUENCE_EDITOR`, unless you pass `--no-edit -m "the message"`, but then it just creates the commit without showing any diff.

**Comment by zachvalenta** [comment]
What I'm after is replacing the in-editor diff with something that looks better. I'm not sure how it would work; I am, I admit, more of a [punk rock Git user](https://zwischenzugs.com/2018/05/14/beyond-punk-rock-git-in-eleven-steps/).

I was bugging the crew over at `diff-so-fancy` about this ([link](https://github.com/so-fancy/diff-so-fancy/issues/365)) and it seemed possible but perhaps difficult enough and far enough away from the scope of a tool meant for dealing with diffs in the context of stdout and a terminal. 

Just wanted to see if it was something your project was either more familiar with or potentially had in mind. Either way, thanks for hearing me out. Very cool project.

**Comment by dandavison** [comment]
OK, thanks for getting back on that, that helps a lot. Hmm, interesting. There does seem to be a question to be answered about whether git offers any control over the diff that it sends to `$EDITOR` when it's doing it's `commit -v` thing. I.e. is there an equivalent of the`interactive.diffFilter` git variable (which allows us to modify the diff used with `git add -p`).

That said, in a way I do have a solution to this ready to use right now, but you're probably not going to like it! Magit is an amazing git client. It does however run in a certain well-known lisp execution environment. But people use Magit who don't use Emacs for anything else. So... bear with me... you could have git use `emacsclient` as `$EDITOR` for `git commit`, and then when you issue `git commit` from the command line, `emacsclient` will bring up a commit editing interface in emacs, using Magit, displaying the diff on the right hand side. And we already have delta integration with Magit.  Here's what it looks like: https://github.com/dandavison/magit-delta All the 24-bit ANSI color escape sequences from delta's stdout are translated into Emacs-native display properties, and you end up with Delta's colors being displayed in a GUI application.

That's my own work flow. To make it happen for other editors in the git commit context would I think depend on them handling all the ANSI escape sequences correctly, as well as depending on it being possible to get git to allow us to insert some sort of diff filter in the process.

**Comment by zachvalenta** [comment]
lol I do actually welcome your solution; I've heard positive rumblings about Magit for long enough and have always needed a convenient excuse to give it a whirl.

I'll give this a spin. If I turn into an Emacs evangelist I'll have someone to blame :)

**Comment by dandavison** [comment]
Haha, great! It will hopefully soon be available for installation via the standard emacs package manager; see https://github.com/melpa/melpa/pull/6905.

**Comment by dandavison** [comment]
[magit-delta](https://github.com/dandavison/magit-delta) is available from the Emacs MELPA package manager now:

```
M-x package-refresh-contents
M-x package-install RET magit-delta RET
```

@zachvalenta ask me if you do try out magit-delta and have any questions!

I'm going to close this one for now, but feel free to reopen, e.g. if anyone's aware of git exposing an ability to insert delta into the `commit -v ` flow. However, the solutions (e.g. for dealing with the ANSI color escape sequences properly) will be editor-specific. Currently the only editor I'm aware of with delta integration is Emacs (Magit): [magit-delta](https://github.com/dandavison/magit-delta).

**Comment by zachvalenta** [comment]
@dandavison will do!
