### ISSUE TITLE
How can I ignore files?

### ISSUE THREAD

**Issue by baldore** [dandavison/delta#196]
Hi! first at all, excellent program. I use it everyday.

Is there a way to ignore specific files? For example, package-lock.json in Node.js projects tends to be really big. Any way to pass an argument to ignore the diff?

**Comment by dandavison** [comment]
Hi @baldore, thanks!

I agree it would be good to find a workflow that avoids unhelpful display of large files. OK, so a couple of thoughts:

1. There's a related issue #156 in which I just asked this question: https://github.com/dandavison/delta/issues/156#issuecomment-630990424.

> Can I ask one thing to make sure I'm clear about this. This is not to say the suggestion doesn't make sense, but how were you doing this prior to using delta? I.e. didn't you encounter the same problem with vanilla git? Or is the issue that delta's background colors make the large files seem more heavyweight? Or is it simply that, seeing as delta aims to improve our experience of using git, this is a git annoyance that maybe delta could improve on?

Could I ask you the same question? (Feel free to reply in #156 if you think that makes sense).

2. I'm not saying this is the idea solution, but one option is to "officially"  ignore those files at the git level. For example, by adding them to a global gitignore file (run `git config core.excludesfile` to see what yours is, probably `~/.gitignore`. See also https://stackoverflow.com/a/18703637/583763).

**Comment by baldore** [comment]
@dandavison you're right. This is not a problem of this package. It should come from `git` itself. This is what I found in https://stackoverflow.com/questions/10415100/want-to-exclude-file-from-git-diff

**Option 1:** `git diff -- . ':(exclude)package-lock.json'`
**Option 2 (per project):** Modify `.git/info/attributes` and add the file you want to ignore with this format:

`package-lock.json   diff=nodiff`

And config your git to apply a different command for `nodiff` files:

`git config --global diff.nodiff.command /usr/bin/true`

**NOTE:** `/usr/bin/true` on OSX.

Thanks.
