### ISSUE TITLE
🚀 Moving around in the diff

### ISSUE THREAD

**Issue by driesg** [dandavison/delta#199]
Hi,

delta is an awesome tool, thanks for sharing! One feature I'm missing from diff-so-fancy is ["Moving around in the diff"](https://github.com/so-fancy/diff-so-fancy/blob/master/pro-tips.md#moving-around-in-the-diff), it allows to pre-seed the pager with a pattern so that we can quickly jump between files. They achieve this by prefixing the file names with `Date|added|deleted|modified`. 

How would it be possible to achieve the same in delta? Would it be possible to also prefix the file names?

**Comment by dandavison** [comment]
Thanks @driesg! There's already been some discussion of this in #50 -- shall we discuss there?

**Comment by driesg** [comment]
ahh! My search skills are horrible! Yes let's keep the discussion there
