### ISSUE TITLE
🚀 Provide a compact --list-themes output

### ISSUE THREAD

**Issue by waldyrious** [dandavison/delta#207]
I agree with @lydell in #170 on the usefulness of the theme examples in `--list-themes`:

> When I ran `delta --list-themes` for the first time I was pleasantly surprised – I expected a list of theme names to be printed, but you also get an example of each theme. Very helpful!

But I would say that printing such a large amount of output unexpectedly may not be the best user experience. How about having `--list-themes` produce a simple text list of the themes and a brief description, and then having a new `--show-themes` option (or something along those lines) that actually provides the visual demonstration?

**Comment by dandavison** [comment]
Hi @waldyrious, yes I hesitated on this too when I did it. So we do have the short version: it's called `--list-theme-names`. The reason at the time I didn't make `--list-themes` be text only and have `--show-themes` was because I was keeping things similar to `bat`, and `bat --list-themes` dumps color examples. I don't have a clear view of what's best. But it is true that delta is very closely related to bat when it comes to themes -- e.g. to add a custom theme/language for delta, you literally just install bat and add it for bat.

**Comment by waldyrious** [comment]
I get that, and I'll respect your choice if you prefer to keep the default verbose for those reasons. I'll point out, though, that many commands have `--list-*` options, and most of them provide a compact list rather than examples of each entry, so IMO it's reasonable to assume that most users will not be expecting the output to be as long, so this will be surprising more often than not (and not always in a pleasant way).

Thanks for the `--list-theme-names` hint! That's exactly what I wanted.

**Comment by dandavison** [comment]
Thanks @waldyrious, I agree with this and have addressed it. The names of the commands have changed in master:

```
--list-languages
--list-syntax-themes
--show-syntax-themes
```

and they do what it says on the tin. There is also `--show-config` which takes everything (git config, features, command line) into account and shows you what is live:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/85936452-0cbef580-b8c9-11ea-9b93-6bebd0cf9488.png" alt="image" /></td></tr></table>

**Comment by waldyrious** [comment]
Nice, thanks!

Perhaps it could be useful for `--list-syntax-themes` to suggest `--show-syntax-themes`, for increased discoverability :) WDYT?

**Comment by dandavison** [comment]
> Perhaps it could be useful for --list-syntax-themes to suggest --show-syntax-themes, for increased discoverability :) WDYT?

Yes, good call. Done in 811bf56114dc7cadf53bd9b80e16550a0cb03bde. (And just in case anyone uses this in a script, I've made it emit tab-separated tabular data when stdout is not a tty.)
