### ISSUE TITLE
🚀 Configure class information header

### ISSUE THREAD

**Issue by Aridor2006** [dandavison/delta#228]
Is there a way to configure what is shown for the class header? For example, in C# (.cs) files, it will show the namespace instead of the class. The files are generally structured like following, with the class usually being the important part, not the namespace.

```
namespace Namespace.Test
{
  public class TestClass
  {
  }
}
```

Is that something that can be done with a custom syntax file?

**Comment by dandavison** [comment]
Hi @Aridor2006, this is actually controlled by a git config value `diff.<lang>.xfuncname`: see https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header

Thanks for raising this -- I've been meaning to improve this in my own config files but hadn't got around to it yet. I see a few pages that might be useful:

- https://gist.github.com/ruediger/5647207
- http://git.661346.n2.nabble.com/xfuncname-problems-with-C-td7623563.html (discussion about xfuncname for C++)
- https://stackoverflow.com/questions/39481258/appending-a-pattern-to-the-default-diff-header-pattern-diff-cpp-xfuncname

I'd love it if delta could provide optimized defaults. However, delta receives output from git but does not control the git process, so it can't literally change the active xfuncnames. However, in master (soon to be released) I have switched delta configuration over to read values from git config, so there is going to be a very close relationship between delta configuration and gitconfig. Perhaps delta could distribute, or link to, a file containing a collection of good default xfuncnames, to make it easy for delta users to extend their gitconfig with that collection.

...time for me to try improving the regexps in the languages I'm using!

**Comment by Aridor2006** [comment]
Thanks, that helped me a lot! For me it was enough to add ```*.cs         diff=csharp``` to my .gitattributes, it looks like git already has the correct regex patterns for csharp built in.
