### ISSUE TITLE
🚀 improve diff -u comparison

### ISSUE THREAD

**Issue by MarcoIeni** [dandavison/delta#229]
I am comparing this project with [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) with the `diff -u` usage.
I want to see the difference between two files named `one` and `two`:

![image](https://user-images.githubusercontent.com/11428655/85955758-2f144a00-b981-11ea-829b-7ca87aa66ead.png)

As you can see diff-so-fancy highlights the different word on the first line.
Why delta doesn't do it?

**Comment by dandavison** [comment]
Hi @MarcoIeni, In the current version of delta, you can make it do it by bumping the `max-line-distance` parameter (see https://github.com/dandavison/delta/issues/140 for explanation):

<table><tr><td><img width=700px src="https://user-images.githubusercontent.com/52205/85957963-d3859480-b95f-11ea-80eb-6c4523e3bbce.png" alt="image" /></td></tr></table>

I'm about to release a new version of delta which will highlight this by default (`master` branch):

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/85957972-f152f980-b95f-11ea-80cc-e7019a0e4afd.png" alt="image" /></td></tr></table>

Incidentally, in the new version you will be able to use `delta one two` as a wrapper for `diff -u one two | delta`:

<table><tr><td><img width=400px src="https://user-images.githubusercontent.com/52205/85957981-0d569b00-b960-11ea-8f8a-cde1b727ec50.png" alt="image" /></td></tr></table>

**Comment by MarcoIeni** [comment]
Awesome, thanks!

**Comment by dandavison** [comment]
What #140 comes down to is that delta (unlike diff-highlight, diff-so-fancy, GitHub, GitLab, etc) does not assume that a pair of lines are homologous and should be highlighted as if one has evolved from the other. The reason for this is that delta (unlike the others), when confronted with a hunk containing different numbers of `-` and `+` lines, attempts to infer which lines "match" each other. So, it has to have a criterion. And the default value of the parameter defining that criterion was set a bit too conservatively in the released version. There's room for improvement/expansion of the options delta offers regarding edit inference algorithms. For example, the simple-minded algorithm implemented by [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight) (which diff-so-fancy uses as a library) could be added to delta.
