### ISSUE TITLE
🐛 option `--show-syntax-themes` is broken

### ISSUE THREAD

**Issue by wescande** [dandavison/delta#230]
Hi !

This just happened when trying following command:
```
delta --show-syntax-themes
```

![image](https://user-images.githubusercontent.com/20841006/85961111-60ecd700-b9a8-11ea-80ce-32d3abccb732.png)

I just `git clone [...] && cargo build && ./target/debug/delta --show-syntax-themes`
I am using kitty 0.16, but the same happen on Konsole

And I don't know if it's a feature (to let the time to view the theme)or a bug, but the command take 12 second to execute !

**Comment by dandavison** [comment]
Hi @wescande, thanks for this! I can reproduce both problems, and have fixed them in master, soon to be released.
