### ISSUE TITLE
🚀 directory diff

### ISSUE THREAD

**Issue by wescande** [dandavison/delta#232]
Hi !

When doing `diff -u a.txt b.txt | delta` it's working great.
But doing `diff -ur dir_a dir_b | delta` is not working, even if there is only one file different

The diff output is so close in both case, i think (hope) the feature should not be hard to implement.

Thanks !

Edit:

- if i have only diff in files, this is working by doing `diff -u -r dir_a dir_b | delta` but `diff -ur` or `diff -ru` doesn't work.
- If I have a a new file (added or deleted) before starting to parse (`touch dir_a/aaa`) it will not work, but if it's at the end (`touch dir_a/zzz`), it will work great !

**Comment by dandavison** [comment]
Hi @wescande, thanks! Could you add some explicit examples of directories that are not working, and a screenshot showing what is not working?

> If I have a a new file (added or deleted) before starting to parse (touch dir_a/aaa) it will not work, but if it's at the end (touch dir_a/zzz), it will work great !

I think I've just fixed this bug in master. Is this the bug you mean?

**Bug**
<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86259689-538f4280-bb8a-11ea-9819-9c0271be4872.png" alt="image" /></td></tr></table>

**Fixed**
<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86259729-5f7b0480-bb8a-11ea-9e61-e1d2b836a830.png" alt="image" /></td></tr></table>

> if i have only diff in files, this is working by doing diff -u -r dir_a dir_b | delta but diff -ur or diff -ru doesn't work.

I don't think I know how to reproduce this bug: it seems to be working with `-ur` and `-ru`?

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86260026-bf71ab00-bb8a-11ea-806a-00ff0c382b9d.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/86260297-16778000-bb8b-11ea-8399-3a148dbd5777.png" alt="image" /></td></tr></table>

**Comment by wescande** [comment]
Sorry i should have had some screen and example.
Yes i was talking about that !
You solve it all with the commit yesterday ! Thanks !

**Comment by dandavison** [comment]
Awesome, thanks!
