### ISSUE TITLE
🚀 Don't always page with --navigate option.

### ISSUE THREAD

**Issue by kevinhwang91** [dandavison/delta#234]
When the output of  `git diff` is shorter than the screen lines, delta always pages the output.
![image](https://user-images.githubusercontent.com/17562139/86504666-feec0180-bded-11ea-8dd4-455b59c5b2d8.png)

**Comment by Kr1ss-XD** [comment]
Well, it doesn't _always_ page the output; you can control this behavior with the options for `less`, e.g.

`LESS=F git diff`

**Comment by kevinhwang91** [comment]
It doesn't work for me.

`GIT_PAGER='delta --navigate' LESS=F git diff`

**Comment by Kr1ss-XD** [comment]
Whoops sorry... I overlooked you were referring to `--navigate`. My bad.

**Comment by dandavison** [comment]
Thanks @kevinhwang91 and @Kr1ss-XD, I noticed this also and was disappointed by it.  I think that this is a problem with `less`, not with `delta`. Note that `delta --navigate` is implemented by delta starting a `less` process passing `--pattern=<some regex>`. When delta is in `--navigate` mode, it doesn't change anything about the way it usually invokes less, other than passing `--pattern <regex>` (and setting the `LESSANSIENDCHARS` env var to `mK`).

But see e.g. see https://superuser.com/questions/951405/less-with-f-option-and-pattern-matching, or experiment with piping input to `less --pattern --quit-if-one-screen`. It seems that less fills the screen with these lines if given short input and `--pattern`.

So, the question is -- can anyone come up with a `cat myfile.txt | less --pattern ...` invocation that behaves the way they would like? If not, then this might have to be solved in `less`, if that is possible. I don't know any way to implement `delta --navigate` other than via `less --pattern`.

**Comment by Kr1ss-XD** [comment]
@dandavison not sure if you can use that, but
```
LESS=XE less --pattern=$pattern <short_file
```
does exit from less if `short_file` fits into the screen.

**Comment by kevinhwang91** [comment]
It seems that I shouldn't use --navigate option until this issue was solved. Honestly, I hate to fill the screen after invoking delta. 

@dandavison You can close this issue if you want.

**Comment by kevinhwang91** [comment]
#237 has discussed this issue.

**Comment by ronjouch** [comment]
This thread helped me realize what was wrong in my config, and causing `--paging=auto` to fail, printing these `~` characters and failing to not page in short diffs: I configure my `less` with `LESS='-M +Gg'`, for `less` to display in its status bar a percentage of where I'm in the file. So, keeping this as-is because it's helpful when `less`ing a big file, e.g. a log, but overriding it with `LESS=F` in my diff alias.

Thanks for the discussion, everybody.

**Comment by dandavison** [comment]
> It seems that I shouldn't use --navigate option until this issue was solved

@kevinhwang91 I don't have a proper solution yet but one nice thing is that we can easily toggle navigate on/off like this:

```sh
git config delta.navigate true
```

I'm finding that makes it fairly convenient to activate when appropriate (e.g. for `git log -p` or a commit you know has many files & hunks). Of course, one could also create shell aliases doing something similar.

**Comment by dandavison** [comment]
The latest release of delta allows `navigate` to be activated via an environment variable, e.g.:

```
DELTA_NAVIGATE=1 git diff
```

This is motivated by the fact that leaving `navigate` active all the time is problematic; please see the README section https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs

**Comment by dandavison** [comment]
In addition to the `DELTA_NAVIGATE` env var, `git -c ...` can now be used with all delta options. I think this is an improvement in our abilities to configure delta on-the-fly. So here for example,

```
git -c delta.navigate=true log -p
git -c delta.navigate=false log -p
```

This requires the delta 0.6.0.
