### ISSUE TITLE
🐛 `line-number` breaks with 5 digits

### ISSUE THREAD

**Issue by SimenB** [dandavison/delta#238]
![image](https://user-images.githubusercontent.com/1404810/86543227-f5ad8280-bf1c-11ea-8318-81226c46d130.png)

The blue "edge" line is what I'm talking about

I can't share the full diff, unfortunately.

**Comment by dandavison** [comment]
Thanks for this @SimenB! I'll get a fix released. In the meantime, I believe something like below provides a workaround, at the cost of unnecessary loss of screen real estate for lower-numbered hunks. cc @clnoll 

```gitconfig
[delta]
    ...
    line-numbers-left-format = "{nm:^5}⋮"
    line-numbers-right-format = "{np:^5}│"
```
