### ISSUE TITLE
🐛 Duplicate "renamed" header when file is renamed with changes

### ISSUE THREAD

**Issue by waldyrious** [dandavison/delta#245]
For https://github.com/Homebrew/homebrew-cask-fonts/pull/2188, I renamed a file and also edited it. Here's how delta shows the diff (with `diff-highlight` emulation and a couple extra customizations, which should only influence style, not semantics):

![Screenshot 2020-07-11 at 22 37 38](https://user-images.githubusercontent.com/478237/87234280-5a5a5880-c3c7-11ea-9c24-f9c3d903a7d7.png)

And for comparison, here's how git shows it natively (without using a pager):

![Screenshot 2020-07-11 at 22 37 39](https://user-images.githubusercontent.com/478237/87234281-5b8b8580-c3c7-11ea-9e39-51cf67138e67.png)

I would like delta to not show the renamed header twice.

**Comment by waldyrious** [comment]
There's also the sub-optimal detection of the changed text, by the way. Should I open a separate issue for that?

For reference, diff-so-fancy/diff-highlight shows a much more sensible result:

![Screenshot 2020-07-11 at 23 22 41](https://user-images.githubusercontent.com/478237/87234902-8547ab00-c3cd-11ea-94f6-5d92abed6de9.png)

**Comment by dandavison** [comment]
Hey @waldyrious, thanks.

> There's also the sub-optimal detection of the changed text, by the way. Should I open a separate issue for that?

Yes please.  FWIW, with `word-diff-regex = .` delta gives better highlighting than diff-highlight:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/87235044-8b299600-c3a5-11ea-8786-77c6ab7ad1de.png" alt="image" /></td></tr></table>

The algorithm in diff-highlight/diff-so-fancy is [described](https://github.com/git/git/tree/master/contrib/diff-highlight) thus:

> It will find the common prefix and suffix of two lines, and consider everything in the middle to be "different". 

In contrast, delta's algorithm is to tokenize into "words" defined by the customizable regex (`word-diff-regex`), and then run a Levenshtein-type dynamic programming edit inference algorithm at the level of "words" (I think this is more properly known as Wagner-Fischer or Needleman-Wunsch).

I've been thinking that it will probably make sense to implement the more simple-minded algorithm of diff-highlight as an alternative diff-highlighting algorithm in delta. Do you think `diff-highlight` and `diff-so-fancy` in delta should default to using the original, simpler, diff highlight algorithm? On the one hand there is something appealing in being able to say that `delta --diff-highlight`aims for a pixel-for-pixel emulation, and OTOH I do find that the dynamic programming algorithm often gives more helpful results.
