### ISSUE TITLE
🚀 Be able to change theme from env var

### ISSUE THREAD

**Issue by ggsalas** [dandavison/delta#248]
I'm using macOS and sometimes I change from dark to light colors. I would like to be able to change the delta colors automatically, I try with this on my `.gitconfig`:
```
  pager = delta --navigate --syntax-theme="%$DELTA_THEME%"

```
I change `export DELTA_THEME="Dracula"` to `export DELTA_THEME="OneHalfLight"` but not works

There is some other way to do this?

Also, to see if dark mode is active I use [dark-mode](https://github.com/sindresorhus/dark-mode)

**Comment by dandavison** [comment]
Hi @ggsalas, how about using shell functions for this? For example

```sh
delta-dark-on () {
    git config core.pager 'delta --dark --syntax-theme=Dracula'
}

delta-light-on () {
    git config core.pager 'delta --light --syntax-theme=OneHalfLight'
}
```

or as a variation of the above, you can use the environment variable `BAT_THEME` (delta doesn't currently have its own env var; it uses bat's. But I'm happy to change that if people tell me that they'd like them to be independent.)

```sh
delta-dark-on () {
    git config core.pager 'delta --dark'
    export BAT_THEME=Dracula
}

delta-light-on () {
    git config core.pager 'delta --light'
    export BAT_THEME=OneHalfLight
}
```

**Comment by dandavison** [comment]
`--dark/--light` change the default background colors used by delta.

`BAT_THEME` changes the syntax-highlighting colors, i.e. foreground (text) color.

**Comment by ggsalas** [comment]
Thanks @dandavison I have used `export BAT_THEME=Dracula` and works fine 🎉.

If somebody uses kitty terminal, this is my config:
```
export BAT_THEME=Dracula
kittyDarkMode() {
  if [[ $(echo $TERM) == 'xterm-kitty' ]] then
    local LIGHT=(kitty @ set-colors --all --configured $HOME/.config/kitty/kitty_colorLight.conf)
    local DARK=(kitty @ set-colors --all --configured $HOME/.config/kitty/kitty_colorDark.conf)

    if [[ ( $(dark-mode status) =~ 'on' ) ]]; then
      export BAT_THEME=Dracula
      $DARK
    else
      export BAT_THEME=OneHalfLight
      $LIGHT
    fi
  fi
}
```
`kitty_colorLight.conf` and `kitty_colorDark.conf` are theme files. 

Then I add this aliases: 
```
alias colorDark="dark-mode on && kittyDarkMode"
alias colorLight="dark-mode off && kittyDarkMode"
```
<img width="1059" alt="Screen Shot 2020-07-13 at 19 13 23" src="https://user-images.githubusercontent.com/8403993/87358833-feb1db80-c53c-11ea-8ec4-f7ec2f88261c.png">
<img width="1059" alt="Screen Shot 2020-07-13 at 19 13 04" src="https://user-images.githubusercontent.com/8403993/87358843-02456280-c53d-11ea-9b76-b704869a442d.png">

**Comment by dandavison** [comment]
@ggsalas can I just check -- what version of delta are you using? In the latest version of delta you would need to use `--light` and `--dark` to explicitly set delta's background colors defaults.

**Comment by ggsalas** [comment]
@dandavison I'm using delta 0.3.0

**Comment by dandavison** [comment]
Right, thanks, I was confused, ignore!
