### ISSUE TITLE
0.3.0 release not on `crates.io` yet?

### ISSUE THREAD

**Issue by ErichDonGubler** [dandavison/delta#250]
Just a quick report that I was excited to `cargo install-update git-delta`...but was disappointed when it failed because of this. I can run `cargo install --git ... --tag 0.3.0`, of course, but then that makes it harder to keep things up-to-date. :)

**Comment by dandavison** [comment]
Oh! Thanks very much, fixed now.

I have a [Makefile](https://github.com/dandavison/delta/blob/master/release.Makefile) that does all the release steps but I haven't quite got it to the point where it can be ran without hand-holding and I forgot to run the last step on Saturday when I released 0.3.0.
