### ISSUE TITLE
🐛 Line numbers style not taking effect with `--side-by-side`

### ISSUE THREAD

**Issue by amanjitsk** [dandavison/delta#251]
Hi, I don't see the line number style taking effect with the new `--side-by-side` option.
For example, I am getting this
![image](https://user-images.githubusercontent.com/12499495/87360262-bfcd5700-c537-11ea-9643-b3f8b20dfe86.png)
but I am expecting this
![image](https://user-images.githubusercontent.com/12499495/87360306-d96e9e80-c537-11ea-9cde-94ce17390eda.png)
My delta config is as follow:
```
[core]
  pager = delta --side-by-side --syntax-theme=Nord
  ; pager = delta --syntax-theme=ansi-dark
  ; pager = delta --syntax-theme=ansi-light
[delta]
  ; features = defaults unobtrusive-line-numbers decorations light
  features = defaults unobtrusive-line-numbers decorations dark
[delta "defaults"]
  navigate = true
  paging = always
  whitespace-error-style = 22 reverse
[delta "unobtrusive-line-numbers"]
    line-numbers = true
    line-numbers-minus-style = red
    line-numbers-plus-style = green
    line-numbers-left-format = "{nm:>4}┊"
    line-numbers-right-format = "{np:>4}┊"
    line-numbers-left-style = red
    line-numbers-right-style = green
[delta "decorations"]
    commit-style = yellow
    commit-decoration-style = yellow box ul
    file-style = bold cyan ul
    file-decoration-style = none
    hunk-header-style = bold blue
    hunk-header-decoration-style = blue box
[delta "dark"]
    line-numbers-zero-style = "#75829c"
    minus-style = syntax "#5A4646" 
    minus-emph-style = black red
    plus-style = syntax "#415541"
    plus-emph-style = black green
[delta "light"]
    line-numbers-zero-style = "#AAAAAA"
    minus-style = syntax "#FEEDEF" 
    plus-style = syntax "#E4FDEB"
```

**Comment by dandavison** [comment]
Hi @amanjitsk, nice delta config! I think moving `side-by-side` to the left-hand end of the features list gets you what you want:

```gitconfig
[core]
    pager = delta --syntax-theme=Nord
[delta]
    features = side-by-side defaults unobtrusive-line-numbers decorations dark
...
```

If you want to know the details: what was going wrong with your version was this:

- `side-by-side` is a "builtin-feature" and [includes](https://github.com/dandavison/delta/blob/14e894214d782b11a0e1243c6b55b91b37cafc6b/src/features/side_by_side.rs#L22) the `line-numbers` built-in feature.
- The `line-numbers` built-in feature has [its own](https://github.com/dandavison/delta/blob/14e894214d782b11a0e1243c6b55b91b37cafc6b/src/features/line_numbers.rs#L13=L60) default values for line numbers styles etc
- So delta has to have some rules saying how to take in all the features mentioned as command-line flags (e.g. `--side-by-side`) and in feature lists, even taking into account that features are allowed to reference other features... So there's actually a tree of features with values at each node, that may conflict.

So basically in your original version, `--side-by-side` as a command-line flag was taking precedence over the features list, whereas you wanted the opposite.

With a complex config like yours, I'd recommend putting everything in the features list, and not using any flags like `--side-by-side`. The rule then is that (a) features later in the list have priority over features earlier in the list, and (b) the linear ordering is a pre-order traversal, starting from the right end of the list.

If you think it's a bit OTT to define some rules for resolution of config values over a tree...I agree! So I don't expect users to want to know that. I'd just say that "delta does its best to make sense of all the linked features" and if it gets it wrong then the thing to do is to list out individual config values explicitly (and open an issue if it's not easy to get delta to do what you want)

**Comment by dandavison** [comment]
The full rules are given in a [code comment](https://github.com/dandavison/delta/blob/14e894214d782b11a0e1243c6b55b91b37cafc6b/src/options/set.rs#L202) but like I said, it is a bit OTT and I don't expect many people to care or want to know about it!

**Comment by amanjitsk** [comment]
Hi @dandavison , Thanks for the detailed feedback. That did the trick!
Thanks for helping me understand the config as well - I was just trying to put together somewhat of a readable dark scheme.
On the same note, another minor question: is it also possible to specify the `syntax-theme` as a config parameter as opposed to explicitly specifying it as a command line argument, as I have done above ? I know of the `BAT_THEME` environment variable, just wondering if there is a config alternative to that as well.
Thanks for the awesome tool btw! I had been using [kitty's diff](https://sw.kovidgoyal.net/kitty/kittens/diff.html) but it doesn't offer as much flexibility in terms of customization (specifying foreground color of `{plus, minus}-{emph}-style` helps the legibility quite a lot in dark schemes) and usage (ex. for over ssh, in tmux etc.). I think I finally have something that rivals that tool now!
Thanks,
Amanjit

**Comment by dandavison** [comment]
Hey @amanjitsk,

>  is it also possible to specify the syntax-theme as a config parameter as opposed to explicitly specifying it as a command line argument, as I have done above ?

Yes, absolutely: all<sup>1</sup> command line flags can be used as git config entries, just strip the `--` prefix:

```gitconfig
[delta]
    syntax-theme = Nord
```


<sup>1</sup> All the ones that make sense anyway. So not e.g. `--show-syntax-themes` etc.

**Comment by amanjitsk** [comment]
Great, I was adding it to the "defaults" feature group before.
Thank you!

**Comment by dandavison** [comment]
Thanks, I think that's a bug: #252 

>  I had been using kitty's diff 

Oh, you know, I had not seen that. It looks very impressive -- I shall have to take a closer look!
