### ISSUE TITLE
🐛 syntax-theme should be honored in a custom feature in gitconfig

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#252]
With this config, the `syntax-theme` should be activated, but is not. `side-by-side` is activated however, as expected. cc @amanjitsk ref #251 

```gitconfig
[delta]
    features = my-feature

[delta "my-feature"]
    syntax-theme = Nord
    side-by-side = true
```

**Comment by amanjitsk** [comment]
I have also noticed that the `paging = always` option does not take effect for diffs shorter than the height of the terminal (which is really my sole usecase for paging=always). Don't know if this is how its meant to be or if I have something weird going on.

**Comment by dandavison** [comment]
Hi @amanjitsk, I think that's working for me. What do you get if you do these?

```
env | grep -iE '(pager|less)'
echo hello | delta --paging=always
```

I get this:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/87462287-b26aa800-c5dd-11ea-845c-b4b583e76fe8.png" alt="image" /></td></tr></table>

**Comment by amanjitsk** [comment]
For the first command, I get a huge list, but the relevant portion is
![image](https://user-images.githubusercontent.com/12499495/87463132-f5794b00-c5de-11ea-861d-c5d7fa5aeb60.png)
For the second command, I get something weird. I get 
![image](https://user-images.githubusercontent.com/12499495/87463217-12ae1980-c5df-11ea-95f3-66bb22d0eeac.png)

but then on pressing any other key, I proceed to get the paged output as expected (with the pager)

**Comment by dandavison** [comment]
> For the second command, I get something weird. I get

OK, that's because you have `navigate` active. I've added a [section](https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs) in the README now describing this problem, pasted below. Incidentally, I'm finding `git config --global` really useful for toggling certain delta settings on-the-fly.

------------------------------------------------------------------

The recommended way to use `navigate` is to activate it only when needed, for example by doing

```bash
git config --global delta.navigate true
```

The reason is the following: Delta uses `less` as its pager, and the `navigate` feature works by doing `less --pattern <regex-matching-file-and-commit-lines>`. When the git output does not contain file/commit diff lines, `less --pattern` behaves unhelpfully (see [#234](https://github.com/dandavison/delta/issues/234), [#237](https://github.com/dandavison/delta/issues/2)).

**Comment by amanjitsk** [comment]
Ah I see, thanks for the pointer, makes sense!

**Comment by amanjitsk** [comment]
One more question; I currently have `paging = always` set in my git config, but it doesn't seem to work unless I specify it at the command line. Is this also expected ? That's what I had originally meant!

**Comment by dandavison** [comment]
> I currently have paging = always set in my git config, but it doesn't seem to work unless I specify it at the command line. Is this also expected ?

Hm, I think that's a bug. I can reproduce it. Thanks!

**Comment by dandavison** [comment]
@amanjitsk the bugs you reported with `syntax-theme` and `paging` not respecting (custom features in) git config have both been fixed on master. I'll aim to release them in the next few days and will probably mention on this ticket when released.

**Comment by amanjitsk** [comment]
Thanks for the quick update! I'll wait for the binary release as I don't have rust installed
