### ISSUE TITLE
🐛 Strange colored output on Windows 10

### ISSUE THREAD

**Issue by connorskees** [dandavison/delta#255]
Hello!

I hope I'm not missing anything, but it seems that when using cmd.exe or Powershell on Windows 10, all colored output becomes a shade of blue. I would blame the terminal, but this issue appears to occur in the new windows terminal, the old windows terminal, git bash, and alacritty.

When doing just a plain `git diff` with only `git config --global core.pager delta` I see the following output:

<details>

<summary>vscode integrated terminal with delta</summary>

![image](https://user-images.githubusercontent.com/39542938/87561074-295d7a80-c68a-11ea-9f96-671d6cdab723.png)

</details>

As a comparison, this is what `git --no-pager diff` looks like

<details>

<summary>vscode integrated terminal without delta</summary>

![image](https://user-images.githubusercontent.com/39542938/87561177-4bef9380-c68a-11ea-84bc-eca150b2e857.png)

</details>

These screenshots are from the vscode integrated terminal on `Microsoft Windows [Version 10.0.20161.1000]`. This seems to reproduce in every other terminal:

<details>

<summary>Output of various terminals</summary>

### Alacritty (using Powershell)
![image](https://user-images.githubusercontent.com/39542938/87561433-ad176700-c68a-11ea-934b-6bb2a8173ba6.png)

### [The new Windows terminal](https://github.com/microsoft/terminal) with cmd.exe
![image](https://user-images.githubusercontent.com/39542938/87561479-c6201800-c68a-11ea-9d36-f2a50286e048.png)

### The old/legacy Windows terminal running cmd.exe
![image](https://user-images.githubusercontent.com/39542938/87562246-c4a31f80-c68b-11ea-8951-8c24b1e8c29f.png)

### The old/legacy Windows terminal running git bash
![image](https://user-images.githubusercontent.com/39542938/87562809-72aec980-c68c-11ea-84ee-fb7440be7083.png)

</details>

This issue does not occur in WSL2,

<details>

<summary>WSL2 in the new Windows terminal</summary>

![image](https://user-images.githubusercontent.com/39542938/87561908-565e5d00-c68b-11ea-97d8-1bed4c026cc2.png)

</details>

It seems like on Windows it also ignores any configuration of colors, only printing the blue. In both WSL2 and the Windows environment I installed delta with `cargo install git-delta`

**Comment by dandavison** [comment]
Hi @connorskees, thanks for submitting the issue. Did you see the [Windows instructions](https://github.com/dandavison/delta#using-delta-on-windows) in the README? I'm hoping that that's the problem.

**Comment by connorskees** [comment]
Ah my apologies! I saw that but embarrassingly did not think it might be related to this issue. Yes replacing `C:\Program Files\Git\usr\bin\less.exe` with the version provided solved the issue. Thank you! Perhaps it might make sense to document that the output will be modified.

It seems, though, that the unicode characters used for boxes are replaced with their escape sequences,

![image](https://user-images.githubusercontent.com/39542938/87569144-b0afeb80-c694-11ea-9607-5641b4026fec.png)

**Comment by dandavison** [comment]
> Perhaps it might make sense to document that the output will be modified.

Good call. Changed that to

> However, the `less.exe` installed with git has some bugs: you will see incorrect colors and other problems.

> It seems, though, that the unicode characters used for boxes are replaced with their codepoints,

OK, that definitely shouldn't be happening. Is that occurring in all the terminal emulators you are testing? (If you want to take `less` out of the equation while testing, you can do that with `--paging never`)

**Comment by connorskees** [comment]
Hm it appears to only occur in the [new Windows terminal](https://github.com/microsoft/terminal). Alacritty, the old Windows terminal, vscode/xterm.js, and git bash all properly emit the dashes.

I'm not sure if this is helpful at all, but

<details>

<summary>My gitconfig</summary>

```
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.autocrlf=true
core.fscache=true
core.symlinks=true
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
winupdater.recentlyseenversion=2.18.0.windows.1
core.pager=delta
core.bare=false
core.repositoryformatversion=0
core.filemode=false
core.ignorecase=true
core.logallrefupdates=true
submodule.sass-spec.url=https://github.com/sass/sass-spec
submodule.sass-spec.active=true
remote.origin.url=https://github.com/connorskees/grass.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
```

</details>

**Comment by dandavison** [comment]
Hm, that is unexpected -- I'm pretty sure that there are people using it successfully with the new Windows terminal. What happens if you do this (or the equivalent) in that terminal?

```
echo "───────────────────────────────────"
```

**Comment by connorskees** [comment]
Ah so this is interesting. `bat` was also emitting codepoints instead of dashes, which seems to have been caused by my putting the new `less.exe` in my `PATH`.

![image](https://user-images.githubusercontent.com/39542938/87572467-962c4100-c699-11ea-8238-d251eccc41ab.png)

Removing `less.exe` seems to have fixed the issue in `bat`,

![image](https://user-images.githubusercontent.com/39542938/87572514-a9d7a780-c699-11ea-92de-46776471ae4a.png)

However the issue still remains with `delta`. I suppose because its using `less.exe` from git?

![image](https://user-images.githubusercontent.com/39542938/87572296-52d1d280-c699-11ea-98c7-73173daf2691.png)

**Comment by dandavison** [comment]
>  I suppose because its using less.exe from git?

It's correct that if you start the `delta` process with `core.pager = delta` in git config, then `delta` will by default pick up the `less.exe` from git, since in that situation `delta` runs as a child process of git. And so it makes sense that delta and bat might be picking up different less executables, or one of them picking up something and the other nothing. There's more discussion of how we might get less installed more conveniently on Windows in https://github.com/dandavison/delta/issues/197 which might be helpful (I haven't had time to move that forwards yet).

In any case, with delta using the less.exe recommended in the README, both colors and unicode markers should render correctly, which is what you've found for some terminal emulators IIUC. It's possible that some of the Windows users in #197 would be able to say something about you're seeing problems with the Windows Terminal.

**Comment by dandavison** [comment]
Do you have any environment variables affecting less? E.g. I have

```bash 
$ env | grep -iE '(pager|less)'
LESS=-RS
PAGER=less
```

If this is only affecting Windows Terminal and the others are working correctly, do you think we can close this issue as not being a delta issue?

**Comment by connorskees** [comment]
Certainly, yes. I'm not sure if this is a `bat`, Windows terminal, or `less` issue, but it seems to be unrelated to `delta`. I don't usually look at `git diff` with `cmd.exe` in the Windows terminal, so this is not an issue affecting me very heavily. Thanks for your help!

> Do you have any environment variables affecting less?

No, it seems not
![image](https://user-images.githubusercontent.com/39542938/87631065-9a417880-c704-11ea-95ec-d310f53ed9e8.png)

**Comment by khellang** [comment]
Hey @connorskees! 👋🏻

Sorry to drag this up again, but did you ever figure out what caused the codepoint output? I'm running the latest Windows version of less and now I'm seeing the exact same output:

![image](https://user-images.githubusercontent.com/582487/123150084-4128ab80-d462-11eb-848e-54af1c43e193.png)

**Comment by connorskees** [comment]
@khellang unfortunately i haven't looked into that very deeply. it's presumably related to `bat`'s paging in some way, but i no longer have a windows machine on which to test this

**Comment by dandavison** [comment]
@connorskees one question is, is there any possibility that delta is not actually picking up the version of less that you are thinking it is? To test that, can you try this:

```
git -c pager.diff='less --version' diff
```

That should cause the pager to print out its version instead of actually paging the git output. A similar trick (at least on a unix-like machine) is `git -c pager.diff='which less' diff` to interrogate the path of the less executable that is being resolved _in the context of the pager invocation by the git process_.

I guess I'm wondering whether git is doing something causing you to pick up a different version of less that exists on your system.
