### ISSUE TITLE
🚀 Support displaying files and commits as OSC 8 hyperlinks

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#257]
[This proposal](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) introduces a spec for displaying hyperlinks in terminal emulators. Support for it among terminal emulators is already good, with more pending. Unfortunately neither [less -R](https://github.com/gwsw/less/issues/54) nor [tmux](https://github.com/tmux/tmux/issues/911) support it yet, so for now Delta users would only be able to benefit by (a) using a fork of `less` (and tmux), or (b) not using `less` (or tmux) with delta.

In any case, two ways in which delta could make use of this feature are

1. Format file names as clickable `file://` links.
2. Format commit hashes as links to an appropriate page in a git web-hosting site, if that is discernible from the git remote in the repo in which delta was invoked.

Both these would be optimistic: delta just receives text on stdin and there's no guarantee that the files in that text have ever existed anywhere! Also delta doesn't need to be invoked inside a git repo, and I think perhaps neither type of link-formatting  should be done when delta is not invoked inside a git repo.

**Comment by navarroaxel** [comment]
I tried to use `git config --global delta.hyperlinks true` without your `less` patch and the result was the expected:
![Screenshot_20200722_221909](https://user-images.githubusercontent.com/1536740/88245926-4b995e80-cc6f-11ea-9d42-eae942ca647f.png)
![Screenshot_20200722_221959](https://user-images.githubusercontent.com/1536740/88245929-4d632200-cc6f-11ea-88fb-0f68fbf64ef0.png)

But I tested your patch in `less`, first using the stable `v551` and then the beta `v563`.

These are the Arch Linux's `PKGBUILD` files for `less` and `git-delta`: https://gist.github.com/navarroaxel/40fea15bae01d6ffb0d2d4109474bdf1. 

the result, with or without the `delta.line-numbers=true` was the same:
![Screenshot_20200722_224000](https://user-images.githubusercontent.com/1536740/88246006-8ac7af80-cc6f-11ea-95eb-da1609baef37.png)
![Screenshot_20200722_224554](https://user-images.githubusercontent.com/1536740/88246008-8c917300-cc6f-11ea-8c2d-33d731db40b4.png)

I'm using KDE's Konsole as my main terminal, and XTerm, but the line numbers or the filename is not a link. What I'm doing wrong? or the Konsole terminal doesn't support this? @Kr1ss-XD do you have some ideas?

**Comment by dandavison** [comment]
@navarroaxel Can you try with a terminal emulator that definitely supports the hyperlinks? Based on the links in https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda I fear that Konsole does not yet.

**Comment by navarroaxel** [comment]
Works in a Konsole's PR still not merged!

![Screenshot_20200723_084951](https://user-images.githubusercontent.com/1536740/88283350-9643c680-ccc1-11ea-8507-7f422e274730.png)

**Comment by dandavison** [comment]
> But don't open the editor in the line I clicked, should you add `#position=line`?

Hi @navarroaxel, this is discussed in the help text for the `hyperlinks-file-link-format` option. Basically `file://` URLs simply do not support opening at a line number: the [spec](https://tools.ietf.org/html/rfc8089) doesn't contain any place to put the line number, and text editors/IDEs have different syntax for requesting that they open at a line. So, what I am doing is

1. Changing the format of the file URLs emitted by delta
    ```gitconfig
    [delta]
        hyperlinks-file-link-format = "file-line-column://{path}:{line}"
    ```
That's a custom URL scheme that I just made up for my use. So it will emit URLs that look like the standard compiler output, e.g. `file-line-column:///home/dan/file.rs:77` 

2. Configuring an application to act as the URL handler for those URLs, and open the line in a text editor. For this I have written a small utility: https://github.com/dandavison/open-in-editor since I couldn't see something that did exactly what I wanted for multiple text editors.

The utility currently supports opening in VSCode, Sublime, Emacsclient and PyCharm, and has instructions for registering the URL handler in MacOS.

If you can see a more streamlined way for delta users to do this, please let me know! Alternatively, if you would like to use [open-in-editor](https://github.com/dandavison/open-in-editor) then I'd appreciate any instructions for registering the application as the URL handler in Linux. And support for more editors could easily be added to the python script (e.g. I'm not sure exactly what behavior vim users would want).


> Could you add support for commit SHA links to GitLab or custom GitLab servers?

Yeah, I was lazy and only added GitHub so far, I'll do GitLab! So that would be URLs of the format https://gitlab.com/gnachman/iterm2/-/commit/4600e60a0494d630ac25a277940bbd6359d89565, correct? Do you have an example of what the URL would look like for a custom GitLab server? The information delta is using is the git remote URL (`remote.origin.url`).

**Comment by dandavison** [comment]
> Could you add support for commit SHA links to GitLab or custom GitLab servers? like https://invent.kde.org/utilities/konsole/-/commit/f8e06d55a2d2a7e322cc980052aa86d67d3aae17

@navarroaxel almost a year later but your suggestion is now implemented on master (there'll be a release soon). See https://github.com/dandavison/delta/issues/613

**Comment by navarroaxel** [comment]
Thanks awesome @dandavison! :star_struck: I'll test it sooner
