### ISSUE TITLE
Unusual context box

### ISSUE THREAD

**Issue by lzybkr** [dandavison/delta#27]
The context box here is not sized correctly. It's also an odd attribution, but maybe that's `git` and not `delta`.

![image](https://user-images.githubusercontent.com/2148248/66858816-efb2e400-ef3e-11e9-8e0e-4db756e68685.png)

To repro:

```
git clone clone https://github.com/lzybkr/less
cd less
git show 163de2d
```

**Comment by dandavison** [comment]
Thanks! This is delta failing to deal with tabs correctly. It currently expands tabs to spaces when they occur as indentation at the beginning of the line, but isn't addressing tabs elsewhere in the line.

`bat -A` output on screen.c:

![image](https://user-images.githubusercontent.com/52205/66859892-fcd0d280-ef40-11e9-9168-15cd5a5bdbcf.png)
