### ISSUE TITLE
No colours

### ISSUE THREAD

**Issue by tigger04** [dandavison/delta#273]
Apologies for raising this in the issues section, but wasn't quite sure where else to look. I believe I have followed all of the installation and config steps, but I cannot persuade delta to show any colours at all, even with delta --show-syntax-themes

Here's an extract from my git config ... am I missing some really obvious setting?

```
[core]
	pager = delta

[interactive]
	diffFilter = delta --color-only

[delta]
	features = side-by-side line-numbers decorations
	whitespace-error-style = 22 reverse
	plus-color = "#012800"
	minus-color = "#340001"
	syntax-theme = Monokai Extended

[delta "decorations"]
  commit-decoration-style = bold yellow box ul
	file-style = bold yellow ul
	file-decoration-style = none
```

**Comment by dandavison** [comment]
Hi @tigger04 thank you for opening this, I'd like to get to the bottom of it ASAP.

Two quick questions:

1. What's your `delta --version`?
2. Does anything change if you add the setting

```gitconfig
    inspect-raw-lines = true
```

Thanks!

**Comment by dandavison** [comment]
Could you post a screenshot also?

**Comment by tigger04** [comment]
As below - it's the most recent one from Homebrew

```
$ delta --version
delta 0.4.0
$ uname -a
Darwin AMAC02ZKFUGMD6N 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

```

**Comment by tigger04** [comment]
inspect-raw-lines (under delta category of git config I presume) does not appear to make a difference - screenshots to follow

**Comment by tigger04** [comment]
A short video clip will shortly be here to show you what I'm seeing: https://youtu.be/EuN2yVdQgOo

also - 
<img width="980" alt="snip-area-open-qSZUnD" src="https://user-images.githubusercontent.com/43514058/89438641-f9f9d500-d740-11ea-9c41-ce5b95780d62.png">

**Comment by dandavison** [comment]
Hm! I don't know what's going on yet. Would you be able to do some more things?

1. What's your terminal emulator?
1. Run this shell script and post a screenshot of the output: https://github.com/dandavison/delta/blob/master/etc/diagnostics


For me, the output of the diagnostics shell script is

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/89461987-c0be6680-d73a-11ea-8674-b14b50f9ad63.png" alt="image" /></td></tr></table>

**Comment by tigger04** [comment]
Sure thing - I use iTerm2 on MacOS but seeing the same results with Apple's Terminal.app

<img width="995" alt="delta1-iterm" src="https://user-images.githubusercontent.com/43514058/89546168-30485a80-d7fc-11ea-9cab-ebe21aa5c9ec.png">
<img width="995" alt="delta2-iterm" src="https://user-images.githubusercontent.com/43514058/89546164-2fafc400-d7fc-11ea-8a25-8daea0332d89.png">
<img width="885" alt="delta3-apple-terminal" src="https://user-images.githubusercontent.com/43514058/89546157-2f172d80-d7fc-11ea-862c-ca3236589fb7.png">
<img width="885" alt="delta4-apple-terminal" src="https://user-images.githubusercontent.com/43514058/89546148-2a527980-d7fc-11ea-9f8a-59c1bd314b15.png">

**Comment by dandavison** [comment]
OK, now we're getting somewhere!

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/89547123-5e657480-d7d3-11ea-8ee1-da0483e76966.png" alt="image" /></td></tr></table>

This indicates that on your system the executable name `less` resolves to an executable named `cat`. I can reproduce the error message by using the BSD `cat` that comes with MacOS:

```
~ /bin/cat --version
/bin/cat: illegal option -- -
usage: cat [-benstuv] [file ...]
```


<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/89547572-ee0b2300-d7d3-11ea-90f3-db52ca0480c2.png" alt="image" /></td></tr></table>

And this indicates that somehow [vimcat](https://github.com/vim-scripts/vimcat/blob/master/vimcat#L9) is involved (I'm not familiar with that). 

To get to the bottom of this, I would do `type -a less` to see what it is resolving as. For me that gives

```
~ type -a less
less is an alias for less -S
less is /Users/dan/bin/less
less is /usr/bin/less
```

To make delta work, you'll need to either make `less` resolve to `/usr/bin/less`, or set the `PAGER` or `BAT_PAGER` environment variables to something like `/usr/bin/less -R`.

**Comment by tigger04** [comment]
How very interesting. So
![image](https://user-images.githubusercontent.com/43514058/89616253-f751c980-d87f-11ea-8795-426dcc2065f6.png)

Nothing for PAGER or BAT_PAGER, something funky going on with BATPAGER though

Less looks ok, nothing tot see here

<img width="636" alt="image" src="https://user-images.githubusercontent.com/43514058/89616379-37b14780-d880-11ea-9308-d5cb8b535c0a.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/43514058/89616930-2452ac00-d881-11ea-8d9c-a97f776a1954.png">

This alll looks proper

<img width="668" alt="image" src="https://user-images.githubusercontent.com/43514058/89616571-865ee180-d880-11ea-862e-c084b79331eb.png">

And yet

<img width="381" alt="image" src="https://user-images.githubusercontent.com/43514058/89616851-fec5a280-d880-11ea-865c-5cfb27954563.png">

gives us colours!

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/43514058/89616965-36cce580-d881-11ea-86ca-570dcc786773.png">

I'm a bit confused, but we have a solution at least

**Comment by tigger04** [comment]
Doh, the clue was in your last comment of course

<img width="476" alt="image" src="https://user-images.githubusercontent.com/43514058/89617954-0b4afa80-d883-11ea-95b3-dea36ba59b57.png">

The culprit!

Thanks for your help, delta looks nice! Look forward to using it in technicolor now :)

**Comment by tigger04** [comment]
Still a little confused as to why though, my understanding is that aliases are only in force during interactive sessions. I suppose when we invoke delta it is, just did not think an alias would apply when running a script etc.

**Comment by dandavison** [comment]
Ok great, I'm happy we have a solution at least!

You're right though. The alias only affects the shell process it's defined in, and delta is not starting a shell process in order to invoke less, let alone one with your dotfiles sourced, so it seems the alias must be a red herring. We could do more investigation, to see what a rust program using `std::Process::Command::new("less")` is picking up on your system but, absent that, I don't have an explanation yet but I'll remember this case and perhaps the answer will become apparent to one of us at some point (do post here if so).

Meanwhile, yes, Delta will probably be better with colours :)
