### ISSUE TITLE
🐛  [Linux] git add -p not working with side-by-side

### ISSUE THREAD

**Issue by msirringhaus** [dandavison/delta#274]
System: openSUSE Tumbleweed, self-packaged delta as `git-delta` (because of naming conflicts).
Happens for delta 0.3 and 0.4

My gitconfig:
```
[core]
    pager = git-delta

[interactive]
    diffFilter = git-delta --color-only

[delta]
    features = side-by-side line-numbers
    light = true
```

My diff:
```
 /* Disable DoH by default */
 pref("network.trr.mode", 5);
-// do not disable system-global or app-global extensions
-pref("extensions.autoDisableScopes", 3);
+// do not disable any scope
+pref("extensions.autoDisableScopes", 0);
 pref("extensions.shownSelectionUI", true);
+pref("extensions.langpacks.signatures.required", false);
```

Doing `git diff` works fine, but doing `git add -p` gives me
```
fatal: mismatched output from interactive.diffFilter                                                                                                                         
hint: Your filter must maintain a one-to-one correspondence                                                                                                                  
hint: between its input and output lines
```

If I explicitly set `side-by-side = false` in .gitconfig -> [delta], it works.

**Comment by dandavison** [comment]
Thanks for this @msirringhaus! The good news is there's a PR in progress for this linked to https://github.com/dandavison/delta/issues/258.

**Comment by msirringhaus** [comment]
Ah, perfect. I saw that PR, but didn't realize it was my issue. 
Thanks!

**Comment by yoichi** [comment]
This is another problem.
side-by-side feature should be disabled with raw/color-only mode.

**Comment by alfredbez** [comment]
I checked the PR, but it does not solve this issue.

**Comment by yoichi** [comment]
@dandavison This issue is not solved yet. Please reopen this.

Its cause is that delta shows modified line (+ line and - line) into 1 line and it violates a requirement for interactive.diffFilter:
https://github.com/git/git/blob/master/add-patch.c#L601
```
mismatched_output:
		error(_("mismatched output from interactive.diffFilter"));
		advise(_("Your filter must maintain a one-to-one correspondence\n"
			 "between its input and output lines."));
```

**Comment by yoichi** [comment]
I'm sorry. I was missing a fix in
https://github.com/dandavison/delta/commit/6669e6ad698e44c51856ab40fe0dc6d87b7cb4b7

**Comment by adampetrovic** [comment]
Upgrading to 0.4.1 didn't solve this issue for me.

note the omit hunk-header-style
```
[delta]
    line-numbers = true
    plus-style = syntax "#003800"
    minus-style = syntax "#3f0001"
    hunk-header-style = omit

[delta "line-numbers"]
    line-numbers-left-style = cyan
    line-numbers-right-style = cyan
    line-numbers-minus-style = 124
    line-numbers-plus-style = 28

[interactive]
    diffFilter = delta --color-only
```

```
$ git add -p
fatal: mismatched output from interactive.diffFilter
hint: Your filter must maintain a one-to-one correspondence
hint: between its input and output lines.
```

If I comment out `hunk-header-style = omit` it works.

**Comment by dandavison** [comment]
Thanks @adampetrovic. I'll get this fixed. Linking #293 where @iyerusad also made this diagnosis.

**Comment by dandavison** [comment]
Thanks @adampetrovic for that diagnosis. There's good discussion also in #320, which is the same bug. I'm going to close this one to keep discussions in one place.
