### ISSUE TITLE
🚀 Release aarch64 build

### ISSUE THREAD

**Issue by gavinbeatty** [dandavison/delta#278]
I see there is now an armhf build for the latest release. It would be great if there was also an aarch64 build going forward.

I do some hobbyist mirageos work on a Raspbery Pi 4 running 64 bit, and I'd love to be able to use delta there, without having to compile from source. I use Arch Linux, and https://aur.archlinux.org/packages/git-delta-bin/ works great on x86_64 and armv7h, I can create an Arch package from your release binaries, without having to compile from source (installing rust on my small device, already flooded with OCaml packages :) ). With aarch64 release builds, a minor change would let it work on aarch64 as well.

**Comment by dandavison** [comment]
Hi @gavinbeatty, I'm happy to help make this happen. However I'll admit that I don't have a good knowledge of what the different architectures and binary types you're referring to are. Do you (or @navarroaxel or @Kr1ss-XD ) know exactly what needs to be done here? Feel free to submit PRs against delta's travis config.

**Comment by gavinbeatty** [comment]
@dandavison, cool, I've never really used travis, or rust cross-compiling, but this is a cookie-cutter approach based on the armhf cross-compile already there. If there's a way for me to trigger travis to use the updated config from my branch, as a test, I'm not aware of it.

If/when the release builds are added, I can talk to navarroaxel about updating the AUR. It'll be a simple 2 line change.

**Comment by gavinbeatty** [comment]
I see the travis build now. I'll fix the issues.

**Comment by navarroaxel** [comment]
Hey @gavinbeatty,

The content between the `delta-0.4.0-x86_64-unknown-linux-gnu.tar.gz`, the `git-delta_0.4.0_amd64.deb` used by `git-delta-bin` and the AUR `git-delta` compilation is diff. This is caused by `etc/ci/before_deploy.sh`.

If you add the `makepkg` for Arch Linux, we can use that `.tar.zst` directly in the `git-delta-bin`.

**Comment by navarroaxel** [comment]
The `.deb` file was not generated for `aarch64`: https://github.com/dandavison/delta/releases/tag/0.4.1

**Comment by navarroaxel** [comment]
hey @gavinbeatty, I've updated the `git-delta-bin` package in AUR. Please try the `aarch64` installation.

**Comment by gavinbeatty** [comment]
Works great, thanks.

**Comment by dandavison** [comment]
Can anyone summarize what more is needed here (if anything)?

**Comment by gavinbeatty** [comment]
Nothing from me. Closed.
