### ISSUE TITLE
🐛 Git diff Zebra mode

### ISSUE THREAD

**Issue by kjmph** [dandavison/delta#280]
In the case that one sets zebra mode in their git config:

```ini
[diff]
        colorMoved = dimmed-zebra
```

This results in output problems with delta:

<img width="1439" alt="Screen Shot 2020-08-07 at 9 26 51 AM" src="https://user-images.githubusercontent.com/1075649/89661837-6c2cff80-d890-11ea-995d-e478dc27a5d7.png">

This can be worked around slightly by using `--tabs=0` when not in `--side-by-side` mode:

<img width="1440" alt="Screen Shot 2020-08-07 at 9 30 59 AM" src="https://user-images.githubusercontent.com/1075649/89662048-b910d600-d890-11ea-9c62-9bb8f54bd320.png">

For my purposes, this is enough, because I use difftool when I would like side-by-side comparisons so I can have the full context. However, I figured I would report this in case it bothers anyone else.

**Comment by dandavison** [comment]
Thanks @kjmph, that's fixed in master (not released).

>  I use difftool when I would like side-by-side comparisons so I can have the full context. 

Can you expand on this? What is difftool?

**Comment by kjmph** [comment]
Thanks for such a quick fix again! I removed `--tabs=0` and now `--side-by-side` works.

Note, difftool allows one to use common diff tooling, yet the nicest thing is that it makes a copy of the revision you are diffing against in `/tmp/` and you can execute your diff tool of choice. Your tooling of choice may have more aggressive diffing searches, or a native OS interface like `FileMerge` or `tkdiff`. As a positive, you have the full context of both revisions, so one see the surrounding code giving you more context on the change. Personally, I just use emacs' ediff as a difftool with two windows side-by-side. `tig` has a nice way to approach this as well, where `[` and `]` change the number of lines displayed for context around a frag. However, sometimes it is desirable for side-by-side and full context.
