### ISSUE TITLE
🚀 How can I install it for Ubuntu? [help]

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/delta#282]
Hi, thanks for contributing to Delta, please go ahead and describe your proposal!

**Comment by dandavison** [comment]
Hi @avatar-lavventura,

There are a few different options:

1. The simplest is to download one of the `*linux*.tar.gz` executables at https://github.com/dandavison/delta/releases, unpack it, and use the executable file that it contains. If you're not sure which one is right for your computer's architecture, run the command `uname -a` and see if that makes it clear. If you can't find one that works, please post here again and we'll help.

2. You could also use a Debian `.deb` file and install it with `dpkg -i <name-of-file>.deb`. See the "Debian" section in https://github.com/dandavison/delta#installation (Ubuntu is a derivative of Debian).

cc @barnumbirr in case he can improve upon these instructions (it would be nice to make the README more helpful for Ubuntu users).

**Comment by barnumbirr** [comment]
Hello,  
I'll create a PR with more detailed isntallation isntructions in the next couple of days.  
Cheers.
