### ISSUE TITLE
🚀 Is it possible to open `git show` in subshell and prevent output on console?

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/delta#283]
As pager I was using `less -r`

```
[core]
    pager = less -r
```

----

When I have done `git show`, the results show in less window and when I press `q` , I won't see any printed output in the  terminal shell. Is it possible to obtain same approach using `delta`. Basically when I do `git show` and afterwards press `q` I dont want to see its outout on the shell like less does

**Comment by ryuta69** [comment]
@avatar-lavventura 
I think you can achieve this by command below or setting in your (bash/zsh)rc file.

```
export LESS=R
```

![ss](https://user-images.githubusercontent.com/41639488/94184522-fbdd4a80-fede-11ea-9d3d-9a7f25828f18.gif)
