### ISSUE TITLE
🐛 Side-by-side view not available in latest version from Chocolatey

### ISSUE THREAD

**Issue by adam-c-anderson** [dandavison/delta#285]
# Description

I've installed Delta and the updated `less.exe`, set the pager to `delta`, and copied the config used in the README into my global .gitconfig. However, the side-by-side view simply doesn't appear.

I've concluded this is because the version available through Chocolatey is too old to support the side-by-side view. Please consider this a request to update the Chocolatey package. 😄 

# Environment

Delta 0.2.0
Windows 10, Windows Terminal, Git for Windows with fixed `less.exe`

**Comment by dandavison** [comment]
Hi @adam-c-anderson, thanks for this. Yes, 0.2.0 is an old version; `side-by-side` was added in 0.3.0.

@nzbart would you be able to advise here -- how is the update process supposed to work for the chocolatey package? (ref #197).

**Comment by nzbart** [comment]
@dandavison The Chocolatey package is supposed to be automatically rebuilt when you release a new version of Delta here on Github. However, I was installing the `-x86_64-pc-windows-gnu.zip` version, which appears to no longer be built. I've updated the Chocolatey package to now look for the `-x86_64-pc-windows-msvc.zip` version, so hopefully the new version should be out in the next couple of days after approval by the Chocolatey admins.

**Comment by dandavison** [comment]
Thanks @nzbart! Yes, delta has switched back to the `msvc` toolchain for Windows binaries: Travis has switched between the two, unpredictably, as far as I understand it; I just track it when the Windows builds fail. I'll tell you if something like that happens again.

**Comment by adam-c-anderson** [comment]
🎉 Thanks, everyone! I'll look forward to the new version appearing soon! 😁

**Comment by adam-c-anderson** [comment]
Chocolatey version is still at 0.2.0. Is it just taking a long time for approval?

**Comment by nzbart** [comment]
@adam-c-anderson unfortunately, yes. It's awaiting approval here: https://chocolatey.org/packages/delta/0.4.1

**Comment by nzbart** [comment]
@adam-c-anderson version 0.4.1 has been approved and should be available for updating from Chocolatey.

**Comment by adam-c-anderson** [comment]
Excellent. Thanks!

**Comment by dandavison** [comment]
Thanks a lot @nzbart.
