### ISSUE TITLE
🚀 Display git blame commit hashes as hyperlinks 

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#291]
With `hyperlinks = true`, commit hashes shown by `git blame` should be rendered as hyperlinks. By default, these should be http links to the commit page in the remote web-hosted git repo.

A new option `hyperlinks-commit-link-format` could be added to allow the nature of commit links to be customized. For example, one could use a custom link protocol and register a handler on your system to do something like

1. Display the commit using git and delta in a new terminal window

2. Display the commit in a different git client, such as magit.

 We already have `hyperlinks-file-link-format` which allows users to use custom protocols to open delta file hyperlinks in their editor/IDE. See https://github.com/dandavison/open-in-editor for some usage notes.

cc @navarroaxel @Kr1ss-XD

**Comment by phil-blain** [comment]
Hi @dandavison ! searching "blame" in the issues brought me to this one, but here is one (crazy?) idea:

delta could syntax-highlight `git blame output` ! that would be really great. What do you think (I can open a new issue for that if you like) ?

**Comment by dandavison** [comment]
> delta could syntax-highlight git blame output ! that would be really great. What do you think (I can open a new issue for that if you like) ?

I agree! Please do open an issue. I also think delta should highlight merge conflicts in a way that is helpful. So, there are definitely some major features that should  be added to delta but haven't been yet. Of course, they are open to anyone out there who'd like to have a go. (And having open issues for them is a very good start.)
