### ISSUE TITLE
🐛 Running "git branch" results in "Pattern not found"

### ISSUE THREAD

**Issue by CodePurble** [dandavison/delta#295]
Running `git branch` results in the following

![screenshot-1597761338](https://user-images.githubusercontent.com/49452779/90526792-72738380-e18e-11ea-997b-fe370806467d.png)

On pressing `Return`, I get the expected output but it is oddly formatted 

![screenshot-1597761380](https://user-images.githubusercontent.com/49452779/90526794-730c1a00-e18e-11ea-8a58-9eb79c907d17.png)

Is this supposed to happen? It works fine with `delta` disabled.

![screenshot-1597761942](https://user-images.githubusercontent.com/49452779/90527897-abf8be80-e18f-11ea-8798-67bc533bc012.png)

Relevant portions from my `.gitconfig`

```
[core]
	pager = delta
	excludesfile = ~/.gitignore_global

[delta]
	navigate = true
	line-numbers = true
	plus-style = 'bold "#04B201"'
	minus-style = 'bold strike "#CC0000"'
	zero-style = 'dim'
	syntax-theme = Solarized (dark)

[interactive]
	diffFilter = delta --color-only
```

System information:

```
OS: Manjaro Linux (20.1)
delta version: 0.4.1 (From AUR)
Terminal: Alacritty
```

**Comment by dandavison** [comment]
Hi @CodePurble, this is because you have `navigate = true`.

`navigate` is useful, but it doesn't behave as desired in all situations, and so it is recommended not to leave it activated all the time. There's a section in the README documenting this: https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs

What I suggest there is using commands like the following to activate it when needed:

```sh
git config --global delta.navigate true
```

```sh
git config --global delta.navigate false
```

**Comment by CodePurble** [comment]
Oh that's right :sweat_smile:. Works like a charm now. I'll remember that from now on. Sorry about that. Thank you for the incredibly fast reply (I was quite surprised!)

**Comment by dandavison** [comment]
The latest release of delta allows `navigate` to be activated via an environment variable, e.g.:

```
DELTA_NAVIGATE=1 git diff
```

This is motivated by the fact that leaving `navigate` active all the time is problematic; please see the README section https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs
