### ISSUE TITLE
🐛 Fedora version stuck at 0.1.1

### ISSUE THREAD

**Issue by koterpillar** [dandavison/delta#303]
Following the instructions to install Delta on Fedora 32 installs:

```
$ delta --version
delta 0.1.1
```

Should the latest version be uploaded to the repositories automatically?

Is there another way of installing a recent version, preferably with auto-update?

**Comment by dandavison** [comment]
Thanks @koterpillar.

 @ignatenkobrain do you know whether the fedora packages should be auto-updating from Delta releases, or what needs to be done? ref https://github.com/dandavison/delta/pull/172

**Comment by ignatenkobrain** [comment]
I usually just update it myself. I'll check why we have old version later today.

**Comment by dandavison** [comment]
Thanks @ignatenkobrain!

**Comment by ignatenkobrain** [comment]
@dandavison @koterpillar I've had to package some new dependencies & update some of them... But now I managed to build it and it is building now with proper autocompletions now: https://koji.fedoraproject.org/koji/taskinfo?taskID=50295303

Once that is done, I'll build it for stable releases and submit updates into the update system bodhi... Will send you a link here. Please test it and leave karma if it works or does not.

**Comment by ignatenkobrain** [comment]
F32: https://bodhi.fedoraproject.org/updates/FEDORA-2020-94f36b401a
F33: https://bodhi.fedoraproject.org/updates/FEDORA-2020-be4093c436
F34: https://bodhi.fedoraproject.org/updates/FEDORA-2020-8ccb6ceafa

**Comment by dandavison** [comment]
Thanks @ignatenkobrain! @koterpillar all good?

**Comment by koterpillar** [comment]
Yes, it's made its way to Fedora 32. Thank you!
