### ISSUE TITLE
🐛 Sometimes it doesn't work and just freezes

### ISSUE THREAD

**Issue by EvgenyOrekhov** [dandavison/delta#304]
Sometimes when I execute `git diff` it just doesn't work and freezes. <kbd>Ctrl + C</kbd> doesn't work also.

![image](https://user-images.githubusercontent.com/8045060/91561351-1ce46700-e944-11ea-8d42-2e728ea613cb.png)

OS: Windows 10
Terminal: Git Bash in VS Code
delta version: 0.4.1
Git version: 2.28.0

Git config:

```
[core]
        pager = delta  
[delta]
        features = line-numbers
```

If you need me to run it in debug mode or something to gather more info, please tell me how to do so.

**Comment by dandavison** [comment]
Hi @EvgenyOrekhov, OK, let's try to get to the bottom of it. Here are some things I would try

- Comment out the `pager = delta` line and confirm `git diff` works
- Use the absolute path of the delta executable in your git config, something like `pager = Path\To\Delta.exe`
- Run `delta --help` to check delta is working
- Pipe the git output directly into delta: `git diff package.json | delta`

**Comment by EvgenyOrekhov** [comment]
The thing is that it doesn't work **sometimes**. It works fine 9 out of 10 times. Sometimes it doesn't work, I open another terminal tab, and it works there just fine, on the same set of files. So it is definitely not a problem with `git diff` (`git diff` itself always works fine, and it has always been working fine with diff-so-fancy). And it is definitely not a problem with the path.

**Comment by dandavison** [comment]
Can you reproduce the problem by piping git diff to delta explicitly? E.g. `git diff package.json | delta` Also, if you use a use a different shell/terminal emulator, do you still see the problem?

**Comment by EvgenyOrekhov** [comment]
OK, will try to catch it using piping.

Able to reproduce in Windows Terminal (also Git Bash).

**Comment by dandavison** [comment]
Any luck @EvgenyOrekhov ?

**Comment by EvgenyOrekhov** [comment]
I've been using it dozens of times per day, and It's been working fine for the past few days. Perhaps the Moon was in the wrong phase :)

**Comment by dandavison** [comment]
Oh OK that's good to hear!
