### ISSUE TITLE
🚀 using static binaries

### ISSUE THREAD

**Issue by hboetes** [dandavison/delta#305]
Perhaps you could add instructions on how to set up static binaries, since they are portable and make installing delta on various hosts a breeze. For example:
```
sudo apt install musl-tools
rustup target add x86_64-unknown-linux-musl
cargo build --release --target x86_64-unknown-linux-musl
install -s -D target/x86_64-unknown-linux-musl/release/delta   /usr/local/bin/delta
```
You could also consider adding them to the github binaries so people won't have to go through the hasle of setting up rust.

**Comment by hboetes** [comment]
The static binary is smaller actually.
```
% ls -lh delta.dynamic
-r-xr-xr-x 1 root root 4.4M Aug 23 00:22 delta.dynamic
% file delta.dynamic
delta.dynamic: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e214f2aaca699d56985859e0035502c0894de41a, for GNU/Linux 3.2.0, stripped

% ls -lh delta.static
xr-xr-x 1 root root 4.3M Aug 29 20:05 delta.static
% file delta.static
delta.static: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=dfbc3262d258303f4d2454745ae1e5f598998a10, with debug_info, not stripped
```

**Comment by dandavison** [comment]
Hi @hboetes, thanks for this. I'm not very expert in this area but is it not the case that the musl binaries that we're distributing are already statically linked?

https://github.com/dandavison/delta/releases/download/0.4.3/delta-0.4.3-x86_64-unknown-linux-musl.tar.gz
```
$ file delta-0.4.3-x86_64-unknown-linux-musl/delta 
delta-0.4.3-x86_64-unknown-linux-musl/delta: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=2707a1a30febd4bbc42bca2519258cf422b64e76, stripped
```

**Comment by hboetes** [comment]
You're right, that's a static binary that should work on any Linux amd64 system. :-)

**Comment by dandavison** [comment]
Great, feel free to propose (e.g. via PR) any extra instructions or links to Rust docs to add to the README regarding static binaries.
