### ISSUE TITLE
🐛 Can't disable line numbering from command line

### ISSUE THREAD

**Issue by HaleTom** [dandavison/delta#307]
If I run:

    git diff | delta --line-numbers=false | cat

I see line numbers.

How do I disable line numbers from the command line?

I tried `--no-line-numbers`, but no joy.  It would be great to be able to disable any boolean with `--no-*`, to override something that had been previously enabled (eg by a script or bash alias)

**Comment by dandavison** [comment]
Hi @HaleTom, thanks for this. I agree it would be nice if this were more convenient. I think the best that's available right now is:

1. `git config --global delta.line-numbers false; git diff`
  Not perfect but I've been finding this approach quite useful. Of course one can go further in this direction with custom shell aliases / wrapper functions.

1. `delta --no-gitconfig`
  But then you have to build back up the options you do require

A couple of tangential thoughts:

Sometimes I wonder if it might have been better not to use boolean flags at all in delta and only use flags with explicit values, especially seeing as delta is mostly not used directly at the command line. However, I don't think there's a path there that retains backwards compatibility.

Is adding `--no-*` negating versions automatically something that one could hope that Rust's `clap` (and hence `structOpt`) package could do automatically? I don't _think_ it does.

**Comment by dandavison** [comment]
Ref https://github.com/clap-rs/clap/issues/815 ("Add support for automatic negation flags")

**Comment by dandavison** [comment]
The current plan for addressing this is https://github.com/dandavison/delta/pull/340#issuecomment-744257639 (and see  https://github.com/dandavison/delta/issues/446).

**Comment by dandavison** [comment]
@HaleTom is the following a workaround for you?

```gitconfig
[delta]
    features = line-numbers

[delta "no-line-numbers"]
    line-numbers = false
```

Now by default delta will have `line-numbers` and they can be disabled with `delta --features=no-line-numbers`, or `DELTA_FEATURES=no-line-numbers git show` etc. There's similar discussion at https://github.com/dandavison/delta/issues/492#issuecomment-755821580 and https://github.com/dandavison/magit-delta/issues/13#issuecomment-754736108.

**Comment by dandavison** [comment]
In the master branch we can now do `git -c delta.line-numbers=false` (see #493).

So I think that's the most convenient way to do it for the case of using delta with git. It _should_ also be possible to disable it on the delta command line somehow, but perhaps that's less of  a priority since we can do it conveniently in the git case, and we have the features workaround https://github.com/dandavison/delta/issues/307#issuecomment-755823411 otherwise.

**Comment by Atemu** [comment]
@dandavison I'm using your magit plugin and want it to display line numbers when called from command line git but not when called from magit.  
In order to achieve that, `line-numbers` needs to be in the git config and magit needs a `--no-line-numbers` flag to override it.

**Comment by dandavison** [comment]
Hi @Atemu, two thoughts:

1. If you only need a few options set in `magit-delta`, then you could make it be completely independent of your git config using `--no-gitconfig`. This is what I do:
```elisp
  (add-to-list 'magit-delta-delta-args "--no-gitconfig")
  (add-to-list 'magit-delta-delta-args "--light")
```

2. Otherwise, I think it should be possible to do what you want with a delta "[feature](https://dandavison.github.io/delta/features-named-groups-of-settings.html)" for use by magit-delta. This might take a bit of playing around, but I just had a go and the following seems to work:

```gitconfig
[delta]
   features = not-magit-delta

[delta "not-magit-delta"]
   line-numbers = true

[delta "magit-delta"]
    line-numbers = false
```
```elisp
  (setq magit-delta-delta-args (append magit-delta-delta-args '("--features" "magit-delta")))
```

**Comment by dandavison** [comment]
This doesn't help with disabling something set in git config, but in case anyone comes across this issue searching for how to conveniently _enable_ something like line-numbers or side-by-side, then IMO the best way is the `DELTA_FEATURES` environment variable, with its special and very useful `+` prefix (thanks to @bew: https://github.com/dandavison/delta/issues/848#issuecomment-991891453):

on:
```
export DELTA_FEATURES=+line-numbers
```

off:
```
export DELTA_FEATURES=+
```

**Comment by aleksandersumowski** [comment]
The workaround from https://github.com/dandavison/delta/issues/307#issuecomment-755823411 doesn't work for me. Is it expected?

I have .gitconfig with 

```
[delta]
  features = regular-usage decorations
  whitespace-error-style = 22 reverse
  wrap-max-lines=unlimited
  theme = "Nord"
  line-numbers = true

[delta "decorations"]
  commit-decoration-style = bold yellow box ul
  file-style = bold yellow ul
  file-decoration-style = none

[delta "regular-usage"]
  line-numbers = true
  side-by-side = true

[delta "copy"]
  line-numbers = false
  side-by-side = false
```

I do `export DELTA_FEATURES=copy` and yet the output of `git log -p` contains line numbers (but no side-by-side comparison)

![image](https://user-images.githubusercontent.com/6926/204011367-7a48aad6-3423-4915-8e2a-9639a8f76af7.png)
