### ISSUE TITLE
Is it possible to show the file path in the hunk header?

### ISSUE THREAD

**Issue by infokiller** [dandavison/delta#309]
Hi,

Right now, the hunk header only shows the line number. diff-so-fancy also shows the file path, which I like because it gives me better orientation in a large diff (although it can be redundant with the commit/file box).
Is it possible to emulate this in delta?

Thanks!

**Comment by dandavison** [comment]
Hi @infokiller, that's very interesting, I didn't know (or had forgotten; I used d-s-f for many years) that diff-so-fancy did that. I think I might like that also -- as you say, in large multi-file diffs, I do find myself looking at a hunk and then having to scroll up or something to confirm what file it's in.

**Comment by torarnv** [comment]
This would be great to add! 

A related idea is to hyperlink the hunk context. Right now the context line number looks a bit off to me. 

![image](https://user-images.githubusercontent.com/7536/94999943-2739f680-05bd-11eb-9c19-3648d51c84c0.png)

Especially for e.g. removed files:

![image](https://user-images.githubusercontent.com/7536/95000033-a4656b80-05bd-11eb-920f-8afb86eebad6.png)

I know I can disable it with `line-numbers = false`, but that loses out the hunk context link too.

I'm aware that the hunk context isn't at the line number reported, but as the hunk context line number doesn't refer to the first line of the context, but to the first line where there's a change, the line number is "wrongly placed" anyways, and merging it into the hunk context (function) line would simplify things visually.

**Comment by phil-blain** [comment]
This would also make it easier to open the file directly at the given line number for a hunk, with tools that understand the `file:lineno` format (like Vim with the [vim-fetch extension](https://github.com/wsdjeg/vim-fetch)).

**Comment by dandavison** [comment]
This is implemented in master (not yet released). To select the new behavior, you use a special style attribute `file` in `hunk-header-style`. This causes the file path to be included in the hunk header. For example: `hunk-header-style = file syntax`. The style for the file path is determined by `file-style`.

It is possible to omit the main file section and display hunk headers only. Here's an example:

```gitconfig
[delta]
	hunk-header-style = file syntax  # use new attribute
	file-style = red omit  # set the color for the file path, but omit the main file section
	hunk-header-decoration-style = blue box ul
```

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/102689836-44b05100-41f9-11eb-83df-edda995f76d9.png" alt="image" /></td></tr></table>

Feedback and/or testing of master branch welcome.

**Comment by dandavison** [comment]
@torarnv I don't want to lose your idea above (https://github.com/dandavison/delta/issues/309#issuecomment-703152533). Maybe we should open a new ticket for it. Do you use the file/line-number hyperlinks? (Have you set things up so they open in an editor/IDE?)

**Comment by dandavison** [comment]
This is released now (v0.4.5).

**Comment by infokiller** [comment]
Many thanks @dandavison, delta is great and you keep making getting better!

**Comment by Dreomite** [comment]
Is there a way to prefix every hunk with `[filename: scope]` or just `[filename]` when the diff is in the root of the file?
Using
```gitconfig
[delta]
	hunk-header-style = file syntax
	file-style = red omit
	hunk-header-decoration-style = blue box ul
```
from the example shows headers only for hunks that are scoped:

![image](https://user-images.githubusercontent.com/35058624/103060890-9e7a9780-45ba-11eb-9253-f5c96215cf70.png)

**Comment by dandavison** [comment]
@Dreomite good call, absolutely, let's get that fixed.

**Comment by dandavison** [comment]
0.5.0 was just released and contains all the changes discussed in this ticket and related PRs. Copying from the release notes:

-----------

This release introduces a cosmetic change to delta output: the line number (when full `line-numbers` mode is not active) is now displayed in the hunk header line, along with the hunk header code fragment, and optionally a file path. Thanks to @infokiller and @torarnv for suggesting these changes.  For example, it might now look like this, if you use `hunk-header-style = file line-number syntax`:

<table><tr><td><img width=400px src="https://user-images.githubusercontent.com/52205/103388356-8a60f980-4ad6-11eb-862f-b2a62b3bf245.png" alt="image" /></td></tr></table>

Use `hunk-header-style` to configure it:

```
--hunk-header-style <hunk-header-style>
    Style (foreground, background, attributes) for the hunk-header. See STYLES section. Special attributes
    'file' and 'line-number' can be used to include the file path, and number of first hunk line, in the hunk
    header. If included in the hunk header, 'file' and 'line-number' are styled according to 'file-style' and
    'hunk-header-decoration-style' respectively. The style 'omit' can be used to remove the hunk header section
    from the output [default: line-number syntax]
```

If you are displaying the file path in the hunk header, you may want to get rid of the main file line. Use `file-style = <my-file-color> omit` to set the color of the file in the hunk header while deactivating the main file section.
