### ISSUE TITLE
🚀 Control foreground colour?

### ISSUE THREAD

**Issue by Integralist** [dandavison/delta#311]
Hi,

Is there a way to control the foreground color of text. I believe the issue of contrast has been discussed in another issue but it didn't appear to solve the issue for me.

I'm using a dark background terminal theme on macOS (using the kitty terminal):

```
pager = delta --highlight-removed --keep-plus-minus-markers --plus-color="#005913" --plus-emph-color="#2bff00" --minus-color="#db1714" --minus-emph-color="#bab400" --dark
```

So in a case like this it's ok...

![Screenshot 2020-09-02 at 16 31 26](https://user-images.githubusercontent.com/180050/92004340-04a48b80-ed3a-11ea-970e-ef9cf4f9265a.png)

But in this example it doesn't work as the light green and white aren't constrasting enough...

![Screenshot 2020-09-02 at 16 31 49](https://user-images.githubusercontent.com/180050/92004357-0bcb9980-ed3a-11ea-8acc-01a969fd2456.png)

It seems we'll always struggle to find a happy middleground unless the emphasis foreground text can be controlled to align with the emphasis background colour.

Thoughts on how best to address this? Is it even possible to control the foreground colour in these scenarios?

Thanks!

**Comment by dandavison** [comment]
Hi @Integralist. My quick answer (I might be getting something wrong) is that the foreground colors are determined by the color theme that is in effect: i.e. delta has no direct control over the assignment of foreground colors to different syntactic elements of the code; this is done by the syntect library, and the mapping is defined by a sublime color theme. Have you played around with different themes?

There is a subset of sublime color themes that might offer a particular way in. These are the themes like [base16](https://github.com/chriskempson/base16). When I first encountered these I didn't understand what was going on: one needs to know that, while the [256 color palette is hardcoded](https://www.wikiwand.com/en/ANSI_escape_code#/Colors) (and full RGB colors are also obviously fixed at whatever color they say they are), the 16 color palette is dynamic: one's terminal emulator supplies the mapping from 0-15 codes to actual colors.

So, I am wondering whether solutions to what you describe lie in that direction?

Perhaps it is relevant that iTerm2 [allows](https://www.iterm2.com/documentation-escape-codes.html) the 16-color palette to be changed dynamically by an application using proprietary escape sequences. (I don't know whether kitty does; I didn't see it in a quick glance, and I don't know whether linux terminal emulators do.) If you wanted to add a feature to delta that did something crazy with proprietary escape sequences I'd be totally open to it! Delta is all about providing extreme customizability to a community of programmers, and it's at least intended to be a fun project as well as providing an enhanced environment for serious work.

**Comment by Integralist** [comment]
Thanks for the feedback. I'll have a play around to see what I can find out 👍
