### ISSUE TITLE
🚀 How to ignore changes where lines are all blank [help]

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/delta#313]
Using `git diff --ignore-blank-lines` help me to ignore changes for new lines. Is it possible to achieve this in `delta`?

```
-B, --ignore-blank-lines
       ignore changes where lines are all blank
```

**Comment by dandavison** [comment]
Hi @avatar-lavventura, can you post an example showing the output that you get from `git diff --ignore-blank-lines` when git is configured to use delta, and the output you get when not using delta, and describe how you want delta to behave differently?

Note that, as long as you have `core.pager = delta` in your gitconfig, then delta just receives as input whatever output git produces. So you can use any git options you want.

**Comment by dandavison** [comment]
It seems to me that this works as expected:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/92033394-9b247d00-ed39-11ea-90a6-75f789302ef1.png" alt="image" /></td></tr></table>

**Comment by avatar-lavventura** [comment]
Thanks @dandavison `git diff --ignore-blank-lines` handled by `delta` as well and works on my end too.
