### ISSUE TITLE
Is it possible to not use hunk header and see absolute (true) not relative line numbers?

### ISSUE THREAD

**Issue by nortliteborealis** [dandavison/delta#319]
When I disable hunk header (**_set hunk-header-style = omit_**) the line numbers are calculated as relative numbers, but i want to see absolute numers in diff. I realy want see absolute line numbers without hunk header, please tell me how to set it up, if of course it's possible.
Thank you in advance))

With hunk headers
![with hunk headers](https://user-images.githubusercontent.com/44495093/92603170-aaff0c80-f2b7-11ea-8ce0-35bafb2926ac.png)
Without hunk headers
![without hunk headers](https://user-images.githubusercontent.com/44495093/92603500-0df0a380-f2b8-11ea-91f9-573c540aead0.png)

My git config

```
[interactive]
    diffFilter = delta --color-only

[diff]
    colorMoved = default

[delta]
    side-by-side = true
    features = line-numbers decorations
    whitespace-error-style = 22 reverse
    hunk-header-style = omit
    syntax-theme = base16

[delta "line-numbers"]
    line-numbers = true
    line-numbers-minus-style = red
    line-numbers-zero-style = "#444444"
    line-numbers-plus-style = green
    line-numbers-left-format = "{nm:^4}┊"
    line-numbers-right-format = "{np:^4}│"
    line-numbers-left-style = red
    line-numbers-right-style = green

[delta "decorations"]
    commit-decoration-style = bold yellow box ul
    file-style = bold yellow ul
    file-decoration-style = none
    hunk-header-decoration-style = yellow box
```

**Comment by dandavison** [comment]
Hi @nortliteborealis! You're right, this is a bug with `hunk-header-style=omit`. It's actually the same as reported in #293 and #274 (but the issue titles make it hard to search for.) It's the top priority bug to fix next.

**Comment by nortliteborealis** [comment]
Thank you very much for your reply and I apologize for duplicating the issue. I will wait for a solution of this problem. Delta is a super tool!

**Comment by dandavison** [comment]
Hi @nortliteborealis, 

@ryuta69's work is fixing this issue (not released yet).

> I really want see absolute line numbers without hunk header,

Can you tell me more about how you use delta without hunk headers. If there's a file with multiple hunks, how do you tell when one hunk ends and the next starts?

Would you like there to be a blank line separating the hunks? Or do you want the next hunk to literally follow straight on, as if there was no break in the underlying code?

**Comment by nortliteborealis** [comment]
Hi @dandavison 

Without using hunk headers, I would like to see modified hunks with an empty line separator in a different color, perhaps with some special character, such as "@@ ... @@" or just "..." or something else. I think that the presence of such symbols will give an intuitive understanding that these are different hunks.

Thank you!

**Comment by nortliteborealis** [comment]
I think that I can close this issue, because in version 0.4.5 it is no longer there.

Thanks for the work you've done!

**Comment by dandavison** [comment]
Right, thanks @nortliteborealis. This should be fixed now due to @ryuta69's work.
