### ISSUE TITLE
Second document label is missing last character (truncated)

### ISSUE THREAD

**Issue by AndydeCleyre** [dandavison/delta#324]
```console
$ printf '%s\n' 1 2 3 4 >a.txt
$ printf '%s\n' 1 TWO 3 FOUR >b.txt
$ diff -u a.txt b.txt
```
```diff
--- a.txt	2020-09-17 13:57:56.160725335 -0400
+++ b.txt	2020-09-17 13:58:11.573565683 -0400
@@ -1,4 +1,4 @@
 1
-2
+TWO
 3
-4
+FOUR
```
```console
$ diff -u a.txt b.txt | delta
```
![image](https://user-images.githubusercontent.com/1787385/93510241-deace880-f8ee-11ea-8266-833d437d2f47.png)
```console
$ diff -u -L FIRST a.txt -L SECOND b.txt
```
```diff
--- FIRST
+++ SECOND
@@ -1,4 +1,4 @@
 1
-2
+TWO
 3
-4
+FOUR
```
```console
$ diff -u -L FIRST a.txt -L SECOND b.txt | delta
```
![image](https://user-images.githubusercontent.com/1787385/93510449-32b7cd00-f8ef-11ea-80da-259e78b64291.png)
```console
$ delta --version
delta 0.4.3
$ diff --version | head -1
diff (GNU diffutils) 3.7
```

**Comment by dandavison** [comment]
Hi @AndydeCleyre, thanks for this. I can't reproduce it however. I don't have a good theory yet for what might be causing it at your end  though! Could you try with `delta --no-gitconfig` to double-check it's not something in your git/delta config? Could you also pipe the output of delta into `cat -A` so that we can see that there really is a missing character as opposed to e.g. something odd going on at the level of ANSI sequences influencing terminal emulator display.


```
~ cat src/delta/diff1 
--- a.txt   2020-09-17 13:57:56.160725335 -0400
+++ b.txt   2020-09-17 13:58:11.573565683 -0400
@@ -1,4 +1,4 @@
 1
-2
+TWO
 3
-4
+FOUR
~ delta --no-gitconfig < src/delta/diff1

comparing: a.txt ⟶   b.txt
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

1
1
2
TWO
3
4
FOUR
~ delta --no-gitconfig < src/delta/diff1 | cat -A
␊
␛[38;5;4mcomparing:•a.txt•\u{27f6}•••b.txt␛[0m␊
␛[38;5;4m\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}␛[0m␊
␊
␛[38;5;4m1␛[0m␊
␛[38;2;248;248;242m1␛[0m␊
␛[48;2;63;0;1m2␛[0m␛[48;2;63;0;1m␛[0K␛[0m␊
␛[48;2;0;40;0;38;2;248;248;242mTWO␛[0m␛[48;2;0;40;0m␛[0K␛[0m␊
␛[38;2;248;248;242m3␛[0m␊
␛[48;2;63;0;1m4␛[0m␛[48;2;63;0;1m␛[0K␛[0m␊
␛[48;2;0;40;0;38;2;248;248;242mFOUR␛[0m␛[48;2;0;40;0m␛[0K␛[0m␊
~ delta --version
delta 0.4.3
```

**Comment by AndydeCleyre** [comment]
Thanks so much for taking a good look at this so quickly!

Same results with `--no-gitconfig`, and in my usual zsh env, a `zsh -f` session, and bash.

You're right, the text *is* there:

```
␊
␛[38;5;4mcomparing:•a.txt•\u{27f6}•••b.txt␛[0m␊
␛[38;5;4m\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}␛[0m␊
␊
␛[38;5;4m1␛[0m␊
␛[38;5;7m1␛[0m␊
␛[48;2;63;0;1m2␛[0m␛[48;2;63;0;1m␛[0K␛[0m␊
␛[48;2;0;40;0;38;5;7mTWO␛[0m␛[48;2;0;40;0m␛[0K␛[0m␊
␛[38;5;7m3␛[0m␊
␛[48;2;63;0;1m4␛[0m␛[48;2;63;0;1m␛[0K␛[0m␊
␛[48;2;0;40;0;38;5;7mFOUR␛[0m␛[48;2;0;40;0m␛[0K␛[0m␊
```

So I'm having this issue with konsole, but *not* with alacritty.

**Comment by dandavison** [comment]
Hm, OK, glad we're getting somewhere! So, I guess the obvious next step would be to try to isolate a minimal `printf` example of some text with ANSI escapes that is behaving badly in your konsole (Is your version reasonably recent?). I'm a bit surprised; I think delta is using ANSI escapes standardly there and so I wouldn't expect konsole to have any problems (and I'm sure there are plenty of delta konsole users).

**Comment by AndydeCleyre** [comment]
It's konsole 20.08.1, and I'm now reproducing with a default profile there. If I use zsh's `print -b` it looks alright, except for the horizontal line (here `c` and `p` are copy and paste):

![image](https://user-images.githubusercontent.com/1787385/93522259-305d6f00-f8ff-11ea-9282-fd4747e9ec93.png)

I'm not sure how to properly feed these escape codes to `printf`:

![image](https://user-images.githubusercontent.com/1787385/93523031-66e7b980-f900-11ea-88bd-235f5002b219.png)

Now also reproduced with konsole `20.08.0`, `20.07.90`, and `20.07.80`, but *not* with `20.04.3`.

Sorry for the noise here as this seems really unrelated to your project. Feel free to close this; I'll check for or open a new konsole issue, and maybe do a git bisect to track this down, and just post a relevant link here for others to find.

Thanks again!

**Comment by dandavison** [comment]
OK good luck investigating. If you get a chance to post any conclusions or further links here then please do; that could be useful to other konsole & delta users.

**Comment by AndydeCleyre** [comment]
Continued discussion: https://bugs.kde.org/show_bug.cgi?id=426655

**Comment by dandavison** [comment]
Does this reproduce the problem without involving delta?

```
printf "\x1b[38;5;4mcomparing: a.txt ⟶  b.txt\x1b[0m\n"
```

(What about without the unicode arrow character?)

**Comment by AndydeCleyre** [comment]
Just as you suggest: reproduced with the arrow, not reproduced without it. I guess it's konsole's character width calculations. Thanks!
