### ISSUE TITLE
Somehow I have to `git diff | delta` to make it work

### ISSUE THREAD

**Issue by zachliu** [dandavison/delta#337]
I installed `delta` and set up everything in my `.gitconfig` but it didn't work out of the box. I have to pipe `git diff` into `delta` manually. Here is some relevant info:
```
delta 0.4.3
git version 2.25.1
less 551 (POSIX regular expressions)
```
and my `.gitconfig`:
```
[user]
  name = zachliu

[core]
  editor = nvim
  autocrlf = input
  safecrlf = true
  pager = delta

[alias]
  hist = log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short
  type = cat-file -t
  dump = cat-file -p

[pull]
  rebase = true

[delta]
  plus-style =  syntax "#214f11" # set background color
  syntax-theme = Monokai Extended
  dark = true
  side-by-side = true

[interactive]
  diffFilter = delta --color-only
```

**Comment by dandavison** [comment]
Hi @zachliu, hm, maybe git isn't finding your delta executable? Try typing `which delta` at the command line and then using that absolute path as the value for `core.pager`. To double check what git is finding in the config, you can do

```
git config --get core.pager
```

**Comment by zachliu** [comment]
Tried. Now i have 
```
$ which delta
/usr/bin/delta
```
and
```
$ git config --get core.pager
/usr/bin/delta
```
but `git diff` still doesn't use delta :crying_cat_face:

**Comment by dandavison** [comment]
OK, let's get to the bottom of this! What about if you do

```gitconfig
[core]
	pager = bash -c 'echo Hello, world!'
```

That should result in

```
$ git show
Hello, world!
```

If that works as expected, what about if you do

```gitconfig
[core]
	pager = delta > /tmp/delta.out 2> /tmp/delta.err
```

Does that create the files? Is there an error?

**Comment by zachliu** [comment]
found the problem! something is setting the env var `GIT_PAGER=less` somewhere
the damn thing is i can't seem to find the `something` and the `somewhere` :facepalm:

**Comment by dandavison** [comment]
OK, great! Hm, good luck finding that. Not an oh-my-zsh plugin or something like that?

**Comment by zachliu** [comment]
It turns out `tmux` is persisting my already-commented-out `export GIT_PAGER=less` in `.zshrc`
all i needed to do was to restart `tmux`
`¯\_(ツ)_/¯`
