### ISSUE TITLE
🐛 Delta is doing something weird to git tag.

### ISSUE THREAD

**Issue by CamJN** [dandavison/delta#348]
Running `git --no-pager tag`: gives a list of tags.

Running `git tag`: prompts`Pattern not found  (press RETURN)` after which I hit enter, then the list of tags shows.

My `.gitconfig`:
```
[core]
	pager = delta --dark
[interactive]
	diffFilter = delta --color-only
[delta]
	features = side-by-side line-numbers decorations navigate
	hyperlinks = false
	whitespace-error-style = 22 reverse
[delta "decorations"]
	commit-decoration-style = bold yellow box ul
	file-style = bold yellow ul
	file-decoration-style = none
```

**Comment by dandavison** [comment]
Hi @CamJN, this is due to `navigate`. It's best to only use this when needed: see the explanation in the README: https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs

**Comment by CamJN** [comment]
Huh, thanks.
