### ISSUE TITLE
🐛  Hyperlinks not rendered correctly

### ISSUE THREAD

**Issue by paulirish** [dandavison/delta#362]
Great project! Love it.

So.. the hyperlink test file (mentioned in the gist) works correctly:

```sh
curl -L  https://git.gnome.org/browse/vte/plain/perf/hyperlink-demo.txt
```

![image](https://user-images.githubusercontent.com/39191/96805362-55457600-13c6-11eb-82d1-ca3e06c28a83.png)

However with `hyperlinks = true` in my config.. The rendering of hyperlinks seems bugged.

![image](https://user-images.githubusercontent.com/39191/96805295-262f0480-13c6-11eb-9163-8b392143c882.png)

any ideas?

i'm in Iterm2 Build 3.4.0beta11

**Comment by dandavison** [comment]
Hi @paulirish, thanks! And thanks for diff-so-fancy, which I was a user of for many years up until I started this project.

Does this do it? Pass the `-r` flag to less (as opposed to `-R`), e.g. via

```
export DELTA_PAGER='less -rX'
```

(if you're on an older version of delta than the current 0.4.4 you can use the `BAT_PAGER` env var)

I'll add this to the README (ref #332).

**Comment by dandavison** [comment]
As mentioned above, I think that this will be solved by passing `-r ` (as opposed to `-R`) to less. I believe that the next version of less [will support](https://github.com/gwsw/less/issues/54) hyperlinks with the `-R` flag. I'll close this for now but do let me know if it's not working with `-r`.
