### ISSUE TITLE
🐛 Background colors: Granularity too coarse under tmux

### ISSUE THREAD

**Issue by Pistos** [dandavison/delta#365]
I am able to change background colours, but the full spectrum of RRGGBB colours doesn't seem to be available.

Given the following config:

```
[core]
  pager = delta

[delta]
  file-decoration-style = none
  file-style = yellow bold
  hunk-header-decoration-style = "#555555" box
  line-numbers = true
  line-numbers-left-style = "#555555"
  line-numbers-right-style = "#555555"
  minus-style = syntax "#700000"
  plus-style = syntax "#003200"
  plus-emph-style = syntax "#003300"
  plus-non-emph-style = syntax "#003200"
  syntax-theme = Solarized (dark)

[interactive]
  diffFilter = delta --color-only
```

You can see that `plus-style` and `plus-emph-style` only differ by 1 in the GG value.  So, they should be extremely similar colours.  However, the `delta --show-config` looks like this:

![Screenshot_20201023_110359](https://user-images.githubusercontent.com/2885/97027383-41ae2280-1520-11eb-9ca7-256f9896696c.png)

As you can see in the output, `plus-style` and `plus-emph-style` are showing up with extremely different colours.

```
    plus-style                    = syntax 235
    plus-non-emph-style           = syntax 235
    plus-emph-style               = syntax 22
```

My `$TERM` is `screen-256color`.  I am using zsh.  I am using tmux.  I have added `set -ga terminal-overrides ",screen-256color:Tc"` to my `~/.tmux.conf`.  I have restarted tmux.  I can see the full, smooth gradient of colours with a basic colour test:

![Screenshot_20201023_110259](https://user-images.githubusercontent.com/2885/97027620-9a7dbb00-1520-11eb-9a3d-076b41078ce7.png)

**Outside of tmux** (plain iTerm2 tab/window), I can see the expected colours in delta.  (With no change to `$TERM`.)  Also, the `--show-config` output prints the full RRGGBB hex values:

```
    plus-style                    = syntax "#003200"
    plus-non-emph-style           = syntax "#003200"
    plus-emph-style               = syntax "#003300"
    plus-empty-line-marker-style  = normal "#002800"
```

delta version 0.4.4, on OSX, installed via brew.

**Comment by Pistos** [comment]
Strangely, it seems to work if I start tmux from within an iTerm2 tab, as opposed to SSH.  Then all subsequently created tmux sessions and windows make delta work correctly.

**Comment by ericsong** [comment]
For anyone stumbling across the same problem years later like myself, what fixed it for me was this [comment](https://github.com/dandavison/delta/issues/567) - setting `COLORTERM` to `truecolor`.

`$COLORTERM` was set in my local config but not in my ssh environment.
