### ISSUE TITLE
Issues with --compare-themes on Windows

### ISSUE THREAD

**Issue by lzybkr** [dandavison/delta#37]
Using the default style (underline files, box chunks, plain commit), I see ^M in chunks and files and no syntax coloring:

![image](https://user-images.githubusercontent.com/2148248/67060693-bdf27680-f112-11e9-9804-34b24ee7fb92.png)

**Comment by dandavison** [comment]
Regarding the lack of syntax highlighting, does that file have a `.rs` extension? Currently, if delta does not recognize the file extension in the diff output, then it does not apply background colors and lets the original `git diff` content through (however, see https://github.com/dandavison/delta/pull/36). So that would explain it if the file doesn't have a recognized extension (`--list-languages`). If that's not it, would it be possible to post a sufficient fragment of text (e.g. `git show`) or a publicly available commit so that I can reproduce locally?

I'll look into the `^M`.

**Comment by lzybkr** [comment]
Yes, the file does have an `.rs` extension.

I thought `--color=always` (suggested by the --compare-themes help) might have made a difference, but it didn't seem to. I saw the same output on Windows or Linux. Is `--color=always` necessary?

**Comment by dandavison** [comment]
The reason I have `git show --color=always` in the `--compare-themes` help text is that it results in the user seeing git's coloring for the parts of the diff output that delta does not take responsibility for coloring. E.g. note the coloring of the commit hash line below. In general, if delta doesn't have an opinion about the color of an element, my intention is that whatever color the user has configured in their gitconfig will be honored (or fallback to git default).

------------------------------------------------------------------------------------------
Without `--color=always`:

![image](https://user-images.githubusercontent.com/52205/67127668-aec10680-f1ae-11e9-8a59-ae7fc9d00bba.png)

------------------------------------------------------------------------------------------
With `--color=always`:

![image](https://user-images.githubusercontent.com/52205/67127836-fb0c4680-f1ae-11e9-808c-5df8dda14984.png)

**Comment by dandavison** [comment]
Is it possible that what's going on here is

1. git is outputting text with `^M` in the line endings.
2. When delta [attempts to parse](https://github.com/dandavison/delta/blob/master/src/parse.rs#L68) the file extension, to set the language, it is failing to handle the line ending, and this is causing it to fail to recognize the language.

I haven't tried to investigate that idea yet. If it's easy to do so, would you be able to post some raw git output or a public commit that exhibits the `^M` problem?

**Comment by dandavison** [comment]
@lzybkr is this still current? (And is it related to #40?) Let me know if I can help.

**Comment by lzybkr** [comment]
I'll close this as I can no longer repro. It's unclear if this was related to #40.
