### ISSUE TITLE
🐛 Windows download link broken in README

### ISSUE THREAD

**Issue by SuperCuber** [dandavison/delta#370]
Currently points at https://github.com/dandavison/delta/releases/download/0.4.4/delta-0.4.4-x86_64-pc-windows-gnu.zip
Should probably point at https://github.com/dandavison/delta/releases/download/0.4.4/delta-0.4.4-x86_64-pc-windows-msvc.zip I guess

**Comment by dandavison** [comment]
Thanks @SuperCuber! Fixed (and I'll start using [markdown-link-check](https://github.com/tcort/markdown-link-check)) now.
