### ISSUE TITLE
🐛 Latest Release doesn't work after libgit2 1.1.0 update

### ISSUE THREAD

**Issue by LovecraftianHorror** [dandavison/delta#373]
I was a bit hesitant opening this since master works fine, but I figured it would be good to open it anyways before someone else with less information does. I'm on the latest release (`0.4.4`) and after updating to `libgit2 1.1.0` I'm now getting 

```text
delta: error while loading shared libraries: libgit2.so.1.0: cannot open shared object file: No such file or directory
```

This is because `libgit2.so.1.0` doesn't exist since it's now `libgit2.so.1.1`. The version of `git2` is already bumped on master which is why this works just fine (650d826102e43ef91a5293b18e8515e85a37353d), but a new release hasn't been cut yet, so I figured I would open an issue to let you know and hopefully guide anyone else who gets this error message here first.

**Comment by Kr1ss-XD** [comment]
The release version works fine, it just needs to be rebuilt against the updated libgit2.

**Comment by dandavison** [comment]
@LovecraftianHorror thanks for this, what's your operating system and how are you installing delta? 

> after updating to libgit2 1.1.0

What does this mean exactly? How are you updating this library?

**Comment by Kr1ss-XD** [comment]
The comment is about the AUR package @dandavison (see https://aur.archlinux.org/packages/git-delta/#comment-773304).

Arch has recently updated the `libgit2` package in their official repository, which the (non-binary) AUR package depends on. If `git-delta` has been built before this update, it needs to be rebuild against the new version of that library.

**Comment by dandavison** [comment]
OK, thanks @Kr1ss-XD.

> it needs to be rebuild against the new version of that library.

Perhaps it would help to post a command or link to docs so that people who encounter this know exactly how to resolve it?
