### ISSUE TITLE
🚀 Add a test that enforces clippy and rustfmt compliance

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#384]
Once the codebase is clippy-compliant, let's add a test that ensures it stays that way. (And the same for rustfmt).  cc @MarcoIeni ref #380 #383

**Comment by MarcoIeni** [comment]
I know how to do it by using github actions. See [this](https://github.com/rust-github/template/blob/master/.github/workflows/ci.yml).
I don't know if you have plans to use them.

**Comment by dandavison** [comment]
I'm happy to switch to GitHub actions if that makes sense. But I'm thinking that's pretty much orthogonal to this issue since we can add shell commands here https://github.com/dandavison/delta/blob/b14942527ac7f839f16523f7fe390fe922c20553/etc/ci/script.sh#L10-L15

**Comment by MarcoIeni** [comment]
> I'm happy to switch to GitHub actions if that makes sense.

I don't know, that's just what I happen to use for my open source projects, but yes, it's a separate issue.

Anyway, the commands should be the following:
```
cargo fmt --all -- --check
cargo clippy -- -D warnings
```

**Comment by dandavison** [comment]
Update: we've got a check for rustfmt, and a check for clippy commented out; the only remaining thing here is getting the codebase to pass clippy.

**Comment by dandavison** [comment]
Fixed at #422
