### ISSUE TITLE
🚀 Support for filetype-specific configuration

### ISSUE THREAD

**Issue by kyounger** [dandavison/delta#389]
Hi, thanks for contributing to Delta, please go ahead and describe your proposal!

(edit: not sure how I sent the default content as a comment, please ignore)

**Comment by kyounger** [comment]
This is amazing. My only request would be to be able to adjust the config on a per-filetype basis. I have no need for hunk-headers in yaml, for example.

https://github.com/dandavison/delta/issues/364#issuecomment-718897701

**Comment by kyounger** [comment]
Ah, spent a bit more time diving into this. It works already, I never realized hunk-headers were a `git`-level concept.

For those curious, you need to read this: https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more

What worked for me (for yaml) was:

`.gitattributes`:
```
*.yaml   diff=yaml
```

`.gitconfig`:
```
[core]
  attributesfile = /some/path/to/.gitattributes

[diff "yaml"]
  xfuncname = ""
```

**Comment by dandavison** [comment]
Thanks @kyounger, I'm sure those instructions are going to be useful -- this has come up a few times before.
