### ISSUE TITLE
🚀 Switch from Travis to GitHub actions

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#396]
Travis has been very useful to delta, but they recently changed their policies with the result that delta builds are not currently happening. I'm still waiting for them to tell me whether they'd like delta to switch to a paid plan or whether they're offering to support it as an Open Source project, but, it's probably time to switch to GitHub actions.

Since delta originally copied its Travis-based CI scripts from bat, it may help to consult the bat sources, since bat has since switched to GitHub actions: https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml

cc @MarcoIeni

**Comment by MarcoIeni** [comment]
I will try to work on this :)

**Comment by dandavison** [comment]
> I will try to work on this :)

That would be fantastic! Thanks @MarcoIeni!

**Comment by MarcoIeni** [comment]
> delta builds are not currently happening

Maybe it's because we have to update the path in https://github.com/dandavison/delta/blob/master/.travis.yml by the way 😅

**Comment by dandavison** [comment]
Oh, thanks! Fixed that symlink (4f167f4c7aff1d06d587e43187519f0590c5e49e). But, I don't think that's it -- last build ran on 5th Nov whereas the bat dir rename was on 14 Nov (e527a69e5e61b16bd4198fc6afc8b64b09d0f59b). I believe the issue is that Travis has changed their business model.

![image](https://user-images.githubusercontent.com/52205/100519384-82273e80-3165-11eb-9d66-994288e312f9.png)

I have no criticism at all of them wanting to make some money; their support of open source projects was very generous. But Delta had been relying on their free support for open source projects, and I had been wanting to switch to Github Actions in any case.

**Comment by dandavison** [comment]
Do you think we should close this now @MarcoIeni?
