### ISSUE TITLE
🚀 Calculate code coverage

### ISSUE THREAD

**Issue by MarcoIeni** [dandavison/delta#401]
We could calculate code coverage percentage on every push and display it with a badge in the README.
For code coverage calculation I use https://github.com/actions-rs/tarpaulin
This creates an lcov.info file that I upload to https://coveralls.io/ (free for open source).

Setup example: https://github.com/rust-github/rust-gh-example

https://github.com/rust-github/rust-gh-example/blob/74be2688c366c78791fa52e5674bf317cdf45cbb/.github/workflows/ci.yml#L60

I solve this issue if you want.
Of course the maintainer has to register to the coveralls website.

**Comment by dandavison** [comment]
Sure! I've heard of coveralls but not used it. I've signed up and registered delta:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/99919976-a8288b00-2cee-11eb-9b48-9b8625b752d2.png" alt="image" /></td></tr></table>

**Comment by MarcoIeni** [comment]
Closed by #409
