### ISSUE TITLE
🐛 How to configure the background/frontground color for addition in delta

### ISSUE THREAD

**Issue by simokhwang** [dandavison/delta#407]
I am using delta on iTerm 2 on MacOSx.
How to configure the background/frontground color for addition in delta?
Currently, it is grey on dark green, which is not very visible.

I tried using this in .gitconfig, but it does not change the color:

```
[delta]
    plus-color = "#00592c"
    minus-color = "#340001"

```
![image](https://user-images.githubusercontent.com/73351449/100191038-4c076780-2ea4-11eb-9080-56f44a323176.png)

**Comment by Kr1ss-XD** [comment]
Hi @simokhwang - these options are deprecated, but you might use for example

```gitconfig
[delta]
	plus-style  = normal my_background_color
	minus-style = normal my_background_color
```

or

```gitconfig
[delta]
	syntax-theme = <your_syntax_theme>
	zero-style   = syntax
	plus-style   = syntax <your_background_color>
	minus-style  = syntax <your_background_color>
```

to change the background color while at the same time using syntax highlighting.

There are many many more options for colors and styles, I suggest you take a look at the [README](https://github.com/dandavison/delta#choosing-colors-styles) or `delta --help` (esp. the STYLES and COLORS sections).

**Comment by dandavison** [comment]
I hope you got this working @simokhwang? I'll close it, but please do reply/reopen if you're having any more trouble.
