### ISSUE TITLE
🐛  Wrong colors in tmux

### ISSUE THREAD

**Issue by danielfalbo** [dandavison/delta#410]
When I run `git diff` I get different colors inside and outside tmux.

##### Outside tmux:
![Screenshot 2020-11-28 at 06 19 31](https://user-images.githubusercontent.com/39460524/100494446-11225f80-3142-11eb-8db8-fba8d56e012e.png)

##### In tmux:
![Screenshot 2020-11-28 at 06 19 40](https://user-images.githubusercontent.com/39460524/100494449-167faa00-3142-11eb-8d05-9a808823b865.png)

What do I have to change to get the correct colors in tmux?

`git --no-pager diff` gives me the same colors inside and outside tmux

![Screenshot 2020-11-28 at 06 22 58](https://user-images.githubusercontent.com/39460524/100494469-429b2b00-3142-11eb-96ea-0b55b4ed4ca8.png)
![Screenshot 2020-11-28 at 06 21 14](https://user-images.githubusercontent.com/39460524/100494472-43cc5800-3142-11eb-8019-8a880f019d0f.png)

I'm having [the same issue with `bat`](https://github.com/sharkdp/bat/issues/1408)

I recently enabled italics in tmux by doing [this](https://github.com/tmux/tmux/issues/377#issuecomment-212541169), anyway commenting `set -g default-terminal "tmux-256color"` out of my `.tmux.conf` does not solve the problem, I don't think that is the problem.

**Comment by dandavison** [comment]
Hi @danielfalbo, just quickly -- can you try the instructions here? https://github.com/dandavison/delta#24-bit-color-truecolor

**Comment by danielfalbo** [comment]
Thank you much! It's beautiful: solves this problem with the colors without messing up italics : )

**Comment by dandavison** [comment]
Excellent!

**Comment by stelcodes** [comment]
Previously posted link with the fix is dead, here's the new one: https://dandavison.github.io/delta/tips-and-tricks/using-delta-with-tmux.html
