### ISSUE TITLE
🐛  Delta as unified diff not working 

### ISSUE THREAD

**Issue by gennaro-tedesco** [dandavison/delta#444]
As per documentation we have:

> Delta also handles unified diff output, and can be used as an alternative way of invoking diff -u

however, by doing so, all I get is an error `Pattern not found  (press RETURN)`. I assume this feature is independent of `delta` git's integration, therefore to reproduce:
```
echo "file1" > file1
echo "file2" > file2

delta file1 file2
---
Pattern not found  (press RETURN)
```
or do I have to configure anything to have it work as diff tool independently?

**Comment by gennaro-tedesco** [comment]
By investigating I have found out that the above is generated if having
```
[delta]
    navigate = true
```
in the configuration. I then came across these lines in the docs

>>> The reason that navigate should not be used all the time is that Delta uses less as its pager, and the navigate feature works by doing less --pattern <regex-matching-file-and-commit-lines>. When the git output does not contain file/commit diff lines, less --pattern behaves unhelpfully

which are shedding some light on it. So is passing `DELTA_NAVIGATE=1` as env variable the only way to work around this issue?

**Comment by Kr1ss-XD** [comment]
You can instead use the `--navigate` flag, @gennaro-tedesco.

For convenience, you might want to include something similar to

```sh
alias deltanav='DELTA_NAVIGATE=true delta'
```

or

```sh
alias deltanav='delta --navigate'
```

in your shell startup file.

Anyways, I wouldn't recommend to set the navigate flag globally, for reasons you already found in the documentation.

**Comment by gennaro-tedesco** [comment]
You are right, I believe this issue can then be closed.

**Comment by Kr1ss-XD** [comment]
You can close it yourself if you think it's resolved :wink:
