### ISSUE TITLE
delta shall have non-zero status code if there were any matches found

### ISSUE THREAD

**Issue by salmankhilji** [dandavison/delta#448]
I want to integrate `delta` into my workflow, but I need to have it exit with a different status code depending on whether there were any differences found or not.  Currently, `delta` always exits with a status code of 0 regardless of whether the input files are the same.

> Yes, I can use another tool before I feed the input to `delta` but doing so requires that I create temp files, something I would like to avoid.

To be consistent with other unix tools, please consider having `delta` exit with a status code of:

- `0` if the input files are the same. i.e., no output was produced.
- Non-zero, if the input files were different.

This is how `diff` and `cmp` work.

I tried to work around this limitation by doing something like this in Bash:

```
./delta -s script.sh script.sh | tee >(grep .)
```

But for some reason, piping like this changes the output produced from `delta` altogether.  Being so new to Bash scripting, I am not even sure of the validity of my approach above.

**Comment by dandavison** [comment]
Hi @salmankhilji thank you. That's a bit embarrassing, you are absolutely right, of course! `delta file1 file2` should exit with status 1 if they differ and 0 if they are the same.

**Comment by dandavison** [comment]
This is fixed in master (not released yet). I'd be happy to look at the scripts in which you're using delta if you'd like. Thanks for opening the ticket!

**Comment by salmankhilji** [comment]
Thanks so much!  I use `delta` in the following utility function:

```
write-file() (
  local -r dst="$1"; shift || return
  local -r src="$1"; shift || return

  if [[ -f "${dst}" ]]; then
    local -r tmp="$(mktemp)" && trap "rm -f '${tmp}'" EXIT || return
    cp "${src}" "${tmp}"
    if delta -sw "$(tput cols)" "${dst}" "${tmp}" | tee /dev/tty | [[ "$(wc -l)" -eq 0 ]]; then
      echo -e "\e[36m=\e[0m Already up to date: \e[36m${dst}\e[0m"
    else
      echo -e "\n\e[33m≠\e[0m File contents changed: \e[33m${dst}\e[0m\n"
      cp -i "${tmp}" "${dst}"
    fi
  else
    cp "${src}" "${dst}" && echo -e "\e[94m✓\e[0m Successfully wrote: \e[94m${dst}\e[0m"
  fi
)
```

Since this isn't meant to be a general purpose function, error checking is minimal.

Its purpose is to write a text file given its path as the first argument and contents that reside within a file as the second argument, which is almost always a heredoc.  If the file exists and its contents has changed, then it automatically shows a side-by-side diff using `delta` prompting the user to confirm whether the file shall be overwritten.  Else the file is created.  The mostly common use-case is to invoke it as follows:

```
write-file .vscode/settings.json <(cat <<'EOF'
{
  "files.exclude": {
    "packages/package-a": true,
    "packages/package-b": true,
    "packages/package-c": true
  }
}
EOF
)
```

As you can see, I currently use a workaround to count the number of lines returned and fail the pipe if that is so.  The next version of `delta` won't need this workaround anymore.

(In the past, this routine used the `cmp` utility to do a comparison before it showed the side-by-side diff using `icdiff`.)
