### ISSUE TITLE
Is there some way to change the background colors according to the terminal?

### ISSUE THREAD

**Issue by lourenci** [dandavison/delta#452]
Thank you for the app. It has improved my git workflow a lot.

I'm struggling to set up the background color.

Is there some way to adapt the background color according to the terminal's background? I don't care about the theme, I just want `--light` whenever my terminal is light and `--dark` whenever my terminal is dark.

Thank you again.

**Comment by dandavison** [comment]
Hi @lourenci, thanks for this, coincidentally the same request was made in a ticket just a couple of days ago: #447. So, let's discuss together in there.
