### ISSUE TITLE
color configuration doesnt get applied via fzf preview

### ISSUE THREAD

**Issue by joe23rep** [dandavison/delta#456]
somehow delta does seem to override the config ive added in my .gitconfig file. heres the configuration:

```
[delta]

features = side-by-side line-numbers decorations

whitespace-error-style = 22 reverse

plus-color = "#45f3d3"

minus-color = "#b6aef4"

syntax-theme = Necro
```

normal color settings fo git in .gitconfig are:

```
[color "diff"]

meta = #00eeff

frag = #790bf8

old = #8bf6ff

new = #ff00f4
```

but in the fzf preview function it doesnt get applied- its still green/ red. the bat theme gets applied- although i dont know if threw delta or threw the fzf config in my .zshrc file. i also double checked the bat theme- theres no red and green at all so it cant come from there.

**Comment by dandavison** [comment]
Hi @joe23rep, can you give me instructions for how to reproduce this? How do I run delta in fzf preview?

**Comment by joe23rep** [comment]
im sorry- i was too stupid. just fundled around with it for half an hour and now im coming closer to my goal. i thought i needed to change plus-color and minus-color but i needed to change plus-style and minus-style.

one question tho. is it possible to not have a bold background in that color but rather the text itself? like changing the highlight sytle from background to foreground?

i run it with fzf preview via this little command in my init.vim:

```
let g:fzf_preview_disable_mru = 0
let g:fzf_preview_command = 'bat --color=always --plain {-1}'
let g:fzf_preview_default_fzf_options = { '--reverse': v:true, '--preview-window': 'wrap:70%' }
let g:fzf_preview_git_status_preview_command =
	\ "[[ $(git diff --cached -- {-1}) != \"\" ]] && git diff --cached  -- {-1} | delta || " .
	\ "[[ $(git diff -- {-1}) != \"\" ]] && git diff  -- {-1} | delta || " .
	\ g:fzf_preview_command

```

**Comment by dandavison** [comment]
> one question tho. is it possible to not have a bold background in that color but rather the text itself? like changing the highlight sytle from background to foreground?

@joe23rep have you read through the [README](https://github.com/dandavison/delta) and the `delta --help` output? There are a lot of options for configuring foreground and background colors! Do you want something like `delta --diff-so-fancy` perhaps? That's on the right in the image below.  But you don't have to stick with the colors in the screenshot -- take a look at `delta --show-config --diff-so-fancy` to see the options you might want to change.

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/102997213-74729800-451c-11eb-803c-778923a248cb.png" alt="image" /></td></tr></table>

**Comment by joe23rep** [comment]
thanks. will try it out.
