### ISSUE TITLE
🐛ReadMe can now use latest less.exe (instead of forked version)

### ISSUE THREAD

**Issue by mdentremont** [dandavison/delta#461]
(This is very minor!)
The changes from https://github.com/lzybkr/less are now merged into https://github.com/gwsw/less.

Thus the readme can probably recommend using the main version now, binaries are hosted here: https://github.com/jftuga/less-Windows

**Comment by dandavison** [comment]
Thanks, no, that's really helpful @mdentremont -- the `less` version is the source of nearly all Delta problems on Windows.

**Comment by mdentremont** [comment]
@dandavison No problem! I just filed this issue on the less repository (affects the lzybkr version as well, which is what started me on this hunt) - figured I would pass it along so you're aware just in case somebody files an issue here.

https://github.com/gwsw/less/issues/109
