### ISSUE TITLE
🐛 delta 0.4.5 binary release messes up terminal on Ubuntu 20 04

### ISSUE THREAD

**Issue by salmankhilji** [dandavison/delta#463]
Release 0.4.5, when run on Ubuntu 20 04, messes up the terminal.  After running `delta`, I see the diff output; however, any subsequent typing within the terminal is not echo'd back.

```
salman@byteevo-scm:~/Scratch$ ls update-pcs*
update-pcs  update-pcs-new
salman@byteevo-scm:~/Scratch$ ./delta -s update-pcs update-pcs-new 

comparing: update-pcs ⟶   update-pcs-new
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

│ 1  │#!/bin/sh                                                │ 1  │#!/bin/sh
│ 2  │for i in $(seq 3); do                                    │ 2  │for i in $(seq 4); do
│8m 3  │    rsync -av -e "ssh -i $HOME/.ssh/id_rsa" $HOME/.local→│ 3  │    rsync -av -e "ssh -i $HOME/.ssh/id_rsa" $HOME/.local→
│ 4  │    rsync -av -e "ssh -i $HOME/.ssh/id_rsa" $HOME/.local→│ 4  │    rsync -av -e "ssh -i $HOME/.ssh/id_rsa" $HOME/.local→
│ 5  │done                                                     │ 5  │done
salman@byteevo-scm:~/Scratch$ 
Command 'lll' not found, did you mean:

  command 'dll' from deb brickos (0.9.0.dfsg-12.2)
  command 'lld' from deb lld (1:10.0-50~exp1)
  command 'lli' from deb llvm-runtime (1:10.0-50~exp1)
  command 'llt' from deb storebackup (3.2.1-1+deb8u1build0.20.04.1)
  command 'llc' from deb llvm (1:10.0-50~exp1)

Try: sudo apt install <deb name>

salman@byteevo-scm:~/Scratch$ delta 0.4.5
salman@byteevo-scm:~/Scratch$ 
```

As you can see, I intentionally typed a non-existant command `lll`, which is not echo'd back.  Then I typed `./delta --version`, which is also not echo'd back.  The result of the command is, however, seen in the output above.

**Comment by MarcoIeni** [comment]
I was able to reproduce it.
By the way with zsh it works.

**Comment by dandavison** [comment]
Hi @MarcoIeni. Do you understand what's happening here? I was not able to reproduce this in a docker container.

**Comment by MarcoIeni** [comment]
I tried with `cargo install git-delta` and I have the same problem. So it's not a problem of the released binary only.

I will patiently go back commit by commit to identify where the problem started :)

**Comment by dandavison** [comment]
Thanks very much @MarcoIeni! I'm on MacOS (and can run in Docker also) and cannot reproduce, but I will try to think what might be going wrong. Here are some questions in case they help pinpoint the problem

- Does it depend on the terminal emulator being used?
- Does the problem still occur with `--paging=never`?
- Does it occur with and without `side-by-side`?

**Comment by MarcoIeni** [comment]
> * Does it depend on the terminal emulator being used?

Default ubuntu terminal emulator (gnome-terminal): works with zsh and doesn't work with bash.


> * Does the problem still occur with `--paging=never`?

no!

> * Does it occur with and without `side-by-side`?

yes, both cases

**Comment by dandavison** [comment]
>> Does the problem still occur with --paging=never?
> no!

Interesting! What are your values of the `DELTA_PAGER`, `BAT_PAGER`, `PAGER` and `LESS` env vars?

**Comment by MarcoIeni** [comment]
they are empty

![image](https://user-images.githubusercontent.com/11428655/103084105-76049480-45de-11eb-9e24-974904df1e5d.png)

**Comment by MarcoIeni** [comment]
![image](https://user-images.githubusercontent.com/11428655/103084195-b7953f80-45de-11eb-90c6-3638377e4b8f.png)

as you can see with paging=never it works. Otherwise it doesn't echo your input. I don't know why it added an 'l' at the end

**Comment by dandavison** [comment]
OK, if you could determine the first bad commit that would be fantastic.

**Comment by MarcoIeni** [comment]
It looks like the problem was introduced in 46eb84bd34f8ff67f749eec8a287d5a3e7a0919a

More details soon..

**Comment by dandavison** [comment]
Thanks @MarcoIeni, I think I can see that this is broken on MacOS, even though it isn't messing up my terminal: when I do
`delta Cargo.toml /etc/passwd` I do not see the full output (I only see the red removed lines from `Cargo.toml`). But when I do `delta --paging=never Cargo.toml /etc/passwd` I see the full output (removed and added lines).

I'm guessing I wrote some very bad process management code in 46eb84b and there's a race condition somewhere between `delta`, `diff` and `less`, resulting in some output being truncated.

**Comment by dandavison** [comment]
Thanks very much for debugging @MarcoIeni!

**Comment by MarcoIeni** [comment]
I am trying to find a solution as well, I don't get why it doesn't work <.<

**Comment by MarcoIeni** [comment]
the problem is that you don't have to pass the writer variable to that function.

**Comment by dandavison** [comment]
0.5.0 was just released and contains the fix for this issue. Thanks very much @salmankhilji for reporting this with helpful detail.
