### ISSUE TITLE
Make good color choices in 256-color terminals

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#47]
See #46, cc @jscheid

Possibly follow closely what bat [does](https://github.com/sharkdp/bat/blob/master/src/terminal.rs#L17-L19), i.e. https://docs.rs/ansi_colours/1.0.1/ansi_colours/fn.ansi256_from_rgb.html.

**Comment by ELLIOTTCABLE** [comment]
As someone unfamiliar with Bat's usage of terminal-colour — is this possibly what's causing this issue on macOS for me?

<img width="796" alt="Screen Shot 2019-12-16 at 23 57 10" src="https://user-images.githubusercontent.com/200/70968773-c9551600-205f-11ea-8295-88bd13307f54.png">

Notably, `bat --list-themes` seems to be working fine, so I don't think it's a mis-configuration of the macOS Terminal, despite the README:

<img width="519" alt="Screen Shot 2019-12-16 at 23 57 46" src="https://user-images.githubusercontent.com/200/70968822-e7227b00-205f-11ea-8ddd-4abde35b5df8.png">

**Comment by dandavison** [comment]
Hi @ELLIOTTCABLE. Does Sublime Snazzy look OK in `delta --compare-themes` output? (btw: on master, I have changed the name of this command to `delta --list-themes`).

**Comment by ELLIOTTCABLE** [comment]
Looks about the same as the broken output above — all of the themes do. Odd!

<img width="1152" alt="Screen Shot 2019-12-17 at 01 11 50" src="https://user-images.githubusercontent.com/200/70972948-38d00300-206a-11ea-86c1-8bb1fc4861e2.png">

Also strangely, `delta --compare-themes` is vastly slower than `bat --list themes`; the latter is effectively instant, whereas the former requires noticeable time for each theme enumerated — maybe another bug, or a related one, if this is a fork of `bat`? (If not a signifier of a bug, definitely not worth wasting time on, lmao. Of all commands -not- to prematurely optimize …)

**Comment by dandavison** [comment]
With #111 and #107 (which are in the current released version 0.0.17), delta fully supports 256-color terminal environments: it will automatically map 24-bit colors to their closest 8-bit approximation, and it is now easy to specify 8-bit compatible colors for all the command-line options that support colors. See README, 37cc69ea434303ec8ebf4f248d4bd7f1febafe3e2 commit message and the new output of `--help` for details.

@ELLIOTTCABLE is it behaving correctly for you on 0.0.17? I'm going to close this issue, but if it's not behaving correctly for you let's figure it out.
