### ISSUE TITLE
The project name makes this very difficult to find via search

### ISSUE THREAD

**Issue by fearphage** [dandavison/delta#48]
Since deltas have meaning in a git context, searching for this project with keywords like `github`, `git`,  `delta`, and `download` makes this project almost impossible to find. I had to give up and ask someone to link me to it. It would be nice to make this more discoverable.

FYI there is a (seemingly unmaintained) ruby gem named `git-delta` that I found, but I still couldn't Google my way to this repo.

**Comment by joshka** [comment]
+1 on this - I found git-delta via seeing it in the list of updated tools in homebrew, but then tried to find it from my work computer via google the next day and was a little stymied.

**Comment by dandavison** [comment]
Hm, yes maybe I didn't choose well! Thanks for the feedback, I wonder what's the best course at this stage. I did try adding `git-delta` to the "topics" of the github repo when you first opened this issue @fearphage; not sure if it's helped. It looks like including the term "pager" (or "syntax-highlighting") in google searches does find it currently. But sadly this issue can't be solved by suggesting to people how to search :) Open to suggestions, it's already annoying that "delta" was taken in homebrew and apt-get repositories, so I had to turn to "git-delta" Maybe a more googleable package name while retaining the "delta" executable name. Or hope for more popularity and to eventually prevail with the search engines... not sure!

**Comment by joshka** [comment]
Perhaps rename it ddelta or ddiff or something else as a play on your name.

**Comment by drhayes** [comment]
Just throwing out suggestions:

* `rusty-diff`
* `fancier-diff` (probably too passive aggressive to diff-so-fancy, but whimsy is good)
* `uber-diff`
* `supercool-diff`

:man_shrugging:

**Comment by tmccombs** [comment]
a couple more suggestions:

- `alluvium` (play on words, referring to river deltas)
- `deltoid`
- `fancy-delta`

**Comment by ELLIOTTCABLE** [comment]
`deltalowda`.

![source](https://user-images.githubusercontent.com/200/70969158-d58da300-2060-11ea-85c8-2081159d19f9.gif)

**Comment by dandavison** [comment]
Thanks for the feedback everyone. I don't feel comfortable changing the name now that it's in users' gitconfigs etc. I think I'm just going to to accept that I made a questionable choice, which is hard to google, and preventing it getting into Debian... we'll have to see if delta can battle through despite that!

**Comment by tmccombs** [comment]
> I don't feel comfortable changing the name now that it's in users' gitconfigs etc.

I respect that decision. But I would like to point out that the project name and the command name don't have to be identical. For example the silver searcher and ripgrep use ag and rg as their commands respectively. Also, while there is a "delta" package in debian, it conveniently doesn't have any executable named "delta", so if the package name was different I don't think there would be any problem with having the executable called "delta" in the debian package.

**Comment by dandavison** [comment]
Thanks @tmccombs. That's what I'm aiming for also: package name `git-delta`, installing executable `delta`. That's how it is with Homebrew, Rust Cargo, Archlinux, FreeBSD. Unfortunately Debian is not going completely smoothly. You can read the packaging RFS thread  at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946213

> Also, while there is a "delta" package in debian, it conveniently doesn't have any executable named "delta",

while that's true, it would appear that this package does install an executable named "delta": https://tracker.debian.org/pkg/swap-cwm I don't _think_ that executable is widely used though.

Maybe I shouldn't have closed this issue, I'm very much appreciating the discussion and suggestions. I'm currently thinking that I want the executable name to remain "delta" since that's what the docs have always said and that's what we have in our config file. I'll reopen!

**Comment by dandavison** [comment]
Closing this again :) The project seems to be coming up on the first page now for reasonable search terms in the engines/browsers I'm trying. I'll try to get it included in Debian as `package=git-delta, executable=git-delta`.
