### ISSUE TITLE
[admin only] clean old branches

### ISSUE THREAD

**Issue by MarcoIeni** [dandavison/delta#483]
This repo has a lot of branches: https://github.com/dandavison/delta/branches

Consider cleaning them up and activating this option in [settings](https://github.com/dandavison/delta/settings).

![image](https://user-images.githubusercontent.com/11428655/103438192-c0b28c00-4c30-11eb-868f-f791e255eac9.png)

In this way branches are automatically deleted once the PR is merged.

**Comment by dandavison** [comment]
Thanks! Cleaned up (we did actually have that setting active already.)
