### ISSUE TITLE
🚀 Support for Apple Silicon/ARM64

### ISSUE THREAD

**Issue by johnalanwoods** [dandavison/delta#484]
Is there any plan to support Apple Silicon/ARM64?

Thanks

Building with Cargo 1.48.0 I get:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

**Comment by dandavison** [comment]
Hi @johnalanwoods, the honest answer here is that I do not know what I would need to do to go about this! (I am a mac user but not Silicon/ARM). Maybe someone can chime in here who knows what if anything it's appropriate to do currently, or whether we just wait for developments. cc @MarcoIeni 

 I noticed that when the latest release of delta went up on homebrew yesterday that the  homebrew maintainers checked whether it would build on ARM, and that it didn't work: https://github.com/Homebrew/homebrew-core/pull/68056#issuecomment-752838290. Quick googling brings up https://github.com/actions/runner/issues/805 and https://github.com/rust-lang/rust/issues/73908.

**Comment by johnalanwoods** [comment]
@dandavison  - thanks for the quick reply. No probs I'll see what I can do to try and get it building... also it's such a great project thanks for your creation.

@MarcoIeni  - quick question, do you think this is something that will resolve as Rust support matures or do you have any pointers I can investigate?

**Comment by MarcoIeni** [comment]
Have you tried with rust 1.49? See [here](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html#64-bit-arm-macos-and-windows-reach-tier-2).

Anyway, we are relying on [cross](https://github.com/rust-embedded/cross) for cross compilation. So when it will support M1 we will add it to [Continuous Deployment](https://github.com/dandavison/delta/blob/master/.github/workflows/cd.yml) and the binary will be in [releases](https://github.com/dandavison/delta/releases).

**Comment by domoritz** [comment]
`cargo install git-delta` worked fine for me with the latest rust stable. 

Unfortunately, homebrew did not work

```
brew install --build-from-source git-delta
==> Downloading https://github.com/dandavison/delta/archive/0.5.0.tar.gz
==> Downloading from https://codeload.github.com/dandavison/delta/tar.gz/0.5.0
# #=O#- #
==> cargo install
Last 15 lines from /Users/dominik/Library/Logs/Homebrew/git-delta/01.cargo:


  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-apple-darwin" "-Wall" "-Wextra" "-o" "/private/tmp/git-delta-20210104-90319-x2yzxi/delta-0.5.0/target/release/build/ansi_colours-d354c876e404800b/out/src/ansi256.o" "-c" "src/ansi256.c" with args "clang" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to compile `git-delta v0.5.0 (/private/tmp/git-delta-20210104-90319-x2yzxi/delta-0.5.0)`, intermediate artifacts can be found at `/private/tmp/git-delta-20210104-90319-x2yzxi/delta-0.5.0/target`

Caused by:
  build failed

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by johnalanwoods** [comment]
Sorry for late reply!

Yep I see this too. Can build manually using cargo. Maybe an issue with the brew formula?

**Comment by dandavison** [comment]
Hi @domoritz @johnalanwoods, see https://github.com/dandavison/delta/issues/487 and 5b627ced94faf03054677d8436463e6da4818d4f. It looks like I have a bad workflow which is resulting in Cargo.lock becoming different from what I get if I delete it and `cargo build --release` again. Do tell me if you have recommendations for what my workflow should be!

**Comment by johnalanwoods** [comment]
@dandavison  I think all we need is a new release with an updated cargo.lock file. I think its easy to update using cargo update.

**Comment by dandavison** [comment]
@johnalanwoods thanks, do you know what the workflow should be? I.e. When ought I to run `cargo update`?

**Comment by johnalanwoods** [comment]
Thanks for quick reply @dandavison.

I'll defer if I may to @carlocab on that

**Comment by dandavison** [comment]
@johnalanwoods assuming the ARM build on Homebrew succeeds (see https://github.com/Homebrew/homebrew-core/pull/68333), is anything more needed here?

**Comment by johnalanwoods** [comment]
@dandavison  - nope I think that's everything, thanks!

**Comment by carlocab** [comment]
delta successfully built on the ARM runner: https://github.com/Homebrew/homebrew-core/pull/68333/checks?check_run_id=1650854158

**Comment by carlocab** [comment]
Oh, and as for `cargo update`, I'm not sure, sorry! I was actually under the impression you always wanted the lock file you get out of `cargo build` because that should always produce a known-good lock file. (At least, a good one for the architecture you've built on.)

**Comment by johnalanwoods** [comment]
Thanks all, will close this issue as soon as I see git-delta work through normal brew install.

**Comment by johnalanwoods** [comment]
@carlocab , @dandavison working perfectly on ARM!:

<img width="1516" alt="Screenshot 2021-01-05 at 15 49 15" src="https://user-images.githubusercontent.com/5158898/103667306-a862aa00-4f6d-11eb-914d-241b41bf1c7c.png">




@carlocab will take a look at the issue you linked, happy to help.

**Comment by JacobEvelyn** [comment]
> Anyway, we are relying on [cross](https://github.com/rust-embedded/cross) for cross compilation. So when it will support M1 we will add it to [Continuous Deployment](https://github.com/dandavison/delta/blob/master/.github/workflows/cd.yml) and the binary will be in [releases](https://github.com/dandavison/delta/releases).

I don't know much about rust/cross but would it now be possible to generate an Apple Silicon binary in the CD system and add the binary to future releases?

**Comment by MarcoIeni** [comment]
Yeah, I can look at it this week 👍

**Comment by dandavison** [comment]
Hi @MarcoIeni, nice to hear from you -- thanks!
