### ISSUE TITLE
🐛 Outdated `Cargo.lock` file?

### ISSUE THREAD

**Issue by carlocab** [dandavison/delta#487]
delta is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for delta on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by dandavison** [comment]
Thanks very much for taking care of this @carlocab. I've released 0.5.1 with a updated `Cargo.lock`: https://github.com/Homebrew/homebrew-core/pull/68333

**Comment by carlocab** [comment]
That did the trick. Delta built successfully on ARM. Thanks for fixing this so quickly!
