### ISSUE TITLE
🚀 Support for Alpine/busybox

### ISSUE THREAD

**Issue by andrei-pavel** [dandavison/delta#488]
I guess this is more of a feature addition, rather than a bug, because it's not stated anywhere that Alpine is supported, right?

So I'm getting the following error in Alpine for a lot of commands, and this is the better version of `less` from the ones that are accessible on this platform i.e. the busybox version.
```
$ git log
less: unrecognized option: RAW-CONTROL-CHARS
BusyBox v1.31.1 () multi-call binary.

Usage: less [-EFIMmNSRh~] [FILE]...

View FILE (or stdin) one screenful at a time

	-E	Quit once the end of a file is reached
	-F	Quit if entire file fits on first screen
	-I	Ignore case in all searches
	-M,-m	Display status line with line numbers
		and percentage through the file
	-N	Prefix line number to each line
	-S	Truncate long lines
	-R	Remove color escape codes in input
	-~	Suppress ~s displayed past EOF
```

`.gitconfig`
```
[core]
    pager = delta --diff-so-fancy
```
The `--diff-so-fancy` is not the culprit.

I don't use Alpine as my main, but I do like to use delta as my pager on all my VMs. I would like to offer support for Alpine or more generically busybox. Would you accept a PR? I'm thinking three bird-eye view solutions:
1. check at runtime if commands that error out here are supported, and if not, then try a more portable call of the command
2. same as 1, but for performance cache the result in some persistent storage
3. more elegantly, remove `less` as a dependency and do everything by hand, in Rust

**Comment by andrei-pavel** [comment]
Hi! Using environment variable with the `-R` parameter works beautifully. `-X` is also not supported.

```
$ less --version
less: unrecognized option: version
```
:laughing: 
But it does appear in the error: `BusyBox v1.31.1`

BusyBox is a standalone set of binaries, you can download them at `https://www.busybox.net/`.

`bat` is my default `cat` and indeed, it displays the same error. Would you happen to know of an environment variable for it too?

This is solved for me. Thank you! You may close the issue. Leaving it open in case you want to pursue it further.

**Comment by dandavison** [comment]
> bat is my default cat and indeed, it displays the same error. Would you happen to know of an environment variable for it too?

Yup -- `BAT_PAGER`.

Great, glad env vars solve this!

**Comment by jyn514** [comment]
It would be nice if this worked out of the box so I didn't have to configure DELTA_PAGER. It looks like delta is trying to do version detection, but detects to passing these flags if it can't find the version?
```
; strace -f -e execve delta 
execve("/home/jyn/.local/lib/cargo/bin/delta", ["delta"], 0x7ffc4280f1e8 /* 32 vars */) = 0
[pid  2271] execve("/usr/bin/less", ["less", "--version"], 0x7fff27ac3bc8 /* 32 vars */) = 0
[pid  2297] read(8, "less", 32)         = 4
[pid  2297] read(8, ": unrecognized option: ", 28) = 23
[pid  2272] execve("/usr/bin/less", ["less", "--RAW-CONTROL-CHARS", "--no-init", "--quit-if-one-screen"], 0x555555f24640 /* 34 vars */The main way to use delta is to configure it as the pager for git: see https://github.com/dandavison/delta#configuration. You can also use delta to diff two files: `delta file_A file_B`.
) = 0
less: unrecognized option: RAW-CONTROL-CHARS
BusyBox v1.30.1 (2021-03-31 04:59:34 UTC) multi-call binary.
```

**Comment by jyn514** [comment]
also, `-R` appears to do something different on busybox:
```
(alpine) $ less --help 2>&1 | grep -- -R
	-R	Remove color escape codes in input
(ubuntu) $ ; less --help | grep -- -R
  -r  -R  ....  --raw-control-chars  --RAW-CONTROL-CHARS
```

**Comment by jyn514** [comment]
and apparently there's not a way to override the pager to say "no arguments" because delta tries to be smart and pass the args anyway :/

```
; echo $DELTA_PAGER 
less
; git diff
less: unrecognized option: RAW-CONTROL-CHARS
```

**Comment by dandavison** [comment]
Hi @jyn514, would you mind summarizing the issue you're describing, something like:

- What I want to do
- What I tried
- What I expected
- What I observed

delta shared pager-launching code with bat; would you mind also reporting whether you see the same behavior with bat?

**Comment by omentic** [comment]
I would similarly like it if this worked out of the box.

@dandavison The issue is that any command run involving `delta` (including `delta --help`) on Alpine (Busybox?) outputs a screen like that above. I do not see the same issue with `bat`. It's fixed by setting `DELTA_PAGER = "less -R"`, but it would be nice to not need to set this in the first place...

Also, I have encountered some weird behaviour. Unless I am mistaken, setting `DELTA_PAGER` *once* seemed fix this issue? Which is really quite strange, perhaps `delta` is doing some global state shenanigans after it recognizes `DELTA_PAGER`?

**Comment by jeff-phil** [comment]
Just add Alpine's `less` package to override busybox's default `less`:

   `apk add less`
