### ISSUE TITLE
🚀 multiline with --side-by-side

### ISSUE THREAD

**Issue by jonathanpoelen** [dandavison/delta#498]
Currently lines that are too long are truncated with `--side-by-side`. I propose `--multi-line-side-by-side` which would give like this example with icdiff:

![2021-01-10-025048_956x201_scrot](https://user-images.githubusercontent.com/1436727/104112643-b3149a80-52f1-11eb-8918-fe9384369aad.png)

**Comment by nghialm269** [comment]
I suggest that we also have an option to fallback to unified view if the line is too long / or the terminal width is small.

**Comment by dandavison** [comment]
Thanks @jonathanpoelen. The good news is that there's a branch in progress for this: https://github.com/dandavison/delta/pull/515

**Comment by dandavison** [comment]
That's right! Thanks, I forgot about this one; will close it now. (Hi @waldyrious!)
