### ISSUE TITLE
🐛 pager starts even if there is an error in the filenames

### ISSUE THREAD

**Issue by jonathanpoelen** [dandavison/delta#502]
With

```ini
# ~/.gitconfig
[delta]
    paging = always
```

When we run `delta` (without git) with zero or a file or if the files do not exist, it still opens the pager which hides the error message. Without a file, this also corrupt the prompt.

Even with this option, I'm not sure that starting the pager if there is no difference is appropriate.

**Comment by dandavison** [comment]
Thanks for this and the other issues @jonathanpoelen. I'm going to be offline for the next two weeks but I'll get back to them.

**Comment by dandavison** [comment]
Hi @jonathanpoelen, I believe this is fixed in master now. Please do reopen if not though.
