### ISSUE TITLE
🐛 `delta` not being used for `git add -p`, but works for `git diff`/`git log -p`

### ISSUE THREAD

**Issue by rory** [dandavison/delta#503]
I have this in my `~/.gitconfig`, and it works for `git diff` & `git log -p`, but not `git add -p`. Am I missing something?

```
[core]
    pager = delta

[delta]
    light = true
```

**Comment by dandavison** [comment]
Hi @rory , I think this should do it:

```gitconfig
[interactive]
    diffFilter = delta --color-only
```

There's lots of stuff in the README and --help output I know!

**Comment by rory** [comment]
Yes that solves it. Thanks for your quick response. Sorry for not seeing that part of the `README.md`. I saw the parts about `plus-color` and presumed that was just for customisability and skipped it.
