### ISSUE TITLE
🚀 Add more than information with build-time ？e.g shadow-rs

### ISSUE THREAD

**Issue by baoyachi** [dandavison/delta#506]
consider https://github.com/baoyachi/shadow-rs

**Comment by dandavison** [comment]
Thanks @baoyachi, I'll definitely keep this in mind and watch out for the next time build-time information like this would solve a problem.

One thought -- is there a single function that will print out a bunch of default information, to make it very easy for users? E.g.

```rust
use shadow_rs

fn main() {
    shadow_rs::print_everything();
}
```

**Comment by baoyachi** [comment]
good idea. 👍 @dandavison

**Comment by baoyachi** [comment]
It's done in version [shadow-rs0.5.24](https://github.com/baoyachi/shadow-rs/blob/df889cdd11/example_shadow/src/main.rs#L20)

add `print_build_in` function
```rust
 build::print_build_in();
```

**Comment by dandavison** [comment]
Thanks @baoyachi, I will keep this in mind like I said and watch out for the next time it solves a problem.
