### ISSUE TITLE
🐛 Wrong syntax highlighting after python docstring

### ISSUE THREAD

**Issue by usualwitch** [dandavison/delta#509]
I used python 
```python
r""" 
Some docstring
"""
``` 
to define a docstring. After I changed a few lines after the docstring, delta will interprete the ending `"""` as the beginning of some comment, and highlight the changed lines as if they were comments.

Here is the git diff output.
[git_diff_output.txt](https://github.com/dandavison/delta/files/5873205/git_diff_output.txt)

**Comment by dandavison** [comment]
Hi @usualwitch, thanks, I agree this is a problem (I also notice it with Python docstrings). This is a duplicate of https://github.com/dandavison/delta/issues/117. Maybe take a look at the discussion there and if you have any ideas/opinions on the best way forwards that would be great to hear.
