### ISSUE TITLE
Install problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by nasafix-nasser** [dandavison/delta#51]
When I want to install on Ubuntu 16.04, I get the following error. 
`$ brew tap dandavison/delta https://github.com/dandavison/delta`
...
`$ brew install dandavison/delta/git-delta`

`Error: No available formula with the name "dandavison/delta/git-delta"`
`==> Searching for a previously deleted formula (in the last month)...`
`Warning: dandavison/delta is shallow clone. To get complete history run:`
`  git -C "$(brew --repo dandavison/delta)" fetch --unshallow`

`Error: No previously deleted formula found.`
`==> Searching for similarly named formulae...`
`Error: No similarly named formulae found.`

I'm new to brew so please excuse me if I've missed a simple thing. I can use `brew install git-delta` and it works fine.

Also:
`$ brew --repo dandavison/delta
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/dandavison/homebrew-delta`
and it's HEAD is 0052bd7b170188ec30fd1beb5ed89b51c8efbd70

**Comment by dandavison** [comment]
Hi @nasafix-nasser, I tried to install homebrew in a docker container to investigate this but didn't quite get it working. However, the public homebrew is now the correct one to install: `brew install git-delta`.

So we no longer need to use my personal homebrew tap (you can remove with with`brew untap dandavison/delta` I believe). 

Thanks for reporting and sorry for the slow response. I'm going to close this but reopen if that's not right.

**Comment by nasafix-nasser** [comment]
Hi @dandavison. Thank you for taking the time to investigate the problem.
OK, I got it.
