### ISSUE TITLE
🐛 Hunk header misaligned in some cases

### ISSUE THREAD

**Issue by NICHOLAS85** [dandavison/delta#510]
Recording demonstrating issue: https://asciinema.org/a/OR4p7nKdnuWK5De0EgnWF0hbI

It seems when using delta on a git diff from a file containing tab characters, the Hunk header container doesn't line up correctly. The right bound is pushed outwards.

Heres the link to the tested file if you'd like to clone and attempt it locally: https://gist.github.com/NICHOLAS85/ac2fae33549b9cb029d5e84cccf7b076

**Comment by dandavison** [comment]
Thanks for this @NICHOLAS85. It should be fixed now in master, and I'm planning on releasing a new version soon.
