### ISSUE TITLE
🚀 How can I wire `delta` into my COMMIT_EDITMSG?

### ISSUE THREAD

**Issue by dycw** [dandavison/delta#517]
Hi, `delta` is amazing! However, is it possible to wire it into my `COMMIT_EDITMSG` so that I get the same amazing-ness when I have to write my commit message? I'm using `vim` in case that helps.

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch test
# Your branch is ahead of 'master' by 1 commit.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#>      new file:   arst
#>      modified:   environment.yml
#
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
diff --git a/arst b/arst
new file mode 100644
index 0000000..bb397ef
--- /dev/null
+++ b/arst
@@ -0,0 +1 @@
+arst
diff --git a/environment.yml b/environment.yml
index f2df9e5..5dc12e9 100644
--- a/environment.yml
+++ b/environment.yml
@@ -2,6 +2,7 @@ name: dotfiles
-
 channels:
   - conda-forge
+  - anaconda
-
 dependencies:
   - python = 3.9
```

**Comment by dandavison** [comment]
Hi @dycw, thanks. Essentially, delta is a program that takes git/diff plain text input and returns it with ANSI color escape codes. So to get the colors etc in your text editor when it's displaying the commit message, your test editor would have to handle the color escape codes, like a terminal emulator does. I've [implemented that](https://github.com/dandavison/magit-delta) for emacs, but I'm not a vim user, so I'm unclear how possible this is. Could you try asking your question in this delta issue thread: https://github.com/dandavison/delta/issues/338, where there are several knowledgable delta+vim users?

**Comment by dycw** [comment]
Absolutely, thank you @dandavison for `delta`; one of my best finds in a decade of programming!

**Comment by jessevdp** [comment]
Hey, did anyone ever figure this out?

I'm really no expert in customizing vim, but I am used to the motions etc. so I use it as my editor of choice for CLI Git usage.

I think #338 spun off into a thread around much more advanced usage within Nvim etc.

But what about just simply using Delta to display the diffs when you `git commit` with `EDITOR=vim`?
