### ISSUE TITLE
🚀 Minimize the number of highlighted blocks

### ISSUE THREAD

**Issue by duongdominhchau** [dandavison/delta#521]
![image](https://user-images.githubusercontent.com/56427890/107524571-81d90400-6be8-11eb-8dfe-70a3b97c8aa2.png)

Here we can see `delta` highlights three blocks, but in this case only two is enough to show the change: one for `<a id="Seconds.fraction">` and one for `</a>`. In this example, we can reduce the number of highlighted blocks by moving these blocks to the left as far as possible and merge.

**Comment by dandavison** [comment]
Hi @duongdominhchau, thanks for this. You're definitely right that the highlighting algorithm could be improved, and your example is very helpful. So it's a worthwhile project for me or anyone else to work on! #246 is similar, and #140 is related.

**Comment by dandavison** [comment]
I'm going to close this one and keep #246 as the primary ticket for this work, but thanks for the additional detail here.
