### ISSUE TITLE
🐛 Windows: setting as a pager through gitconfig results in escape codes, but piping works.

### ISSUE THREAD

**Issue by danspunkmeyer** [dandavison/delta#524]
Sample output:
│[38;5;238m 88 [38;5;4m│[38;5;231m                [38;5;208mworkflowsaction[38;5;231m [38;5;81m=>[38;5;231m {[0m       

Less has been upgraded to latest version - in fact there were some significant color issues with the existing less.exe, but it was somewhat readable and this problem started after having upgraded to latest. 

Problem is present even with minimal gitconfig change of setting pager = delta under [core]         

Additionally, side-by-side has glitches with unicodes showing and almost everything underlined.

**Comment by danspunkmeyer** [comment]
(An update on side by side issues: <U+2192> appears if the line needs to wrap. Haven't found a workaround for this. The underlines are resolved by setting --line-numbers-right-style 'auto' --line-numbers-left-style 'auto')

**Comment by dandavison** [comment]
> setting as a pager through gitconfig results in escape codes, but piping works

Hi @danspunkmeyer, I believe this is because when delta is invoked as a child process of git, git is causing it to find a version of `less` that git itself possesses, and not the latest version of less that you intended. You could test that theory out by setting `pager = less --version`. One way to solve it would be to set the env var `DELTA_PAGER` to the absolute path to your desired less executable.

**Comment by dandavison** [comment]
Did you make any progress with this @danspunkmeyer ?

**Comment by dandavison** [comment]
I'll close this for now, but do feel free to keep discussing. Problems like this on Windows are always either due to the less version or the terminal emulator not supporting 24-bit colors or certain utf-8 characters.

**Comment by dandavison** [comment]
There are several similar Windows issues in delta issue history which may be illuminating. It would be fantastic to have all the Windows troubleshooting knowledge summarized in a single document. Perhaps the bat project has something like that; these issues will also affect bat users on Windows.
