### ISSUE TITLE
core.pager breaks output of other git commands

### ISSUE THREAD

**Issue by lhunath** [dandavison/delta#528]
The recommended way to enable delta is by adding to `~/.gitconfig`:
```
[core]
    pager = delta
```

This works great; unfortunately it also appears to break other git commands that use the pager.

For instance:

```
$ git branch
Pattern not found  (press RETURN)
$ git grep a
Pattern not found  (press RETURN)
$ git tag
Pattern not found  (press RETURN)
$ git reflog
Pattern not found  (press RETURN)
```

That said, `git log`, `git diff`, `git show`, etc. all work as expected.

**Comment by Kr1ss-XD** [comment]
@lhunath do you happen to have `delta.navigate=true` in your gitconfig ?

If so, I'd suggest to remove that, and use navigate on a case-by-case base. It's known to cause problems like that.

Do activate it on demand, you can use for examples
```sh
DELTA_NAVIGATE=true git show
```

or set up an alias like `alias nav='DELTA_NAVIGATE=true git'` in one of your shell startup files.

**Comment by dandavison** [comment]
On the plus side, thanks to @cben I think we have an improvement in-the-works for navigate that will allow us to leave it activated always if we want. See https://github.com/dandavison/delta/issues/237#issuecomment-780673148.

**Comment by lhunath** [comment]
Yup, thanks!  That appears to be the culprit.
