### ISSUE TITLE
Transparent backgrounds via alpha hex values 🚀 

### ISSUE THREAD

**Issue by thornycrackers** [dandavison/delta#530]
First off thanks so much for Delta, this is such a great tool.

I was wondering how hard it would be to set transparent colors by specifying alpha codes so you could do stuff like `#ffffff80`.

**Comment by dandavison** [comment]
Hi @thornycrackers, thanks! OK so it was my impression that there was no way to use ANSI escape sequences to cause terminal emulators to render colors with alpha transparency. Do you know if that's wrong/right? Can you give me an example of an ANSI color escape sequence with alpha channel and a terminal emulator that will render it?

**Comment by thornycrackers** [comment]
Well now after some debugging I've come to the conclusion that you are 100% correct about there not being any. What happened is I was testing one of the 24 bit true color scripts in a floating window and seeing the opacity in the background but in my non floating window where I was running delta there it wasn't. It was due to a picom opacity rule picking up one window but not the other, I just thought since the man page mentioned nothing about transparency that it was an unimplemented feature. PEBKAC error, thanks for the prompt reply.
