### ISSUE TITLE
Show commit hash (sha) in front of line (like in git blame)

### ISSUE THREAD

**Issue by krei-del** [dandavison/delta#533]
Hello,

is it possible to show the commit hash aka sha (and even Author) in front of the lines (like it is shown in git blame)?
The source for that information could be 'git blame per file' itself.

Sorry, if I have missed that option in case you have already implemented something like that.

Thanks and kind regards!

**Comment by dandavison** [comment]
Hi @krei-del, thanks for this. I agree. What do you think of having delta apply syntax-highlighting (and maybe some reformatting) to `git blame` output itself (https://github.com/dandavison/delta/issues/426)? Would that give you what you had in mind?

**Comment by krei-del** [comment]
Hello @dandavison,

yes indeed, the syntax-highlighting for `git blame` would be really nice.
And also for showing a simple file on its own via `git show hash:filepath`. Maybe the latter  is already working, but I don't know, yet .. ??


Some more thoughts about having the hash in diff itself (sorry for the following explanation, but I wanted to clarify it for myself):

_If you diff two commits, passing two hashes(branches/etc.), like `git diff A B` (same as: `git diff A`, being on branch B) you need to know that the first commit (A) is the baseline while the diff showing what changes would be brought in, when you would apply commit (B) onto it._
- Therefore lines marked with - minus belonging to commit A.
- Lines marked with + plus belonging to commit B.

**Idea 1 _(no `git blame` needed)_:**
Maybe I'm still not used to diff listings, but having that information somewhere in the diff listing itself, could be helpful I suppose:
Maybe above/below each filename in the lisitng, in the same color of additions/removals, e.g. 
- (RED) --- A hash / branchname(s), if existing
- (GREEN) +++ B hash / branchname(s), if existing

**Idea 2 - using it on merge commits:**
If the hash is in front of the line itself, you could maybe better see which parent brought the code in! (also see _new_ lines brought in an "evil merge"):
A + code ...  (parent A)
B + code ... (parent B)
C + code ... (actual merge commit itself C)

**Idea 3:**
Now if you apply the git blame information (commit hash, eventually author) to the the diff you actually would see which commit (in the past, possibly before commits used for the diff call) brought the specific line into that file, that would be removed or added.
I'm not sure, how often it would be helpful to have that information to justify the effort ..
Showcases:
- You hunted for a bug, that broke your system, you identified the responsible commit (like with `git bisect`), you identified the responsible lines of code and you create a bugfix commit. In the diff you should see the correct commit hashes, that assures you you changes the correct lines of that buggy commit.
- Knowing the author of the (-) lines, you see whose code always needs improvements .. :smile: 
- ...

**Comment by dandavison** [comment]
Hi @krei-del , can you try the latest version of delta? Delta now has syntax-highlighted git blame, and support for merge conflicts showing diffs from the ancestral commit ( if you have `diff.conflictstyle=diff3`). So could you let me know which new features you suggest given the new features added to delta in recent months?

**Comment by dandavison** [comment]
> `git show hash:filepath` 

This is implemented now also. I'm going to close this ticket now because a few things you mentioned have been implemented. But if you could try the latest version and describe further feature suggestions that's always welcome.

**Comment by krei-del** [comment]
Hello @dandavison,
thanks for your work!
The new styling of git blame and and merge conflicts are really supportive in the every day work!

I guess "Idea 3" should be anyway provided by the git tools itself, instead of "highlighting tool"
