### ISSUE TITLE
Support case-insensitive search as pager 

### ISSUE THREAD

**Issue by mrjoel** [dandavison/delta#538]
I have recently switched to using delta as a git pager instead of less. The biggest thing I've been missing is support for the `--ignore-case` search option as is provided by less. This option allows searching by lower case characters matching all cases by default, but it the search term includes uppercase characters then switch searches to case sensitive searching.

**Comment by dandavison** [comment]
Hi @mrjoel, I'm happy to say that (if I'm understanding correctly) this is easy! The delta process itself invokes `less` to act as the pager for delta's output and this `less` process will respect all the standard environment variables. So, there are a few ways to do what you want: you could:

1. Set the `LESS` environment variable to hold the `i` flag along with any others you want. `R` is generally required to show the colors. So for example, perhaps `export LESS='-iR'`
2. Or you could do something similar with either `DELTA_PAGER` or `PAGER` (this latter one will affect any application using a pager, including delta). In this case it looks more like `export DELTA_PAGER = less -iR`.

There's some documentation of this here: https://github.com/dandavison/delta#a-delta

Let me know if I can help further. I do understand that if setting environment variables is not already part of your workflow in your development environment that there can be various gotchas relating to shell programming and unix processes; or if it's Windows, I can imagine that there are also gotchas there. On Linux or MacOS the most common approach is to have a line line `export LESS='iR'` in a shell config file like `~/.bashrc`.

**Comment by Kr1ss-XD** [comment]
> On Linux or MacOS the most common approach is to have a line like export LESS='iR' in a shell config file like ~/.bashrc.

This. However, if it's inconvenient for you to work with global environment variables for some reason (or you want to use a different default `$LESS` globally), it's also possible to set them in the the `gitconfig`, just for the `delta` process, e.g.

```gitconfig
[core]
	pager = LESS=iR delta
```

**Comment by mrjoel** [comment]
Well the backend callout to less itself is obvious in hindsight and plenty easy enough. It turns out I have a shell alias for less to run `less -i -R` instead of using the environment variable approach. I'll switch my dotfiles to use the `LESS` envvar and should be set. Many thanks!
