### ISSUE TITLE
troubleshooting: base16 theme

### ISSUE THREAD

**Issue by yaahc** [dandavison/delta#54]
It seems that base16 support for delta may be broken atm.

![Screenshot from 2019-11-12 11-18-20](https://user-images.githubusercontent.com/1993852/68703368-5b3ca100-053f-11ea-8451-1335e6772eca.png)

Here is `bat`'s output when previewing the base16 theme

![Screenshot from 2019-11-12 11-26-20](https://user-images.githubusercontent.com/1993852/68703416-77404280-053f-11ea-9946-aec47b6997c7.png)

the color gradient test works and shows that my terminal supports 24 bit colors.

**Comment by dandavison** [comment]
Hi @yaahc, thanks very much for reporting this. Sorry it took so long. base16 was indeed completely broken, along with ansi-dark and ansi-light. Fixed in #74.
