### ISSUE TITLE
🐛 Missing line markers using `diff-highligh` feature

### ISSUE THREAD

**Issue by ambroisie** [dandavison/delta#544]
Hello, first of all, thanks for the software. It looks really promising as a current user of `diff-highlight`.

I am hitting an issue that I have not seen described, or have failed to find. When using the `diff-highlight` and `keep-plus-minus-markers` features at the same time, the markers do not appear on lines that are empty.

Here are two files as an example:
`whitespace.txt`
```
Hello

  
World
End
```
`whitespace-bis.txt`
```
Hello
World
  

End
```

You should notice that there are two "blank" lines, one with spaces and one without. Their order is reversed between both files and `World` has been moved above them.

Here is the output that I get with `delta --no-gitconfig --diff-highlight --keep-plus-minus-markers=true whitespace.txt whitespace-bis.txt`:
![delta](https://user-images.githubusercontent.com/12465195/111854082-c8bfc500-891d-11eb-9c20-0429ee669494.png)

And here is what I would expect to see, using `diff-highlight`:
![diff-highlight](https://user-images.githubusercontent.com/12465195/111854069-b9407c00-891d-11eb-8f31-8c0dc46d0408.png)

I would like to be able to see the see the markers instead of an empty green/red space.

Is this a misconfiguration on my part?

**Comment by dandavison** [comment]
Hi @Ambroisie, thanks for this. I can reproduce it and will look into it.

For reference when investigating this, here's some commands that repro it:

```
git -c core.pager=diff-highlight diff --no-index 544-input-1.txt 544-input-2.txt
git -c core.pager=delta -c delta.diff-highlight=true -c delta.keep-plus-minus-markers=true diff --no-index 544-input-1.txt 544-input-2.txt
``` 


![image](https://user-images.githubusercontent.com/52205/111906269-b88f0f00-8a1d-11eb-9aef-98251b32d2ac.png)

**Comment by ambroisie** [comment]
@dandavison friendly ping. Do you have an update on this issue per chance?

**Comment by dandavison** [comment]
Hi @ambroisie, thanks for reminding me. It looks like this issue is fixed (I'm using 0.10.2 but probably before that also):

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/143880009-15ad3450-f3ff-4be1-bcde-439c38e66235.png" alt="image" /></td></tr></table>

I'm not sure when; we could bisect to find out. In any case, let me know if it's not fixed for you.

**Comment by ambroisie** [comment]
Indeed, I can confirm that it works correctly. Thank you :-)

**Comment by ambroisie** [comment]
I would have a quick question, if per-chance you know what I am missing @dandavison.

I would like to keep a similar highlighting style as I use with `diff-highlight`, which is the following options:

```gitconfig
[color "diff-highlight"]
	newHighlight = "green bold 22"
	newNormal = "green bold"
	oldHighlight = "red bold 52"
	oldNormal = "red bold"

# Delta configuration for context
[delta]
	features = "diff-highlight decorations"

[delta "decorations"]
	keep-plus-minus-markers = true
	paging = "always"
```

I see that `delta` picks up the `color "diff-highlight"` configuration when using `diff-highlight` emulation (!), I also noticed an issue which I would like to solve (which also exists with `diff-highlight`, I just hadn't noticed before) which is that the lines that are being highlighted are bolder than the ones that aren't (specifically, the text which *isn't* being highlighted looks bolder when I would expect them to look the same as the rest).

Here's an example with the following diff:
```diff
diff --git a/pkgs/development/python-modules/django-js-reverse/default.nix b/pkgs/development/python-modules/django-js-reverse/default.nix
index 8d591c43644..b245c113117 100644
--- a/pkgs/development/python-modules/django-js-reverse/default.nix
+++ b/pkgs/development/python-modules/django-js-reverse/default.nix
@@ -8,7 +8,7 @@
 
 buildPythonPackage rec {
   pname = "django-js-reverse";
-  version = "0.10.0";
+  version = "0.10.0"; # FIXME: too new?
 
   src = fetchFromGitHub {
     owner = "ierror";
diff --git a/pkgs/development/python-modules/pyyaml/default.nix b/pkgs/development/python-modules/pyyaml/default.nix
index 10073176aeb..82ee5c6d3c2 100644
--- a/pkgs/development/python-modules/pyyaml/default.nix
+++ b/pkgs/development/python-modules/pyyaml/default.nix
@@ -3,19 +3,20 @@
 , fetchFromGitHub
 , cython
 , libyaml
-, isPy27
+, isPy3k
 , python
 }:
 
 buildPythonPackage rec {
   pname = "PyYAML";
-  version = "5.4.1.1";
+  version = "6.0";
+  disabled = !isPy3k;
 
   src = fetchFromGitHub {
     owner = "yaml";
     repo = "pyyaml";
     rev = version;
-    sha256 = "1v386gzdvsjg0mgix6v03rd0cgs9dl81qvn3m547849jm8r41dx8";
+    sha256 = "sha256-wcII32mRgRRmAgojntyxBMQkjvxU2jylCgVzlHAj2Xc=";
   };
 
   nativeBuildInputs = [ cython ];
@@ -23,7 +24,7 @@ buildPythonPackage rec {
   buildInputs = [ libyaml ];
 
   checkPhase = let
-    testdir = if isPy27 then "tests/lib" else "tests/lib3";
+    testdir = "tests/lib";
   in ''
     runHook preCheck
     PYTHONPATH="${testdir}:$PYTHONPATH" ${python.interpreter} -m test_all
diff --git a/pkgs/development/python-modules/recipe-scrapers/default.nix b/pkgs/development/python-modules/recipe-scrapers/default.nix
index 6f44425c8f1..d14962e8ec4 100644
--- a/pkgs/development/python-modules/recipe-scrapers/default.nix
+++ b/pkgs/development/python-modules/recipe-scrapers/default.nix
@@ -12,7 +12,7 @@
 
 buildPythonPackage rec {
   pname = "recipe-scrapers";
-  version = "13.6.0";
+  version = "13.6.0"; # FIXME: too new?
 
   src = fetchFromGitHub {
     owner = "hhursev";
```

With the following result:

![bolder-lines](https://user-images.githubusercontent.com/12465195/143902407-131cce49-db3f-4493-b0c4-796b5b9d3151.png)

I'm not sure how to configure `delta` to keep a similar style, just not bolding non-highlighted text.

**Comment by dandavison** [comment]
I haven't thought this through properly but does this do it?

```gitconfig
    plus-style = green bold
    minus-style = red bold
```

**Comment by ambroisie** [comment]
Actually the opposite, after looking at `delta --show-config` I discovered the `*-{non-,}emph-style` which were the ones I wanted to change.

For future reference if other people want to have the same configuration as I do:

```gitconfig
[delta]
	features = "diff-highlight decorations"

[delta "decorations"]
	keep-plus-minus-markers = true
	paging = "always"

[delta "diff-highlight"]
	minus-emph-style = "bold red 52"
	minus-non-emph-style = "red"
	minus-style = "red"
	plus-emph-style = "bold green 22"
	plus-non-emph-style = "green"
	plus-style = "green"
	whitespace-error-style = "reverse red"
```

Where only the highlighted parts are emboldened, and have a more readable style than reverse video.

**Comment by dandavison** [comment]
OK excellent. Let me know if you feel that delta's defaults should be changed in any way to make diff-highlight emulation more accurate. Thanks for posting the config.

**Comment by ambroisie** [comment]
@dandavison I found one difference, which is that the header in `git show` is not colored correctly.

`diff-highlight` correctly uses my colors for `HEAD`, `main`, `origin/main`, and `origin/HEAD`:
![diff-highlight](https://user-images.githubusercontent.com/12465195/144478455-b32480c8-dcdf-4a8d-81e9-96a14e49f106.png)

Whereas `delta` does not:
![delta](https://user-images.githubusercontent.com/12465195/144478563-a9229742-3b7d-41e1-9c8a-1bc16c49268b.png)

**Comment by dandavison** [comment]
Hi @ambroisie, can you post your config and the command you are using? `diff-highlight` uses `commit-style = raw`, so it is supposed to let the original colors that git emits in the commit line through. That is what I am seeing:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/144525088-26e95c4b-b76d-421e-9eae-3c83c12edbcc.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
(Of course, if you are piping to delta, like `git show | delta` then git won't send any colors at all, unless you use `git --color=always`, but I don't think that's your issue as you have yellow).

**Comment by ambroisie** [comment]
I think `delta` was picking up `yellow` for `commit-style` from this block in my configuration, is that right?

```gitconfig
[color "diff"]
	commit = "yellow"
	frag = "cyan"
	meta = "yellow"
	new = "green"
	old = "red"
	whitespace = "red reverse"
```

Explicitly setting `commit-style` to `raw` fixed it, thank you :+1:.

And thank you for your work and involvement on this software, once again.
