### ISSUE TITLE
What is the best way to selectively use Delta🚀 

### ISSUE THREAD

**Issue by zach-is-my-name** [dandavison/delta#548]
I'm trying to configure a way to optionally use Delta.  So far I've come up with setting the variable GIT_PAGER for that session.  Is there a better way? maybe using command `delta ...`  vs. `git diff (etc) ...`?

**Comment by dandavison** [comment]
Hey @zach-is-my-name, how about, for arbitrary git operations:

```
git -c core.pager=delta ...
```

and for `git diff` specifically, yes, we can do `delta file_a file_b` (see https://github.com/dandavison/delta/issues/543; I'm in the process of switching this to call `git diff`, currently it calls `diff -u`).

**Comment by zach-is-my-name** [comment]
Thanks!
