### ISSUE TITLE
🐛 Something wrong with the env vars PAGER and GIT_PAGER?

### ISSUE THREAD

**Issue by zach-is-my-name** [dandavison/delta#556]
I'll start by just posting this screenshot.  Please tell me anything other info you may need. Thanks!

![Screenshot from 2021-04-01 10-49-42](https://user-images.githubusercontent.com/16063092/113312171-02a6a900-92d8-11eb-8959-213510d85e03.png)

**Comment by dandavison** [comment]
Hm! I am not sure what's going on, let's get to the bottom of it. Can you post the contents of `env | grep -i pager`?

**Comment by zach-is-my-name** [comment]
Sure... thanks

`DELTA_PAGER=delta
PAGER=less
`

**Comment by zach-is-my-name** [comment]
UPDATE sorry I fouled that up. Let me recreate that from scratch.  please stand by one moment

**Comment by dandavison** [comment]
Right, that's it. `DELTA_PAGER=delta` implies the infinite recursion; you could unset it (which will fallback to `PAGER`) or set it equal to `less`. There's some info here: https://github.com/dandavison/delta#environment

```
delta(master) DELTA_PAGER=delta git diff
It looks like you have set delta as the value of $PAGER. This would result in a non-terminating recursion. delta is not an appropriate value for $PAGER (but it is an appropriate value for $GIT_PAGER).
```

**Comment by zach-is-my-name** [comment]
Thank you.  I've unset DELTA_PAGER and everything is fine.  I'll have to find how that is being set originally
