### ISSUE TITLE
🚀 support .git/config settings

### ISSUE THREAD

**Issue by juanMarinero** [dandavison/delta#566]
`delta` reads `~/.gitconfig`. My request is, in a git-project, to read  its `[project-path]/.git/config` ([https://git-scm.com/docs/git-config](https://git-scm.com/docs/git-config)) overriding the `~/.gitconfig` settings.

That way, one could customize `delta` settings per git-project as easy as:
```
cd [git-project]
cat ~/.gitconfig >> ./.git/config
vim ./.git/config                   # e.g. comment line: side-by-side = true
git diff ~/.gitconfig ./.git/config # test changes
```

E.g. if in `~/.gitconfig` I use `side-by-side = true`, but in a particular git-project I rather disable it. Then one should run [like] previous commands. So if `PWD` is in a git repo, then `git diff` should obey `./.git/config` instead of `~/.gitconfig`. 

Next screenshot shows that I commented `side-by-side = true` of `./.git/config`, but in vain (as screenshot itself also shows) 
![delta-feature_to_add](https://user-images.githubusercontent.com/40007751/115635080-283d3600-a30b-11eb-8c8b-24ee941701cc.png)

**Comment by dandavison** [comment]
Hi @juanMarinero, delta does read `.git/config` in the repo. It also reads your other config files and combines the result according to precedence rules (see below).  I think perhaps in your experiment you need to set `side-by-side = false` instead of commenting it out?

`delta` doesn't implement this itself: it uses a rust [crate](https://docs.rs/git2/0.13.18/git2/) that provides bindings for [libgit2](https://libgit2.org/), which is a project which basically intends to behave the same as the original git itself. So, delta should be behaving as documented for libgit2 and I believe that means project config (`./.git/config`) has precedence over user config (e.g. `~/.gitconfig`) which has precedence over system config.

**Comment by juanMarinero** [comment]
> It also reads your other config files and combines the result  [...]  project config (`./.git/config`) has precedence over user config (e.g. `~/.gitconfig`) which has precedence over system config

Good to know that it combines `[project-path]/.git/config` with `~/.gitconfig` (and with system one).

> set `side-by-side = false` instead of commenting it out?

Since it combines results, aye! that fixes it.

Thank you very much for such an excellent answer! 🎉
PD: feature request to be closed

**Comment by juanMarinero** [comment]
Please consider quick explain this all in `README.md` like: [https://github.com/dandavison/delta/compare/master...juanMarinero:patch-1](https://github.com/dandavison/delta/compare/master...juanMarinero:patch-1)

**Comment by dandavison** [comment]
No problem, thanks for the suggestion, I'll update the README in a way similar to your patch, but maybe transferring the information in from this issue. If you felt like modifying that patch so that it brings the info into the README instead of linking to the issue that would be great.

**Comment by juanMarinero** [comment]
In my [newby proposal](https://github.com/dandavison/delta/compare/master...juanMarinero:patch-1) I linked current issue mainly because:
- it explains the combination-hierarchy of git config files (with a praxis example)
- and because  `crate` and `libgit2` explanation could be relevant:
> delta doesn't implement this itself: it uses a rust crate that provides bindings for libgit2 [...]

... but at the same time a TLDR guy would just need (next and maybe its combination-hierarchy): 
> Set delta to be git's pager in your `~/.gitconfig` or `[project-path]/.git/config`

I'm sorry, you are the expert, you should consider what is relevant in `README.md`. From spartan to overfitting-detailed:
- no changes at all (searching issues with pattern "gitconfig" should link to current issue)
- just adding my previous TLDR suggest
- combine TLDR with link to issue as in my [newby proposal](https://github.com/dandavison/delta/compare/master...juanMarinero:patch-1)
- combine TLDR with quick `crate` and `libgit2` explanation (no links to issues)
- ...
- Or even, as this project gets bigger and bigger, consider start editing the `delta`-[wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis). E.g. _coc.nvim_ (a [Vim](https://www.vim.org/) plugin) has a rather concise [Readme.md](https://github.com/neoclide/coc.nvim) but an in detail [coc.nvim/wiki](https://github.com/neoclide/coc.nvim/wiki). Easier said than done to restructure `Readme.md` in split inter-linked wikis.

In my opinion, the [delta-README.md](https://github.com/dandavison/delta/blob/master/README.md) is not so big, so a [github-wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) is not urgent. I suggest you discard my [newby proposal](https://github.com/dandavison/delta/compare/master...juanMarinero:patch-1) and maybe modify `README.md` as you feel is under/over-fitting optimum. Happy coding!

**Comment by dandavison** [comment]
OK, thanks, I'll make sure it's clear!
