### ISSUE TITLE
🚀 --quit-if-one-screen is always appended to the pager

### ISSUE THREAD

**Issue by TwoFinger** [dandavison/delta#568]
I've arrived at a workflow involving `delta.navigate` and nested less(1) instances that I like, but the `--quit-if-one-screen` option ruins it for me. Setting the pager via DELTA_PAGER, LESS, or lesskey(1) didn't help, as it seems the option is always appended.

My workflow is as follows.
Since running `git log -p` can be distracting with larger commits, I wished I could start with `git log`, and only if I'm interested in a particular commit, run `git show` on it (without leaving or suspending git log). This is a pretty baseline feature for git GUI clients.
The way I did it was to put a simple shell script in my `$PATH`, called `gos`:
```sh
head -1 | strings | cut -d' ' -f2 | xargs git show
```
This script is invoked from within `git log`'s less(1) instance via a tmux(1) shortcut
```tmux
bind g send |\ngos\n
```
For it to work properly the commit you want to inspect must be at the top line of the screen (`delta.navigate` makes this easy).
Then, pressing `C-bg` takes you to another less(1) instance, this time part of `git show`.
You can scroll around, and when you finish, you press `q<Enter>`, and you are back to where you were in `git log`.
So far so good, but if the commit you wanted to inspect was shorter than your screen, two issues arise:

- the output of _both_ `git log` and `git show` is visible on the screen, and it's hard to see where one ends and the other starts.
- if you press `q<Enter>` by habit, you will quit `git log`, because `git show` was already gone.

Is there a way to disable `--quit-if-one-screen` for delta?

**Comment by dandavison** [comment]
Hi @TwoFinger, this is really interesting. I hadn't thought of using tmux as the channel for capturing the key input here, but I've certainly wondered about how we can add functionality to delta given that it is not a TUI app.

Just quickly: does passing `--paging=always` to delta solve it?

**Comment by TwoFinger** [comment]
@dandavison The `--paging=always` solved it indeed!
The first issue with the mixed output was still there, but I handled it by adding `--clear-screen` to less(1).

Thanks a lot! I wouldn't have found this myself.

**Comment by TwoFinger** [comment]
TIL, git allows for choosing a pager per command:

```gitconfig
[core]
        pager = delta
[pager]
        show = delta --paging=always
```

(I previously set `core.pager` to `delta --paging=always`, but it affected all commands and having to quit often was annoying.)

**Comment by dandavison** [comment]
> TIL, git allows for choosing a pager per command:

Thanks for that @TwoFinger, I actually went changed the recommended delta configuration instructions to use the per-command pagers. See https://github.com/dandavison/delta/pull/610

**Comment by MrMino** [comment]
@dandavison Is it possible to pass this via an environment variable? I'd like to subprocess a `git show`, have it always use the pager, and preserve user's settings - without having to parse them, or modify them on the fly.

**Comment by dandavison** [comment]
Hi @MrMino, yes, how about something based on

```
git -c core.pager=delta --whatever show
```

or

```
git -c pager.show=delta --whatever show
```

Note that delta has `--no-gitconfig` if you need to run a one-off command without having you git config influence it.

**Comment by dandavison** [comment]
You could also use the `GIT_PAGER` env var, but the `git -c` versions might be more ergonomic.

**Comment by MrMino** [comment]
I meant the `--paging=always` option to Delta itself. I'm building a TUI wrapper around some git commands, and I need to preserve user's config. I cannot assume usage of any particular pager, my current strategy is to speculatively add environment variables to make each work nicely with my app.

So for Less I'm augmenting the value of `LESS` variable, and for Delta I'm currently resorting to changing `DELTA_PAGER`, but that is undesirable since it's might override user's setting.

**Comment by MrMino** [comment]
@dandavison would you consider implementing `DELTA` environment variable, with which the user would be able to provide additional settings or override the default ones?

**Comment by Daghall** [comment]
I want to have the paging set to automatic when working in the terminal, but when invoked from `tig` I need the output to always be paginated, so I need to override it in only this case.

I could not get any of these to work:
```
git -c delta.paging=always show
git -c core.pager="delta --paging always" show
git -c pager.show="delta --paging=always" show
DELTA_FEATURES=+"paging=always" git show
```
`.gitconfig`:
```
[core]
  pager = delta --paging always
[delta]
  paging = "always"
```

The only thing that worked for me was:
```
git show | delta --paging always
```
---
macOS Sonoma 14.3 (23D56)

```
$ less --version
less 581.2 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by dandavison** [comment]
@Daghall can you try using `DELTA_PAGER` to control the options you want to send to `less`? E.g. `DELTA_PAGER='less -FRS` etc. Delta also respects the `LESS` env var. https://dandavison.github.io/delta/environment-variables.html


> DELTA_FEATURES=+"paging=always"

This is invalid usage of `DELTA_FEATURES` (and I'm not sure `DELTA_FEATURES` will help mwith what you want). It holds a comma-separated list of "feature" names, such as `line-numbers`, `side-by-side`, or your own custom features. See https://dandavison.github.io/delta/features-named-groups-of-settings.html

**Comment by Daghall** [comment]
@dandavison, I can't get it to work with `DELTA_PAGER` either. The `-F` flag seems to stick somehow, with the combination of `git` and `delta`.

`less -F` on a small file quits. `\less` on the same file doesn't. 🤷 

`LESS` is not set, `PAGER` is set to `less`. `less` is aliased to `less -R`.

I found a workaround that is acceptable. Thank you for your time and suggestions, and for the excellent work on this project, that I use every day! 🙏
