### ISSUE TITLE
🐛 Delta gets confused when highlighting some Python classes with block comments

### ISSUE THREAD

**Issue by radupotop** [dandavison/delta#577]
## What happens

Delta gets confused when highlighting some diffs involving Python classes where multi-line/block comments are used.
It seems like the syntax highlight algorithm considers the comment to be the code and the code to be the comment, resulting in a muted highlight colour for the code, and a bright highlight for the comments.

The following picture illustrates this bug:

![image](https://user-images.githubusercontent.com/54769/116115919-7c04a200-a6b2-11eb-920b-e89f11dcd2fa.png)

## What should actually happen

The comment should have the muted colours and the code should have the bright syntax highlight.

## Steps to reproduce:

    git clone git@github.com:radupotop/deltabug.git
    git -c pager.show=delta show HEAD

Edit: this is `delta 0.7.1`

**Comment by dandavison** [comment]
Hi @radupotop, thanks for this! I definitely agree with your analysis. We actually already have an issue open for this, so let's discuss there https://github.com/dandavison/delta/issues/117. I'm always open to suggestions and PRs.
