### ISSUE TITLE
Patch file generation🚀 

### ISSUE THREAD

**Issue by liamwarfield** [dandavison/delta#578]
It would be nice to have a `--patch` or `--patch-file` option that outputs a patch file.

**Comment by dandavison** [comment]
Hi @liamwarfield, thanks. What functionality would you want to add over that provided by git? (To prevent git from using delta, just redirect output to file).

**Comment by liamwarfield** [comment]
This more for other scm. Currently I have delta hooked up to perforce by piping perforce's output into delta. Perforce does patching via old fashioned diff patches. This means that I have to change a config file when ever I want to give a patch to a coworker. It would be nice to either have `--patch` to output a patch file, or something like `--noop` to leave input stream unaltered.

**Comment by dandavison** [comment]
That sounds really interesting. I've never used Perforce. If you have time, it would be great to have a few sentences describing how to get delta to display Perforce output, so I can add it the to README. (As a comment here would be great, but you're welcome to open a PR against the README also).

> It would be nice to either have `--patch` to output a patch file, or something like `--noop` to leave input stream unaltered.

delta has `--raw` which promises to leave the input unchanged. Does that do what you need?

**Comment by liamwarfield** [comment]
🤦, My bad

**Comment by dandavison** [comment]
No worries, the delta `--help` output is a tiny bit verbose :)

**Comment by noboruma** [comment]
For those wondering how to achieve that with `git`, simply use: `git --no-pager diff`
