### ISSUE TITLE
🐛 Doesn't behave properly when using any pager variable apart from `DELTA_PAGER`

### ISSUE THREAD

**Issue by smac89** [dandavison/delta#582]
I have `PAGER` set to `less`, and `LESS` is set for less options (`-g -i -M -N -S -R -w -z-4`).

When I run `git log` or `git diff`, the output is not cleared from the screen. Even if I do `DELTA_PAGER="/usr/bin/less"` the output is still not cleared from the screen after running any of the git commands i mentioned.

Not even doing `PAGER="/usr/bin/less $LESS"` works to clear the output, even though you can see that there is no `-X` option supplied in `LESS` environment variable.

The only thing that works is when I set `DELTA_PAGER` to the full command-line used by less: `DELTA_PAGER="/usr/bin/less $LESS"`.

This seems like a regression, because this is my first time noticing this and I've been using delta for a while now.

**Comment by dandavison** [comment]
Hi @smac89, sorry this is being a pain. Delta actually uses code from bat for invoking the child pager process, and so I believe that you'll see similar  behavior if you use bat. As you can see, the code does involve magically injecting the `--no-init` (`-X`) argument under certain circumstances:

https://github.com/dandavison/delta/blob/5ece1944f1a7df30d342452d7a85d4871c16a42c/src/bat_utils/output.rs#L93-L110

 I'd like to not have to do this, but I know the bat project will have thought carefully through these issues. Nevertheless, it is tempting to just not support old versions of less and not do call less and parse its help text at run time.

In any case, I wonder why this has changed recently for you. Could you confirm the less version that delta is seeing when invoked by git? (Perhaps the most bulletproof test of that is something like `git -c core.pager='less --version' show`)

**Comment by TwoFinger** [comment]
Not OP, but on my machine Delta doesn't use the alternate screen either. And I don't even use the `*PAGER` variables, just `core.pager` in my ~/.gitconfig.

Since my less(1) is very recent, I assumed that `retrieve_less_version` itself might be wrong. I changed the `None` leg of the above code to `"--yes-init"` and on the next Delta invocation, less(1) complained that there is no such option. So, for some reason (I don't know Rust) it really can't get the version. My `less --version` output is `less 581.2 (PCRE2 regular expressions)`.
Maybe the dot in the version is the issue?

**Comment by tpoliaw** [comment]
Just come across this as well. Setting DELTA_PAGER works but neither BAT_PAGER or PAGER do. From looking at the [less release history](http://greenwoodsoftware.com/less/index.html), 591.2 seems to be the only point release version.

Looks like the retrieve version method will fail to parse a `usize` from a dot version. 
https://github.com/dandavison/delta/blob/5ece1944f1a7df30d342452d7a85d4871c16a42c/src/bat_utils/less.rs#L8-L16

Maybe changing the find regex to `'\s|\.'` would work?

**Comment by tpoliaw** [comment]
NB, bat has had the same problem: https://github.com/sharkdp/bat/commit/91a347bf6d549ba543f1b4bfdc2a05f269c975c8
