### ISSUE TITLE
🐛 Added/removed empty lines are shown the same as unchanged empty lines

### ISSUE THREAD

**Issue by SimonSapin** [dandavison/delta#593]
In this example, it looks like nothing has changed:

<img src=https://user-images.githubusercontent.com/291359/117321843-c42f7b80-ae8d-11eb-9a37-1bca05afd4ad.png width=600>

Adding `line-numbers = true` helps understand what’s going on:

<img src=https://user-images.githubusercontent.com/291359/117322173-0eb0f800-ae8e-11eb-84c6-bc963ee5620b.png width=600>

… but the first screenshot is missing critical information. A possible fix might be to extend the background color of added/removed lines to the entire width of the terminal.

<details>
<summary>Raw diff</summary>

```diff
diff --git a/rust/hg-core/src/dirstate/dirstate_map.rs b/rust/hg-core/src/dirstate/dirstate_map.rs
--- a/rust/hg-core/src/dirstate/dirstate_map.rs
+++ b/rust/hg-core/src/dirstate/dirstate_map.rs
@@ -14,11 +14,11 @@ use crate::{
     CopyMap, DirsMultiset, DirstateEntry, DirstateError, DirstateMapError,
     DirstateParents, StateMap,
 };
+
 use micro_timer::timed;
 use std::collections::HashSet;
 use std::iter::FromIterator;
 use std::ops::Deref;
-
 #[derive(Default)]
 pub struct DirstateMap {
     state_map: StateMap,
```
</details>

**Comment by th1000s** [comment]
Indeed, and this should be fixed soon. See [this commit](/th1000s/delta/commit/b70612d6bfbb2a5035623f81ad9a704120787b7d) which is currently part of the WIP side-by-side-wrapping feature.

**Comment by dandavison** [comment]
Hi @SimonSapin, thanks for this and sorry to be slow. I believe this is fixed in master:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/130340242-cd92954a-0ae3-437b-afdf-ba1b18b7e5ab.png" alt="image" /></td></tr></table>
