### ISSUE TITLE
🐛 sometimes exits without showing anything

### ISSUE THREAD

**Issue by ahmetb** [dandavison/delta#601]
I am noticing some `git diff` our `git config -l` commands exit without showing anything on the screen.

Install method: macOS Homebrew.

git config:
```
credential.helper=osxkeychain
gpg.program=gpg
core.pager=delta
core.editor=vim
core.excludesfile=/Users/ahmetb/.gitignore_global
interactive.difffilter=delta --color-only --width 100
diff.colormoved=default
delta.features=line-numbers decorations
delta.whitespace-error-style=22 reverse
delta.decorations.commit-decoration-style=bold yellow box ul
delta.decorations.file-style=bold yellow ul
delta.decorations.file-decoration-style=none
delta.decorations.syntax-theme=Dracula
delta.decorations.plus-style=syntax #003800
delta.decorations.minus-style=syntax #3f0001
commit.gpgsign=true
sequence.editor=interactive-rebase-tool
```

raw diff:

```
diff --git a/themes/bootstrap/layouts/home.html b/themes/bootstrap/layouts/home.html
index 54dcf1d..eceed29 100644
--- a/themes/bootstrap/layouts/home.html
+++ b/themes/bootstrap/layouts/home.html
@@ -131,6 +131,8 @@
                     </li>
                 </ul>
 
+                <blockquote class="twitter-tweet" data-dnt="true"><p lang="en" dir="ltr">From GitHub to Twitter <a href="https://twitter.com/ahmetb?ref_src=twsrc%5Etfw">@ahmetb</a> is who you should be following for all things Kubernetes and Google Cloud. Ahmet is extra dope and someone I respect deeply for his engineering and human skills. <a href="https://t.co/FV5lPRW8q1">https://t.co/FV5lPRW8q1</a></p>&mdash; Kelsey Hightower (@kelseyhightower) <a href="https://twitter.com/kelseyhightower/status/1103139066416111616?ref_src=twsrc%5Etfw">March 6, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
+
                 <h2>Previous work</h2>
                 <p>
                     I worked at Microsoft Azure from 2012 to 2016. I delivered
```

Piping diff/config commands to |cat shows them, so I am inclined to think something is wrong with delta.

This only happens sometimes (I think when diff is small). Also, sometimes it almost does something on the screen for a split millisecond and goes away immediately.

**Comment by dandavison** [comment]
Hi @ahmetb, delta doesn't have any problem displaying that diff for me:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/118912335-a3d3d800-b8f5-11eb-9dc1-f08f0db90cc2.png" alt="image" /></td></tr></table>

I don't think there's a bug in delta here. I wonder if it's your version of less. What's your less version? If you're using `/usr/bin/less`, can you try installing the newer one from Homebrew?

**Comment by ahmetb** [comment]
```
 less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman
```

everything is up to date with homebrew. I also have `LESS=-R` and `PAGER=less` env vars set.

**Comment by ahmetb** [comment]
It seems `LESS=-R` is the culprit. Unsetting that works. Any ideas why -R is not supported?

I use other printing tools e.g. `bat` and I set its pager to `less -RF` so that I can have mouse wheel scrolling.

**Comment by dandavison** [comment]
`-R` is definitely supported -- it's essential for less to display the ANSI color sequences. I'm not sure exactly what's going on in your case but the less version you have is old, I think it's the system less supplied with your Mac (does `which less` say `/usr/bin/less`?). Can you install less from homebrew? You'll get v581.2. I'm on a Mac also:
```
delta(583-file-mode) /usr/bin/less --version | head -n1 
less 487 (POSIX regular expressions)
delta(583-file-mode) /usr/local/bin/less -V | head -n1  
less 581.2 (PCRE regular expressions)
```

**Comment by ahmetb** [comment]
```
# which less
/usr/bin/less
```

so I installed less from homebrew (I actually mostly replace bsd ones with GNU coreutils, but I didn't have "less").

After switching to GNU less, the problem disappeared.

```
# less --version
less 581.2 (PCRE regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by dandavison** [comment]
OK, excellent, glad to hear it's solved!
