### ISSUE TITLE
Light grey on bold green is unreadable on some terminals🐛 

### ISSUE THREAD

**Issue by jyn514** [dandavison/delta#608]
Delta by uses light grey on bold green for "added text within a new line". This is very difficult to read on the default mingw terminal (used by Git Bash on Windows).

![image](https://user-images.githubusercontent.com/23638587/119182955-6b411500-ba41-11eb-8257-bac47f2ebe0a.png)

**Comment by jyn514** [comment]
For comparison, this is what `diff` looks like:
![image](https://user-images.githubusercontent.com/23638587/119183504-2e295280-ba42-11eb-8aab-0c46914974fa.png)

**Comment by dandavison** [comment]
Hi @jyn514, I agree that's unreadable. To clarify discussion, in delta, the foreground colour (the light grey here) comes from the syntax theme (which delta chooses to be "Monokai Extended" by default) whereas the background colours come from delta itself. The problem you've highlighted relates to the colours used by the syntax theme for comments, but in general the problem that delta has to solve is finding a combination of  syntax theme and background colours such, for every syntactic category (function names, strings, comments, etc), the foreground colour assigned by the syntax theme looks good against every possible background colour (minus, minus-emph, zero, plus, plus-emph). Furthermore, delta needs to make this election once for dark terminal backgrounds ("dark mode") and once for light terminal backgrounds ("light mode").

If anyone has any ideas about a syntax theme that would make a better dark mode default choice than Monokai Extended, or about default background colours, those would be welcome. In general, I have found that this is much harder to solve for dark terminal backgrounds than for light. E.g. here we can see the two emph colours doing fine on a comment line, and in fact I'm not aware of bad clashes for any syntactic categories in light mode.

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/119185138-69c51c00-ba44-11eb-8045-f2d0004faf07.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
Let's discuss at https://github.com/dandavison/delta/issues/481, of which I think we can consider this is a duplicate.
