### ISSUE TITLE
🐛 Support diffs of unmerged path

### ISSUE THREAD

**Issue by bew** [dandavison/delta#609]
These can happen when doing rebases.
I don't have much time now for reproducible steps, but if you need them I can add them a bit later!

For unmerged paths, the diff uses 2 columns for `- +` symbols.
At first glance I don't see a way to detect this in advance (unless you're doing `git status --porcelain` before (I don't know), you'll see `UU` as a status).

Here is what is looks like in delta:
![image](https://user-images.githubusercontent.com/9730330/119205778-850e4680-ba99-11eb-8992-746d39fc768e.png)
Notice all the `-`

The plain git diff looks like: (cut horizontally because the rest is _easy to guess_)
![image](https://user-images.githubusercontent.com/9730330/119205878-c999e200-ba99-11eb-9dfb-6c2b9864e48f.png)

**Comment by phil-blain** [comment]
This seems to be a duplicate of #189 (`git diff` with conflicted files does in fact `git diff --cc`, see [my comment on that issue](https://github.com/dandavison/delta/issues/189#issuecomment-747745163)).

**Comment by bew** [comment]
Indeed, it is the same, with more details, thanks, let's close this one and I'll follow the other one!
