### ISSUE TITLE
🐛 Newline preceding hunk header breaks interactive commands

### ISSUE THREAD

**Issue by wmedlar** [dandavison/delta#611]
Unless `hunk-header-style = raw` delta will print a newline preceding the diff hunk header, breaking interactive commands.

<img width="600" alt="Screen Shot 2021-05-24 at 7 35 52 PM" src="https://user-images.githubusercontent.com/5326769/119431572-ace2f180-bcc7-11eb-848a-d92f45ccd3d3.png">

My delta config:

```gitconfig
[core]
	pager = delta
[delta]
	file-style = raw
	file-decoration-style = omit
	hunk-header-style = syntax line-number
	hunk-header-decoration-style = omit
	line-numbers = true
	minus-style = syntax
	zero-style = dim syntax
[interactive]
	diffFilter = delta
```

I don't use `diffFilter = delta --color-only` because I like the line numbers in `git add -p`.

**Comment by dandavison** [comment]
Hi @wmedlar, thanks for this. To have line numbers with `git add -p` we just set `line-numbers = true` as usual, in conjunction with `diffFilter = delta --color-only`. Does that work for you?

`--color-only` is a hard requirement for `git add -p`. It might not be the best name, but it's behind this setting that we've implemented all the logic for keeping lines in one-to-one correspondence with the raw diff.

**Comment by wmedlar** [comment]
`--color-only` retains the +/- prefix in addition to coloring lines, is there a way to disable the +/- ? Ultimately that's what I'm hoping to accomplish.

**Comment by dandavison** [comment]
Yep! There's `keep-plus-minus-markers = false`.

**Comment by wmedlar** [comment]
I thought I tried this but it looks like I was mistaken. It's working great, thank you!
