### ISSUE TITLE
🐛 Colors are stripped from Git's `--decorate` flag

### ISSUE THREAD

**Issue by zx8** [dandavison/delta#622]
When running `git show` or `git diff`, the branch colors in the very first line are not preserved with `delta`, but are with `diff-so-fancy`:

i.e. take the following commit:

```
commit ff2be4d73546f7b9e44bcd1212b444b955ec28eb (HEAD -> master, origin/master)
```

and run `git show ff2be4d73546f7b9e44bcd1212b444b955ec28eb`:

### `delta`

![image](https://user-images.githubusercontent.com/8544900/120454432-ca7d1e80-c38b-11eb-9928-7ef333a6ae03.png)

### `diff-so-fancy`

![image](https://user-images.githubusercontent.com/8544900/120454383-bcc79900-c38b-11eb-8479-e72857da0ebe.png)

---

How can I maintain these colours with `delta`? I'm using the `diff-so-fancy` emulation mode:

```ini
[delta]
    diff-so-fancy = true
    relative-paths = true
```

**Comment by dandavison** [comment]
Hi @zx8, I think that `commit-style = raw` is what you're looking for.

**Comment by zx8** [comment]
That fixed it!

And yeah, I think it makes sense to make it the default for `diff-so-fancy` mode. 👍

**Comment by dandavison** [comment]
> And yeah, I think it makes sense to make it the default for diff-so-fancy mode. 👍

Right, that's done in #623. (It may be a little slow to be released since there was  a recent release)
