### ISSUE TITLE
❓ Aligning color output between environments

### ISSUE THREAD

**Issue by eddy-geek** [dandavison/delta#624]
Sorry if it does not belong here, I do think we can at least improve documentation in the [truecolor](https://github.com/dandavison/delta#24-bit-color-truecolor) section.

I am having trouble trying to align colors between 2 machines/envs (host on the left, and ssh guest on the right)

![image](https://user-images.githubusercontent.com/2772505/120647109-86b51280-c47a-11eb-8c66-abe3bae670d5.png)
As you see the host on the left is darker.

I am using this command `delta --no-gitconfig --theme='Solarized (dark)' --plus-style='syntax "#004000"' --plus-non-emph-style='syntax "#004000"'` but the difference also exists with the default theme.
I am trying to bypass any pager differences with `LESS='' PAGER=cat`.

I did investigate the 24-bit support with the following commands, and it seems the same (screenshot)

```sh
24-bit-color.sh
term-colors.pl
echo $TERM
( export PAGER=cat ; export LESS='' ; git diff master^^ master^ | delta --no-gitconfig --theme='Solarized (dark)' --plus-style='syntax "#004000"' --plus-non-emph-style='syntax "#004000"' | head -n20 )
```

( and the top one is the awk snippet from https://github.com/tmux/tmux/issues/696 )
![image](https://user-images.githubusercontent.com/2772505/120647530-fdeaa680-c47a-11eb-9673-5aa5e9a924da.png)

I'm using some differing zsh setup but bash gives the same result.

I think either I'm forgetting some important env variables, or there are some terminfo database differences I need to dig into (`TERM=xterm-256color` on both sides) -- which is where I'd welcome help.

**Comment by eddy-geek** [comment]
hmmm... I am now unable to reproduce outside of tmux (which clearly has specific issues documented elsewhere)

it seems the issue somehow "leaked" outside of a tmux session which baffles me... sorry for the noise

**Comment by dandavison** [comment]
Hi @eddy-geek, OK, great. I was thinking about it but hadn't come up with any ideas!
