### ISSUE TITLE
🚀 don't omit context lines if it produces more lines

### ISSUE THREAD

**Issue by HarHarLinks** [dandavison/delta#629]
I noticed when a diff is split into hunks, the header is actually so large (newline, 2 box lines, description) that it is bigger than simply showing the omitted context lines:
```
Δ .config/htop/htoprc

──────┐
Δ :1: │
──────┘
 1  ⋮ 1  │# Beware! This file is rewritten by htop when settings are changed in the interface.
 2  ⋮ 2  │# The parser is also very primitive, and not human-friendly.
 3  ⋮    │fields=0 48 17 18 38 39 40 2 46 47 49 1
    ⋮ 3  │fields=0 48 17 18 38 39 40 2 46 47 49 1
 4  ⋮ 4  │sort_key=46
 5  ⋮ 5  │sort_direction=1
 6  ⋮    │hide_threads=1
    ⋮ 6  │tree_sort_key=0
    ⋮ 7  │tree_sort_direction=1
 7  ⋮ 8  │hide_kernel_threads=1
 8  ⋮ 9  │hide_userland_threads=1
 9  ⋮ 10 │shadow_other_users=0

───────────────────────────┐
Δ :13: show_program_path=1 │
───────────────────────────┘
 12 ⋮ 13 │highlight_base_name=0
 13 ⋮ 14 │highlight_megabytes=1
 14 ⋮ 15 │highlight_threads=0
    ⋮ 16 │highlight_changes=0
    ⋮ 17 │highlight_changes_delay_secs=5
    ⋮ 18 │find_comm_in_cmdline=1
    ⋮ 19 │strip_exe_from_cmdline=1
    ⋮ 20 │show_merged_command=0
 15 ⋮ 21 │tree_view=0
```

In this example, the `Δ :13:` header takes twice the space than just showing lines ` 10 ⋮ 11` and ` 11 ⋮ 12`.
Running plain old `git diff` also omits the same 2 lines, but the hunk header is only 1 line.

In my opinion, it would be less confusing to just print the context here. Currently I need to check okay what does this reference, oh I'm here already, and even lose some space unnecessarily.

Can delta check for such a case and decide to just print the context instead of splitting a hunk? Based on the current theme/settings?

**Comment by dandavison** [comment]
Hi @HarHarLinks, sorry to be slow replying here.

> Can delta check for such a case and decide to just print the context instead of splitting a hunk?

All delta has is the diff on standard input that git is sending it: delta does not currently try to locate the original file on disk (and indeed such a file might not exist as someone might just be piping imaginary diffs to delta), so it can't retrieve the missing lines unless they are in the git output.

I wonder whether a solution that would appeal to you might be found by adjusting git's hunk algorithm? E.g. https://stackoverflow.com/questions/59270198/how-to-get-better-hunks-in-git-add-interactive-patch-mode
https://stackoverflow.com/questions/33891010/can-i-modify-git-adds-default-hunk-size/33891676

And of course there are various ways to configure delta to emit a one-line hunk header (using `raw`, removing the box decoration, etc).

**Comment by HarHarLinks** [comment]
Sounds about right, and of course this is very niche.

You second link talks about `diff.interCunkContext`. This can also set per call on the command line.
Specifically, in the above example, `git diff --inter-hunk-context=2` is sufficient to fuse the hunks since there are 2 lines omitted. I suppose that would mean with my 4 line hunk header, `git diff --inter-hunk-context=4` should always work.

As far as I understand, delta gets run by (i.e. after) git diff itself. Is it possible to hook in somehow to supply that command automatically? Alternatively it could of course be set manually in .gitconfig, which I am doing for now. Perhaps it could only be mentioned alongside the other delta install/config instructions.

**Comment by dandavison** [comment]
> As far as I understand, delta gets run by (i.e. after) git diff itself. Is it possible to hook in somehow to supply that command automatically?

It's right that delta gets run as a child process of git, so delta can't change the git invocation.

> Alternatively it could of course be set manually in .gitconfig, which I am doing for now.

I'm not sure if it helps but another option is to use `git -c` which would allow you to create a (shell or git) alias for use with delta

```
git -c diff.interHunkContext=4 diff
```

I'll close this one now since I think we're not planning changes to delta.
