### ISSUE TITLE
side-by-side option only works when piping🐛 

### ISSUE THREAD

**Issue by salmankhilji** [dandavison/delta#631]
`delta` 0.8 breaks the `--side-by-side` option when directly comparing files A and B (without any `git`).  The option works correctly when `diff` output is piped to `delta`, but invoked directly on files A and B, `delta` seems to ignore the `--side-by-side` option.

```
$ diff -u <(seq 5) <(seq 10) | delta --side-by-side

comparing: /dev/fd/63 ⟶   /dev/fd/62
───────────────────────────────────────────────────────────────────────────────

───┐
3: │
───┘
│ 3  │3                                │ 3  │3
│ 4  │4                                │ 4  │4
│ 5  │5                                │ 5  │5
│    │                                 │ 6  │6
│    │                                 │ 7  │7
│    │                                 │ 8  │8
│    │                                 │ 9  │9
│    │                                 │ 10 │10
precor@byteevo-scm:~/Scratch$ seq 5 >a
precor@byteevo-scm:~/Scratch$ seq 10 >b
precor@byteevo-scm:~/Scratch$ delta --side-by-side a b

a ⟶   b
───────────────────────────────────────────────────────────────────────────────

───┐
3: │
───┘
3
4
5
6
7
8
9
10
```
![Screenshot from 2021-06-12 10-07-58](https://user-images.githubusercontent.com/40219235/121783893-26069380-cb66-11eb-904e-60aef7b29d2d.png)

**Comment by dandavison** [comment]
Thanks @salmankhilji! That should be fixed by https://github.com/dandavison/delta/pull/632.

**Comment by salmankhilji** [comment]
Thanks!  When will be the next patch release?

**Comment by dandavison** [comment]
I'm not sure when the next release will be, but I believe you could work around the bug by setting the `GIT_PAGER` env var to `delta --side-by-side`.

**Comment by dandavison** [comment]
This has been released in 0.8.1

**Comment by rbutoi** [comment]
Is this the same problem?
```
❯ delta <(seq 5) <(seq 10)

proc/self/fd/12 ⟶   proc/self/fd/14

───┐
1: │
───┘
│ 1  │pipe:[62420208]                                                  │    │
\ No newline at end of file
│    │                                                                 │ 1  │pipe:[62420209]
\ No newline at end of file
```

My workaround is to use a wrapper like `diff() { /usr/bin/diff -u "$@" | delta --side-by-side; }`

**Comment by dandavison** [comment]
Hi @rbutoi, your error is not this one but rather #626. Diffing using shell process substitution syntax doesn't work because delta uses `git diff` for diffing, and git doesn't support it (although patches have been proposed). See https://github.com/dandavison/delta/issues/626#issuecomment-855532012 So I don't currently see a way to fix this, other than to help out with the git development process and get it fixed there.
