### ISSUE TITLE
🚀 Review GitHub PRs and what they change in delta

### ISSUE THREAD

**Issue by Milo123459** [dandavison/delta#635]
Hi, thanks for contributing to Delta, please go ahead and describe your proposal!

Idea: Be able to type `delta pr owner/repo#123` and get the files that the PR changes and display them.

**Comment by dandavison** [comment]
Hi @Milo123459, thanks! I agree this is a useful thing to be able to do, and in fact we can already do this right now, using https://github.com/cli/cli:

```
gh config set pager delta
gh pr diff 515
```

Plus lots of other things one can do with `gh`: https://cli.github.com/manual/

There definitely might be other CLI tools out there that would be worth mentioning in this thread, but for now that's my recommendation for delta users.

**Comment by Milo123459** [comment]
Cool! Sorry for making an issue.

**Comment by dandavison** [comment]
No problem, thanks for the suggestion.
