### ISSUE TITLE
CentOS support 

### ISSUE THREAD

**Issue by zoulja** [dandavison/delta#637]
Seems Delta supports a lot of minor distros, but not very popular Centos(as it not even listed)
Static binary fails to run on Centos 7 with the following error:
`./delta: /lib64/libc.so.6: version GLIBC_2.18 not found (required by ./delta)`

**Comment by dandavison** [comment]
Hi @zoulja, thanks. Let's try to get this working. I'm not very knowledgable about the issues here but could you try the musl-linked executable to start off with:

https://github.com/dandavison/delta/releases/download/0.8.0/delta-0.8.0-x86_64-unknown-linux-musl.tar.gz

I'm assuming the one you tried first was this:
 
https://github.com/dandavison/delta/releases/download/0.8.0/delta-0.8.0-x86_64-unknown-linux-gnu.tar.gz

If that doesn't work then perhaps the thing to do would be to contact people involved in centOS packaging.

**Comment by zoulja** [comment]
Thanks @dandavison musl version worked

**Comment by dandavison** [comment]
OK, great. I'll close this then, although that's not meant to imply that getting it into CentOS package repositories wouldn't be worthwhile.
