### ISSUE TITLE
Delta uses less so that it doesn't clear screen afterwards

### ISSUE THREAD

**Issue by dimonomid** [dandavison/delta#652]
Normally, `less` clears the screen on exit. There is an option to disable it: `less -X` would leave the output after exiting, but default behavior is to clear screen.

Apparently, `delta` always invokes `less` so that the screen is not cleared (I don't know if it uses `-X` for that), and it breaks my workflow.

Would be nice to have an option to disable that behavior. I apologize if there is an option for that, but I didn't find it in `delta --help`.

**Comment by dandavison** [comment]
Hi @dimonomid, there are a few ways to do this.

Firstly,

> Apparently, delta always invokes less so that the screen is not cleared

Delta does not do this for recent versions of `less`. Specifically, if you have less >=530 (or >=558 on Windows) then it will not do it. However, there was a bug in delta related to less parsing, so you must also be using delta >= 0.8.0

So one way to fix this for you might be to use a more recent version of `less`.

Beyond that, if you specify the less process options explicitly, delta also will not do this. You can specify the less command via the `DELTA_PAGER` env var, or the `delta --pager` command line option (equivalently `pager = less --whatever` in gitconfig).

**Comment by dimonomid** [comment]
Thanks @dandavison, very helpful! This did the trick for me

```bash
export DELTA_PAGER="less $LESS"
```

**Comment by dandavison** [comment]
Great, glad to hear that worked.
