### ISSUE TITLE
Checksum missmatch for 0.0.15 on MacOS

### ISSUE THREAD

**Issue by tnyblom** [dandavison/delta#66]
$ brew install dandavison/delta/git-delta
==> Installing git-delta from dandavison/delta
==> Downloading https://github.com/dandavison/delta/releases/download/0.0.15/delta-0.0.15-x86_64-apple-darwin.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/193526915/e4129e00-160e-11ea-97ce-b
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: a6df3b6d3a3698997dc84ddfe8d8880493524549138b18b9c9a48aa43c5b716f
  Actual: d99153513940b2ce599a7913a8682403e507e2bf254abd50da560aae02f5329d

**Comment by dandavison** [comment]
Oops, thank you! Fixed.
