### ISSUE TITLE
Git diff shows wrong data🐛 

### ISSUE THREAD

**Issue by mortymacs** [dandavison/delta#661]
Hi,

Today, when I changed only one character in a file, I saw `git diff` show the wrong data. I saw it several times in different submodule directories. In the beginning, I thought maybe my editor did something, then I start using ydiff just to check what Delta shows is the same, then I realized that no, the data that Delta shows is wrong:

![image](https://user-images.githubusercontent.com/1261448/126083333-8197af0e-5ca9-40f5-8a39-7a3191dafc64.png)

Here, I only expect to see `pkgrel=2` as the changed line which `git --no-pager` shows the same as ydiff:

![image](https://user-images.githubusercontent.com/1261448/126083363-b4f90589-9e4d-4493-812e-9d2ef18e530d.png)

But Delta shows some other changes which I really don't have.

When I start executing `git diff` several times, then it could finally show the correct result which I expected:

![image](https://user-images.githubusercontent.com/1261448/126083580-5d6c8f6e-8928-4d76-bf7e-a8c630a40a0f.png)

Why couldn't show the correct diff at the beginning?

This is my system config:

Os: ArchLinux
Delta version: delta 0.8.3
My Git config:
```ini
[pager]
    diff = delta
    log = delta
    reflog = delta
    show = delta

[interactive]
    diffFilter = delta --color-only

[delta]
    features = side-by-side line-numbers decorations
    whitespace-error-style = 22 reverse
    line-numbers = true
    side-by-side = true
```

**Comment by dandavison** [comment]
Hi @mortymacs, hm, that is strange. Delta takes input from git on stdin, so running `git diff` with delta configured should be the same as running `git diff | delta`. Can you capture a raw diff (as plain text) that delta is displaying wrongly, and post it here? For example, when you see the wrong output from delta, do `git diff > mydiff.txt`. I can't think of a reason why you would see characters changed in delta output that aren't changed in the raw diff.

**Comment by dandavison** [comment]
Hi @mortymacs, I'm happy to help here if I can, but I'll close the issue for now. If you can post some instructions for  reproducing the bug that you saw then we can re-open it. But do feel free to carry on discussing even if it's closed.

**Comment by mortymacs** [comment]
Hi @dandavison ,
Thank you. I was thinking of closing the ticket as I couldn't reproduce it yet. But yeah, if I could reproduce it, then I'll come with details :wink:
