### ISSUE TITLE
🚀 [help] Is it possible to show branch names at top while using `git diff`?

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/delta#665]
I am sorry if this is already explained in documentation.

When I run ```git diff origin/master..dev```  I am getting following output, please see its head section.:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/18537398/126628444-b918f144-a764-4956-886e-fbd880c86f54.png">

==> Would it be possible to show `origin/master` and `dev` at the top section for its related file name? in order to remind me left hand side is `origin/master` and right hand side is `dev`?

**Comment by Kr1ss-XD** [comment]
Hi @avatar-lavventura - not exactly what you're asking for, but there are the `--src-prefix`/`--dst-prefix` options; maybe these would help ?  For example : 

```sh
git diff --src-prefix=REMOTE/ --dst-prefix=LOCAL/ origin/master..dev
```

**Comment by avatar-lavventura** [comment]
Now

```
git diff --src-prefix=REMOTE/ --dst-prefix=LOCAL/ origin/master..dev
```

shows:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/18537398/126752617-2453febb-d182-4b4a-abba-d7bf1f968e0e.png">

Instead of `REMOTE/broker/Driver.py ⟶   LOCAL/broker/Driver.py` Can it show the compared branch names, for example:

`MASTER/broker/Driver.py ⟶   DEV/broker/Driver.py`

**Comment by avatar-lavventura** [comment]
Thanks. I have to do something like: ```git diff --src-prefix=master/ --dst-prefix=dev/ dev..origin/master```

Having branch changes on the left hand side is less confusing :)

**Comment by dandavison** [comment]
Thanks @avatar-lavventura and @Kr1ss-XD, I agree that seems like the best solution. It would be hard for delta to automatically determine the labels, unless they are in the diff output it receives from git.

**Comment by avatar-lavventura** [comment]
```git diff --ignore-blank-lines --src-prefix=master/ --dst-prefix=dev/ dev..origin/master```

Output:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/18537398/126757608-cbc4a457-8f17-4767-b5ba-3e1a391cf226.png">

At top can ```master/broker/Driver.py ⟶   dev/broker/Driver.py``` shown as ```dev/broker/Driver.py -->master/broker/Driver.py``` in order to sync with having `dev` on the left hand side?

**Comment by dandavison** [comment]
This is git functionality, not delta: delta is just passing on what git is outputting. So if you are using `dev..origin/master` then you should use `--src-prefix=dev/` (because `dev` is your "source" branch) and `--dst-prefix=master/` (because `master` is now your "destination" branch)
