### ISSUE TITLE
🚀 Show Github commit hyperlinks even if remote URL does not contain `git@`

### ISSUE THREAD

**Issue by spaarmann** [dandavison/delta#667]
Hi! I was recently a bit confused why hyperlinks for commits were working in some of my local clones but not others.
After a bit of investigation I've figured out that it's caused by the remote URL being simply `github.com:user/repo` instead of `git@github.com:user/repo`, which is not matched by the current regex.

Now, this remote URL only works in the first place because of a custom SSH config containing something like this:
```
Host github.com
    HostName github.com
    User git
    IdentityFile <some key>
```

Considering that I fully understand if you'd prefer to not support such configs out-of-the-box. (You can also put anything into the `Host` portion there and have it still end up going to GitHub with configs like this and I imagine that parsing the SSH config or anything similar to make everything here work is definitely out of scope 😄 ).

Still, I figured specifically allowing omitting the `git@` is a pretty small change so I might as well ask (and I suspect this is at least a *somewhat* common config; I don't remember where I stole it, but I definitely got the idea from someone else).

**Comment by spaarmann** [comment]
(Fwiw, if you deem this to a feature you want included in the first place, I'd be happy to submit a PR adding it if that's useful :)

**Comment by dandavison** [comment]
Hi @spaarmann, we recently added this option:

```
        --hyperlinks-commit-link-format <hyperlinks-commit-link-format>
            Format string for commit hyperlinks (requires --hyperlinks). The placeholder "{commit}" will be replaced by
            the commit hash. For example: --hyperlinks-commit-link-format='https://mygitrepo/{commit}/'
```

Am I right in thinking that that can be used to solve this? (It takes precedence over the auto-recognizing of github URLs)

**Comment by spaarmann** [comment]
That could be used to make hyperlinks work but unless I'm missing something, I believe that would have to be configured for every repository / clone separately, because the custom format would have to include the `user/repo` part. The main advantage of tweaking the Regex is that it would work for every repository automatically.

**Comment by dandavison** [comment]
Yes, you're right. Ok, sure, it would be great if you're able to improve this regex!

**Comment by spaarmann** [comment]
Great! I'm about to go to bed, but I'll look at sending a PR tomorrow.
