### ISSUE TITLE
Navigate shortcuts conflict with `less` search shortcuts

### ISSUE THREAD

**Issue by OliverJAsh** [dandavison/delta#671]
The navigate shortcuts `n` and `N` conflict with the search shortcuts built in to `less` which are also `n` and `N`.

The navigate shortcuts work until I perform a search, at which point it's no longer possible to use the navigate shortcuts to navigate between files.

Perhaps we should use different shortcuts? Or is there a way to "exit" the search mode in `less` so that these shortcuts can work again?

**Comment by dandavison** [comment]
Hi @OliverJAsh, as you probably have inferred the `navigate` shortcuts in delta are implemented as standard `less` searches, and therefore the keybindings are the same. On the plus side, this means that the delta `navigate` search is in the `less` search history, so to return to `navigate` search you enter `/` followed by up arrow, and select the search that delta added behind the scenes (it will look like `^(commit|Δ|added:|removed:|renamed:)`).

**Comment by OliverJAsh** [comment]
Ahhh that makes sense, thanks!

**Comment by dandavison** [comment]
No problem. It's not perfect yet -- for example a normal less search done in delta will not be recorded in your normal less history. See https://github.com/dandavison/delta/issues/237 and https://github.com/dandavison/delta/blob/c2dc651678843c18287e7dab6e189b1f8eb4e123/src/features/navigate.rs#L49-L52
