### ISSUE TITLE
🐛  Hunk header prints ":" with no file or line number, even when hyperlinks are off

### ISSUE THREAD

**Issue by ynavott** [dandavison/delta#672]
This issue relates to the bug already discussed in #650. Since then. It was probably broken again by some newer commits. To demonstrate:

![broken-delta-hunk-header](https://user-images.githubusercontent.com/48953594/127354636-baeb248e-b17f-40cb-ba4d-f139df958977.png)

As you can see, both `file-modified-label` (it is set to ` [M] ` in this theme) and a `:` are printed before the hunk header, even though hyperlinks are off. The issue persists when hyperlinks are turned on, even though this bug was supposed to be fixed by #650.

**Comment by dandavison** [comment]
Hi @ynavott, thanks for this. Can you post the delta config that produces this behavior please?

**Comment by ynavott** [comment]
I am currently on vacation in the highlands of Iceland at the moment and don't have very good reception most of the time, will try to send you the exact config as soon as possible.

**Comment by dandavison** [comment]
Thanks @ynavott, are you sure that's your entire config? I'm only able to reproduce this by setting `hunk-header-style` to a value that does not include `line-numbers`. e.g.

```gitconfig
[delta]
    hunk-header-style = syntax
    navigate = true
```

For example, using the wooly-mammoth theme would have this effect, and it looks like you might be using that in your first screenshot?

**Comment by ynavott** [comment]
My apologies, I am indeed using that theme.
