### ISSUE TITLE
🚀 JS lib similar to delta / 🏗️ or maybe delta as a WASM library?

### ISSUE THREAD

**Issue by jasikpark** [dandavison/delta#675]
Howdy! I love delta, I'm looking for a JS library that you can use to get similar output like delta's with the nice block level syntax aware diffs that I can use in https://github.com/lukeed/uvu/issues/128

This is probably out of scope, since this is a rust project, but I figured I'd ask if y'all knew!

Thanks again, and keep up the hard work making and amazing tool!!!

**Comment by dandavison** [comment]
Hi @jasikpark, thanks! Would https://github.com/rtfpessoa/diff2html be helpful for your use case? Demo here: https://diff2html.xyz/demo.html
