### ISSUE TITLE
🚀 Avoid truncating lines on the right in side-by-side mode

### ISSUE THREAD

**Issue by ajeetdsouza** [dandavison/delta#679]
In side-by-side mode, delta usually fills up the entire screen, truncating the lines on both the left and the right sides.

IMO, it's unnecessary to truncate the line on the right side. If delta showed the whole line, I'd be able to press the right arrow key and see the entire line, which would be more useful IMO.

**Comment by dandavison** [comment]
Hi @ajeetdsouza, I understand what you're saying, but I'm not very attracted to the asymmetry between the left and right panels that it would entail. There are two positive things I'll point to. Firstly, the README contains this section (maybe you already saw it):

> Wide lines in the left or right panel are currently truncated. If the truncation is a problem, one approach is to set the width of Delta's output to be larger than your terminal (e.g. delta --width 250) and ensure that less doesn't wrap long lines (e.g. export LESS=-RS); then one can scroll right to view the full content. (Another approach is to decrease font size in your terminal.)

Secondly, @th1000s has an almost-ready branch which brings line wrapping to side-by-side mode, with quite sophisticated control over the details. See https://github.com/dandavison/delta/pull/515

I'm thinking that adding asymmetric non-truncated lines on the right doesn't seem like it fits with those two directions, so I'll close this for now, but feel absolutely free to continue the discussion!

**Comment by ajeetdsouza** [comment]
> one approach is to set the width of Delta's output to be larger than your terminal

This would mean a lot of left-right scrolling. Currently, when we truncate the line on the right, we show a truncation character. If we avoid truncating the line on the right, `less` itself would show a truncation character, but you'd also be able to scroll right and see what was truncated. The way I see it, this is just utilizing `less` in a better way -- it would add more functionality without taking anything away.

If you don't see it as a good fit, that's okay. Thanks for making this tool!
