### ISSUE TITLE
🐛 delta 0.8.3 leaves terminal in an inconsistent state on exit

### ISSUE THREAD

**Issue by abbeyj** [dandavison/delta#681]
This seems similar to #463, but can still be reproduced with delta 0.8.3.  Using CentOS 7, less version 458 from package less-458-9.el7.x86_64.

Run `delta` with no command line arguments.  It will print out the message:
```
The main way to use delta is to configure it as the pager for git: see https://github.com/dandavison/delta#configuration. You can also use delta to diff two files: `delta file_A file_B`.
```

It will exit and return to the shell, but the shell prompt will not be drawn.

When using `delta --paging=never`, the problem does not occur.

There seems to be a race condition  Sometimes this problem will occur the first time I run `delta`, but other times it will work correctly.  Running delta 3 or 4 times in a row will usually reproduce the problem.

Even more rarely, the terminal will be left with echo turned off  (like `stty -echo`).  This can be reproduced by running delta a bunch of times in a row, e.g.
```
for i in $(seq 1 100); do delta; done; echo Done
```

This will run delta 100 times, print out "Done" and then return to the shell.  But sometimes echo will be turned off and you will not be able to see what you're typing in your shell.

A possibly related problem happens when using Ctrl+C to exit delta.  Run `yes | delta` so that you are assured of having more than a page of output.  At the `less` prompt, press Ctrl+C.  Now `delta` will exit, and the shell prompt will be drawn.  But `less --RAW-CONTROL-CHARS --no-init --quit-if-one-screen` is still running in the background (reparented to pid 1).  The next keystroke is processed by `less`.  Trying a newer version of `less` (581.2, compiled from source), shows similar symptoms.  The command left running in the background is instead `less --RAW-CONTROL-CHARS --quit-if-one-screen`.  And now you're left on the terminal's "alternate screen" until less exits.  Then you're returned to the "normal screen".  Let me know if you'd prefer that I open a separate bug for this issue.

I think the root cause here might be the same.  You launch `less` but there are some situations where you do not wait for it to exit before exiting yourself.  I think the invariant needed here is that once the pager is started you cannot exit until it has exited.  I'm not sure of the best way to accomplish that.  It seems like any place that you use `process::exit` in the code is a place where this bug may potentially occur.  Any fatal signal would seem to have the same issue.  You could perhaps at least work around the Ctrl+C issue by ignoring `SIGINT`.

**Comment by Kr1ss-XD** [comment]
>Now delta will exit, and the shell prompt will be drawn. But less [...] is still running in the background (reparented to pid 1). The next keystroke is processed by less.

For ref.:
* This did also happen here, as I was reproducing #683, after sending SIGINT.

**Comment by thiagomg** [comment]
It also happened to me.

```sh
$ delta
The main way to use delta is to configure it as the pager for git: see https://github.com/dandavison/delta#configuration. You can also use delta to diff two files: `delta file_A file_B`.
$ ls
<redacted>
$ $ $ $ $ $ $ $ 
```

And then after the next command (ls), the terminal was broken.

**Comment by Kr1ss-XD** [comment]
>I believe that I've fixed the first bug (running delta with no arguments corrupts terminal) via #685.

Yes @dandavison - just rebuilt from master, and that one is fixed. :+1:

**Comment by thiagomg** [comment]
I built from source and it worked. Thanks much !!! (I am using Ubuntu 20.04.2 LTS)

**Comment by dandavison** [comment]
@thiagomg @Kr1ss-XD  Great!

And also following @abbeyj's suggestion, https://github.com/dandavison/delta/pull/686 makes delta ignore ctrl-c (SIGINT). This seems to fix the `yes | delta` followed by `ctrl-c` bug on Ubuntu in a docker container. If anyone would like to test that, the branch is named `handle-sigint`.

I need to refresh myself on exactly how this works. Perhaps someone could tell me where the following is wrong (@abbeyj ?).

I'm thinking that `less` itself is ignoring `SIGINT`, and thus the signal is propagated to the parent `delta` process, which prior to this change handled it by terminating itself, leaving the `less` process orphaned but running. So this change makes ctrl-c do nothing when delta output is being paged to less, which is what a less user expects (they use `q` to exit).

I was initially worried that this change might be annoying when one accidentally sends `git log -p` to delta with the pager deactivated (i.e. tons of commits flying past), but I believe that similar logic applies: delta now ignores the signal, it is propagated to the parent `git` process, which does terminate, and thus breaks the pipe to delta and delta exits. (I think I'm slightly unclear why delta exits when this pipe is broken but less does not.)

**Comment by Kr1ss-XD** [comment]
>If anyone would like to test that, the branch is named handle-sigint.

Looks good, indeed. 

I'm right now reproducing the situation from #683 again, using a build of the `handle-sigint` branch. Now, after sending SIGINT or pressing CTRL-C, `less` stays under the same parent process (which is `delta`), the `git diff` process terminates, and the delta-formatted diff output is displayed by less.

**Comment by Kr1ss-XD** [comment]
>I'm thinking that less itself is ignoring SIGINT

FWIW, there's a flag that makes `less` terminate on SIGINT / CTRL-C : `-K` or `--quit-on-intr`. From the manual : 

>Causes less to exit immediately (with status 2) when an interrupt character (usually ^C) is typed.  Normally, an interrupt character causes less to stop whatever it is doing and return to its command prompt.  Note that use of this option makes it impossible to return to the command prompt from the "F" command.

Maybe this could help ?  I _think_ by the way that when `less` **is** in command prompt mode, it actually ignores that signal. Don't know that for sure though.

**Comment by abbeyj** [comment]
> I need to refresh myself on exactly how this works. Perhaps someone could tell me where the following is wrong (@abbeyj ?).
> 
> I'm thinking that `less` itself is ignoring `SIGINT`, and thus the signal is propagated to the parent `delta` process, which prior to this change handled it by terminating itself, leaving the `less` process orphaned but running. So this change makes ctrl-c do nothing when delta output is being paged to less, which is what a less user expects (they use `q` to exit).
> 
> I was initially worried that this change might be annoying when one accidentally sends `git log -p` to delta with the pager deactivated (i.e. tons of commits flying past), but I believe that similar logic applies: delta now ignores the signal, it is propagated to the parent `git` process, which does terminate, and thus breaks the pipe to delta and delta exits. (I think I'm slightly unclear why delta exits when this pipe is broken but less does not.)

I think you're close here, but not entirely accurate.  When you press Ctrl-C, all processes in the current "process group" get a `SIGINT` signal.  See the man pages for `setpgid` and/or `setpgrp` for information about process groups.  The shell starts a new process group for each pipeline that it runs so you normally do not have to worry about touching this in your own code.

In the case where we are running `yes | delta`, the process tree would look something like this:
```
bash
├── yes
└── delta
    └── less
```

The shell has launched off two subprocesses, one for `yes` and one for `delta`, and hooked them together with a pipe.  It is now waiting for both of them to exit.  Once they do it will know that everything from this pipeline is done and it can print a new prompt and read the next command from the user.

When we press Ctrl+C, all of these processes get a SIGINT.  Since `yes` does not register a handler for SIGINT and since SIGINT is fatal by default, the `yes` process immediately terminates.  The `less` process will also receive a SIGINT but it ignores this.

The `delta` process will also receive a SIGINT.  Before #686, that signal would be fatal, and `delta` would exit.  Then the shell would see that both `yes` and `delta` have exited and think that everything is done, but `less` would still be running.  With two programs both running on the same pty and both trying to read from stdin, we would have a conflict.  Exactly what happens at this point is probably dependent on both the OS and the current `stty` settings.  Since we never want to get into this state in the first place, I think we can skip the details.

So there is no "propagation" of blocked signals.  Every process gets the signal and then it is up to each process to decide what to do with it.  Other processes are not (directly) affected by your process's choice.

In the case where the pager is disabled, things work like this: both processes get a SIGINT.  The process that is hooked up to delta's stdin (`yes` or `git diff` or whatever) will receive that signal and shut down.  That closes that process's stdout, which is the write end of a pipe.  The read end of that pipe is hooked up to delta's `stdin`.  The delta process also gets a SIGINT.  If it chooses to ignore that signal then it can keep running.  Eventually it will get around to reading from `stdin` again.  And once it has exhausted any data remaining in the pipe, it will get EOF.  At this point it will decide that there is no more work to do will start its shutdown process.

This assumes that there are no bugs in delta that cause it to go get stuck in an infinite loop or something.  If there is such a bug then delta won't shut down and the user will be stuck, unable to get their prompt back no matter how many times they press Ctrl+C.  If you want to protect against this type of situation then maybe you could set delta to ignore SIGINT only for the duration that the pager is running.  I'm not sure if that kind of complication is worth it or not.

The reason that delta exits but less does not is because of the design of the programs.  Many programs will naturally exit when they read EOF on stdin.  Things like `sed`, `grep`, `bc`, `ftp`, etc. work this way.  And `delta` also behaves this way, at least when paging is disabled.  But `less` is different because it is designed to keep running even after getting an EOF on stdin.  Consider the case of a command like `perl -e 'print "$_\n" for (1 .. 100)' | less`.  The `perl` command will run, print out 100 lines to stdout, and then exit, implicitly closing its stdout.  The `less` process will read all of this data from stdin and then the next read will return EOF.  But despite getting EOF on stdin, we do not want less to exit at this point.  We want it to keep running so we can scroll through the data, perform searches on it, etc.  We only want to exit when the user is done with this data and presses `q`.

I believe all of the above is accurate, but it is possible that I could have missed something.  If you need more details or have questions, feel free to ask.

**Comment by dandavison** [comment]
Wow, thanks very much for that fantastic explanation @abbeyj.

> This assumes that there are no bugs in delta that cause it to go get stuck in an infinite loop or something. If there is such a bug then delta won't shut down and the user will be stuck, unable to get their prompt back no matter how many times they press Ctrl+C.

I agree that this risk is acceptable, since it is not expected (it would be a bug in delta). It would cause frustration; I expect some people will kill from the command line in that case but that many users will just close their terminal emulator tab / tmux pane.
