### ISSUE TITLE
Output without paging doesn't stop highlighting

### ISSUE THREAD

**Issue by travankor** [dandavison/delta#70]
Setting `PAGER` or `BAT_PAGER` to none will keep highlighting text in certain shells like bash or dash. Strangely, this does not happen on fish.

Example:
![2019-12-10-04:33:35PM](https://user-images.githubusercontent.com/38744110/70578410-8994b700-1ba5-11ea-8d1e-df124be7dc5b.png)

Tested on delta 0.0.15.

**Comment by dandavison** [comment]
Thanks for reporting @travankor! To make sure I understand, could you clarify exactly what you mean by "setting PAGER to none"? If you could post the output of `env | grep PAGER` that would help too.

**Comment by travankor** [comment]
Thanks for the quick response! The program `bat`, which seems to be where `delta`'s pager support comes from, lets you set `PAGER=none` or add the flag `--pager=none` to turn off paging. `delta` doesn't seem to have the latter option, but setting the environment variable `BAT_PAGER=none` allows you to output to the terminal without calling a pager.

Admittedly, this sort of feature is not so useful for git diffs (I was just testing `delta` out in the screenshot), but this would be neat for using with `diff -u`, where you don't necessarily to call the pager (since `diff -u` does not call `less` by default).

**Comment by travankor** [comment]
On second glance, setting `BAT_PAGER` or `PAGER=none` completely messes up delta's formatting, so I'm guessing this is unsupported behaviour. Apologies for not noticing this earlier (just started looking at delta today).

**Comment by dandavison** [comment]
> Edit: So I think this is a duplicate of #45

Right, that's what I was thinking too. But this ticket has good information in it for when someone deals with #45; thanks again.
