### ISSUE TITLE
🚀 Extra flags via environment variables.

### ISSUE THREAD

**Issue by WhyNotHugo** [dandavison/delta#703]
## Problem statement

Most of the time, I want `side-by-side` off.

However, about 10-20% of the time, side-by-side is better for a specific diff and I _do_ want it. What I do right now is open `~/.config/git/config`, find the right line for `delta.diff`, and then run `git diff` on my code again. Once I'm done, I change that back.

This is very unergonomic, it's a looot of manual steps.

## Potential solution

What I'm really after in this case is just a one-time exception. I think like this would be super handy:

    DELTA_FLAGS=--side-by-side git diff

And delta does a `--side-by-side` only for this call.

## Notes

I'm honestly open to other proposals to work around this scenario, the proposed solution is just one, but I'm not married to it -- I mostly want to avoid jumping so many extra hoops the few times I do want side-by-side.

**Comment by dandavison** [comment]
There's a related discussion here: https://github.com/dandavison/delta/discussions/749

I'll close this now; the discussion has thrown up some different solutions. Feel free to suggest / make PRs for documentation changes.
