### ISSUE TITLE
Green highlight is too bright for comments

### ISSUE THREAD

**Issue by YaLTeR** [dandavison/delta#71]
The inserted word is basically invisible:
![image](https://user-images.githubusercontent.com/1794388/70596845-e91bb280-1bf7-11ea-87b9-a2afd3a48340.png)
On regular code it's fine but could still be less bright:
![image](https://user-images.githubusercontent.com/1794388/70596880-fdf84600-1bf7-11ea-9ac5-d544ee0f66b4.png)

Themes I tried: default, OneHalfDark. Terminal: alacritty. Alacritty theme: base16-ocean.

**Comment by dandavison** [comment]
Hi @YaLTeR, the choice of theme determines the foreground color of the text for syntax highlighting, but it does not determine the background color. To select the background color, delta provides [options](https://github.com/dandavison/delta#options) `--minus-color`, `--minus-emph-color`, `--plus-color`, `--plus-emph-color` allowing the 4 background colors to be specified as hex codes, so with a 24-bit color-capable terminal emulator there is a lot of choice! To quickly try out colors, the `--show-background-colors` option can be useful.

It sounds like you want to experiment with the value of `--plus-emph-color`.

I don't have a terminal emulator with base16-ocean theme installed, but the dark mode defaults used by delta were chosen for a black terminal background. Is the answer here to choose your own custom colors for base16-ocean?

**Comment by YaLTeR** [comment]
FWIW with completely black background (alacritty defaults) it's the same issue:
![image](https://user-images.githubusercontent.com/1794388/70689449-5ea18480-1cc5-11ea-91ca-068a63ccd624.png)

I can play with `--plus-emph-color`, just trying to figure out if it is perhaps an issue with the default value?

**Comment by dandavison** [comment]
Oh I'm sorry, yes you're absolutely right. The default `--plus-emph-color` in commented text on a black / dark terminal background is unreadable. Have you found an alternative color you like?

Honestly, I have struggled with finding good defaults for delta on a dark background. I think it looks great on a light background with the defaults (e.g. white, or I sometimes use the iTerm2 "material" theme which is a sort of very light pearl gray background). But I'd always felt that we can find  better defaults for dark.

![image](https://user-images.githubusercontent.com/52205/70724743-2439e680-1cc9-11ea-8ed7-9e1a903f0ebb.png)

![image](https://user-images.githubusercontent.com/52205/70724761-2bf98b00-1cc9-11ea-950c-87747d17e4f2.png)

**Comment by YaLTeR** [comment]
`#005000` seems to work better. I can't quite strike a good balance between enough highlight and comment color legibility.

![image](https://user-images.githubusercontent.com/1794388/70747157-6e0de580-1d38-11ea-8035-a973579aa79a.png)
![image](https://user-images.githubusercontent.com/1794388/70747168-72d29980-1d38-11ea-96a5-0a7b581dd547.png)

On a related note, `--show-background-colors` drops leading zeros from individual color bytes making it really hard to tell what the actual values are. E.g. for the default `--plus-emph-color` it shows `#e7ce` and you can only guess that it's actually `#0e7c0e`.

**Comment by dandavison** [comment]
Great thanks, I think I'll go with `#006000` for now.

>  --show-background-colors drops leading zeros from individual color bytes making it really hard to tell what the actual values are.

Yes, agreed!

current (`#0e7c0e`)
![image](https://user-images.githubusercontent.com/52205/70756686-3472b580-1d0b-11ea-9eb2-26345a95977e.png)

`#006000`
![image](https://user-images.githubusercontent.com/52205/70756744-5c621900-1d0b-11ea-9b9b-f6a79896e343.png)
