### ISSUE TITLE
Toggle side-by-side mode while viewing diff 🚀 

### ISSUE THREAD

**Issue by janeklb** [dandavison/delta#711]
Is there a mechanism by which one could toggle `side-by-side` mode while viewing a diff?

**Comment by dandavison** [comment]
Hi @janeklb, sorry I missed this question.

Unfortunately, not really. Delta uses less for paging, whereas I feel like what you're suggesting is more in the realm of one of the TUIs such as https://github.com/jesseduffield/lazygit/.

The best that I'm aware of that we can do with delta is stuff like

```
export DELTA_FEATURES=side-by-side
# Now it's on
export DELTA_FEATURES=
# Now it's off
```

Obviously there's scope for your own shell aliases and shell functions.
