### ISSUE TITLE
🐛 git blame color not readable on konsole

### ISSUE THREAD

**Issue by pickfire** [dandavison/delta#714]
![Screenshot_20210913_133954](https://user-images.githubusercontent.com/4687791/133029836-d7ab487d-9fe2-4022-bbf0-34cf42a6a282.png)

Color is white but those are the default 256 color but it's wrong.

git config

```
[core]
        pager = delta
```

`uname -a`

```
Linux mi 5.14.2-zen1-2-zen #1 ZEN SMP PREEMPT Thu, 09 Sep 2021 09:42:32 +0000 x86_64 GNU/Linux
```

environment variables

```
TERM=xterm-256color  # even when I used konsole-direct it still have the same issue
COLORTERM=truecolor
```

delta 0.8.4

**Comment by Kr1ss-XD** [comment]
Hi @pickfire !

You might want to experiment with the `--blame-palette` parameter, or the according `gitconfig` option `delta.blame-palette`. This enables you to customize the background colors in blame output that's handled by `delta`.

Please keep in mind that the feature is still in an early state, there's no mention in the project's README yet. Although you can consult this [comment](https://github.com/dandavison/delta/issues/426#issuecomment-907716396) by @dandavison as to how it works, and there's a short summary in the output of `delta --help`.

Dan mentioned also that there will probably be two defaults at some point, one for dark themes and another for light ones.

---

By the way, if you want blame output _not_ to be handled by `delta`, but rather by a normal pager, a good way to go woud be a `gitconfig` like :

```gitconfig
[core]
	pager	= less
[pager]
	blame	= true
	diff	= delta
	show	= delta
	log		= delta
	stash	= delta
	; asf, with all the subcommands you want to pipe their output to delta
```

_Cheers !_

**Comment by dandavison** [comment]
Hi @pickfire, can you try with the latest version? Delta now has different default `blame-palette` values for `light` and `dark`.

**Comment by pickfire** [comment]
Yup, it works nicely now. But I am curious how it can support both.

**Comment by dandavison** [comment]
Great.

>  I am curious how it can support both.

It was basically a bug that it was giving you those light colors before. By default, delta assumes the user has a dark terminal background. Users who have a light terminal background have to set `light = true` in delta settings. So by default the blame background is for dark, but if you have `light = true` it will be light. There's no (not yet) any magical autodetection of terminal background colors or of system light vs dark mode.
