### ISSUE TITLE
🐛File path for the removed file 

### ISSUE THREAD

**Issue by zewelor** [dandavison/delta#715]
Hi

thanks for great git addon ! I'm wondering, if its possible to show file path, when file was removed. It would be helpful for example to revert it etc. Now when file is deleted, filepath says only /dev/null, for example, using default setup from readme:

```
─────────────┐
/dev/null:0: │
─────────────┘
apiVersion: v2
```

Where plain git diff produces:

```
--- gitops/charts/system-monitoring/prometheus-nut-exporter/Chart.yaml
+++ /dev/null
@@ -1,7 +0,0 @@
-apiVersion: v2
```

**Comment by dandavison** [comment]
Thanks @zewelor, I had not noticed this. I agree with you, displaying `/dev/null` there is not what we want to be doing!
