### ISSUE TITLE
🐛 Themes whose names have uppercase letters are silently ignored

### ISSUE THREAD

**Issue by Tak** [dandavison/delta#716]
If I create a theme feature in `.gitconfig` (or an included file) named like `[delta "Tak"]`, it will be silently ignored (also in e.g. `--show-themes`)

This appears to be a result of force-lowercasing in some places for comparison and doing original-case lookups in other places.

Obviously there's an easy workaround, but it took quite a while to find out why my theme wasn't getting picked up. :slightly_smiling_face:

**Comment by dandavison** [comment]
Hi @Tak, oops! OK, thanks very much for the report; will fix. (Of course, if you feel like a Rust PR, go for it also!)
