### ISSUE TITLE
🚀 Make whole-line changes bright when sharing a hunk with partial-line changes

### ISSUE THREAD

**Issue by jaminthorns** [dandavison/delta#722]
The partial-line change detection of `git-delta` is really great, but when there are partial-line changes next to whole-line changes within a hunk, the highlighting can be a bit confusing.

For a partial-line changes, `git-delta` paints the changed parts bright and the unchanged parts normal. For whole-line changes, `git-delta` just paints the changes normal. My proposal would be to change the painting of whole-line changes to be bright _if_ they're within a hunk that has any partial changes. This seems to be the behavior of VS Code's diff view, and I find it much easier to visually parse.

## Delta

<img width="542" alt="Screen Shot 2021-09-24 at 2 13 12 PM" src="https://user-images.githubusercontent.com/6618434/134729185-af153c76-a8ff-4e73-8868-2ce071d1c738.png">

## Visual Studio Code

<img width="558" alt="Screen Shot 2021-09-24 at 2 13 03 PM" src="https://user-images.githubusercontent.com/6618434/134729230-5b3d5eb5-8da1-488a-bc31-b4a321286cf1.png">

**Comment by th1000s** [comment]
Related, again, PR #13 :)

**Comment by dandavison** [comment]
@jaminthorns thanks for this!  This is possible now in master. Basically all you have to do is

```gitconfig
    minus-style = minus-emph-style
    plus-style = plus-emph-style
```

See https://github.com/dandavison/delta/pull/785#issuecomment-981179697 for a full example.

Except, I haven't made it conditional on whether the hunk has partial line changes. Let me know if you think that's very desirable.
