### ISSUE TITLE
🚀 Use deleted filename for hunk-header-style file

### ISSUE THREAD

**Issue by mrjoel** [dandavison/delta#731]
I try to emphasize vertical space compactness in my delta output configuration. I recently was looking at my config again and realized that I could possibly save lines by using the embedded file in `hunk-header-style` and omit `file-style` entirely. From brief initial testing that almost works, except for the case of deleted files.

When a file is deleted the hunk-header dutifully shows `/dev/null` as the affected filename based on the raw diff output. It would be more beneficial to show something like `path/for/original/file (deleted)` if the new filename from git is `/dev/null`. Another perfectly suitable option would be to use the existing detection in the `file` section which already outputs `removed: path/for/original/file`.

**Comment by Kr1ss-XD** [comment]
Hi @mrjoel - I think this is actually already solved, although not yet released. :grin:

Ref:
* https://github.com/dandavison/delta/issues/715
* https://github.com/dandavison/delta/blob/d0c3fc52f856f1a1c82b2144106cb813d1f4f8fd/src/handlers/hunk_header.rs#L77

_Cheers !_

**Comment by mrjoel** [comment]
Indeed, that looks like it is indeed, thanks!

**Comment by mrjoel** [comment]
Closing as duplicate of #715
