### ISSUE TITLE
🚀  Is there anything to properly preview git's combined diff output ?

### ISSUE THREAD

**Issue by akharrou** [dandavison/delta#736]
*Thank you for this amazing diff render I really love it and use it ALL the time*

Currently, with my configurations at least, the "combined diff" output that `git` produces for unmerged files is interpreted like any other regular diff output.

```zsh
# combined diff example (currently have files in an unmerged state)
$ git diff
diff --cc file.txt
index 1191247,e2709b3..0000000
--- i/file.txt
+++ w/file.txt
@@@ -1,2 -1,2 +1,7 @@@
  1
++<<<<<<< .merge_file_ehjgho
 +2
++||||||| .merge_file_r2aEcC
++=======
+ 102
++>>>>>>> .merge_file_VIgoDD
```

Lines with:
- "`  `": are already present on both "ours" and "theirs" copy
- "`+ `": are additions to "ours"
- "` +`": are additions to "theirs"
- "`++`": are additions to both "ours" and "theirs"
- ... ditto for subtractions

Currently I get this `delta` output for combined diffs:

![image](https://user-images.githubusercontent.com/36056254/137437840-6ef8a120-4025-4036-b9b9-d7a76c3a0404.png)

It's not wrong, you can still interpret the first column yourself. my question is: is there currently a way of interpreting combined diffs ? otherwise my feature suggestion would be: maybe it would be a nice addition to `delta` if it could be passed an option or somehow detect that the output is a combined diff output (e.g. maybe the first line of the diff output `diff --cc ...` gives it away) and highlight in a certain way for additions to "ours", in another for additions to "theirs" and another for additions to both, etc.

**Comment by dandavison** [comment]
Hi @akharrou, thanks for this, it doesn't exist yet but I absolutely agree -- I'd love to see this tackled. There are a couple of related issues: https://github.com/dandavison/delta/issues/189 and https://github.com/dandavison/delta/issues/609, but yours gives good discussion of merge conflict markers. If anyone would like to start making progress in this area that would be very welcome.

**Comment by dandavison** [comment]
@akharrou I've made a start on this. It would be great to have your feedback/thoughts. If you're interested, let's discuss in this issue: https://github.com/dandavison/delta/issues/189#issuecomment-985954812

Screenshots from #189 copied below:

The merge conflict handling is particularly intended for users who have set `merge.conflictstyle = diff3`: it diffs the ancestral commit against the two derived commits in turn. I'm not sure how merge conflicts should be styled and welcome suggestions!

<table>
<tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/144694131-ce603ccf-5ca3-4c88-94a5-faa9ef95cbf7.png" alt="image" /></td>
</tr></table>

Combined diff handling looks like this (note the 2-char-wide prefixes):

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/144694306-f9913dd6-5d78-4b39-b0c8-f249ffdd2259.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
Initial handling of combined diff, and merge conflicts, has been implemented in https://github.com/dandavison/delta/pull/812. I'll release it soon; if anyone's able to test (on master) that would be fantastic.
