### ISSUE TITLE
🐛 `--minus-style=raw` strips all colors

### ISSUE THREAD

**Issue by plgruener** [dandavison/delta#753]
I ran into this today while testing another, probably semi-related issue (bug-report incoming). I tried to get an as-unaltered-as-possible output from delta, for a simple diff of a whole line:

![diff delta--raw](https://user-images.githubusercontent.com/5796100/139348785-df65e2ed-56b1-45c0-82e1-40bfc4dacc10.png)

As we can see, `delta --raw` produces the same colors as git, as expected.

![delta-minus+emph-raw](https://user-images.githubusercontent.com/5796100/139348796-c6e2b6b5-23fd-48f2-9414-06a311b84025.png)

However, `--minus-style=raw` does not, it totally strips the entire line off any color. This seems not an issue with the raw style per se, as eg `--minus-emph-style=raw` or `--file-style=raw` work as they should. (But if both `minus-style` and `minus-emph-style` are present, the former always takes precedence.)

This also affects the `--plus-[emph-]style`s.

Tested with delta version 0.9.1 on ArchLinux.
Please let me know if you need more info/testing.

**Comment by dandavison** [comment]
Hi @plgruener, thanks for writing this up. I’ll take a look at what’s going on.
