### ISSUE TITLE
🐛 Cannot make highlighting of single words to work

### ISSUE THREAD

**Issue by loubregand** [dandavison/delta#760]
Hello, I cannot seem to make single words differences to be highlighted.
a simple example is:

file a:
ab cd ef

file b:
ab ef ef

output of diff a b:

```
1c1
< ab cd ef
---
> ab ef ef
```

delta output is:
![delta_output](https://user-images.githubusercontent.com/6709324/140035896-5187625a-7882-4337-858d-c3fde0cf64d0.png)

I would have expected something like:
![git_output](https://user-images.githubusercontent.com/6709324/140036167-3546df8a-f599-4d53-994a-9f85eea04b8f.png)

or at least the highlighting of the modified portion both for the previous and for the modified line

adding --word-diff-regex . to delta doesn't change the output

is my expectaction wrong?

**Comment by dandavison** [comment]
Hi @loubregand, hm, your example is working for me:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/140217294-06f06626-2520-45c5-b432-be778e5cb413.png" alt="image" /></td></tr></table>

Can you try ` --no-gitconfig` (to see if it's one of your local settings), and if that's not it, then post the output from

- `delta --version`
- `delta --no-gitconfig a b | cat -A`  (or `bat -A` if you use bat)
- A screenshot of `delta --no-gitconfig --show-config`

**Comment by loubregand** [comment]
Hello, --no-gitconfig didn't change the result. Here is what you asked:

delta --version
delta 0.9.1

delta --no-gitconfig a b | cat -A
$
^[[34ma M-bM-^_M-6   b^[[0m$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m$
$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m^[[34mM-bM-^TM-^P^[[0m$
^[[34m1^[[0m: ^[[34mM-bM-^TM-^B^[[0m$
^[[34mM-bM-^TM-^@M-bM-^TM-^@M-bM-^TM-^@^[[0m^[[34mM-bM-^TM-^X^[[0m$
^[[48;5;52mab ^[[48;5;124mcd^[[48;5;52m ef^[[0m^[[48;5;52m^[[0K^[[0m$
^[[48;5;22;38;5;231mab ^[[48;5;28mef^[[48;5;22m ef^[[0m^[[48;5;22m^[[0K^[[0m$

here is bat output:

![bat_output](https://user-images.githubusercontent.com/6709324/140272472-756ca1e2-b0f1-43c6-bb86-a1785b500aba.png)

delta config:

delta --no-gitconfig --show-config
    commit-style                  = raw
    file-style                    = blue
    hunk-header-style             = syntax
    minus-style                   = normal 52
    minus-non-emph-style          = normal 52
    minus-emph-style              = normal 124
    minus-empty-line-marker-style = normal 52
    zero-style                    = syntax
    plus-style                    = syntax 22
    plus-non-emph-style           = syntax 22
    plus-emph-style               = syntax 28
    plus-empty-line-marker-style  = normal 22
    whitespace-error-style        = reverse purple
    true-color                    = false
    file-added-label              = 'added:'
    file-modified-label           = ''
    file-removed-label            = 'removed:'
    file-renamed-label            = 'renamed:'
    hyperlinks                    = false
    inspect-raw-lines             = true
    keep-plus-minus-markers       = false
    line-numbers                  = false
    max-line-distance             = 0.6
    max-line-length               = 512
    line-fill-method              = ansi
    navigate                      = false
    navigate-regexp               = 
    pager                         = none
    paging                        = auto
    side-by-side                  = false
    syntax-theme                  = Monokai Extended
    width                         = 170
    tabs                          = 4
    word-diff-regex               = '\w+'

and my locale settings:

locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=

I already tried also:

LC_ALL=C delta --no-gitconfig a b

but I got the same result

**Comment by Kr1ss-XD** [comment]
@loubregand Since `--{minus,plus}-style` and `--{minus,plus}-emph-style` colors are in fact different (as to be expected without configuration), are you by any chance using a terminal emulator that supports only a 16 color set ?
That might render the emph colors to look to same like the normal ones.

**Comment by dandavison** [comment]
I'm also wondering the same as @Kr1ss-XD said. It's clear you don't have 24bit colors (true-color is false in your config).

When you run `--show-config`, do you see a difference between emph snd non-emph colors? (You could post a screenshot of `--show-config`.

**Comment by loubregand** [comment]
Oh ok, that's why you asked about the screenshot. Indeed they appear the same:

![image](https://user-images.githubusercontent.com/6709324/140317318-457f7a3a-9031-4785-a1f6-69b4e203572d.png)

I'm using terminator, which doesn't support 24bit colors.

If I run this in gnome-terminal there is a difference (although could be accentuated, but it is only a matter of changing a param):

![image](https://user-images.githubusercontent.com/6709324/140318004-820f9793-2194-4d8c-90cf-474d9b6d2559.png)

**Comment by Kr1ss-XD** [comment]
That's weird. GNOME-terminator _does_ support true color output. Here's what I'm getting : 

<details>
	<summary>screenshot - click to expand</summary>

![terminator-truecolor](https://user-images.githubusercontent.com/28707521/140379737-cb0fb99a-74f5-425c-bb89-f506871d4443.png)
</details>

What stands out is that in your `--show-config` output, delta uses the 256-color space while on my end it's using RGB colors.
I don't use that terminal emulator normally, maybe it can be configured to make use of 24bit colors ?

**Comment by loubregand** [comment]
I found out what my problem is, apparently screen doesn't support truecolor. I have screen as default command for terminator, so although per se it is able to display rgb colors it seemed unable to; I wasn't aware this is instead a screen issue.

**Comment by loubregand** [comment]
I cannot seem to find if delta supports configuration through a config file when used standalone, does it?

**Comment by Kr1ss-XD** [comment]
Yes @loubregand, it does read your git configuration.

**Comment by dandavison** [comment]
There's a magic incantation for tmux given here: https://github.com/dandavison/delta#24-bit-color-truecolor

I'm not sure what the fix for screen is but hopefully it's similar? Let's add help for screen users to the README if we discover something useful.

**Comment by loubregand** [comment]
@Kr1ss-XD I am aware, but I would prefer to keep a config file separated for each software.

In the meantime I found out here:

https://askubuntu.com/questions/87169/using-gnu-screen-with-256-colors

how to make screen display 256 colors, which is quite a nice side-effect of this issue not being limited to 8 colors anymore 😛. I don't really care for true color anyway. Screen seem to have support for true color only if you build it by yourself, which I don't really care doing.

With 256 colors I can now see the emphasized portions correctly in delta output

![image](https://user-images.githubusercontent.com/6709324/140428069-8be13962-b0ad-4b1a-8eec-dd82784744c6.png)

**Comment by Kr1ss-XD** [comment]
Great, thank you for researching !
So it needs to be configured with a `--enable-colors256` flag before compiling. I assume that this is the case with binary packages in the major distros.

@dandavison I could add a note to the README.

>I would prefer to keep a config file separated for each software.

Git supports nested includes in its configuration. Maybe you could do something like : 

```gitconfig
[include]
	path	= /home/USERNAME/.config/delta/config
```

and have your delta configuration in `~/.config/delta/config`

**Comment by loubregand** [comment]
as a matter of fact in ubuntu 16.04 and 18.04 screen seem to be already compiled correctly, all I had to do is to add:

term screen-256color
attrcolor b ".I"
termcapinfo xterm 'Co#256:AB=\E[48;5;%dm:AF=\E[38;5;%dm'
defbce on

to my .screenrc for screen (actually the last line doesn't seem necessary but was listed in the link I posted previously, so maybe it is still useful, I will research later) and add:

set -g default-terminal "screen-256color"

to my .tmux.conf to enable them in tmux also.

As for your solution for having a different config file for delta including a file from git configuration: recently I switched to git, but my old svn and mercurial guts are a bit unhappy about this solution, you know.

**Comment by Kr1ss-XD** [comment]
I did get truecolor support working in screen. :partying_face:

<details><summary>screenshot</summary>

![screen-truecolor](https://user-images.githubusercontent.com/28707521/140619344-fd4cc4e5-2f75-45e4-bf63-6037aa2454ff.png)
</details>

The feature hasn't been released yet, hence this involves building the master branch, as the poster already indicated.
Gonna write a note for the README tomorrow. :smiley:
