### ISSUE TITLE
🚀 gitlab runner doesn't have pty so no color from delta

### ISSUE THREAD

**Issue by mcallaghan-geotab** [dandavison/delta#771]
Hi team,

This is (initially at least) in the form of a question.  Does delta have a flag that _forces_ colorization?

Due to https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1500, when running `delta` via `git diff`, color highlighting/etc does not work.

There are some interesting workarounds (such as https://stackoverflow.com/questions/32910661/pretend-to-be-a-tty-in-bash-for-any-command), but wondering first if one of delta's flags would work.

From https://github.com/dandavison/delta#24-bit-color-truecolor, testing the colors clearly reveals gitlab's limitation here.

**Comment by mcallaghan-geotab** [comment]
![Uploading 2021-11-12_175323.png…]()

**Comment by dandavison** [comment]
Hi @mcallaghan-geotab, so I think the first thing to note is that git itself doesn't invoke its pager when output is not a tty, so delta never comes into the picture if you do `git diff` when standard output is a non-tty.

However, the plus side of that is that `git diff | delta` *will* output color even when output is a non-tty: delta doesn't do any automatic disabling of color (to convince yourself, compare `git diff | cat` with `git diff | delta | cat`).

Finally, I also came across probably the same SO link you gave above, and so delta has a test that uses that obscure `script` technique for tricking git into thinking output is a tty: https://github.com/dandavison/delta/blob/master/tests/test_navigate_less_history_file#L32-L34

**Comment by mcallaghan-geotab** [comment]
Very cool thanks @dandavison  - piping to `delta` directly instead of the `pager` is exactly the trick.

**Comment by mcallaghan-geotab** [comment]
(might it be worth an addition to the README?)

**Comment by dandavison** [comment]
Yes, good call. The README has become a bit chaotic over time, but added this in ba446070223873487e25197ff39af9997bc4da28
