### ISSUE TITLE
Can't decide if actually a 🐛: Issue with semantics around emph- and non-emph- styles

### ISSUE THREAD

**Issue by unphased** [dandavison/delta#776]
I have been using a custom diff with git, for a while now, but I have always wanted a fully syntax-highlighted diff, so I am very excited to use Delta and configure it for daily driving use.

I have a sort of conceptual/semantic issue with the fact that there are three color styles. The issue applies to a specific, not rare, situation, where a token is entirely removed or entirely added. 

Let me just show a simple example, with different diff viewing options:

1. git diff
2. diff-highlight
3. diff-so-fancy 
4. My character based diff that uses background color to indicate minus/plus
5. Delta

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1542910/141917972-b71c18fa-5fa0-4876-9871-7a22645c7636.png">

Overall, what I want to do for Delta is to improve its rapid scannability. What I mean by this is minimizing the time taken for my brain to comprehend the change. As lovely as syntax highlighting is, I have come to the unfortunate realization that I think I need to crank this metric back up more before I can daily drive Delta and I really really want to do so. 

Although I do not use (2) or (3), I will rank these 5 options' readability as follows:

### 4, 2, 3, 5, 1

(Let me know if you agree...)

The deficiency in Delta that this highlights is that the line 51 add hunk is shown with `plus-style`, rather than `plus-non-emph-style`. The reason that this is such a big deal is that I have, over the years, found the in-your-face background color contrast mode to be the most effective way to communicate the notion of change in a diff. What this requires is that the highest contrast red and green background colors unambiguously indicate change. 

So, the way that the emphasis works is inconsistent with my desired visual semantics, because as Delta works currently, there are two scenarios in which `plus-style` is used:

- Line is new or entirely changed: **I want to display these lines in bold and with highest visual contrast.**
- Some complete token was removed from (or in the symmetrical case, added to) this line, leaving nothing to emphasize in it: **I do not want to mark the entire line in bold with highest visual contrast; I want to mark it with a low contrast similar to `non-emph-style`.**

Config used in the screenshots is as follows (minus is all the same just on the red channel): 

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1542910/141921768-84571c9c-63af-47e0-90d2-692ff62961ac.png">

I hope this makes sense. In order to achieve the optimal degree of visual clarity of actual changes made, it seems that I need one more class of style to apply to differentiate between the above two classes of entirely changed line. Basically I think it's best if it is possible to configure this thing so that we can use a style to completely unambiguously specify which literal characters are insertion/deletion characters and which are unchanged context characters. The current implementation of the `{plus,minus}-style` is not capable of satisfying this principle.

----------------

If you'll humor me in continuing down this path of psychovisual efficiency optimization...

- Well, first off I have a request to be able to eliminate the empty line at the top of the Delta hunks. If there is already an option for this, I apologize. But I do not want to lose a line of real estate for no reason.

- Side by side diffs are nice but the problem I have with them is that it takes longer to look through them for me. In particular moving my eyes left and right generates fatigue, not unlike reaching for the mouse, but marginally less acceptable to complain about. Rather than complain, I propose an alternative. I gravitate towards the unified diff for this reason and less duplicated information means information density. Now what this makes me think, though, is, and I've never seen this implemented, the following enhancement to unified mode:
  
  ### **What if we apply the same concept of visual alignment to a unified diff in the transverse axis?**

I will illustrate by generating a fully colored mockup:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1542910/141925651-f10565a8-416a-47ea-905d-b751d09e43b0.png">

Which is not far off from maybe:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1542910/141926301-6040a61e-dd2a-4c0e-80a1-b33329b000d8.png">

Which really makes me feel like I just want to do it my old way with the plain character diff, but to try to shoehorn syntax highlighting into it somehow... But no, I think the syntax will make character diff actually unreadable with real-life-gnarly code. I think that I should definitely be okay with duplicating the lines: both sets of lines would be
- both highlighted in a dim color and physically immediately adjacent, to indicate no physical character change in those zones (rather than being side by side and physically separated by a scores/hundreds of chars)
- syntax highlighted based on these actual old/new line contents, which is a pretty big deal, allows us to potentially even see syntax errors

It's the physical alignment that I think will really speed up comprehension.

**Comment by dandavison** [comment]
Hi @unphased, I really appreciate this issue. Obviously there's a lot to think about and I'm not going to attempt to address it all in this comment. But in general I'm very happy to discuss ideas along these lines and might be able to find time to create experimental branches, and would definitely anyone else out if they investigated creating an experimental branch.

Your idea about aligning lines in the unified diff view by inserting whitespace is really interesting -- I'd like to try out a working implementation of that if someone can put the required code change together. I *think* it may involve creating an artificial whitespace insertion here https://github.com/dandavison/delta/blob/90fd9c60493cc6f653e76277d67e1fce611bbb1d/src/edits.rs#L197 and in the corresponding place for insertion, and then dealing with the fall out, e.g. related to [`superimpose_style_sections `](https://github.com/dandavison/delta/blob/90fd9c60493cc6f653e76277d67e1fce611bbb1d/src/paint.rs#L783).

There are a few other related issues and PRs which I'm going to link here. cc @th1000s.

- https://github.com/dandavison/delta/pull/13 @nkouevda's proposal very early on in delta development which I didn't feel quite able to incorporate at the time but which I think is now largely achievable by delta styles that were introduced subsequently
- https://github.com/dandavison/delta/issues/722
- https://github.com/dandavison/delta/issues/522
- https://github.com/dandavison/delta/issues/440
- https://github.com/dandavison/delta/issues/152

**Comment by dandavison** [comment]
Oh and yes, I agree with 4, 2, 3, 5, 1!

**Comment by unphased** [comment]
I've not looked *too* extensively out there but I haven't really seen anything other than my homebrew implementation of number 4. It definitely started as a wild experiment on my part (a very old C++ STL based implementation of diff-match-patch in char-wise mode, with its raw output lightly wrapped with a very poorly maintained python script I named `sift`). It's clear now that I want my ideal diff tool to be constructed upon Delta's foundation. New to rust, but I would love to experiment with it when find some time. Thank you so much for everything!

**Comment by unphased** [comment]
@dandavison Could you comment on the original question of my issue though? Do you think we need a fourth emphasis mode or is there maybe a cleaner way to address the issue I pointed out? This is a bigger issue than being able to horizontally align text with added whitespace lol.

**Comment by dandavison** [comment]
Right, point definitely taken re. desirability of styling (1) and (2) differently. And as you say, they are both currently given `plus-style`, so something would need to change.

How about: we leave (1) with `plus-style` and change (2) to `plus-non-emph-style` (and the corresponding change for `*-minus-*`.

Would that give you sufficient degrees of freedom to achieve the styling you want?

Since `foo-non-emph-style` defaults to `foo-style`, this will only cause a visual change for users who have customized the non-emph style. And I suspect that those people would have agreed with doing it your way from the beginning (in fact I kind of think it was just a mistake I made / didn't think through properly). But of course I would like to hear from people who would not appreciate this change iof there are some.

**Comment by dandavison** [comment]
@unphased Tangentially related - https://github.com/dandavison/delta/pull/784 makes it possible to specify styles as references to other styles, e.g. you can do things like `plus-emph-style = plus-style`. That might make it easier to experiment with the different approaches discussed here.

**Comment by dandavison** [comment]
#784 also allows custom style variables in gitconfig, so you can do something like

```gitconfig
[delta]
    dark-pink-style = normal "#ffc0c0"  # custom style name
    pink-style = normal "#ffe0e0"  # custom style name
    minus-style = pink-style
    minus-non-emph-style = minus-style
    minus-emph-style = dark-pink-style
```

**Comment by unphased** [comment]
Wow very handy! Can't wait to play with this.

**Comment by dandavison** [comment]
OK, I've opened https://github.com/dandavison/delta/pull/785 to address this. Maybe helpful to discuss in there where there are some screenshots etc.
