### ISSUE TITLE
Just need synax highlight🚀 

### ISSUE THREAD

**Issue by laoshaw** [dandavison/delta#781]
Add a flag that just enables the syntax highlight, no background color no anything fancy, basically just the original git-diff etc but with syntax highlight, is this possible?

**Comment by laoshaw** [comment]
well just found out diff-highlight kind of works for the purpose, it does not have the syntax highlight but adds the highlight-of-the-exact-diffs-in-each-line.

**Comment by dandavison** [comment]
Hi @laoshaw! `git diff` uses foreground colors to mark added and removed lines:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/142242578-8726b61a-1f5c-4260-a520-2fec71423bd0.png" alt="image" /></td></tr></table>

But syntax highlighting also uses foreground colors. So when adding syntax highlighting to the diff, what would you choose? The red/green foreground colors from git, or the syntax highlighting?

**Comment by dandavison** [comment]
OK, feel free to let me know exactly what you want, if you have any trouble making delta do it. For example, you can have the red and green foreground colors with no syntax highlighting, but syntax highlighting everywhere else. That's just

```gitconfig
[delta]
    plus-style = green
    minus-style = red
```

<table>
<thead><th>git</th><th>delta</th></thead>
<tr>
<td><img width=300px src="https://user-images.githubusercontent.com/52205/142269730-2c10edbd-7465-45df-89a2-541e9353317f.png" alt="image" /></td>
<td><img width=300px src="https://user-images.githubusercontent.com/52205/142269896-cbfbcc99-3a17-4960-99b9-81156311afbf.png" alt="image" /></td>
</tr></table>

If you take a look at the `STYLES` and `COLORS` section of `delta --help` you'll see there's quite a lot that can be done with the various `--*-style` options.
