### ISSUE TITLE
dark theme doesn't match repo and is hard to read

### ISSUE THREAD

**Issue by hoshsadiq** [dandavison/delta#79]
Hello, I'm unable to replicate the dark theme on the README here. This is the diff for `git diff 13e39b1~10`. This is not necessarily an issue with delta, and could very well be my terminal setup in general. How can I go about debugging what the reason is for this? The annoying thing is this is a similar output even when I use a different theme. 

![Screenshot from 2020-01-07 03-02-00](https://user-images.githubusercontent.com/600045/71865261-1e81c600-30fa-11ea-82e7-b31fc473f527.png)

**Comment by hoshsadiq** [comment]
This seems to be an issue with tmux and alacritty, in that, 24 bit colours aren't properly set up. Adding below to my `.tmux.conf` fixed the issue.

```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by hoshsadiq** [comment]
Also see https://github.com/alacritty/alacritty/issues/109

**Comment by dandavison** [comment]
Great, sorry I didn't reply to this before you fixed it! Let me know if the [README](https://github.com/dandavison/delta#24-bit-color) can be improved.

**Comment by fabian-thomas** [comment]
Note that the COLORTERM env var needs to be set correctly too. This is especially important when using delta over ssh, since ssh usually discards COLORTERM.
```
export COLORTERM=truecolor
```
