### ISSUE TITLE
Solarized not supported

### ISSUE THREAD

**Issue by mulholio** [dandavison/delta#80]
I'm a little confused as, although I can see a PR to add solarized and this [code here](https://github.com/dandavison/delta/commit/7951807910045f1280e5eeffb91d9044381749d3#diff-b04a284005f80bd64da3b5f7c723b2c2R8) seems to list Solarized (light) as a theme, I can't see solarized themes (light or dark) in `delta --list-themes` or get it working with this in my `git config`:

```
  pager = delta --dark --theme='Solarized (light)'
```

![image](https://user-images.githubusercontent.com/20966690/71893966-e5bb0e80-3144-11ea-99c4-9524746fca44.png)

**Comment by dandavison** [comment]
Hi @mulholio, the latest [release](https://github.com/dandavison/delta/releases) of delta is 0.0.15 on Dec 03 2019. The Solarized PR came after. So you'd have to build the rust project yourself to get an executable with that feature. However, there's nothing stopping us from making another release and updating Homebrew etc soon. I'll ping this ticket when that's done.
