### ISSUE TITLE
providing theme via git config doesn't seem to work

### ISSUE THREAD

**Issue by djdv** [dandavison/delta#83]
Using:
- `delta-0.0.15-x86_64-pc-windows-msvc`, also built and tested against latest master (9f258c1c1e625210306ba04af6bbadd3d1503ec7)
- `git version 2.24.1.windows.2` ("Git for Windows" builds)
- less: https://github.com/lzybkr/less/commit/163de2db8c7a0c6650b18b2f59e27806b4f4682b
***
Oddities:
- renamed `delta.exe` to `git-delta.exe`, both exhibit this issue
- screencast shows the problem in the new Microsoft Terminal, but this issues happens in the stock console as well
- The problem is the same regardless of the shell (tried with `cmd.exe` and `pwsh.exe`)
***

Screencast of the problem (provides a bit more context than this text alone): 
https://www.youtube.com/watch?v=JZiZx-aR168

When I pipe from `git` to `delta` via `git show | delta --dark` or `git show | delta --dark --theme='sometheme'`, everything seems to work fine.

However, when configuring `git`'s pager to use `delta`, Delta does not seem to be using its default theme, and it is also not using the requested theme (if provided).
`pager = delta --dark`
`pager = delta --dark --theme='Monokai Extended Origin'`

**Comment by dandavison** [comment]
Hi @djdv, thanks for the excellent screencast. One quick thought. Your executable-renaming experiment may have already covered this, but could you confirm that `delta --version` in the shell gives the same result as `pager = delta --version` in gitconfig? I.e. just ruling out the possibility that gitconfig is picking up an old version. Actually, a better version of that experiment might be to use an absolute path in gitconfig.

**Comment by dandavison** [comment]
Or maybe I hit submit too quickly there. Is it possible that the answer is similar to that hypothesis but for `less.exe`? I.e., I wonder whether when invoked with a pipe in the shell, `delta` is picking up the desired `lzybkr/less`, but that when delta is invoked by git as git's pager, the `$PATH` seen by that process is such that a stock `less` is being picked up?

**Comment by djdv** [comment]
You got it.
While the new `less.exe` was at the front of my `$PATH`, "Git for Windows" includes a bunch of POSIX tools in the same directory as `git.exe`, which take precedence in the Windows "Command Search Sequence" over `$PATH`.
I didn't even think of that since `where` was only referencing the new `less.exe` and nothing else.

Thanks for that!

**Comment by dandavison** [comment]
Awesome, glad that's sorted out. It looks like you have delta working nicely in Windows. Is there anything you're aware of that's missing from the README that would help Windows users?

**Comment by djdv** [comment]
@dandavison 
Not that I can think of. I'm always glad to see ubiquity in tools. The less platform specific instructions needed the better imo. And `delta` was very simple to integrate with here. 👍 

This particular issue with `less` may be worth linking in that section, but (hopefully) won't be relevant when those patches get merged upstream (and actually distributed with git, msys2, etc.).

If something comes up, I'll be sure to mention it ;^)
The only thing on my mind at the moment isn't Windows specific.
(I want to look into adding a flag to change the line number and box colour, but not sure when I'll have a chance to look into it)
