### ISSUE TITLE
🐛 test_two_plus_lines_spaces_and_ansi failing on ppc64le

### ISSUE THREAD

**Issue by sashkab** [dandavison/delta#842]
It looks like test `test_two_plus_lines_spaces_and_ansi` is failing on [ppc64le](https://wiki.alpinelinux.org/wiki/Ppc64le) arch. 

```
failures:
---- features::side_by_side::tests::test_two_plus_lines_spaces_and_ansi stdout ----
thread 'features::side_by_side::tests::test_two_plus_lines_spaces_and_ansi' panicked at 'assertion failed: `(left == right)`
  left: `"(blue)│(88)    (blue)│(normal)              (blue) │(28) 1  (blue)│(231 22)a (203)=(231) (141)1(normal)"`,
 right: `"(blue)│(88)    (blue)│(normal)              (blue) │(28) 1  (blue)│(231 22)a (203)=(231) (216)1(normal)"`: on line 1 of input', src/tests/integration_test_utils.rs:118:9
failures:
    features::side_by_side::tests::test_two_plus_lines_spaces_and_ansi
test result: FAILED. 300 passed; 1 failed; 9 ignored; 0 measured; 0 filtered out; finished in 81.38s
```

Since this test is new to 0.11.2 release (see #831; commit d7ef078acbd97d45448237617b03d516969430f4) reporting the issue here. You can find affected [build log](https://gitlab.alpinelinux.org/sashk/aports/-/jobs/558501#L668). 

Thanks!

**Comment by dandavison** [comment]
Thanks @sashkab! I've ignored the test in the master branch for now so the test suite should pass on that branch. Do you need a release to unblock your pipeline or can you work with the change in master?

I also noticed it failing on my local machine last night but haven't got around to looking into it properly. I think we probably need to do a little bit more work to make it avoid picking up certain default colors determined by the environment. I see now that it passes for me in one terminal emulator (MacOS Terminal.app) and fails in iTerm2 :) We'll reactivate the test once we tweak it as needed.

Here's my iTerm2 failure FWIW

```
  left: `"(blue)│(88)    (blue)│(normal)              (blue)│(28) 1  (blue)│(231 22)a (203)=(231) (141)1(normal 22)         (normal)"`,
 right: `"(blue)│(88)    (blue)│(normal)              (blue)│(28) 1  (blue)│(\"#333333\" \"#d0ffd0\")a (\"#a71d5d\")=(\"#333333\") (\"#0086b3\")1(normal \"#d0ffd0\")         (normal)"`: on line 1 of input', src/tests/integration_test_utils.rs:118:9
```

**Comment by sashkab** [comment]
@dandavison thanks for quickly addressing the issue. 

I think I should be good by applying your patch, so no need to create new release at this point.

**Comment by dandavison** [comment]
@sashkab I'm going to re-enable the test in question together with a fix that prevents delta from honoring a certain environment variable. I believe this will now not cause you problems.

To check whether I actually do understand the bug...I believe that you had the environment variable `BAT_THEME` set in the environment that generated the failing test output that you posted. Do you happen to be able to confirm whether that was the case?

**Comment by sashkab** [comment]
@dandavison I do not specifically set any environment variables during tests. I checked test log and I don't see any mentions of `BAT_THEME`. Neither they set by [gitlab-ci](https://gitlab.alpinelinux.org/sashk/aports/-/blob/v3.15.0/.gitlab-ci.yml). So, I'd guess my answer is no.

**Comment by dandavison** [comment]
Hm. OK, thanks very much for getting back to me. Please do let me know if anything goes wrong with your builds again.

**Comment by sashkab** [comment]
Hi @dandavison. Just created a pull request where upgrading to 0.11.3 and it passed without issues, so I guess issue is actually resolved. Link to [pipelines](https://gitlab.alpinelinux.org/sashk/aports/-/pipelines/103014) in case you wondering.

Thanks again!

**Comment by dandavison** [comment]
Excellent, thanks for letting me know.
