### ISSUE TITLE
🐛 DELTA_FEATURES env var should add to other features, not replace them

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#848]
I think it would be more useful if `DELTA_FEATURES` added to features specified in git config, rather than replacing them as it does today. For example, this would make it more convenient as a way to toggle `side-by-side` mode. I'm thinking that if a user does need to deactivate the features in git config they have `--no-gitconfig`.

**Comment by bew** [comment]
What about requiring that env var to start with `+` to mean append?
This way it can do both

**Comment by dandavison** [comment]
> What about requiring that env var to start with + to mean append?

OK, I can do that, thanks for the suggestion!
