### ISSUE TITLE
Update binary assets from bat

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#85]
Do this when the `.mjs` javascript file extension is recognized in bat, see #78, cc @devsnek.

**Comment by dandavison** [comment]
Need to wait for https://github.com/sharkdp/bat/pull/768 to be released.

**Comment by calbrecht** [comment]
bump :) https://github.com/sharkdp/bat/pull/768 is released. 

Meanwhile there are updated solarized themes available as well. 
See https://github.com/sharkdp/bat/issues/941.

**Comment by dandavison** [comment]
Thanks @calbrecht! Delta `assets/syntaxes.bin` and `assets/themes.bin` now match bat@dcfdbf82dd6abaef8047fe0deb7a6a808f15bb15.
