### ISSUE TITLE
🐛 Big performance hits compared to `diff` on "small" files

### ISSUE THREAD

**Issue by rivten** [dandavison/delta#856]
Hello ! 

I hope you are doing fine. 
I was doing a diff on two env files on a project and noticed that using `delta` was _noticably_ slower than using `diff`.
I went ahead and did a performance check with `hyperfine` on my two files (since they are env files, I obviously won't give the content, but they are just a few kilobytes files).

Here are my results :

```
~/dev/f dev* ❯ hyperfine -i --warmup 4 'delta .env .env.dist'                                                                                                                                                                       
Benchmark 1: delta .env .env.dist
  Time (mean ± σ):      97.2 ms ±   1.0 ms    [User: 88.0 ms, System: 9.3 ms]
  Range (min … max):    95.9 ms …  99.2 ms    29 runs

~/dev/f dev* ❯ hyperfine -i --warmup 4 'diff .env .env.dist'                                                                                                                                                                        
Benchmark 1: diff .env .env.dist
  Time (mean ± σ):       1.0 ms ±   0.7 ms    [User: 1.2 ms, System: 0.7 ms]
  Range (min … max):     0.5 ms …   4.6 ms    848 runs

  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
  Warning: Ignoring non-zero exit code.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

~/dev/f dev* ❯ wc .env .env.dist                                                                                                                                                                                                    
  153   268  7319 .env
  151   250  6425 .env.dist
  304   518 13744 total
```

Even though results for `diff` might be slightly innacurate, the time for `delta` to process to 10 kB files is 2 order of magniture slower than `diff`.
I understand that `delta` is probably doing more than `diff`, but two orders of magnitude seems like a big deal to me.

**Comment by dandavison** [comment]
Hi @rivten, thanks very much for this. Can you try with the latest version of delta (`0.11.3`)? There were two related performance problems that affected people on Linux: https://github.com/dandavison/delta/issues/824 and https://github.com/dandavison/delta/issues/839.

**Comment by dandavison** [comment]
`delta file_A file_B` just calls `git diff --no-index file_A file_B` and then sends the results through delta. There shouldn't be any noticeable performance penalty over doing it without delta.

**Comment by rivten** [comment]
Hey @dandavison ! Thanks for the awesomely-quick answer :)

I just compiled v0.11.3 directly from source (since it is not available in my package manager yet for some reason).
So, I run `hyperfine` and had the same result.

```
~/dev/f dev* ❯ /tmp/delta/target/release/delta --version                                                                                                                                       
delta 0.11.3
~/dev/f dev* ❯ hyperfine --warmup 3 '/tmp/delta/target/release/delta .env .env.dist'                                                                                                           
Benchmark 1: /tmp/delta/target/release/delta .env .env.dist
  Time (mean ± σ):      97.6 ms ±   0.8 ms    [User: 86.2 ms, System: 11.4 ms]
  Range (min … max):    96.6 ms …  99.5 ms    29 runs

~/dev/f dev* ❯ hyperfine --warmup 3 -i 'git diff --no-index .env .env.dist'                                                                                                                    
Benchmark 1: git diff --no-index .env .env.dist
  Time (mean ± σ):       1.1 ms ±   0.4 ms    [User: 1.0 ms, System: 1.0 ms]
  Range (min … max):     0.8 ms …   4.4 ms    861 runs

  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
  Warning: Ignoring non-zero exit code.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

BUT. What's weirder is that, when I just run the command (without hyperfine), I can indeed _feel_ a perf improvement with this version :)

So, as to my user experience, my issue is indeed fixed with version 0.11.3 !

Thank a lot taking the time to answer me. I wish you a pleasant day !

**Comment by dandavison** [comment]
I think that running `delta file1 file2` under hyperfine might not be doing what we expect. The exit code of `delta file1 file2` should be the same as `diff` and `git diff`, i.e. 0 means the files are the same and 1 means the files are different. So, why then do we see this:


```
$ delta f g > /dev/null; echo $?
1
```

and yet hyperfine does not require the `-i` argument when running `delta f g` when files f and g differ?

The way delta works internally is that it checks at startup to see whether stdin is a tty: if it is, then it tries to run `delta file_1 file_2` and complains if we haven't supplied two positional aguments. If stdin is not a tty, then delta processes stdin as usual. Perhaps what we're seeing is something to do with stdin not being a tty when delta is invoked by hyperfine? (Although  clearly `echo | delta` should be fast, so it can't be doing that...)

**Comment by dandavison** [comment]
(I'll close since it seems like we're not discussing a bug in delta any longer, but I'm curious what's going on. Why doesn't `hyperfine --show-output` show anything in `hyperfine 'delta file_1 file2' --show-output`?)
