### ISSUE TITLE
💲 Sign up for GitHub Sponsors 💲

### ISSUE THREAD

**Issue by zachriggle** [dandavison/delta#866]
@dandavison you're doing wonders for my productivity, and are a large part of my inspiration to (eventually!) learn Rust.

It would be nice if I could toss you some coffee / beer money as a sign of appreciation.

It's very easy to sign up, and if you are a FOSS project, there are no fees deducted by GitHub.

# [⭐️Haz Un Clic Por Aqui⭐️](http://github.com/sponsors)

**Comment by dandavison** [comment]
Thanks for the suggestion @zachriggle. That's now live. All donations go to https://www.rainforesttrust.org.

https://github.com/sponsors/dandavison

---------------------------------------------

![image](https://user-images.githubusercontent.com/52205/148281961-3fb0b3b3-fa6a-4872-9670-cfe86252045b.png)
