### ISSUE TITLE
🚀 Blame Highlighting: Do not use background colors for the actual code

### ISSUE THREAD

**Issue by zachriggle** [dandavison/delta#867]
As I've said in the last few issues, thank you so much @dandavison for your time and effort.

The new Blame functionality is very useful, but occasionally the code on the right-hand-side is difficult to read (or unhighlighted, might file a bug if I can find a FOSS example) due to the background coloring.

If there was a way to toggle this, it would be great! Thanks! ❤️

**Comment by dandavison** [comment]
Agreed! I've made a start on this in https://github.com/dandavison/delta/pull/870 (adding a new option `blame-code-style`).
