### ISSUE TITLE
🚀 "git blame ... | delta" will colorize based on commit date, even if only "--blame-format '{author} |'" is specified

### ISSUE THREAD

**Issue by zachriggle** [dandavison/delta#868]
## Much Love ❤️ 

Thank you so much @dandavison for making a tool that I continue to use on a daily basis!

Up front: The "blame" highlighting functionality works great as-is, this is just an enhancement request.

I've started using the Blame functionality #761, and often the age of the code (or its specific commit) is not as relevant as simply who WROTE the code -- i.e., who can help me understand it better and answer any questions I have.

For example, if we take some code from the Linux kernel and do...

```
$ git blame drivers/misc/lkdtm/core.c | delta --blame-format '{author}'
```

There are a lot of commits for various bits of this code, but for the most part it's a single author.  It would be nice, if `{timestamp}` and `{commit}` are not listed in the format options, that we just do a comparison against the author name.  This has the added benefit of reducing the reuse / recycling of colors used to do the highlighting.

Let me know what you think!

**Comment by dandavison** [comment]
Let me check that I understand the suggestion correctly:

We can describe delta's blame procedure as follows: 

- For each line of blame output we compute a "key"
- Successive lines are colored differently if their keys differ
- Currently, the key for a line is the blame commit for that line

The suggestion here is to change the key to be <whatever the blame format will display for that line>

Right?
