### ISSUE TITLE
Don't pass `--no-init` to less when `BAT_PAGER` is explicitly set

### ISSUE THREAD

**Issue by masaeedu** [dandavison/delta#88]
Hello. I'm running into some issues where `git log --graph` is no longer clearing the screen after I exit. I believe this is because `delta` is passing the `--no-init` argument (along with a few others) to less explicitly. See the screenshot below:

![image](https://user-images.githubusercontent.com/3674056/73313899-7e9bf180-41fa-11ea-94a7-7a7fee1251cc.png)

I already have my own set of less configuration options in `LESS='-R -F --mouse --wheel-lines=10'`, and it would be ideal if the tool could avoid overriding the user's explicit settings.

I noticed that a similar problem was recently addressed in bat: https://github.com/sharkdp/bat/issues/749, where their solution was to stop passing `--no-init` to recent enough versions of `less`; is it possible that `delta` is just not depending on a recent enough version of `bat`?

**Comment by da-x** [comment]
Pushed a PR for this.
