### ISSUE TITLE
🚀 Add spellcheck support

### ISSUE THREAD

**Issue by matthauck** [dandavison/delta#899]
I would love to have a pager / `git diff` view that showed spelling errors, similar perhaps to vim spellcheck. 

Looking for this I stumbled upon `delta`, which looks amazing, and wondered if this is a feature that delta might be well suited for / interested in?

**Comment by dandavison** [comment]
Hi @matthauck, thanks for this. Ha, that's certainly one I hadn't considered so far! So, presumably this would be for text files / HTML / JSX templates, that sort of thing? Or are you thinking of mis-spelled tokens in programming language source code? 

It's technically possible I think, some thoughts:

- We should remember that delta only has access to the fragments of files that are present in diff hunks; not the source file (at least, currently delta does not try to locate and open the source file)
- I think it would depend on the existence of a suitable Rust library implementing appropriate spell checking logic
- Are you sure that a pre-commit or pre-push hook isn't a more appropriate place for this? That might be quite easy to get up-and-running.

**Comment by matthauck** [comment]
Yeah. The particular use case I had in mind would be to enable spell check for `git diff` so that I can notice spelling errors before submitting PR for review. 

I think:
- would not need to be programming language syntax aware
- would not need to be a git hook: function names, etc. will probably always be flagged as misspelled. I would personally just use this for visual inspection and expect some false positives
- a brief search on crates.io shows a number of spellcheck hits

**Comment by dandavison** [comment]
> would not need to be a git hook:

It wouldn't need to be, but it would be much easier to add a git hook using an established command-line utility for spell checking, than to build it into delta. So I think we'd want to explore that option first. Conceptually, highlighting possible spelling errors feels comparable to highlighting syntax errors or type-check errors, which of course isn't really in-scope for delta.

**Comment by dandavison** [comment]
I don't think spell-checking is delta's responsibility: delta is for viewing diffs, not for assessing correctness of the diff content. A linter might be a suitable place for spell-check functionality. I'm going to close this since I don't think it's going to result in delta development, but thanks for the suggestion and interest in delta.
