### ISSUE TITLE
Show binary files changes in delta output

### ISSUE THREAD

**Issue by gibfahn** [dandavison/delta#93]
When I use `GIT_PAGER=less git show` I see the following section for each binary file:

```diff
diff --git a/foo b/foo
new file mode 100644
index 0000000..4088911
Binary files /dev/null and b/foo differ
```

When I use delta with `GIT_PAGER="delta --theme=TwoDark" git show`, I don't see any output for `foo`, which is a binary file.

It would be great to see something that shows that there was a binary file and that it has changed, what less shows would be fine.

Quick repro:

```sh
mkdir -p tst && cd tst
git init
echo -n -e \\x48\\x00\\x49\\x00 > foo
git add foo
GIT_PAGER="delta --theme=TwoDark" git diff --staged
GIT_PAGER=less git diff --staged
```

Output:

```console
$ mkdir -p tst && cd tst
$ git init
Initialized empty Git repository in ~/tmp/tst/.git/
$ echo -n -e \\x48\\x00\\x49\\x00 > foo
$ git add foo
$ GIT_PAGER="delta --theme=TwoDark" git diff --staged
$ GIT_PAGER=less git diff --staged
  diff --git a/foo b/foo
  new file mode 100644
  index 0000000..7a42ff1
  Binary files /dev/null and b/foo differ
```

Thanks for making such a great diff viewer by the way, best one I've found hands down.

**Comment by dandavison** [comment]
Thanks for reporting this and thanks for the reproduction script. I've fixed this in https://github.com/dandavison/delta/pull/94, and added a test. However, as noted in that PR, I am currently confused about why the test is passing before the fix commit. If you do have a local rust setup and feel like building on that branch to confirm the fix that would be great, but no worries if not and thanks for the report!

**Comment by Kr1ss-XD** [comment]
FWIW, I just checked out https://github.com/dandavison/delta/pull/94 and rebuilt; on my end this issue is fixed. 

Looks good to me, thx !  :+1:

**Comment by gibfahn** [comment]
Checked and it works, thanks for fixing it so quickly!
