### ISSUE TITLE
🐛 File redirection support

### ISSUE THREAD

**Issue by unphased** [dandavison/delta#932]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/1542910/150869993-b199a283-8410-4823-ae96-e36c7060f293.png">

I find myself often using `<(ssh user@server "cat remotefile")` as one of the diff files. Would like it if delta can support this. 

On my other Linux machine it actually ran but provided this output: 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1542910/150870736-c5d60304-2087-421b-bbf4-3eb7164f8a85.png">

**Comment by dandavison** [comment]
Hi @unphased, thanks for this, we actually already have an open issue for this: https://github.com/dandavison/delta/issues/666

Coincidentally https://github.com/dandavison/delta/issues/929 was also opened today which is related. It would be great if we could solve this.
