### ISSUE TITLE
test handlers::blame::tests::test_color_assignment ... FAILED🐛 

### ISSUE THREAD

**Issue by vt-alt** [dandavison/delta#957]
Test `handlers::blame::tests::test_color_assignment` is unreliable and [fails with](https://git.altlinux.org/beehive/logs/Sisyphus/x86_64/archive/2022/0212/error/git-delta-0.11.3-alt1):
```
+ cargo test -j16 --release --no-fail-fast
...
failures:

---- handlers::blame::tests::test_color_assignment stdout ----
thread 'handlers::blame::tests::test_color_assignment' panicked at 'assertion failed: `(left == right)`
  left: `[("5 months ago    Dan Davison     aaaaaaa ", "1")]`,
 right: `[("4 months ago    Dan Davison     aaaaaaa ", "1")]`', src/handlers/blame.rs:334:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    handlers::blame::tests::test_color_assignment

test result: FAILED. 314 passed; 1 failed; 11 ignored; 0 measured; 0 filtered out; finished in 9.78s

```
2.2.3

**Comment by dandavison** [comment]
Thanks @vt-alt! This is actually fixed in master but unreleased: https://github.com/dandavison/delta/commit/66b467ffe57059eaf3a93776ced35f0f43350478 (perhaps you'll agree with the commit message there...) Is it causing problems with a distro packaging pipeline?

**Comment by dandavison** [comment]
I've just made a release: https://github.com/dandavison/delta/releases/tag/0.12.0

(I'll close this now, but lmk if any problems persist.)

**Comment by vt-alt** [comment]
Thanks much!
