### ISSUE TITLE
🐛  apt --fix-broken install for Ubuntu <20.04

### ISSUE THREAD

**Issue by BennettZA** [dandavison/delta#958]
```bash
git-delta : Depends: libgcc-s1 (>= 4.2) but it is not installable
```

**Comment by dandavison** [comment]
@BennettZA let us know if  @Kr1ss-XD's suggestions and https://dandavison.github.io/delta/installation.html and #504 don't solve this for you. I'll close this for now though since I suspect there's no Delta development work to be done.

**Comment by ishaan-kapoor** [comment]
Using Ubuntu 22.04 WSL amd 64 and I get this error post installation
```
memory allocation of 1970324836974592 bytes failed
Aborted
```
I tried both musl and normal, and got the same error.

**Comment by rljohnsn** [comment]
> Using Ubuntu 22.04 WSL amd 64 and I get this error post installation
> 
> ```
> memory allocation of 1970324836974592 bytes failed
> Aborted
> ```
> 
> I tried both musl and normal, and got the same error.

I'm seeing the same error as a normal user but if I run it as root it works fine.
