### ISSUE TITLE
Hunk style line number references

### ISSUE THREAD

**Issue by luisdavim** [dandavison/delta#97]
Would it be possible to add an option to use the `--hunk-style` `box` or `underline` but keep the string format the same as `plain`, including the line number references (ex: `@@ -193,7 +199,9 @@ `)?

**Comment by dandavison** [comment]
Hi @luisdavim, thanks for opening this. On `master` you can now do e.g.

```
--hunk-header-style=raw --hunk-header-decoration-style='blue box'
```

`raw` means that the text is unchanged and the original colors from git come through, so you can control the color using the `color.diff.frag` section of `~/.gitconfig`. E.g.

```
$ git -c color.diff.frag='' show 0ff1a jedi/evaluate/names.py
```

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/83366157-588a8780-a37b-11ea-8163-d581525cd095.png" alt="image" /></td></tr></table>


```
$ git -c color.diff.frag='red bold' show 0ff1a jedi/evaluate/names.py
```

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/83366090-d26e4100-a37a-11ea-904a-0417459c9614.png" alt="image" /></td></tr></table>


```
$ git -c color.diff.frag='red #dddddd' show 0ff1a jedi/evaluate/names.py
```

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/83366137-2547f880-a37b-11ea-9f24-a8b6e0b51ecf.png" alt="image" /></td></tr></table>

See #205 for full details of the new options.

**Comment by luisdavim** [comment]
That's awesome, thanks.
