### ISSUE TITLE
🚀 Line numbers in blame output

### ISSUE THREAD

**Issue by matthiasbeyer** [dandavison/delta#970]
It seems that delta is not yet able to display line numbers in blame output, is it? Maybe I am missing something.

If it is not yet able, please consider this a feature request. If it is, please consider this a request to improve the documentation on this part! :laughing: 

:rocket: delta is awesome!

**Comment by bew** [comment]
#885 was merged recently, and it's available in the latest release [0.12.0](https://github.com/dandavison/delta/releases/tag/0.12.0)

**Comment by matthiasbeyer** [comment]
:partying_face:
