### ISSUE TITLE
🚀 Update syntax definitions from bat

### ISSUE THREAD

**Issue by pbsds** [dandavison/delta#988]
I've upstreamed some contributions to the syntax definitions in bat, could you please pull the latest definitions?

**Comment by dandavison** [comment]
Hi @pbsds, sure! We've actually improved the way that delta uses bat themes. With https://github.com/sharkdp/bat/pull/2030 delta will use the themes from bat-as-a-library, so the update will just involve updating the bat library version. So I'm just waiting for bat 0.19.1 which they've said is coming soon.

**Comment by pbsds** [comment]
Neato
