### ISSUE TITLE
Add option to change color of box/underline/file text

### ISSUE THREAD

**Issue by hipstersmoothie** [dandavison/delta#99]
Hey! This package seems awesome!

The one thing preventing me from using it though is the blue chosen for header text and box/underlines is pretty hard for me to see. I would like an option that allows me to set this to white for maximum contrast in my dark terminal.

Thanks!

**Comment by dandavison** [comment]
Thanks, agreed! I'd forgotten there were hard-coded colors ([here](https://github.com/dandavison/delta/blob/master/src/delta.rs#L206), [here](https://github.com/dandavison/delta/blob/master/src/delta.rs#L235), and [here](https://github.com/dandavison/delta/blob/master/src/delta.rs#L257)). We should add the ability to configure them.

**Comment by dandavison** [comment]
Hi @hipstersmoothie, I'm working on a branch that will allow all colors to be specified as either RGB, or as an ANSI terminal code, using command line options. However, I realized there's a quick fix for this. (Comment below copied from #103):

That blue color is not specified as RGB by Delta: it's ANSI terminal color code 34 ("blue foreground"). I.e. the actual displayed colour is controlled by your terminal emulator, so there's a quick fix if you're happy with altering that blue everywhere. In my terminal (iTerm2), I can change it like this:

![image](https://user-images.githubusercontent.com/52205/75356702-ec791e80-5875-11ea-8a9a-74f7d3625a56.png)

**Comment by dandavison** [comment]
I've merged a branch which allows all colors to be configured using command line options. The new options are described in the `--help` output:

```
--commit-color <commit_color>              Color for the commit section of git output. [default: yellow]
--commit-style <commit_style>                                                                   
    Formatting style for the commit section of git output. Options are: plain, box. [default: plain]

--file-color <file_color>                  Color for the file section of git output. [default: blue]
--file-style <file_style>
    Formatting style for the file section of git output. Options are: plain, box, underline. [default:
    underline]                                                                                  
--hunk-color <hunk_color>                  Color for the hunk-marker section of git output. [default: blue]
--hunk-style <hunk_style>
    Formatting style for the hunk-marker section of git output. Options are: plain, box. [default: box]
```

along with a section describing how to specify colors:

```
Colors
------

All delta color options work the same way. There are two ways to specify a color:

1. RGB hex code

   An example of passing an RGB hex code is:
   --file-color="#0e7c0e"

2. ANSI color name

   There are 8 ANSI color names:
   black, red, green, yellow, blue, magenta, cyan, white.

   In addition, all of them have a bright form:
   bright-black, bright-red, bright-green, bright-yellow, bright-blue, bright-magenta, bright-cyan, bright-white

   An example is:
   --file-color="green"

   Unlike RGB hex codes, ANSI color names are just names: you can choose the exact color that each
   name corresponds to in the settings of your terminal application (the application you use to run
   command line programs). This means that if you use ANSI color names, and you change the color
   theme used by your terminal, then delta's colors will respond automatically, without needing to
   change the delta command line.

   "purple" is accepted as a synonym for "magenta". Color names and codes are case-insensitive.
```
